Repository knative/eventing, pull requests merged in 2018-08, with the labels that each got.

#304 Update VirtualSerivce to pass Istio validation
  pkg/controller/channel/controller.go
Labels: approved, lgtm, size/S

#298 Avoid replacing the monitor's bus with the wrong bus
  pkg/buses/monitor.go
Labels: approved, lgtm, size/S

#308 Only update the feed in one place
  pkg/controller/feed/reconcile.go
Labels: approved, lgtm, size/M

#312 Opt-in to istio sidecar injection
  config/100-namespace.yaml
  config/500-controller.yaml
  config/500-webhook.yaml
  pkg/controller/feed/reconcile_test.go
  pkg/controller/feed/resources/job.go
  pkg/sources/container_event_source_job.go
  test/e2e/k8sevents/e2etestfnnamespace.yaml
  test/e2e/k8sevents/e2etestnamespace.yaml
Labels: approved, lgtm, size/S

#303 Create loggers in controllers main function.
  Gopkg.lock
  cmd/controller-manager/main.go
  cmd/controller/main.go
  cmd/webhook/main.go
  config/500-controller-manager.yaml
  config/500-controller.yaml
  config/500-webhook.yaml
  config/config-logging.yaml
  pkg/apis/channels/logkey/constants.go
  pkg/apis/feeds/logkey/constants.go
  pkg/apis/flows/logkey/constants.go
  pkg/logconfig/config.go
  vendor/github.com/knative/pkg/LICENSE
  vendor/github.com/knative/pkg/configmap/default.go
  vendor/github.com/knative/pkg/configmap/doc.go
  vendor/github.com/knative/pkg/configmap/fixed.go
  vendor/github.com/knative/pkg/configmap/load.go
  vendor/github.com/knative/pkg/configmap/watcher.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/logging/logger.go
  vendor/github.com/knative/pkg/logging/logkey/constants.go
  vendor/github.com/knative/pkg/logging/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#296 Add '-dispatcher' suffix to bus dispatcher deployment
  config/buses/gcppubsub/README.md
  config/buses/kafka/README.md
  config/buses/stub/README.md
  pkg/controller/names.go
Labels: approved, lgtm, size/S

#306 Adding flow default and validation stubs.
  Gopkg.lock
  pkg/apis/flows/v1alpha1/flow_defaults.go
  pkg/apis/flows/v1alpha1/flow_types.go
  pkg/apis/flows/v1alpha1/flow_validation.go
  vendor/github.com/knative/pkg/apis/defaults.go
  vendor/github.com/knative/pkg/apis/field_error.go
Labels: approved, lgtm, size/L

#307 Test ParametersFrom feature
  pkg/controller/feed/reconcile.go
  pkg/controller/feed/reconcile_test.go
Labels: approved, lgtm, size/L

#292 Use logs as termination message
  config/500-controller-manager.yaml
  config/500-controller.yaml
  config/500-webhook.yaml
Labels: approved, lgtm, size/XS

#291 Pull feedlet image only if not present
  pkg/controller/feed/reconcile_test.go
  pkg/controller/feed/resources/job.go
Labels: approved, lgtm, size/XS

#317 Adding short names to eventing resources.
  config/300-bus.yaml
  config/300-channel.yaml
  config/300-clusterbus.yaml
  config/300-clustereventsource.yaml
  config/300-clustereventtype.yaml
  config/300-eventsource.yaml
  config/300-eventtype.yaml
  config/300-flow.yaml
  config/300-subscription.yaml
Labels: approved, lgtm, size/S

#305 Document all feed controller methods
  pkg/controller/feed/errors.go
  pkg/controller/feed/provider.go
  pkg/controller/feed/reconcile.go
  pkg/controller/feed/resources/job.go
Labels: approved, lgtm, size/M

#311 Don't update status for deleted resources
  pkg/buses/monitor.go
Labels: approved, lgtm, size/S

#313 Run all controllers in the same process
  cmd/controller-manager/kodata/LICENSE
  cmd/controller-manager/kodata/VENDOR-LICENSE
  cmd/controller/controller-runtime-main.go
  cmd/controller/main.go
  config/500-controller-manager.yaml
Labels: approved, lgtm, size/L

#321 Adding validatable to bus types.
  Gopkg.lock
  pkg/apis/channels/v1alpha1/bus_defaults.go
  pkg/apis/channels/v1alpha1/bus_types.go
  pkg/apis/channels/v1alpha1/bus_validation.go
  pkg/apis/channels/v1alpha1/bus_validation_test.go
  pkg/apis/channels/v1alpha1/clusterbus_defaults.go
  pkg/apis/channels/v1alpha1/clusterbus_validation.go
  pkg/webhook/bus.go
  pkg/webhook/webhook_channels_test.go
Labels: approved, lgtm, size/XL

#326 Clarify relationship between Feeds and Flows
  pkg/apis/feeds/v1alpha1/feed_types.go
  pkg/apis/flows/v1alpha1/flow_types.go
  pkg/controller/flow/reconcile.go
Labels: approved, lgtm, size/XS

#316 Flow resource creation comes from the resource dir.
  pkg/controller/flow/reconcile.go
  pkg/controller/flow/resources/channel.go
  pkg/controller/flow/resources/feed.go
  pkg/controller/flow/resources/subscription.go
  pkg/controller/owner_references.go
Labels: approved, lgtm, size/L

#320 Adding channel defaults and validation.
  cmd/webhook/main.go
  pkg/apis/channels/v1alpha1/channel_defaults.go
  pkg/apis/channels/v1alpha1/channel_types.go
  pkg/apis/channels/v1alpha1/channel_validation.go
  pkg/apis/channels/v1alpha1/channel_validation_test.go
  pkg/webhook/channel.go
  pkg/webhook/channel_test.go
  third_party/VENDOR-LICENSE
Labels: approved, lgtm, size/L

#295 Start to use `pkg/signals` from `knative/pkg`.
  Gopkg.lock
  cmd/controller/main.go
  cmd/webhook/main.go
  pkg/buses/gcppubsub/dispatcher/main.go
  pkg/buses/gcppubsub/provisioner/main.go
  pkg/buses/kafka/dispatcher/dispatcher.go
  pkg/buses/kafka/provisioner/provisioner.go
  pkg/buses/stub/main.go
  pkg/sources/k8sevents/receive_adapter/receive_adapter.go
  vendor/github.com/knative/pkg/signals/signal.go
  vendor/github.com/knative/pkg/signals/signal_posix.go
  vendor/github.com/knative/pkg/signals/signal_windows.go
Labels: approved, lgtm, size/S

#324 Add configmap for flow controller
  config/400-flow-controller-config.yaml
  pkg/controller/flow/provider.go
  pkg/controller/flow/reconcile.go
  pkg/controller/flow/reconcile_test.go
Labels: approved, lgtm, size/L

#345 Fix e2e test after removal of controller manager.
  config/config-logging.yaml
  pkg/logconfig/config.go
  test/e2e-tests.sh
Labels: approved, lgtm, size/S

#346 Stage subscriptions to be validatable by new webhook.
  pkg/apis/channels/v1alpha1/subscription_defaults.go
  pkg/apis/channels/v1alpha1/subscription_types.go
  pkg/apis/channels/v1alpha1/subscription_validation.go
  pkg/apis/channels/v1alpha1/subscription_validation_test.go
  pkg/webhook/subscription.go
  pkg/webhook/subscription_test.go
Labels: approved, lgtm, size/L

#347 Stage feeds to be validatable by new webhook.
  pkg/apis/feeds/v1alpha1/feed_defaults.go
  pkg/apis/feeds/v1alpha1/feed_validation.go
  pkg/apis/feeds/v1alpha1/feed_validation_test.go
  pkg/webhook/feed.go
  pkg/webhook/feed_test.go
Labels: approved, lgtm, size/L

#340 Convert github source to cloud events.
  pkg/sources/github/README.md
  pkg/sources/github/events.go
  pkg/sources/github/eventsource.yaml
  pkg/sources/github/eventtype.yaml
  pkg/sources/github/feedlet/feedlet.go
  pkg/sources/github/receive_adapter/receive_adapter.go
  sample/github/legit.go
Labels: approved, lgtm, size/L

#348 Adding shell _default and _validation files for event type and source.
  pkg/apis/feeds/v1alpha1/cluster_event_source_defaults.go
  pkg/apis/feeds/v1alpha1/cluster_event_source_types.go
  pkg/apis/feeds/v1alpha1/cluster_event_source_validation.go
  pkg/apis/feeds/v1alpha1/cluster_event_type_defaults.go
  pkg/apis/feeds/v1alpha1/cluster_event_type_types.go
  pkg/apis/feeds/v1alpha1/cluster_event_type_validation.go
  pkg/apis/feeds/v1alpha1/common_event_source_defaults.go
  pkg/apis/feeds/v1alpha1/common_event_source_types.go
  pkg/apis/feeds/v1alpha1/common_event_source_validation.go
  pkg/apis/feeds/v1alpha1/common_event_type_defaults.go
  pkg/apis/feeds/v1alpha1/common_event_type_types.go
  pkg/apis/feeds/v1alpha1/common_event_type_validation.go
  pkg/apis/feeds/v1alpha1/event_source_defaults.go
  pkg/apis/feeds/v1alpha1/event_source_types.go
  pkg/apis/feeds/v1alpha1/event_source_validation.go
  pkg/apis/feeds/v1alpha1/event_type_defaults.go
  pkg/apis/feeds/v1alpha1/event_type_types.go
  pkg/apis/feeds/v1alpha1/event_type_validation.go
Labels: approved, lgtm, size/L

#325 add support for Subsciption.replyTo property
  pkg/apis/channels/v1alpha1/subscription_types.go
  pkg/buses/gcppubsub/bus.go
  pkg/buses/kafka/dispatcher/dispatcher.go
  pkg/buses/message.go
  pkg/buses/message_dispatcher.go
  pkg/buses/stub/main.go
Labels: approved, lgtm, size/L

#357 Sync our pr template to match serving.
  .github/pull-request-template.md
Labels: approved, lgtm, size/S

#315 Reconcile with context
  pkg/controller/feed/reconcile.go
Labels: approved, lgtm, size/L

#359 Move bus deployments to knative-eventing
  config/200-serviceaccount.yaml
  config/201-clusterrolebinding.yaml
  config/buses/gcppubsub/README.md
  config/buses/kafka/README.md
  config/buses/stub/README.md
  pkg/controller/bus/controller.go
  pkg/controller/channel/controller.go
  pkg/controller/clusterbus/controller.go
  pkg/controller/names.go
Labels: approved, lgtm, size/L

#369 Fix misspellings of a few words in the code base.
  pkg/apis/channels/v1alpha1/subscription_validation.go
  pkg/apis/feeds/v1alpha1/feed_types.go
  pkg/apis/flows/v1alpha1/flow_types.go
  pkg/buses/message_receiver.go
  pkg/event/handler.go
  pkg/event/handler_test.go
Labels: approved, lgtm, size/S

#375 Ran gofmt -s on the repo.
  pkg/apis/flows/v1alpha1/flow_types_test.go
  pkg/controller/feed/resources/job.go
  pkg/controller/util/subscription_util.go
  pkg/event/handler.go
  pkg/sources/container_event_source_job.go
  pkg/sources/gcppubsub/watcher_pod.go
  pkg/sources/k8sevents/watcher_pod.go
Labels: approved, lgtm, size/S

#374 We never used the err from uuid.NewRandom.
  pkg/sources/gcppubsub/gcp_pubsub.go
  pkg/sources/k8sevents/k8s_events.go
Labels: approved, lgtm, size/XS

#379 Update e2e-test.sh to be portable
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#380 Type is not a field on source. Removed.
  pkg/sources/gcppubsub/eventsource.yaml
  pkg/sources/k8sevents/eventsource.yaml
Labels: approved, lgtm, size/XS

#377 Fix env var len check in gh feedlet
  pkg/sources/github/feedlet/feedlet.go
Labels: approved, lgtm, size/XS

#381 Fix github source to use valid webhook name
  pkg/sources/github/feedlet/feedlet.go
Labels: approved, lgtm, size/XS

#385 Check and return the correct errors.
  pkg/controller/channel/controller.go
Labels: approved, lgtm, size/XS

#388 Found panic on missing flag modification. glog no longer used.
  pkg/sources/github/receive_adapter/receive_adapter.go
Labels: approved, lgtm, size/XS

#389 Don't inject the istio sidecar and fix the tests related.
  pkg/controller/feed/reconcile_test.go
  pkg/controller/feed/resources/job.go
Labels: approved, lgtm, size/S

#390 Remove ultrasaurus from approvers
  OWNERS
Labels: approved, lgtm, size/XS

#391 Remove dead code.
  pkg/controller/flow/reconcile.go
Labels: approved, lgtm, size/XS

#394 Vendor the test-infra scripts
  Gopkg.lock
  Gopkg.toml
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#376 Generated feed names
  pkg/controller/flow/reconcile.go
  pkg/controller/flow/reconcile_test.go
  pkg/controller/flow/resources/feed.go
  test/e2e-tests.sh
Labels: approved, lgtm, size/L

#396 prefer %v err over %s err.Erorr()
  cmd/controller/main.go
  pkg/buses/gcppubsub/dispatcher/main.go
  pkg/buses/gcppubsub/provisioner/main.go
  pkg/buses/kafka/provisioner/provisioner.go
  pkg/buses/monitor.go
  pkg/buses/stub/main.go
  pkg/controller/bus/controller.go
  pkg/controller/channel/controller.go
  pkg/controller/clusterbus/controller.go
  pkg/sources/gcppubsub/gcp_pubsub.go
  pkg/sources/k8sevents/k8s_events.go
  pkg/sources/k8sevents/receive_adapter/receive_adapter.go
Labels: approved, lgtm, size/M

#387 Add grantr to list of approvers
  OWNERS
Labels: approved, lgtm, size/XS

#397 Link to working group document.
  README.md
Labels: approved, lgtm, size/XS

#398 Validate flow as told in the flow spec comments.
  pkg/apis/flows/v1alpha1/flow_defaults.go
  pkg/apis/flows/v1alpha1/flow_types.go
  pkg/apis/flows/v1alpha1/flow_validation.go
  pkg/apis/flows/v1alpha1/flow_validation_test.go
Labels: approved, lgtm, size/L

#400 Nothing to validate with event sources. Removing todos.
  pkg/apis/feeds/v1alpha1/cluster_event_source_defaults.go
  pkg/apis/feeds/v1alpha1/cluster_event_source_types.go
  pkg/apis/feeds/v1alpha1/cluster_event_source_validation.go
  pkg/apis/feeds/v1alpha1/common_event_source_defaults.go
  pkg/apis/feeds/v1alpha1/common_event_source_validation.go
  pkg/apis/feeds/v1alpha1/event_source_defaults.go
  pkg/apis/feeds/v1alpha1/event_source_types.go
  pkg/apis/feeds/v1alpha1/event_source_validation.go
Labels: approved, lgtm, size/M

#383 Delete GitHub samples from eventing.
  sample/README.md
  sample/github/README.md
  sample/github/auth.yaml
  sample/github/flow.yaml
  sample/github/githubsecret.yaml
  sample/github/legit-service.yaml
  sample/github/legit.go
Labels: approved, lgtm, size/L

#384 Delete old pub/sub sample from eventing.
  sample/README.md
  sample/gcp_pubsub_function/README.md
  sample/gcp_pubsub_function/configuration.yaml
  sample/gcp_pubsub_function/flow.yaml
  sample/gcp_pubsub_function/function.go
  sample/gcp_pubsub_function/route.yaml
  sample/gcp_pubsub_function/serviceaccount.yaml
  sample/gcp_pubsub_function/serviceaccountbinding.yaml
Labels: approved, lgtm, size/L

#386 Log dispatch errors in stub bus
  pkg/buses/stub/bus.go
Labels: approved, lgtm, size/S

#407 Add logger context for stubbus
  pkg/buses/stub/bus.go
Labels: approved, lgtm, size/M

#405 Increase EventType's reconciler unit test coverage
  pkg/controller/eventtype/provider_test.go
  pkg/controller/eventtype/reconcile_test.go
  pkg/controller/feed/reconcile_test.go
  pkg/controller/flow/reconcile_test.go
  pkg/controller/testing/mock_client.go
  pkg/controller/testing/table.go
Labels: approved, lgtm, size/L
