Repository knative/eventing, pull requests merged in 2018-09, with the labels that each got.

#413 Update test-infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#415 Do not specify node port number for kafka broker
  config/buses/kafka/broker/kafka-broker.yaml
Labels: approved, lgtm, size/XS

#425 Update Bus README's with correct namespace
  config/buses/gcppubsub/README.md
  config/buses/kafka/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#410 Add a few unit tests for the Feed reconciler.
  pkg/controller/feed/reconcile.go
  pkg/controller/feed/reconcile_test.go
  pkg/controller/feed/resources/job.go
  pkg/controller/feed/resources/job_test.go
  pkg/controller/feed/resources/stub_test.go
Labels: approved, lgtm, size/XXL

#406 Rename [bus|channel|subscription]Ref
  pkg/buses/bus.go
  pkg/buses/cache.go
  pkg/buses/cache_test.go
  pkg/buses/gcppubsub/bus.go
  pkg/buses/gcppubsub/dispatcher/main.go
  pkg/buses/gcppubsub/provisioner/main.go
  pkg/buses/handler_funcs.go
  pkg/buses/kafka/bus.go
  pkg/buses/kafka/dispatcher/main.go
  pkg/buses/kafka/provisioner/main.go
  pkg/buses/message_receiver.go
  pkg/buses/reconciler.go
  pkg/buses/references_test.go
  pkg/buses/stub/bus.go
  pkg/buses/stub/dispatcher/main.go
Labels: approved, lgtm, size/XL

#420 Cleanup Bus/ClusterBus reconciler
  pkg/buses/bus.go
  pkg/buses/reconciler.go
  pkg/buses/references.go
  pkg/buses/references_test.go
Labels: approved, lgtm, size/L

#426 Add scothis as an approver
  OWNERS
Labels: approved, lgtm, size/XS

#422 Reprovision channels and resubscrube when a bus params are updated
  pkg/buses/cache.go
  pkg/buses/cache_test.go
  pkg/buses/reconciler.go
Labels: approved, lgtm, size/M

#421 Create new Subscription in pkg/apis/eventing as per the new spec.
  Gopkg.lock
  hack/update-codegen.sh
  pkg/apis/eventing/register.go
  pkg/apis/eventing/v1alpha1/doc.go
  pkg/apis/eventing/v1alpha1/register.go
  pkg/apis/eventing/v1alpha1/subscription_defaults.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/apis/eventing/v1alpha1/subscription_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_subscription.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/subscription.go
  pkg/client/informers/externalversions/eventing/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/subscription.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  pkg/client/listers/eventing/v1alpha1/subscription.go
Labels: approved, lgtm, size/XXL

#433 Reject non-successful (2xx) dispatch responses
  pkg/buses/message_dispatcher.go
Labels: approved, lgtm, size/XS

#434 Upgrading knative.eventing resources to use knative.pkg.Conditions
  Gopkg.lock
  Gopkg.toml
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/duck/doc.go
  vendor/github.com/knative/pkg/apis/duck/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/doc.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targettable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/knative/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/doc.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/duck_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/generated_expansion.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/topic.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/topic.go
  vendor/github.com/knative/pkg/client/informers/externalversions/factory.go
  vendor/github.com/knative/pkg/client/informers/externalversions/generic.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/expansion_generated.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/topic.go
Labels: approved, lgtm, size/XXL

#436 Adding GetCondition and patch merge to ClusterProvisionerStatus
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
Labels: approved, lgtm, size/M

#452 Improve code coverage on cluster provisioner.
  pkg/apis/eventing/v1alpha1/cluster_provisioner_defaults_test.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types_test.go
Labels: approved, lgtm, size/L

#455 Applying FieldError.Also to eventing.
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  pkg/apis/channels/v1alpha1/bus_validation_test.go
  pkg/apis/channels/v1alpha1/channel_validation_test.go
  pkg/apis/channels/v1alpha1/subscription_validation_test.go
  pkg/apis/eventing/v1alpha1/channel_validation.go
  pkg/apis/eventing/v1alpha1/channel_validation_test.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_validation.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_validation_test.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/apis/eventing/v1alpha1/subscription_validation_test.go
  pkg/apis/feeds/v1alpha1/cluster_event_type_validation_test.go
  pkg/apis/feeds/v1alpha1/event_type_validation_test.go
  pkg/apis/feeds/v1alpha1/feed_validation_test.go
  pkg/apis/flows/v1alpha1/flow_validation_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targettable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/knative/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/doc.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/duck_client.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/generated_expansion.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/clientset/versioned/typed/duck/v1alpha1/topic.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/interface.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/informers/externalversions/duck/v1alpha1/topic.go
  vendor/github.com/knative/pkg/client/informers/externalversions/factory.go
  vendor/github.com/knative/pkg/client/informers/externalversions/generic.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/expansion_generated.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/kresource.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/target.go
  vendor/github.com/knative/pkg/client/listers/duck/v1alpha1/topic.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/XXL

#456 Remove mattmoor from eventing OWNERS.
  OWNERS
Labels: approved, lgtm, size/XS

#459 Subscription controller tweaks
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/subscription_types_test.go
  pkg/controller/eventing/subscription/reconcile.go
  pkg/controller/eventing/subscription/reconcile_test.go
  pkg/controller/testing/table.go
Labels: approved, lgtm, size/L

#460 Update knative/pkg
  Gopkg.lock
  Gopkg.toml
  pkg/apis/eventing/v1alpha1/channel_validation_test.go
  pkg/controller/eventing/subscription/reconcile.go
  vendor/github.com/knative/pkg/apis/duck/patch.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targetable_types.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/apis/kind2resource.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#472 Source kind should be singular in CRD spec
  config/300-source.yaml
Labels: approved, lgtm, size/XS

#473 Fix passing args to variadic func
  pkg/apis/eventing/v1alpha1/source_types.go
Labels: approved, lgtm, size/XS

#466 Cleanup of methods now supported via ducktype.
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_types_test.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types_test.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/subscription_types_test.go
Labels: approved, lgtm, size/L
