Repository knative/eventing, pull requests merged in 2018-10, with the labels that each got.

#471 Cosmetic typofix.
  pkg/sources/github/feedlet/feedlet.go
Labels: approved, lgtm, size/XS

#479 use KindToResource from knative/pkg now that it has been moved there
  pkg/controller/eventing/subscription/reconcile.go
Labels: approved, lgtm, size/S

#481 Add a test for creating a subscription to a Source that resolves then…
  pkg/controller/eventing/subscription/reconcile.go
  pkg/controller/eventing/subscription/reconcile_test.go
Labels: approved, lgtm, size/L

#467 Empty body stops ReplyTo.
  pkg/buses/bus.go
  pkg/buses/message_dispatcher.go
  pkg/buses/message_dispatcher_test.go
Labels: approved, lgtm, size/L

#474 Move the use of `VerifyType` in tests
  Gopkg.lock
  Gopkg.toml
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
  pkg/apis/eventing/v1alpha1/implements_test.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/sinkable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/subscribable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/targetable_types.go
  vendor/github.com/knative/pkg/apis/duck/verify.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#477 Added instruction for installing kafka broker on OpenShift.
  config/buses/kafka/README.md
Labels: approved, lgtm, size/XS

#483 Update knative/test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#416 E2E Go testsuite
  Gopkg.lock
  test/README.md
  test/cleanup.go
  test/clients.go
  test/crd.go
  test/crd_checks.go
  test/e2e-tests.sh
  test/e2e/README.md
  test/e2e/e2e.go
  test/e2e/k8s_events_test.go
  test/e2e/k8sevents/channel.yaml
  test/e2e/k8sevents/e2etestfnnamespace.yaml
  test/e2e/k8sevents/e2etestnamespace.yaml
  test/e2e/k8sevents/flow.yaml
  test/e2e/k8sevents/function.yaml
  test/e2e/k8sevents/k8sevents.yaml
  test/e2e/k8sevents/pod.yaml
  test/e2e/k8sevents/serviceaccount.yaml
  test/e2e/k8sevents/serviceaccountbinding.yaml
  test/e2e/k8sevents/stub.yaml
  test/e2e/k8sevents/subscription.yaml
  test/e2e_flags.go
  test/image_paths.txt
  test/states.go
  test/upload-test-images.sh
  vendor/github.com/knative/pkg/test/cleanup.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
Labels: approved, lgtm, size/XXL

#470 Rename Kafka hook
  README.md
  config/buses/kafka/README.md
  config/buses/kafka/kafka-bus.yaml
  pkg/buses/kafka/dispatcher/main.go
  pkg/buses/kafka/provisioner/main.go
Labels: approved, lgtm, size/S

#486 Added instructions for setting default cluster-bus
  config/buses/gcppubsub/README.md
  config/buses/kafka/README.md
Labels: approved, lgtm, size/S

#490 Add strimzi instructions
  config/buses/kafka/README.md
  config/buses/kafka/broker/README.md
  config/buses/kafka/strimzi/README.md
  config/buses/kafka/strimzi/kafka-ephemeral.yaml
  config/buses/kafka/strimzi/kafka-persistent.yaml
Labels: approved, lgtm, size/L

#493 fix one comment issue.
  pkg/controller/flow/reconcile.go
Labels: approved, lgtm, size/XS

#496 use variable reference instead of hard code port.
  pkg/buses/message_receiver.go
  pkg/controller/bus/controller.go
  pkg/controller/clusterbus/controller.go
Labels: approved, lgtm, needs-ok-to-test, size/S

#501 List only images tagged with latest before tagging
  test/e2e-tests.sh
  test/upload-test-images.sh
Labels: approved, lgtm, size/XS

#492 remove the dead code.
  pkg/sources/container_event_source.go
Labels: approved, lgtm, size/L

#504 Adding config for controller runtime to exclude controllers.
  cmd/controller/controller-runtime-main.go
  cmd/controller/main.go
  config/500-controller.yaml
Labels: approved, lgtm, size/M

#507 Just point to the docs repo for being the best sample source
  sample/README.md
Labels: approved, lgtm, size/S

#435 Create a Sidecar for fanning out HTTP requests
  Gopkg.lock
  cmd/fanoutsidecar/kodata/LICENSE
  cmd/fanoutsidecar/kodata/VENDOR-LICENSE
  cmd/fanoutsidecar/main.go
  pkg/buses/message_receiver.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
  pkg/sidecar/configmap/parse.go
  pkg/sidecar/configmap/parse_test.go
  pkg/sidecar/configmap/watcher/watcher.go
  pkg/sidecar/configmap/watcher/watcher_test.go
  pkg/sidecar/fanout/fanout_handler.go
  pkg/sidecar/fanout/fanout_handler_test.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/sidecar/multichannelfanout/parse.go
  pkg/sidecar/multichannelfanout/parse_test.go
  pkg/sidecar/swappable/swappable.go
  pkg/sidecar/swappable/swappable_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: approved, lgtm, size/XXL

#518 Add channelstatus methods
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_types_test.go
Labels: approved, lgtm, size/L

#505 Bump k8s dep to 1.11.3 and mergo to 0.3.6
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/knative/pkg/apis/duck/doc.go
  vendor/github.com/knative/pkg/apis/duck/proxy.go
  vendor/github.com/knative/pkg/apis/duck/typed.go
  vendor/github.com/knative/pkg/configmap/informed_watcher.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1alpha1/generated.pb.go
  vendor/k8s.io/api/admissionregistration/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta1/generated.pb.go
  vendor/k8s.io/api/apps/v1beta2/generated.pb.go
  vendor/k8s.io/api/authentication/v1/generated.pb.go
  vendor/k8s.io/api/authentication/v1beta1/generated.pb.go
  vendor/k8s.io/api/authorization/v1/generated.pb.go
  vendor/k8s.io/api/authorization/v1beta1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v1/generated.pb.go
  vendor/k8s.io/api/autoscaling/v2beta1/generated.pb.go
  vendor/k8s.io/api/batch/v1/generated.pb.go
  vendor/k8s.io/api/batch/v1beta1/generated.pb.go
  vendor/k8s.io/api/batch/v2alpha1/generated.pb.go
  vendor/k8s.io/api/certificates/v1beta1/generated.pb.go
  vendor/k8s.io/api/core/v1/generated.pb.go
  vendor/k8s.io/api/events/v1beta1/generated.pb.go
  vendor/k8s.io/api/extensions/v1beta1/generated.pb.go
  vendor/k8s.io/api/networking/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1/generated.pb.go
  vendor/k8s.io/api/rbac/v1alpha1/generated.pb.go
  vendor/k8s.io/api/rbac/v1beta1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1alpha1/generated.pb.go
  vendor/k8s.io/api/scheduling/v1beta1/generated.pb.go
  vendor/k8s.io/api/settings/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1/generated.pb.go
  vendor/k8s.io/api/storage/v1alpha1/generated.pb.go
  vendor/k8s.io/api/storage/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/api/resource/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/labels/selector.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.pb.go
  vendor/k8s.io/client-go/restmapper/discovery.go
  vendor/k8s.io/client-go/transport/round_trippers.go
  vendor/k8s.io/code-generator/Godeps/Godeps.json
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/namer.go
Labels: approved, lgtm, size/XXL

#522 Simplify Strimzi install for Kubernetes Kafka deployment
  config/buses/kafka/strimzi/kafka-ephemeral.yaml
  config/buses/kafka/strimzi/kafka-persistent.yaml
Labels: approved, lgtm, size/M

#520 Simplify the controller's main function.
  cmd/controller/main.go
Labels: approved, lgtm, size/M

#484 Create the in-memory-channel ClusterProvisioner
  cmd/fanoutsidecar/main.go
  config/provisioners/in-memory-channel/README.md
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  config/provisioners/in-memory-channel/tmp/bus-with-subs.yaml
  config/provisioners/in-memory-channel/tmp/bus2.yaml
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_types_test.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_types_test.go
  pkg/buses/message_receiver.go
  pkg/controller/eventing/inmemory/channel/controller.go
  pkg/controller/eventing/inmemory/channel/reconcile.go
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
  pkg/controller/eventing/inmemory/clusterprovisioner/controller.go
  pkg/controller/eventing/inmemory/clusterprovisioner/reconcile.go
  pkg/controller/eventing/inmemory/clusterprovisioner/reconcile_test.go
  pkg/controller/eventing/inmemory/controller/main.go
  pkg/sidecar/configmap/parse.go
  pkg/sidecar/configmap/parse_test.go
Labels: approved, lgtm, size/XXL

#509 Re-useable cleaner of test resources
  test/cleanup.go
  test/clients.go
  test/e2e/e2e.go
Labels: approved, lgtm, size/L

#514 Add eventing owner ref helpers for new eventing
  pkg/controller/owner_references.go
Labels: approved, cla: yes, lgtm, size/S

#530 Update VENDOR-LICENSE link.
  cmd/fanoutsidecar/kodata/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XS

#531 Strict channels subscription
  pkg/apis/eventing/v1alpha1/subscribable_channelable_validation.go
  pkg/apis/eventing/v1alpha1/subscription_validation_test.go
  pkg/controller/eventing/subscription/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/S

#533 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#537 Don't use our own text for CODE_OF_CONDUCT.md or CONTRIBUTING.md.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/L

#538 Folllow-up to change wording of contrib text.
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#539 Ask env for preferred bash path.
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS

#482 Adding Knative Eventing Object Model targeting 0.1 release.
  docs/spec/README.md
  docs/spec/images/overview-reference.dot
  docs/spec/images/overview-reference.png
  docs/spec/images/resource-types-overview.svg
  docs/spec/images/resource-types-provisioner.svg
  docs/spec/interfaces.md
  docs/spec/motivation.md
  docs/spec/overview.md
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/L

#541 run update codegen
  Gopkg.lock
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/M

#499 Fix logging typo in e2e-tests.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#494 Subscription Controller supports more than one Subscription per Channel.
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/eventing/subscription/reconcile.go
  pkg/controller/eventing/subscription/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#550 Align Subscription spec name with implementation
  pkg/apis/eventing/v1alpha1/channel_validation_test.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/apis/eventing/v1alpha1/subscription_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/eventing/subscription/reconcile.go
  pkg/controller/eventing/subscription/reconcile_test.go
  pkg/sidecar/fanout/fanout_handler.go
Labels: approved, cla: yes, lgtm, size/L

#546 check the VENDOR-LICENSE, Gopkg.lock and vendor as part of verification
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/S

#540 Include LICENSE and VENDOR-LICENSE in all containers
  pkg/buses/gcppubsub/dispatcher/kodata/LICENSE
  pkg/buses/gcppubsub/dispatcher/kodata/VENDOR-LICENSE
  pkg/buses/gcppubsub/provisioner/kodata/LICENSE
  pkg/buses/gcppubsub/provisioner/kodata/VENDOR-LICENSE
  pkg/buses/kafka/dispatcher/kodata/LICENSE
  pkg/buses/kafka/dispatcher/kodata/VENDOR-LICENSE
  pkg/buses/kafka/provisioner/kodata/LICENSE
  pkg/buses/kafka/provisioner/kodata/VENDOR-LICENSE
  pkg/buses/stub/dispatcher/kodata/LICENSE
  pkg/buses/stub/dispatcher/kodata/VENDOR-LICENSE
  pkg/controller/eventing/inmemory/controller/kodata/LICENSE
  pkg/controller/eventing/inmemory/controller/kodata/VENDOR-LICENSE
  pkg/sources/gcppubsub/kodata/LICENSE
  pkg/sources/gcppubsub/kodata/VENDOR-LICENSE
  pkg/sources/gcppubsub/receive_adapter/kodata/LICENSE
  pkg/sources/gcppubsub/receive_adapter/kodata/VENDOR-LICENSE
  pkg/sources/github/feedlet/kodata/LICENSE
  pkg/sources/github/feedlet/kodata/VENDOR-LICENSE
  pkg/sources/github/receive_adapter/kodata/LICENSE
  pkg/sources/github/receive_adapter/kodata/VENDOR-LICENSE
  pkg/sources/k8sevents/kodata/LICENSE
  pkg/sources/k8sevents/kodata/VENDOR-LICENSE
  pkg/sources/k8sevents/receive_adapter/kodata/LICENSE
  pkg/sources/k8sevents/receive_adapter/kodata/VENDOR-LICENSE
  test/e2e/k8sevents/kodata/LICENSE
  test/e2e/k8sevents/kodata/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/S

#558 Atomically write the file, rather than opening with truncate.
  pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
Labels: approved, cla: yes, lgtm, size/M

#559 Remove the Source CRD, as decided in https://github.com/knative/eventing/pull/482
  cmd/webhook/main.go
  config/300-source.yaml
  pkg/apis/eventing/v1alpha1/source_defaults.go
  pkg/apis/eventing/v1alpha1/source_defaults_test.go
  pkg/apis/eventing/v1alpha1/source_types.go
  pkg/apis/eventing/v1alpha1/source_types_test.go
  pkg/apis/eventing/v1alpha1/source_validation.go
  pkg/apis/eventing/v1alpha1/source_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_source.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/source.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/source.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  pkg/client/listers/eventing/v1alpha1/source.go
  pkg/controller/owner_references.go
Labels: approved, cla: yes, lgtm, size/XXL

#555 No longer use the subscribable interface.
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_types_test.go
  pkg/apis/eventing/v1alpha1/implements_test.go
  pkg/apis/eventing/v1alpha1/subscribable_channelable_validation.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/eventing/inmemory/channel/reconcile.go
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
  pkg/controller/eventing/subscription/reconcile.go
  pkg/controller/eventing/subscription/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#561 Change the Channelable interface to use URIs.
  hack/update-codegen.sh
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/doc.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_validation.go
  pkg/apis/eventing/v1alpha1/channel_validation_test.go
  pkg/apis/eventing/v1alpha1/implements_test.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
  pkg/controller/eventing/subscription/reconcile.go
  pkg/controller/eventing/subscription/reconcile_test.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
  pkg/sidecar/configmap/parse_test.go
  pkg/sidecar/configmap/watcher/watcher_test.go
  pkg/sidecar/fanout/fanout_handler.go
  pkg/sidecar/fanout/fanout_handler_test.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/sidecar/multichannelfanout/parse_test.go
  pkg/sidecar/swappable/swappable_test.go
Labels: approved, cla: yes, lgtm, size/XL

#562 Align ClusterChannelProvisioner with spec
  cmd/webhook/main.go
  config/300-clusterprovisioner.yaml
  config/provisioners/in-memory-channel/README.md
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  pkg/apis/eventing/logkey/constants.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_defaults.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_defaults_test.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types_test.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_validation.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_validation_test.go
  pkg/apis/eventing/v1alpha1/cluster_provisioner_validation_test.go
  pkg/apis/eventing/v1alpha1/implements_test.go
  pkg/apis/eventing/v1alpha1/register.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/clusterchannelprovisioner.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/clusterprovisioner.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_clusterchannelprovisioner.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_clusterprovisioner.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/eventing/v1alpha1/clusterchannelprovisioner.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/eventing/v1alpha1/clusterchannelprovisioner.go
  pkg/client/listers/eventing/v1alpha1/clusterprovisioner.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  pkg/controller/eventing/inmemory/channel/reconcile.go
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
  pkg/controller/eventing/inmemory/clusterchannelprovisioner/controller.go
  pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile.go
  pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile_test.go
  pkg/controller/eventing/inmemory/controller/main.go
  pkg/controller/owner_references.go
Labels: approved, cla: yes, lgtm, size/XXL

#544 Flatten ProvisionerReference
  docs/spec/spec.md
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_validation_test.go
  pkg/apis/eventing/v1alpha1/provisioner_reference.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/eventing/inmemory/channel/reconcile.go
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
  pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile.go
  pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#554 minor edits
  docs/spec/overview.md
Labels: approved, cla: yes, lgtm, size/S

#564 Update in-memory-channel.yaml to conform to the changes made in https://github.com/knative/eventing/pull/562
  config/provisioners/in-memory-channel/in-memory-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#567 fix typo in the path name
  config/provisioners/in-memory-channel/README.md
Labels: approved, cla: yes, lgtm, size/XS

#556 scan all main packages for when collecting licenses
  hack/update-deps.sh
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#566 Update pkg for error merging
  Gopkg.lock
  Gopkg.toml
  third_party/VENDOR-LICENSE
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/gobuffalo/envy/LICENSE.txt
  vendor/github.com/gobuffalo/envy/envy.go
  vendor/github.com/gobuffalo/envy/version.go
  vendor/github.com/joho/godotenv/LICENCE
  vendor/github.com/joho/godotenv/godotenv.go
  vendor/github.com/knative/pkg/apis/duck/patch.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/channelable_types.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/configmap/filter.go
  vendor/github.com/knative/pkg/configmap/store.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/webhook/certs.go
  vendor/github.com/knative/pkg/webhook/webhook.go
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/markbates/inflect/LICENCE
  vendor/github.com/markbates/inflect/helpers.go
  vendor/github.com/markbates/inflect/inflect.go
  vendor/github.com/markbates/inflect/name.go
  vendor/github.com/markbates/inflect/version.go
Labels: approved, cla: yes, lgtm, size/XXL

#569 use the full name for the clusterchannelprovisioner kind CRD file
  config/300-clusterchannelprovisioner.yaml
Labels: approved, cla: yes, lgtm, size/XS

#568 Add Channels with no subscribers to config map
  pkg/controller/eventing/inmemory/channel/reconcile.go
Labels: approved, cla: yes, lgtm, size/S

#570 Add a unit test to prevent regressions of https://github.com/knative/eventing/pull/568
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/M
