Repository knative/eventing, pull requests merged in 2018-12, with the labels that each got.

#655 Format markdown
  .github/issue-template.md
  .github/pull-request-template.md
  DEVELOPMENT.md
  README.md
  config/provisioners/in-memory-channel/README.md
  config/provisioners/kafka/README.md
  config/provisioners/kafka/broker/README.md
  docs/personas.md
  docs/spec/interfaces.md
  docs/spec/motivation.md
  docs/spec/overview.md
  hack/README.md
  hack/release.md
  roadmap.md
  test/README.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/L

#657 Add @Harwayne as reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/S

#659 Fixture builders for Subscription reconcile tests
  pkg/controller/eventing/subscription/reconcile_test.go
  pkg/controller/testing/builder.go
  pkg/controller/testing/table.go
Labels: approved, cla: yes, lgtm, size/L

#652 Kafka provisioner persists its finalizer before manipulating Kafka
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/kafka/controller/channel/reconcile.go
  pkg/provisioners/kafka/controller/channel/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#664 Fix spelling errors
  pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile.go
Labels: approved, cla: yes, lgtm, size/XS

#665 Format markdown
  CODE_OF_CONDUCT.md
  DEVELOPMENT.md
  README.md
  config/provisioners/gcppubsub/README.md
  config/provisioners/in-memory-channel/README.md
  config/provisioners/kafka/README.md
  config/provisioners/kafka/broker/README.md
  docs/personas.md
  docs/spec/README.md
  docs/spec/interfaces.md
  docs/spec/motivation.md
  docs/spec/overview.md
  docs/spec/spec.md
  hack/README.md
  hack/release.md
  roadmap.md
  sample/README.md
  test/README.md
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, size/XL

#660 GCP PubSub controller persists its finalizer before manipulating anything outside of the cluster
  pkg/provisioners/gcppubsub/controller/channel/reconcile.go
  pkg/provisioners/gcppubsub/controller/channel/reconcile_test.go
  pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile.go
  pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#641 message_receiver.go unit tests.
  pkg/provisioners/message_receiver.go
  pkg/provisioners/message_receiver_test.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler_test.go
Labels: approved, cla: yes, lgtm, size/L

#666 CreateK8sService diffs its expected spec against the actual spec and updates the K8s Service appropriately
  config/provisioners/gcppubsub/gcppubsub.yaml
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/provisioner_util.go
Labels: approved, cla: yes, lgtm, size/L

#675 RBAC permission to update Services. Should have been part of #666.
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  config/provisioners/kafka/kafka.yaml
  config/provisioners/natss/provisioner.yaml
Labels: approved, cla: yes, lgtm, size/XS

#667 Update test-infra to include latest features of release.sh
  Gopkg.lock
  hack/release.md
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#669 Run goimports
  pkg/provisioners/gcppubsub/controller/channel/reconcile_test.go
  pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/S

#670 Format markdown
  docs/spec/README.md
Labels: approved, cla: yes, lgtm, size/XS

#679 Format markdown
  config/provisioners/natss/README.md
  config/provisioners/natss/natss/README.md
  hack/release.md
Labels: approved, cla: yes, lgtm, size/M

#683 Pin sources release to last known good
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#678 Fix spelling errors
  pkg/provisioners/natss/dispatcher/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#677 golang format tools
  pkg/provisioners/natss/controller/channel/reconcile_test.go
  pkg/provisioners/natss/dispatcher/dispatcher/dispatcher.go
  pkg/provisioners/natss/dispatcher/main.go
  pkg/provisioners/natss/stanutil/stanutil.go
Labels: approved, cla: yes, lgtm, size/S

#685 golang format tools
  pkg/channeldefaulter/channel_defaulter_test.go
  pkg/provisioners/gcppubsub/controller/channel/reconcile.go
  pkg/provisioners/gcppubsub/controller/cmd/main.go
  pkg/provisioners/gcppubsub/dispatcher/cmd/main.go
  pkg/provisioners/gcppubsub/dispatcher/dispatcher/reconcile.go
  pkg/provisioners/gcppubsub/dispatcher/receiver/receiver.go
  pkg/provisioners/gcppubsub/util/creds.go
  pkg/provisioners/gcppubsub/util/creds_test.go
  pkg/provisioners/gcppubsub/util/names_test.go
  pkg/provisioners/gcppubsub/util/testcreds/helper.go
  pkg/provisioners/kafka/dispatcher/dispatcher_test.go
  pkg/provisioners/natss/dispatcher/dispatcher/dispatcher.go
  pkg/provisioners/natss/stanutil/stanutil.go
Labels: approved, cla: yes, lgtm, size/S

#684 Fallback to `status.domainInternal` if not `Addressable`
  pkg/controller/eventing/subscription/reconcile.go
  pkg/controller/eventing/subscription/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/M

#689 Switching rbac from betav1 to v1
  config/201-clusterrolebinding.yaml
  config/provisioners/gcppubsub/gcppubsub.yaml
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  config/provisioners/kafka/kafka.yaml
  config/provisioners/natss/provisioner.yaml
Labels: approved, cla: yes, lgtm, size/S

#674 Use GenerateName for Channel's Service and VirtualService
  pkg/controller/eventing/inmemory/channel/reconcile.go
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/gcppubsub/controller/channel/reconcile.go
  pkg/provisioners/gcppubsub/controller/channel/reconcile_test.go
  pkg/provisioners/kafka/controller/channel/reconcile.go
  pkg/provisioners/kafka/controller/channel/reconcile_test.go
  pkg/provisioners/natss/controller/channel/reconcile.go
  pkg/provisioners/natss/controller/channel/reconcile_test.go
  pkg/provisioners/provisioner_util.go
  pkg/provisioners/provisioner_util_test.go
Labels: approved, cla: yes, lgtm, size/XL

#695 Update test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L
