Repository knative/eventing, pull requests merged in 2018-07, with the labels that each got.

#269 Issue 235
  pkg/apis/feeds/v1alpha1/feed_types.go
  pkg/controller/feed/reconcile.go
  pkg/controller/feed/reconcile_test.go
  pkg/controller/flow/flow.go
  pkg/sources/k8sevents/watcher_pod.go
  test/e2e-tests.sh
  test/e2e/k8sevents/flow.yaml
  test/e2e/k8sevents/stub.yaml
Labels: approved, lgtm

#271 Add service entries so receive adapter can access metadata server
  pkg/sources/gcppubsub/gcppubsub-serviceentry.yaml
Labels: approved, lgtm, size/M

#275 Remove `k8sevent` sample from eventing now that it's in docs.
  sample/README.md
  sample/flow/README.md
  sample/flow/flow.yaml
  sample/k8s_events_function/README.md
  sample/k8s_events_function/README_CHANNEL.md
  sample/k8s_events_function/feed-channel.yaml
  sample/k8s_events_function/feed.yaml
  sample/k8s_events_function/function.yaml
  sample/k8s_events_function/serviceaccount.yaml
  sample/k8s_events_function/serviceaccountbinding.yaml
  test/e2e/k8sevents/function.go
  test/e2e/k8sevents/function.yaml
Labels: approved, lgtm, size/XL

#272 Pubsub cloudevents
  pkg/sources/gcppubsub/eventsource.yaml
  pkg/sources/gcppubsub/eventtype.yaml
  pkg/sources/gcppubsub/gcp_pubsub.go
  pkg/sources/gcppubsub/googleapis-serviceentry.yaml
  pkg/sources/gcppubsub/receive_adapter/receive_adapter.go
  pkg/sources/gcppubsub/watcher_pod.go
  sample/gcp_pubsub_function/README.md
  sample/gcp_pubsub_function/flow.yaml
  sample/gcp_pubsub_function/function.go
Labels: approved, lgtm, size/L

#278 Add condition for action target resolved
  pkg/apis/flows/v1alpha1/flow_types.go
  pkg/apis/flows/v1alpha1/flow_types_test.go
  pkg/controller/flow/flow.go
  test/e2e-tests.sh
Labels: approved, lgtm, size/M

#279 Use serving style system package for namespace.
  cmd/webhook/main.go
  pkg/controller/channel/controller.go
  pkg/controller/clusterbus/controller.go
  pkg/system/names.go
  pkg/webhook/certs.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/M

#288 Add cluster scoped feed webhooks
  pkg/apis/feeds/v1alpha1/cluster_event_source_types.go
  pkg/apis/feeds/v1alpha1/event_type_types.go
  pkg/apis/feeds/v1alpha1/feed_types.go
  pkg/controller/feed/reconcile.go
  pkg/webhook/cluster_event_type.go
  pkg/webhook/event_type.go
  pkg/webhook/feed.go
  pkg/webhook/feed_test.go
  pkg/webhook/webhook_channels_test.go
  pkg/webhook/webhook_feeds_test.go
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/XXL

#293 Add "godoc" and "go report" badges
  README.md
Labels: approved, lgtm, size/XS
