Repository knative/eventing, pull requests merged in 2019-10, with the labels that each got.

#1954 Update subscription upon sequence update
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1983 Don't restrict namespace for perf test objects
  test/performance/tools/common.sh
Labels: approved, area/performance, area/test-and-release, cla: yes, kind/bug, lgtm, size/XS

#1985 adding email and service accounts to dev mako configs
  test/test_images/performance/dev.config
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1988 nil check in SetSpanID
  hack/set-span-id.patch
  pkg/tracing/traceparent_test.go
  vendor/go.opencensus.io/trace/trace.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1982 Fix spelling errors
  pkg/tracing/traceparent.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1984 Delete roadmap.md
  docs/planning/roadmap.md
Labels: approved, cla: yes, kind/cleanup, kind/doc, lgtm

#1992 Use the correct zap sugared logger syntax
  cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1994 Mako dev.config update
  test/test_images/performance/dev.config
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1993 Add permissions for eventing APIs to k8s's default view and edit role
  config/200-clusterrole-namespaced.yaml
Labels: approved, cla: yes, lgtm, size/S

#1999 Do not fail the performance cluster job if there's error in deletion
  test/performance/tools/common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1990 Remove incorrect host names from tracing setup.
  cmd/apiserver_receive_adapter/main.go
  cmd/cronjob_receive_adapter/main.go
Labels: approved, cla: yes, lgtm, size/XS

#2001 Remove old perf test code and doc
  test/README.md
  test/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1856 Adding Source Spec.
  config/200-source-observer-clusterrole.yaml
  config/300-apiserversource.yaml
  config/300-containersource.yaml
  config/300-cronjobsource.yaml
  docs/spec/README.md
  docs/spec/sources.md
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/L

#2006 redeploy subscription if spec changes
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
Labels: approved, cla: yes, lgtm, size/M

#1997 fixes #1996 , use Role in the test namespace instead of ClusterRole
  test/base/resources/kube.go
  test/common/creation.go
  test/e2e/source_api_server_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#2008 Passing benchmark ids to mako setup
  test/performance/broker-imc/continuous/200-broker-imc.yaml
  test/performance/broker-imc/dev.config
  test/test_images/performance/aggregator.go
  test/test_images/performance/kodata/dev.config
  test/test_images/performance/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2010 change content-type of performance tests to application/json
  test/common/cloudevents_vegeta_targeter.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1995 E2E Test for Broker Tracing
  cmd/broker/ingress/main.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/ingress/ingress_handler.go
  pkg/kncloudevents/good_client.go
  pkg/tracing/names.go
  pkg/tracing/names_test.go
  test/common/creation.go
  test/common/operation.go
  test/common/tracker.go
  test/conformance/broker_tracing_test.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
  test/conformance/helpers/uri.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#2014 Updates to ResourceTracker
  pkg/duck/resource.go
  pkg/duck/resource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/testing/mock_resource_tracker.go
  pkg/reconciler/trigger/controller.go
Labels: approved, cla: yes, lgtm, size/L

#2000 Common trace test infrastructure
  test/conformance/channel_tracing_test.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2017 Tests only wait for Pods that they explicitly create.
  test/common/client.go
  test/common/creation.go
  test/common/operation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2021 Delete 200-source-resolvers-clusterrole.yaml and bind clusterrole sou…
  config/200-source-resolvers-clusterrole.yaml
  config/201-clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/M

#2018 Make broker.spec.channelTempalte immutable
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#2015 fix testcases, duplicated if conditions in subscribe_types_test.go
  pkg/apis/duck/v1alpha1/subscribable_types_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2022 Refactor tracing tests to make it easier to use in other repos.
  test/conformance/broker_tracing_test.go
  test/conformance/channel_tracing_test.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2023 GetAddressableURI supports status.addressable.url
  test/base/resource_inspectors.go
  test/common/operation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2004 Broker URL additional column
  config/300-broker.yaml
  config/300-sequence.yaml
  config/channels/in-memory-channel/300-in-memory-channel.yaml
Labels: approved, cla: yes, lgtm, size/S

#2031 Remove the race condition using the TestCloudEventsClient.
  pkg/adapter/apiserver/adapter_test.go
  pkg/adapter/cronjobevents/adapter_test.go
  pkg/kncloudevents/testing/test_client.go
Labels: approved, cla: yes, lgtm, size/M

#2035 we have only channels in messaging.knative.dev
  config/200-addressable-resolvers-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2027 Tracking resources refactoring
  pkg/duck/listable.go
  pkg/duck/listable_test.go
  pkg/duck/resource.go
  pkg/duck/subscriber.go
  pkg/duck/subscriber_test.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/mock_resource_tracker.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  test/conformance/helpers/broker_tracing_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2037 shared ra main
  cmd/apiserver_receive_adapter/main.go
  cmd/cronjob_receive_adapter/main.go
  pkg/adapter/apiserver/adapter.go
  pkg/adapter/apiserver/adapter_test.go
  pkg/adapter/config.go
  pkg/adapter/cronjobevents/adapter.go
  pkg/adapter/cronjobevents/adapter_test.go
  pkg/adapter/main.go
  pkg/adapter/main_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2033 Adding matzew to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1979 Performance test image refactor
  Gopkg.lock
  test/common/cloudevents_vegeta_targeter.go
  test/common/performance/aggregator/aggregator.go
  test/common/performance/common/constants.go
  test/common/performance/common/event_timestamp.go
  test/common/performance/common/executor.go
  test/common/performance/common/pace.go
  test/common/performance/event_state/client.go
  test/common/performance/event_state/event_state.pb.go
  test/common/performance/event_state/event_state.proto
  test/common/performance/image_helpers.go
  test/common/performance/receiver/id_extractor.go
  test/common/performance/receiver/receiver.go
  test/common/performance/receiver/type_extractor.go
  test/common/performance/sender/http_load_generator.go
  test/common/performance/sender/load_generator.go
  test/common/performance/sender/request_interceptor.go
  test/common/performance/sender/request_interceptor_test.go
  test/common/performance/sender/sender.go
  test/performance/README.md
  test/performance/broker-imc/200-broker-perf.yaml
  test/performance/broker-imc/continuous/200-broker-imc.yaml
  test/performance/channel-imc/200-channel-perf.yaml
  test/performance/direct/200-direct-perf.yaml
  test/test_images/performance/README.md
  test/test_images/performance/main.go
  test/test_images/performance/pod.yaml
  test/test_images/performance/sender_receiver.go
  third_party/VENDOR-LICENSE
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XXL

#2042 hack/udpate-deps.sh removes OWNER_ALIASES.
  hack/update-deps.sh
  vendor/knative.dev/pkg/OWNERS_ALIASES
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2043 updating development guide
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#2041 Update knative.dev/pkg.
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/source/doc.go
  vendor/knative.dev/pkg/source/source_labels.go
  vendor/knative.dev/pkg/test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/M

#2049 E2E tracing tests does not set sampling to 100%.
  test/conformance/helpers/tracing/zipkin.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2051 Remove openapi-gen annotations
  pkg/apis/sources/v1alpha1/apiserver_types.go
Labels: approved, cla: yes, lgtm, size/XS

#2056 adding notes that for KO u need to auth against a container registry
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#2054 Improve Broker's HTTP Client Configuration
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  pkg/broker/filter/filter_handler.go
  pkg/kncloudevents/good_client.go
Labels: approved, cla: yes, lgtm, size/M

#2063 Fixing outdated broker crd file
  config/300-broker.yaml
Labels: approved, cla: yes, lgtm, size/S

#2066 Update to cloudevents golang sdk v0.10.0, adding v1.0 spec support.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/error.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
Labels: approved, cla: yes, lgtm, size/M

#2030 make cronjobsource and apiserversource controllers more consistent
  pkg/apis/sources/v1alpha1/cron_job_lifecycle.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/apiserversource/controller_test.go
  pkg/reconciler/cronjobsource/controller.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
Labels: approved, cla: yes, lgtm, size/L

#2064 Remove provisioner code
  Gopkg.lock
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  pkg/channel/logger.go
  pkg/channel/logger_test.go
  pkg/defaultchannel/channel_defaulter_test.go
Labels: approved, cla: yes, lgtm, size/L

#2068 Do not emit metrics in e2e test
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2069 minor update to logger obj
  cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/XS

#2070 cleaning up broker code and align w/ other components
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
Labels: approved, cla: yes, lgtm, size/M

#2071 Rename helloworld test image to print
  test/base/resources/kube.go
  test/test_images/print/main.go
  test/test_images/print/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2074 fixing RBAC for finalizers sub-resource of Channel
  config/200-controller-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2079 Format markdown
  DEVELOPMENT.md
  test/test_images/performance/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#2080 golang format tools
  cmd/broker/ingress/main.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
  pkg/duck/subscriber_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/trigger/controller.go
  test/common/performance/event_state/event_state.pb.go
  test/common/performance/receiver/receiver.go
  test/test_images/performance/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#2082 duckv1beta1.Status -> duckv1.Status
  Gopkg.lock
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/eventtype_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/eventtype_types.go
  pkg/apis/eventing/v1alpha1/test_helper.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  pkg/apis/messaging/v1alpha1/parallel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/parallel_types.go
  pkg/apis/messaging/v1alpha1/sequence_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/sequence_types.go
  pkg/apis/messaging/v1alpha1/subscription_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/subscription_types.go
  pkg/apis/sources/v1alpha1/apiserver_types.go
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
Labels: approved, cla: yes, lgtm, size/L

#2085 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/v1alpha1/destination.go
  vendor/knative.dev/pkg/metrics/metricskey/constants_serving.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/README.md
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2086 Update knative.dev/pkg
  Gopkg.lock
  pkg/broker/filter/stats_reporter_test.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/v1alpha1/destination.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
Labels: approved, cla: yes, lgtm, size/L

#2084 Registry in Source Spec
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/M

#2091 Update knative.dev/pkg
  Gopkg.lock
  vendor/knative.dev/pkg/apis/v1alpha1/destination.go
Labels: approved, cla: yes, lgtm, size/M

#2097 Format markdown
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2098 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#2099 Adding standard duck label on CRD to signal this resource adheres to Addressable
  config/300-broker.yaml
  config/300-channel.yaml
  config/300-parallel.yaml
  config/300-sequence.yaml
  config/channels/in-memory-channel/300-in-memory-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2100 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/gcp_metadata.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2093 Add yaml to explicitly create our webhook configs.
  Gopkg.lock
  cmd/webhook/main.go
  config/500-webhook-configuration.yaml
  config/500-webhook.yaml
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/webhook/config_validation_controller.go
  vendor/knative.dev/pkg/webhook/resource_admission_controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/L

#2073 Use new performance test script
  Gopkg.lock
  Gopkg.toml
  test/performance/benchmarks/broker-imc/100-broker-perf-setup.yaml
  test/performance/benchmarks/broker-imc/200-broker-perf.yaml
  test/performance/benchmarks/broker-imc/cluster.yaml
  test/performance/benchmarks/broker-imc/continuous/100-broker-imc-setup.yaml
  test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml
  test/performance/benchmarks/broker-imc/dev.config
  test/performance/benchmarks/channel-imc/100-channel-perf-setup.yaml
  test/performance/benchmarks/channel-imc/200-channel-perf.yaml
  test/performance/benchmarks/channel-imc/cluster.yaml
  test/performance/benchmarks/channel-imc/continuous/100-channel-imc-setup.yaml
  test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml
  test/performance/benchmarks/channel-imc/dev.config
  test/performance/performance-tests.sh
  test/performance/tools/README.md
  test/performance/tools/common.sh
  test/performance/tools/recreate_clusters.sh
  test/performance/tools/update_clusters.sh
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/google.golang.org/api/googleapi/googleapi.go
  vendor/google.golang.org/api/googleapi/internal/uritemplates/uritemplates.go
  vendor/google.golang.org/api/googleapi/internal/uritemplates/utils.go
  vendor/google.golang.org/api/googleapi/types.go
  vendor/google.golang.org/api/internal/gensupport/buffer.go
  vendor/google.golang.org/api/internal/gensupport/doc.go
  vendor/google.golang.org/api/internal/gensupport/json.go
  vendor/google.golang.org/api/internal/gensupport/jsonfloat.go
  vendor/google.golang.org/api/internal/gensupport/media.go
  vendor/google.golang.org/api/internal/gensupport/params.go
  vendor/google.golang.org/api/internal/gensupport/resumable.go
  vendor/google.golang.org/api/internal/gensupport/send.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2095 Destination in Parallel
  Gopkg.lock
  pkg/apis/messaging/v1alpha1/parallel_types.go
  pkg/apis/messaging/v1alpha1/parallel_validation.go
  pkg/apis/messaging/v1alpha1/parallel_validation_test.go
  pkg/apis/messaging/v1alpha1/sequence_types.go
  pkg/apis/messaging/v1alpha1/sequence_validation.go
  pkg/apis/messaging/v1alpha1/sequence_validation_test.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/parallel/resources/subscription.go
  pkg/reconciler/sequence/resources/subscription.go
  pkg/reconciler/testing/parallel.go
  pkg/reconciler/testing/sequence.go
  test/e2e/parallel_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2102 Updating pkg to latest for 0.10 release.
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#2089 Update APIServerSource to use Destination
  Gopkg.lock
  config/300-apiserversource.yaml
  pkg/apis/sources/v1alpha1/apiserver_types.go
  pkg/apis/sources/v1alpha1/apiserver_validation.go
  pkg/apis/sources/v1alpha1/apiserver_validation_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/apiserversource/resources/eventtype.go
  test/e2e/source_api_server_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2103 All performance test infra shares one single service account
  Gopkg.lock
  test/performance/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2106 golang format tools
  pkg/apis/eventing/v1alpha1/trigger_validation_test.go
  pkg/apis/messaging/v1alpha1/subscription_lifecycle.go
  pkg/duck/subscriber_test.go
  pkg/reconciler/trigger/trigger_test.go
  test/base/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#2110 remove SubscriberSpec from the API
  Gopkg.lock
  pkg/apis/messaging/v1alpha1/subscription_types.go
  pkg/apis/messaging/v1alpha1/subscription_validation.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/duck/subscriber.go
  pkg/duck/subscriber_test.go
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
Labels: approved, cla: yes, lgtm, size/L

#2108 Update ApiServerSource to warn on setting deprecated ref.
  pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/testing/apiserversource.go
Labels: approved, cla: yes, lgtm, size/M

#2115 use consistent deprecation warning message
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/testing/subscription.go
Labels: approved, cla: yes, lgtm, size/XS

#2109 Update ContainerSource to use Destination
  config/300-containersource.yaml
  pkg/apis/sources/v1alpha1/containersource_lifecycle.go
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/containersource_validation.go
  pkg/apis/sources/v1alpha1/containersource_validation_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/containersource/controller.go
  test/e2e/source_container_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2114 add ready and age columns
  config/300-apiserversource.yaml
  config/300-cronjobsource.yaml
Labels: approved, cla: yes, lgtm, size/S

#2105 Parallel - Sequence Destination updates
  config/300-parallel.yaml
  config/300-sequence.yaml
  pkg/apis/messaging/v1alpha1/parallel_lifecycle.go
  pkg/apis/messaging/v1alpha1/parallel_validation.go
  pkg/apis/messaging/v1alpha1/parallel_validation_test.go
  pkg/apis/messaging/v1alpha1/sequence_lifecycle.go
  pkg/apis/messaging/v1alpha1/sequence_validation_test.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/testing/parallel.go
  pkg/reconciler/testing/sequence.go
  test/e2e/parallel_test.go
  test/e2e/sequence_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#2104 Add Trigger tests for resolving references
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#2107 Update CronJobSource to use Destination
  config/300-cronjobsource.yaml
  pkg/apis/sources/v1alpha1/cron_job_lifecycle.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
  pkg/apis/sources/v1alpha1/cron_job_validation.go
  pkg/apis/sources/v1alpha1/cron_job_validation_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/cronjobsource/controller.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/cronjobsource/resources/eventtype.go
  pkg/reconciler/trigger/trigger_test.go
  test/e2e/source_container_test.go
  test/e2e/source_cron_job_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2118 Adding nachocano to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2119 golang format tools
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/containersource/controller.go
  pkg/reconciler/cronjobsource/controller.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2059 chore(spec): Clarify that a a Callable returns 0 or 1 event
  docs/spec/interfaces.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1949 Initial error handling support
  docs/delivery/README.md
  docs/delivery/imc-one-per-subcriber.yaml
  docs/delivery/imc.yaml
  pkg/apis/duck/v1alpha1/channel_template_types.go
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/channelable_types_test.go
  pkg/apis/duck/v1alpha1/delivery_types.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#2034 Enable eventing when a Trigger is created for first time
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/apis/eventing/v1alpha1/trigger_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation_test.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/controller_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2123 Add vaikas to OWNERS via new account
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2125 approver's list comment
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2126 add application/json encoding
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
  pkg/adapter/cronjobevents/adapter.go
Labels: approved, cla: yes, lgtm, size/M

#2133 Whitelist cshou for running perf tests
  test/performance/benchmarks/broker-imc/dev.config
  test/performance/benchmarks/channel-imc/dev.config
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2127 Pull in the latest knative/pkg, incl. webhook refactor.
  Gopkg.lock
  Gopkg.toml
  cmd/webhook/main.go
  config/200-webhook-clusterrole.yaml
  config/500-webhook-configuration.yaml
  config/500-webhook.yaml
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/crd_validation_test.go
  pkg/apis/eventing/v1alpha1/eventtype_types.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/apis/messaging/v1alpha1/crd_validation_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  pkg/apis/messaging/v1alpha1/parallel_types.go
  pkg/apis/messaging/v1alpha1/sequence_types.go
  pkg/apis/messaging/v1alpha1/subscription_types.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/mutatingwebhookconfiguration/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/validatingwebhookconfiguration/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1beta1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/clients/dynamicclient/dynamicclient.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/test/junit/junit.go
  vendor/knative.dev/pkg/test/mako/alerter/slack/message.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/apicoverage_recorder.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/webhook/webhook.go
  vendor/knative.dev/pkg/webhook/README.md
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/context.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/resourcesemantics.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/user_info.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/testing/factory.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL
