Repository knative/eventing, pull requests merged in 2019-05, with the labels that each got.

#1132 golang format tools
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1119 Remove Istio dependency from Eventing (Part - 5) - final cleanup
  Gopkg.lock
  config/100-namespace.yaml
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  contrib/gcppubsub/config/gcppubsub.yaml
  contrib/kafka/config/kafka.yaml
  contrib/natss/config/broker/README.md
  contrib/natss/config/provisioner.yaml
  docs/broker/README.md
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/containersource/resources/deployment.go
  pkg/reconciler/containersource/resources/deployment_test.go
  pkg/reconciler/cronjobsource/resources/receive_adapter.go
  pkg/reconciler/cronjobsource/resources/receive_adapter_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/v1alpha1/broker/broker_test.go
  pkg/reconciler/v1alpha1/broker/resources/filter.go
  pkg/reconciler/v1alpha1/broker/resources/ingress.go
  test/crd.go
  test/e2e/single_event_test.go
  vendor/github.com/knative/pkg/client/listers/istio/v1alpha3/destinationrule.go
  vendor/github.com/knative/pkg/client/listers/istio/v1alpha3/expansion_generated.go
  vendor/github.com/knative/pkg/client/listers/istio/v1alpha3/gateway.go
  vendor/github.com/knative/pkg/client/listers/istio/v1alpha3/virtualservice.go
Labels: approved, cla: yes, lgtm, size/XL

#1135 Remove unneeded log keys.
  cmd/controller/main.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/v1alpha1/broker/broker.go
Labels: approved, cla: yes, lgtm, size/S

#1142 Format markdown
  docs/broker/README.md
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1145 Add hacky sleep trying to mitigate the test flakiness for now
  test/e2e/e2e.go
Labels: approved, cla: yes, lgtm, size/XS

#1130 Bind webhook controller to a non priviliged port
  cmd/webhook/main.go
  config/400-webhook-service.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1138 Fix typo (contining -> continuing).
  test/test_images/sendevent/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1140 Remove receive adapter images that are not needed
  config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1143 golang format tools
  pkg/adapter/apiserver/adapter_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1136 Move Broker's reconciler out of v1alpha1
  cmd/controller/main.go
  docs/broker/README.md
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/filter.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#1148 Remove Knative Serving installation step
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1128 Fixing namespace reconciler bugs
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/namespace/resources/labels.go
Labels: approved, cla: yes, lgtm, size/L

#1101 Add new E2E test case for event transformation with non-default broker
  test/crd.go
  test/e2e/broker_event_transformation_test.go
  test/e2e/broker_trigger_test.go
  test/e2e/e2e.go
  test/e2e/event_transformation_test.go
  test/e2e/main_test.go
  test/test_images/sendevent/main.go
  test/test_images/transformevents/main.go
Labels: approved, cla: yes, lgtm, size/L

#1150 Fix spelling errors
  test/e2e/broker_event_transformation_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1104 reconcileErr
  pkg/reconciler/broker/broker.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#1141 Adding back statefulSet w/ 0 replicas
  contrib/kafka/config/kafka.yaml
Labels: approved, cla: yes, lgtm, size/S

#1157 Adding comment for reason behind replicas:0
  contrib/kafka/config/kafka.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1137 Update test-infra: some fixes
  Gopkg.lock
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#859 Record the decision on messaging and eventing apiGroups
  docs/decisions/broker-trigger-model.svg
  docs/decisions/channel-subscription-model.svg
  docs/decisions/eventing-and-messaging.md
Labels: approved, cla: yes, lgtm, size/M

#1154 in-memory Channels are asynchronous
  cmd/fanoutsidecar/main.go
  pkg/channelwatcher/channel_watcher.go
  pkg/channelwatcher/channel_watcher_test.go
  pkg/sidecar/multichannelfanout/config.go
  pkg/sidecar/multichannelfanout/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#1015 Registry Design
  docs/registry/README.md
Labels: approved, cla: yes, lgtm, size/L

#1146 Creating EventType upon CronJobSource CO instantiation
  Gopkg.lock
  cmd/cronjob_receive_adapter/main.go
  cmd/sources-controller/main.go
  config/300-eventtype.yaml
  pkg/adapter/cronjobevents/adapter.go
  pkg/apis/sources/v1alpha1/cron_job_lifecycle.go
  pkg/apis/sources/v1alpha1/cron_job_lifecycle_test.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/cronjobsource/resources/eventtype.go
  pkg/reconciler/cronjobsource/resources/receive_adapter.go
  pkg/reconciler/cronjobsource/resources/receive_adapter_test.go
  pkg/reconciler/testing/cronjobsource.go
  pkg/reconciler/testing/eventtype.go
  pkg/utils/utils.go
Labels: approved, cla: yes, lgtm, size/L

#1120 Adding finalizers for a more constraint RBAC
  config/200-controller-clusterrole.yaml
  config/provisioners/in-memory-channel/in-memory-channel.yaml
Labels: approved, cla: yes, lgtm, size/S

#1133 set owner reference on apiserver receive adapter
  pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  pkg/apis/sources/v1alpha1/apiserver_types.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1158 add APIserver source spec description
  config/300-apiserversource.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1170 Format markdown
  docs/registry/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1168 Use kmeta.NewControllerRef
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
  pkg/provisioners/provisioner_util.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1169 golang format tools
  pkg/adapter/cronjobevents/adapter.go
  pkg/reconciler/cronjobsource/resources/eventtype.go
  pkg/utils/utils.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1163 Renamed fanout sidecar to in-memory dispatcher
  Gopkg.lock
  cmd/fanoutsidecar/kodata/HEAD
  cmd/fanoutsidecar/kodata/LICENSE
  cmd/fanoutsidecar/kodata/VENDOR-LICENSE
  cmd/in_memory/controller/kodata/LICENSE
  cmd/in_memory/controller/kodata/VENDOR-LICENSE
  cmd/in_memory/controller/main.go
  cmd/in_memory/dispatcher/kodata/LICENSE
  cmd/in_memory/dispatcher/kodata/VENDOR-LICENSE
  cmd/in_memory/dispatcher/main.go
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  contrib/kafka/pkg/dispatcher/dispatcher.go
  contrib/kafka/pkg/dispatcher/dispatcher_test.go
  pkg/channelwatcher/channel_watcher.go
  pkg/channelwatcher/channel_watcher_test.go
  pkg/provisioners/fanout/fanout_handler.go
  pkg/provisioners/fanout/fanout_handler_test.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
  pkg/provisioners/inmemory/controller/kodata/LICENSE
  pkg/provisioners/inmemory/controller/kodata/VENDOR-LICENSE
  pkg/provisioners/multichannelfanout/config.go
  pkg/provisioners/multichannelfanout/config_test.go
  pkg/provisioners/multichannelfanout/multi_channel_fanout_handler.go
  pkg/provisioners/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/provisioners/multichannelfanout/parse.go
  pkg/provisioners/multichannelfanout/parse_test.go
  pkg/provisioners/swappable/swappable.go
  pkg/provisioners/swappable/swappable_test.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
  pkg/sidecar/configmap/parse.go
  pkg/sidecar/configmap/parse_test.go
  pkg/sidecar/configmap/watcher/watcher.go
  pkg/sidecar/configmap/watcher/watcher_test.go
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: approved, cla: yes, lgtm, size/XXL

#1060 Proposal: How to manage and triage bugs in Knative Eventing
  docs/planning/bug_triage.md
  docs/planning/sprintplanning.md
Labels: approved, cla: yes, kind/proposal, lgtm, size/M

#1171 Adding test for GetGroupVersionKind
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1173 Use kmeta.newControllerRef for Trigger
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/reconciler/trigger/resources/subscription.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1161 Enable e2e tests for Kafka CCP
  contrib/kafka/config/kafka.yaml
  test/config/100-kafka-persistent-single-2.1.0.yaml
  test/config/100-strimzi-cluster-operator-0.11.3.yaml
  test/e2e-tests.sh
  test/e2e/main_test.go
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XXL

#1047 Advanced Trigger Filtering Design Proposal
  docs/broker/filtering.md
Labels: approved, cla: yes, kind/proposal, lgtm, size/XL

#1178 Add unit test to GetGroupVersionKind for Trigger
  pkg/apis/eventing/v1alpha1/trigger_types_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1180 Use kmeta.NewControllerRef for Channel
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_types_test.go
  pkg/provisioners/channel_util.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1181 Use kmeta.NewControllerRef for CronJobSource
  pkg/apis/sources/v1alpha1/cron_job_types_test.go
  pkg/reconciler/cronjobsource/resources/eventtype.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1183 Check that ClusterChannelProvisioner is OwnerRefable
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1186 golang format tools
  pkg/reconciler/trigger/resources/subscription.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1184 Be consistent with other images
  cmd/sources_controller/kodata/HEAD
  cmd/sources_controller/kodata/LICENSE
  cmd/sources_controller/kodata/VENDOR-LICENSE
  cmd/sources_controller/main.go
  config/500-sources-controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1179 Use kmeta.NewControllerRef for Broker
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/broker_types_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/resources/filter.go
  pkg/reconciler/broker/resources/ingress.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1190 Polish GetGroupVersionKind for Broker/Channel/ClusterChannelProvisioner/Trigger
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1187 fix minor quote issue for json tag.
  config/300-eventtype.yaml
  pkg/apis/eventing/v1alpha1/eventtype_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1174 Include the Trigger's UID in the Trigger's path
  pkg/broker/receiver.go
  pkg/broker/receiver_test.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/path/path.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#1192 Delete unused Kafka main.go.
  contrib/kafka/main.go
Labels: approved, cla: yes, lgtm, size/M

#1193 Add and format OwnerRefable check
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/apis/sources/v1alpha1/containersource_types.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1197 Update to CloudEvents Golang SDK 0.7.0
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_interface.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
Labels: approved, cla: yes, lgtm, size/L

#1195 golang format tools
  pkg/provisioners/channel_util.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/resources/filter.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/cronjobsource/resources/eventtype.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1175 Update ApiServerSource
  Gopkg.lock
  cmd/apiserver_receive_adapter/main.go
  config/300-apiserversource.yaml
  pkg/adapter/apiserver/adapter.go
  pkg/adapter/apiserver/adapter_test.go
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
  pkg/adapter/apiserver/ref.go
  pkg/adapter/apiserver/ref_test.go
  pkg/adapter/apiserver/resource.go
  pkg/adapter/apiserver/resource_test.go
  pkg/apis/sources/v1alpha1/apiserver_types.go
  pkg/kncloudevents/testing/test_client.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
  sample/apiserver_pod.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#1199 Add tracing support to in-memory dispatcher.
  Gopkg.lock
  cmd/in_memory/dispatcher/main.go
  config/config-tracing.yaml
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  pkg/provisioners/message_receiver.go
  pkg/tracing/setup.go
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/pkg/tracing/config/doc.go
  vendor/github.com/knative/pkg/tracing/config/tracing.go
  vendor/github.com/knative/pkg/tracing/config/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/tracing/http.go
  vendor/github.com/knative/pkg/tracing/opencensus.go
  vendor/github.com/knative/pkg/tracing/zipkin.go
  vendor/github.com/openzipkin/zipkin-go/LICENSE
  vendor/github.com/openzipkin/zipkin-go/context.go
  vendor/github.com/openzipkin/zipkin-go/doc.go
  vendor/github.com/openzipkin/zipkin-go/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/idgenerator/idgenerator.go
  vendor/github.com/openzipkin/zipkin-go/model/annotation.go
  vendor/github.com/openzipkin/zipkin-go/model/doc.go
  vendor/github.com/openzipkin/zipkin-go/model/endpoint.go
  vendor/github.com/openzipkin/zipkin-go/model/kind.go
  vendor/github.com/openzipkin/zipkin-go/model/span.go
  vendor/github.com/openzipkin/zipkin-go/model/span_id.go
  vendor/github.com/openzipkin/zipkin-go/model/traceid.go
  vendor/github.com/openzipkin/zipkin-go/noop.go
  vendor/github.com/openzipkin/zipkin-go/propagation/propagation.go
  vendor/github.com/openzipkin/zipkin-go/reporter/http/http.go
  vendor/github.com/openzipkin/zipkin-go/reporter/reporter.go
  vendor/github.com/openzipkin/zipkin-go/reporter/serializer.go
  vendor/github.com/openzipkin/zipkin-go/sample.go
  vendor/github.com/openzipkin/zipkin-go/span.go
  vendor/github.com/openzipkin/zipkin-go/span_implementation.go
  vendor/github.com/openzipkin/zipkin-go/span_options.go
  vendor/github.com/openzipkin/zipkin-go/tags.go
  vendor/github.com/openzipkin/zipkin-go/tracer.go
  vendor/github.com/openzipkin/zipkin-go/tracer_options.go
  vendor/go.opencensus.io/exporter/zipkin/zipkin.go
Labels: approved, cla: yes, lgtm, size/XXL

#1201 ApiServerSource creates EventTypes
  cmd/sources_controller/main.go
  docs/registry/example_eventtype.yaml
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/ref_test.go
  pkg/adapter/apiserver/resource_test.go
  pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  pkg/apis/sources/v1alpha1/apiserver_lifecycle_test.go
  pkg/apis/sources/v1alpha1/apiserver_types.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/resources/eventtype.go
  pkg/reconciler/testing/apiserversource.go
Labels: approved, cla: yes, lgtm, size/L

#1207 golang format tools
  pkg/adapter/apiserver/adapter_test.go
  pkg/adapter/apiserver/events/events_test.go
  pkg/adapter/apiserver/ref.go
  pkg/adapter/apiserver/ref_test.go
  pkg/adapter/apiserver/resource.go
  pkg/adapter/apiserver/resource_test.go
  pkg/kncloudevents/testing/test_client.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/tracing/setup.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1200 Adding stats for core eventing Broker, Trigger, Channel, Subscription, ContainerSource, CronJobSource, and ApiServerSource.
  Gopkg.lock
  cmd/controller/main.go
  cmd/sources_controller/main.go
  config/500-controller.yaml
  config/config-observability.yaml
  pkg/metrics/config.go
  pkg/metrics/config_test.go
  pkg/metrics/doc.go
  pkg/metrics/testdata/config-observability.yaml
  pkg/metrics/zz_generated.deepcopy.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/stats_reporter.go
  pkg/reconciler/stats_reporter_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  vendor/github.com/knative/pkg/configmap/testing/configmap.go
Labels: approved, cla: yes, lgtm, size/XXL

#1210 Cleanup the gke import lines. Used for off cluster gke connections.
  cmd/apiserver_receive_adapter/main.go
  cmd/controller/main.go
  cmd/in_memory/controller/main.go
  cmd/in_memory/dispatcher/main.go
  cmd/sources_controller/main.go
  contrib/kafka/cmd/controller/main.go
  pkg/metrics/config.go
Labels: approved, cla: yes, lgtm, size/M

#1209 Changing Source in CronJob
  cmd/cronjob_receive_adapter/main.go
  pkg/adapter/cronjobevents/adapter.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/cronjobsource/resources/eventtype.go
  pkg/reconciler/cronjobsource/resources/receive_adapter.go
  pkg/reconciler/cronjobsource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#1204 Add tracing to NATSS Channels, by watching the config-tracing ConfigMap.
  contrib/natss/config/provisioner.yaml
  contrib/natss/pkg/dispatcher/main.go
Labels: approved, cla: yes, lgtm, size/M

#1212 Get sockpuppet off our backs and stop breaking the format.
  docs/broker/filtering.md
Labels: approved, cla: yes, lgtm, size/L

#1220 add system integrator persona
  docs/personas.md
Labels: approved, cla: yes, lgtm, size/S

#1222 Format markdown
  docs/personas.md
  docs/planning/bug_triage.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1206 Natss broker doesn't require istio injectin enabled
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1149 Subscription and Trigger track their Subscriber
  cmd/controller/main.go
  pkg/duck/addressable.go
  pkg/duck/subscriber.go
  pkg/duck/subscriber_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1223 golang format tools
  cmd/controller/main.go
  cmd/in_memory/controller/main.go
  cmd/sources_controller/main.go
  pkg/apis/sources/v1alpha1/cron_job_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1155 Fix for https://github.com/knative/eventing-sources/issues/314: trackers for sinks in sources
  pkg/duck/sinks.go
  pkg/duck/sinks_test.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/eventtype/eventtype_test.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/factory.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1221 Reconcile EventType upon Source change
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
Labels: approved, cla: yes, lgtm, size/L

#1228 Fix typos
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/message.go
Labels: approved, cla: yes, lgtm, size/S

#1230 Fix unit tests.
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
Labels: approved, cla: yes, lgtm, size/S

#1229 Removing eventTypes if we change the sink to be a non-broker one.
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
Labels: approved, cla: yes, lgtm, size/L

#1203 Add tracing to Kafka Channels, by watching the config-tracing ConfigMap.
  contrib/kafka/cmd/dispatcher/main.go
  contrib/kafka/config/kafka.yaml
Labels: approved, cla: yes, lgtm, size/S

#1232 golang format tools
  pkg/duck/sinks_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/eventtype/eventtype_test.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/factory.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1231 Add tracing to GCP-PubSub Channels, by watching the config-tracing ConfigMap.
  contrib/gcppubsub/config/gcppubsub.yaml
  contrib/gcppubsub/pkg/dispatcher/cmd/main.go
Labels: approved, cla: yes, lgtm, size/M

#1219 In memory to pkg controller + CRD
  cmd/in_memory_channel_controller/main.go
  config/channels/in-memory-channel/200-controller-clusterrole.yaml
  config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
  config/channels/in-memory-channel/200-dispatcher-service.yaml
  config/channels/in-memory-channel/200-serviceaccount.yaml
  config/channels/in-memory-channel/201-clusterrolebinding.yaml
  config/channels/in-memory-channel/300-in-memory-channel.yaml
  config/channels/in-memory-channel/400-controller.yaml
  config/channels/in-memory-channel/500-dispatcher.yaml
  config/channels/in-memory-channel/README.md
  hack/update-codegen.sh
  pkg/apis/messaging/register.go
  pkg/apis/messaging/v1alpha1/crd_validation_test.go
  pkg/apis/messaging/v1alpha1/doc.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_defaults.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_validation.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_validation_test.go
  pkg/apis/messaging/v1alpha1/register.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_inmemorychannel.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/fake/fake_messaging_client.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/inmemorychannel.go
  pkg/client/clientset/versioned/typed/messaging/v1alpha1/messaging_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/messaging/interface.go
  pkg/client/informers/externalversions/messaging/v1alpha1/inmemorychannel.go
  pkg/client/informers/externalversions/messaging/v1alpha1/interface.go
  pkg/client/listers/messaging/v1alpha1/expansion_generated.go
  pkg/client/listers/messaging/v1alpha1/inmemorychannel.go
  pkg/reconciler/inmemorychannel/inmemorychannel.go
  pkg/reconciler/inmemorychannel/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/resources/service.go
  pkg/reconciler/inmemorychannel/resources/service_test.go
  pkg/reconciler/testing/inmemorychannel.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/XXL

#1235 bump pkg & use FilterWithNameAndNamespace from pkg
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/inmemorychannel/inmemorychannel.go
  pkg/reconciler/inmemorychannel/inmemorychannel_test.go
  vendor/github.com/knative/pkg/controller/controller.go
Labels: approved, cla: yes, lgtm, size/M

#1236 Removing the deprecated Kafka Statefulset in 0.7.0 timeframe
  contrib/kafka/config/kafka.yaml
Labels: approved, cla: yes, lgtm, size/M

#1111 Add user info annotations to Broker/Trigger/Channel/Subscription
  Gopkg.lock
  pkg/apis/eventing/register.go
  pkg/apis/eventing/v1alpha1/broker_defaults.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/channel_defaults.go
  pkg/apis/eventing/v1alpha1/channel_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/subscription_defaults.go
  pkg/apis/eventing/v1alpha1/subscription_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/trigger_defaults.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1243 Format markdown
  config/channels/in-memory-channel/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1242 Update test-infra: handle stockout to work with new error string
  Gopkg.lock
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#1244 golang format tools
  pkg/apis/eventing/v1alpha1/broker_defaults.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/channel_defaults.go
  pkg/apis/eventing/v1alpha1/channel_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/subscription_defaults.go
  pkg/apis/eventing/v1alpha1/subscription_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/trigger_defaults.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1234 Update cloud.google.com/go to 0.39.0.
  Gopkg.lock
  vendor/cloud.google.com/go/AUTHORS
  vendor/cloud.google.com/go/CONTRIBUTORS
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/container/apiv1/cluster_manager_client.go
  vendor/cloud.google.com/go/iam/iam.go
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/monitoring/apiv3/alert_policy_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/doc.go
  vendor/cloud.google.com/go/monitoring/apiv3/group_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/metric_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/notification_channel_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/uptime_check_client.go
  vendor/cloud.google.com/go/pubsub/apiv1/doc.go
  vendor/cloud.google.com/go/pubsub/apiv1/publisher_client.go
  vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go
  vendor/cloud.google.com/go/pubsub/doc.go
  vendor/cloud.google.com/go/pubsub/iterator.go
  vendor/cloud.google.com/go/pubsub/pubsub.go
  vendor/cloud.google.com/go/pubsub/pullstream.go
  vendor/cloud.google.com/go/pubsub/service.go
  vendor/cloud.google.com/go/pubsub/subscription.go
  vendor/cloud.google.com/go/pubsub/topic.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/cloud.google.com/go/trace/apiv2/trace_client.go
  vendor/github.com/googleapis/gax-go/v2/call_option.go
  vendor/github.com/googleapis/gax-go/v2/gax.go
  vendor/github.com/googleapis/gax-go/v2/header.go
  vendor/github.com/googleapis/gax-go/v2/invoke.go
Labels: approved, cla: yes, lgtm, size/XL

#1246 Fix race conditions in TestTriggerAnnotateUserInfo
  pkg/apis/eventing/v1alpha1/trigger_defaults_test.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/L

#1247 Remove the deprecated 'in-memory-channel' ClusterChannelProvisioner.
  cmd/in_memory/dispatcher/main.go
  config/provisioners/in-memory-channel/README.md
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  pkg/provisioners/inmemory/channel/controller.go
  pkg/provisioners/inmemory/channel/reconcile.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
  pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile.go
  pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile_test.go
  pkg/provisioners/multichannelfanout/config.go
  pkg/provisioners/multichannelfanout/config_test.go
  test/README.md
  test/constants.go
  test/e2e-tests.sh
  test/e2e/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#1249 Format markdown
  config/provisioners/in-memory-channel/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1245 Update knative/pkg dependency.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/knative/pkg/configmap/informed_watcher.go
  vendor/github.com/knative/pkg/configmap/manual_watcher.go
  vendor/github.com/knative/pkg/configmap/store.go
  vendor/github.com/knative/pkg/configmap/watcher.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/logging/logkey/constants.go
Labels: approved, cla: yes, lgtm, size/M

#1241 Create a ServiceAccount for Broker Ingress
  config/200-broker-clusterrole.yaml
  config/500-controller.yaml
  docs/broker/README.md
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/namespace/resources/names.go
  pkg/reconciler/namespace/resources/role_binding.go
  pkg/reconciler/namespace/resources/service_account.go
  test/e2e/broker_event_transformation_test.go
Labels: approved, cla: yes, lgtm, size/L

#1253 Fix CI flow error for Eventing-0.5
  Gopkg.lock
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XL

#1256 Format markdown
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1257 Remove the redundant Broker and Trigger documentation.
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, size/L

#1252 Update test-infra: get rid of Unbound variable running update-deps wa…
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#1259 Format markdown
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1264 Updating Subscription Ready status on Failed conditions
  pkg/apis/eventing/v1alpha1/subscription_lifecycle.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/subscription.go
Labels: approved, cla: yes, lgtm, size/M

#1265 Removing ChannelInformer from Subscription controller
  cmd/controller/main.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/M

#1254 Rewrite all E2E tests related code
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/subscription_types_test.go
  test/README.md
  test/base/resource_checks.go
  test/base/resources.go
  test/builders.go
  test/common/cleanup.go
  test/common/client.go
  test/common/config.go
  test/common/creation.go
  test/common/operation.go
  test/common/validation.go
  test/crd.go
  test/crd_checks.go
  test/e2e-tests.sh
  test/e2e/README.md
  test/e2e/broker_default_test.go
  test/e2e/broker_event_transformation_test.go
  test/e2e/broker_trigger_test.go
  test/e2e/channel_chain_test.go
  test/e2e/channel_event_transformation_test.go
  test/e2e/channel_single_event_test.go
  test/e2e/e2e.go
  test/e2e/event_transformation_test.go
  test/e2e/main_test.go
  test/e2e/single_event_test.go
  test/e2e/test_runner.go
  test/e2e_flags.go
  test/states.go
  test/test_images/logevents/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#1276 Format markdown
  test/e2e/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1277 golang format tools
  test/common/config.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1278 Consume the simplified controller constructor.
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/inmemorychannel/inmemorychannel.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/stats.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/trigger/trigger.go
  vendor/github.com/knative/pkg/controller/controller.go
  vendor/github.com/knative/pkg/controller/stats_reporter.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/metrics/config.go
  vendor/github.com/knative/pkg/signals/signal.go
Labels: approved, cla: yes, lgtm, size/L

#1271 Adding note for usage of CRD instead
  config/provisioners/in-memory-channel/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1284 Add type godoc for Broker and Trigger
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
Labels: approved, cla: yes, lgtm, size/XS

#1279 Move eventing onto the shared controller.HandleAll
  pkg/duck/addressable.go
  pkg/duck/sinks.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/handler.go
  pkg/reconciler/inmemorychannel/inmemorychannel.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#1286 Format markdown
  config/provisioners/in-memory-channel/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1287 Pickup runtime.Object change
  Gopkg.lock
  Gopkg.toml
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/inmemorychannel/inmemorychannel_test.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/trigger/trigger_test.go
  vendor/github.com/knative/pkg/reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/M

#1288 update test-infra in vendor
  Gopkg.lock
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json
  vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XXL

#1270 Adding CRD to the yaml artifacts, and release
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1269 rename webhook to be eventing-webhook to avoid potential clash
  cmd/webhook/main.go
  config/400-webhook-service.yaml
  config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/M

#1289 remove the test-infra/devstats in vendor
  hack/update-deps.sh
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-and-episodic-pr-contributors.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/new-contributors-table.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-companies-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors-histogram.json
  vendor/github.com/knative/test-infra/devstats/grafana/dashboards/knative/prs-authors.json
  vendor/github.com/knative/test-infra/devstats/metrics/shared/episodic_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/hist_pr_authors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/new_contributors_data.sql
  vendor/github.com/knative/test-infra/devstats/metrics/shared/prs_authors.sql
  vendor/k8s.io/code-generator/Godeps/OWNERS
  vendor/k8s.io/code-generator/OWNERS
  vendor/k8s.io/code-generator/cmd/client-gen/OWNERS
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/OWNERS
Labels: approved, cla: yes, lgtm, size/XXL

#1263 Use OWNERS_ALIASES for productivity approvers/reviewers
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#1296 Start to use GetURL on Addressable instead of assuming Hostname.
  Gopkg.lock
  Gopkg.toml
  contrib/gcppubsub/pkg/controller/channel/reconcile.go
  contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile_test.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver_test.go
  contrib/kafka/pkg/controller/channel/reconcile.go
  contrib/kafka/pkg/controller/channel/reconcile_test.go
  contrib/natss/pkg/controller/channel/reconcile.go
  contrib/natss/pkg/controller/channel/reconcile_test.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/channel_lifecycle.go
  pkg/apis/eventing/v1alpha1/channel_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/test_helper.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle_test.go
  pkg/channelwatcher/channel_watcher_test.go
  pkg/duck/sinks.go
  pkg/duck/sinks_test.go
  pkg/duck/subscriber.go
  pkg/duck/subscriber_test.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/inmemory/channel/reconcile.go
  pkg/provisioners/multichannelfanout/config.go
  pkg/provisioners/multichannelfanout/config_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
  pkg/reconciler/inmemorychannel/inmemorychannel.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/inmemorychannel.go
  pkg/reconciler/trigger/trigger_test.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1298 Add the knative.dev/crd-install=true label in eventtype.yaml
  config/300-eventtype.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1299 golang format tools
  pkg/reconciler/subscription/subscription.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1305 Use envconfig instead of getRequiredEnv
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  cmd/controller/main.go
  cmd/in_memory_channel_controller/main.go
  contrib/gcppubsub/pkg/controller/cmd/main.go
Labels: approved, cla: yes, lgtm, size/L

#1312 Format markdown
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1311 golang format tools
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/channelable_types_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1308 Add openAPIV3Schema to EventType CRD
  config/300-eventtype.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1313 Fix envconfig tags by removing spaces
  cmd/broker/filter/main.go
  contrib/gcppubsub/pkg/controller/cmd/main.go
Labels: approved, cla: yes, lgtm, size/S
