Repository knative/eventing, pull requests merged in 2019-07, with the labels that each got.

#1491 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/shared/testgrid/testgrid.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#1492 fix tracing service name
  cmd/cronjob_receive_adapter/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1495 Fixing RBAC for finalizers sub-resource of Sequences
  config/200-controller-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1499 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/shared/gcs/gcs.go
  vendor/knative.dev/pkg/Gopkg.lock
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1497 applying finalizer subresource for 0.7.x patch
  config/200-controller-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1501 add missing json tags
  pkg/apis/messaging/v1alpha1/sequence_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1502 Skip flaky tests
  contrib/gcppubsub/pkg/dispatcher/receiver/cache/cache_test.go
  pkg/provisioners/fanout/fanout_handler_test.go
  pkg/utils/runnable_server_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1420 Channel spec: iteration 1
  docs/spec/README.md
  docs/spec/channel.md
  docs/spec/channel_060.md
Labels: approved, cla: yes, lgtm, size/L

#1512 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/shared/gcs/gcs.go
  vendor/github.com/knative/test-infra/shared/prow/prow.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/limitrange/limitrange.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/fake/fake.go
  vendor/knative.dev/pkg/injection/informers/kubeinformers/corev1/resourcequota/resourcequota.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1490 Add a ServiceAccount for Eventing Source Controller
  config/200-controller-clusterrole.yaml
  config/200-serviceaccount.yaml
  config/200-sourcecontroller-clusterrole.yaml
  config/201-clusterrolebinding.yaml
  config/500-sources-controller.yaml
Labels: approved, cla: yes, lgtm, size/L

#1514 fix indentation
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1517 Format markdown
  docs/spec/README.md
  docs/spec/channel.md
  docs/spec/channel_060.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1508 Make gcloud a no-op if not available for test scripts
  test/e2e-common.sh
  test/upload-test-images.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#1524 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/record.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/user_info.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1528 fix SequenceList registration
  pkg/apis/messaging/v1alpha1/register.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1531 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/volatile_time.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1538 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1541 Fixing knative eventing namespace teardown step
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#1542 YAMLS_TO_PUBLISH is deprecated, use ARTIFACTS_TO_PUBLISH
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#1540 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1510 Add scrape annotation to services exporting metrics
  config/400-source-controller-service.yaml
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/filter.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/testing/service.go
Labels: approved, cla: yes, lgtm, size/M

#1539 Remove Erik and Nikhil from Productivity Reviewers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1522 Replace AddressableTracker with a generic ResourceTracker
  pkg/apis/duck/v1alpha1/resource_types.go
  pkg/apis/duck/v1alpha1/resource_types_test.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/duck/resource.go
  pkg/duck/resource_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1547 issue 1546: change version->versions for CRD definitions
  config/300-apiserversource.yaml
  config/300-broker.yaml
  config/300-channel.yaml
  config/300-clusterchannelprovisioner.yaml
  config/300-containersource.yaml
  config/300-cronjobsource.yaml
  config/300-eventtype.yaml
  config/300-sequence.yaml
  config/300-subscription.yaml
  config/300-trigger.yaml
  config/channels/in-memory-channel/300-in-memory-channel.yaml
Labels: approved, cla: yes, lgtm, size/M

#1549 Named field initialization.
  pkg/reconciler/sequence/resources/channel.go
Labels: approved, cla: yes, lgtm, size/XS

#1548 Point release documentation to knative/test-infra
  hack/release.md
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1503 Similar to serving, add permissions to admin default roles
  config/200-clusterrole-namespaced.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1552 Disable logging headers in nats dispatcher
  contrib/natss/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1559 fixes #1558 list/get resources in namespace scope only
  test/base/resource_getters.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#1568 Increase code coverage of trigger_lifecycle.go.
  pkg/apis/eventing/v1alpha1/test_helper.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#1572 Channel spec revisions iterations
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/M

#1570 Add unit tests for Broker's Channel and Subscription resources.
  pkg/reconciler/broker/resources/channel.go
  pkg/reconciler/broker/resources/channel_test.go
  pkg/reconciler/broker/resources/subscription.go
  pkg/reconciler/broker/resources/subscription_test.go
Labels: approved, cla: yes, lgtm, size/L

#1571 Add code coverage for utils.go.
  pkg/utils/utils_test.go
Labels: approved, cla: yes, lgtm, size/M

#1569 Default channel for Sequence
  pkg/apis/messaging/v1alpha1/sequence_defaults.go
  pkg/apis/messaging/v1alpha1/sequence_defaults_test.go
  pkg/apis/messaging/v1alpha1/sequence_types.go
  pkg/apis/messaging/v1alpha1/sequence_validation.go
  pkg/apis/messaging/v1alpha1/sequence_validation_test.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/testing/sequence.go
  test/base/resources/messaging.go
  test/common/creation.go
  test/e2e/sequence_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1574 Move 0.7 and 0.8 roadmap into a md doc on the repo (instead of a goog…
  README.md
  docs/planning/roadmap.md
Labels: approved, cla: yes, lgtm, size/S

#1575 followup to 1535
  pkg/broker/ttl.go
Labels: approved, cla: yes, lgtm, size/XS

#1576 ApiServerSource updates its receive adapter, if needed.
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
Labels: approved, cla: yes, lgtm, size/L

#1587 Auto-update dependencies
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/shared/testgrid/testgrid.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/knative.dev/pkg/apis/metadata_validation.go
  vendor/knative.dev/pkg/cloudevents/event.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/kmeta/accessor.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/knative.dev/pkg/signals/signal.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/user_info.go
  vendor/knative.dev/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1577 ApiServerSource tracks its receive adapter.
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/mock_resource_tracker.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1585 Format markdown
  docs/planning/roadmap.md
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1586 golang format tools
  pkg/apis/eventing/v1alpha1/broker_defaults.go
  pkg/apis/eventing/v1alpha1/broker_defaults_test.go
  pkg/apis/messaging/v1alpha1/channel_defaults.go
  pkg/apis/messaging/v1alpha1/channel_defaults_test.go
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/channel_validation.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
  pkg/apis/messaging/v1alpha1/sequence_defaults.go
  pkg/apis/messaging/v1alpha1/sequence_defaults_test.go
  pkg/apis/messaging/v1alpha1/sequence_validation.go
  pkg/defaultchannel/channel_defaulter.go
  pkg/defaultchannel/channel_defaulter_test.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/testing/messagingchannel.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1563 Trigger & Broker - Fixed Names
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/channel.go
  pkg/reconciler/broker/resources/channel_test.go
  pkg/reconciler/broker/resources/subscription.go
  pkg/reconciler/trigger/resources/subscription.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cla: yes, lgtm, size/L

#1578 Apiserversource deployment availability
  pkg/apis/duck/lifecycle_helper.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  pkg/apis/sources/v1alpha1/apiserver_lifecycle_test.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/testing/apiserversource.go
  pkg/reconciler/testing/deployment.go
Labels: approved, cla: yes, lgtm, size/L

#1520 Update pkg, add stats reporter for webhook.
  cmd/webhook/main.go
  contrib/kafka/cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/S

#1489 remove e2e tests for provisioners
  test/README.md
  test/base/resources/constants.go
  test/base/resources/eventing.go
  test/common/config.go
  test/common/creation.go
  test/common/test_runner.go
  test/common/typemeta.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/README.md
  test/e2e/alias.go
  test/e2e/broker_channel_flow_test.go
  test/e2e/broker_event_transformation_test.go
  test/e2e/channel_chain_test.go
  test/e2e/channel_event_transformation_test.go
  test/e2e/channel_single_event_test.go
  test/e2e/sequence_test.go
  test/e2e_flags.go
  test/performance/latency_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#1595 fix Choice ChannelTemplate doc
  pkg/apis/messaging/v1alpha1/choice_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1584 Add Grafana dashboard configuration
  config/monitoring/metrics/grafana/100-grafana-dash-eventing.yaml
  docs/metrics.md
Labels: approved, cla: yes, lgtm, size/L

#1593 Format markdown
  test/README.md
  test/e2e/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#1600 Add InMemoryChannel and Channel.messaging,knative.dev to the addressable-resolver ClusterRole.
  config/200-addressable-resolvers-clusterrole.yaml
  config/channels/in-memory-channel/200-addressable-resolver-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#1601 Add KafkaChannel and NatssChannel to the addressable-resolver ClusterRole.
  contrib/kafka/config/200-addressable-resolver-clusterrole.yaml
  contrib/natss/config/200-addressable-resolver-clusterrole.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#1606 Format markdown
  docs/metrics.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1604 Use knative.dev/test-infra
  Gopkg.lock
  Gopkg.toml
  hack/release.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-common.sh
  test/performance/latency_test.go
  test/performance/performance.go
  test/presubmit-tests.sh
  third_party/VENDOR-LICENSE
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/knative.dev/test-infra/shared/common/common.go
  vendor/knative.dev/test-infra/shared/gcs/gcs.go
  vendor/knative.dev/test-infra/shared/junit/junit.go
  vendor/knative.dev/test-infra/shared/prow/prow.go
  vendor/knative.dev/test-infra/shared/testgrid/testgrid.go
  vendor/knative.dev/test-infra/shared/testgrid/yaml.go
  vendor/knative.dev/test-infra/tools/dep-collector/README.md
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
  vendor/knative.dev/test-infra/tools/dep-collector/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#1608 add sequences and choices in the list of addressable
  config/200-addressable-resolvers-clusterrole.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1534 Expose the RegistrationDelay for webhook deployment
  cmd/webhook/main.go
  config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/M

#1611 fix the propagation of Choice address
  pkg/apis/messaging/v1alpha1/choice_lifecycle.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
