Repository knative/eventing, pull requests merged in 2019-12, with the labels that each got.

#2237 Fix performance tests by passing the publishResults flag value
  test/common/performance/aggregator/aggregator.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XS

#2232 Use apis.URL instead of String in trigger.Status.SubscriberURI
  Gopkg.lock
  pkg/apis/eventing/v1alpha1/test_helper.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/trigger.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/client/injection/client/client.go
  vendor/knative.dev/pkg/client/injection/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
Labels: approved, cla: yes, lgtm, size/L

#2241 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
Labels: approved, cla: yes, lgtm, size/M

#2234 Implement a SinkBinding for injecting K_SINK.
  Gopkg.lock
  cmd/webhook/main.go
  config/200-podspecable-binding-clusterrole.yaml
  config/200-sourcecontroller-clusterrole.yaml
  config/200-webhook-clusterrole.yaml
  config/201-clusterrolebinding.yaml
  config/300-sinkbinding.yaml
  config/500-webhook-configuration.yaml
  pkg/apis/sources/v1alpha1/sinkbinding_context.go
  pkg/apis/sources/v1alpha1/sinkbinding_context_test.go
  pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1alpha1/sinkbinding_lifecycle_test.go
  pkg/duck/subscriber.go
  pkg/reconciler/sinkbinding/controller.go
  pkg/reconciler/testing/containersource.go
  test/common/creation.go
  test/e2e/sinkbinding_test.go
  test/e2e/source_container_test.go
  test/test_images/heartbeats/main.go
  vendor/knative.dev/pkg/apis/duck/const.go
  vendor/knative.dev/pkg/apis/duck/interface.go
  vendor/knative.dev/pkg/apis/duck/unstructured.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/testing/duck/doc.go
  vendor/knative.dev/pkg/testing/duck/register.go
  vendor/knative.dev/pkg/testing/duck/testbindable.go
  vendor/knative.dev/pkg/testing/duck/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/doc.go
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/testing/listers.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2243 Make upgrades from 0.10 (and downgrades) smoother.
  cmd/webhook/main.go
  config/500-webhook-configuration.yaml
Labels: approved, cla: yes, lgtm, size/S

#2247 Backport #2160
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#2244 Ttl fix
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ttl.go
Labels: approved, cla: yes, lgtm, size/M

#2249 Backport ttl fix to release-0.10
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ttl.go
Labels: approved, cla: yes, lgtm, size/M

#2251 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2250 Set defaultMaxIdleConnections and defaultMaxIdleConnectionsPerHost for channel event dispatcher
  pkg/channel/event_dispatcher.go
Labels: approved, cla: yes, lgtm, size/S

#2253 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/webhook/psbinding/README.md
Labels: approved, cla: yes, lgtm, size/M

#2183 Update pkg and OpenCensus SD exporter versions
  Gopkg.lock
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_batcher.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_proto.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/metrics_test_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/aws_identity_doc_utils.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/monitoredresource/gcp_metadata_config.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stats.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/trace.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/monitored_resources_eventing.go
  vendor/knative.dev/pkg/metrics/monitored_resources_serving.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
Labels: approved, cla: yes, lgtm, size/XXL

#2255 Updating pkg to latest for 0.11 release.
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#2256 Change the remaining uri strings to apis.url
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/channelable_types_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_test.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1alpha1/channel_validation.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_validation.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_validation_test.go
  pkg/channel/fanout/fanout_handler.go
  pkg/channel/fanout/fanout_handler_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/channel/multichannelfanout/parse_test.go
  pkg/channel/swappable/swappable_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/subscription.go
Labels: approved, cla: yes, lgtm, size/L

#2258 Correct minor typo in test/README.md
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, needs-ok-to-test, size/XS

#2259 Cloudevent 1.0 - Part1: Updating source to produce 1.0 payload
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
  pkg/adapter/cronjobevents/adapter.go
Labels: approved, cla: yes, lgtm, size/L

#2262 golang format tools
  pkg/adapter/apiserver/events/events_test.go
Labels: approved, cla: yes, lgtm, size/M

#2264 Followup for 2244 - Ttl fix
  pkg/broker/filter/filter_handler.go
  pkg/broker/ingress/ingress_handler.go
Labels: approved, cla: yes, lgtm, size/S

#2257 Add at least one sample point for error throughput
  test/common/performance/aggregator/aggregator.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/M

#2263 Fix the hack to vegeta library in performance test infra
  test/common/performance/sender/http_load_generator.go
  test/common/performance/sender/request_interceptor.go
  test/common/performance/sender/request_interceptor_test.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/M

#2268 golang format tools
  test/common/performance/sender/request_interceptor.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XS

#2269 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2279 fix nil pointer when using only uri to specify sink
  pkg/reconciler/cronjobsource/cronjobsource.go
  pkg/reconciler/cronjobsource/cronjobsource_test.go
Labels: approved, cla: yes, lgtm, size/M

#2280 Adding unit test on subscription generation.
  pkg/reconciler/trigger/resources/subscription_test.go
Labels: approved, cla: yes, lgtm, size/L

#2278 Adding broker filter resource unit tests for more coverage.
  pkg/reconciler/broker/resources/filter_test.go
Labels: approved, cla: yes, lgtm, size/L

#2281 add only uri as sink for tests
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/containersource/containersource_test.go
Labels: approved, cla: yes, lgtm, size/L

#2282 Fix trigger spec
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/M

#2283 Updates towards CloudEvents 1.0 for channel pkg
  pkg/channel/event_dispatcher_test.go
  pkg/channel/event_receiver_test.go
  pkg/channel/fanout/fanout_handler_test.go
  pkg/channel/history_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/channel/swappable/swappable_test.go
Labels: approved, cla: yes, lgtm, size/M

#2284 Format markdown
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/S

#2285 golang format tools
  pkg/reconciler/trigger/resources/subscription_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2286 Broker tests w/ CE 1.0
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/ingress/ingress_handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#2289 Fix the nil ref for when using deprecated fields
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
Labels: approved, cla: yes, lgtm, size/M

#2294 nit: remove old provisioner/ccp reference
  pkg/apis/eventing/v1alpha1/broker_validation.go
Labels: approved, cla: yes, lgtm, size/XS

#2293 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2292 golang format tools
  pkg/channel/event_dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2295 Adding VMware to AUTHORS.
  AUTHORS
Labels: approved, cla: yes, lgtm, size/XS

#2297 Send 1.0 cloudevents for perf tests
  test/common/performance/sender/http_load_generator.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XS

#2303 Spec was finalized before
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/XS

#2304 Fixing typo in the spec, for broker, as we no longer have CCPs
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/XS

#2307 Format markdown
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/XS

#2300 Remove support for deprecated fields in messaging Destinations
  docs/spec/spec.md
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/channelable_types_test.go
  pkg/apis/duck/v1alpha1/delivery_types.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1alpha1/parallel_types.go
  pkg/apis/messaging/v1alpha1/parallel_validation.go
  pkg/apis/messaging/v1alpha1/parallel_validation_test.go
  pkg/apis/messaging/v1alpha1/sequence_types.go
  pkg/apis/messaging/v1alpha1/sequence_validation.go
  pkg/apis/messaging/v1alpha1/sequence_validation_test.go
  pkg/apis/messaging/v1alpha1/subscription_lifecycle.go
  pkg/apis/messaging/v1alpha1/subscription_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/subscription_types.go
  pkg/apis/messaging/v1alpha1/subscription_validation.go
  pkg/apis/messaging/v1alpha1/subscription_validation_test.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/broker/resources/subscription.go
  pkg/reconciler/flowsparallel/resources/subscription.go
  pkg/reconciler/flowssequence/resources/subscription.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/parallel/resources/subscription.go
  pkg/reconciler/sequence/resources/subscription.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/parallel.go
  pkg/reconciler/testing/sequence.go
  pkg/reconciler/testing/subscription.go
  pkg/reconciler/trigger/resources/subscription.go
  test/base/resources/eventing.go
  test/e2e/parallel_test.go
  test/e2e/sequence_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#2309 Move webhooks to separate paths.
  cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/XS

#2313 remove now unused fields from crds
  config/300-parallel.yaml
  config/300-sequence.yaml
  config/300-subscription.yaml
Labels: approved, cla: yes, lgtm, size/M

#2314 adding lionelvillard to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2290 Remove broker ingress channel
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/test_helper.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/trigger/resources/subscription.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/uri.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#2315 Set resource requests and limits for imc-dispatcher
  config/channels/in-memory-channel/500-dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2317 fix incorrect error tacked to event when status fails
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/S

#2245 Fix for missing pull secrets in auto created namespaces
  config/500-controller.yaml
  pkg/reconciler/namespace/controller.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/namespace/resources/secret.go
  pkg/utils/secret.go
  pkg/utils/secret_test.go
  test/common/creation.go
  test/common/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#2318 remove now unused replystrategy
  pkg/apis/messaging/v1alpha1/subscription_types.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/S

#2319 when secret copy fails, emit warning event
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/M

#2320 remove pointer for subscriber. not optional
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/apis/eventing/v1alpha1/trigger_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  test/base/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2325 add more coverage
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/M

#2324 Use cloudevents V01 in eventing tests
  Gopkg.lock
  Gopkg.toml
  test/common/performance/sender/http_load_generator.go
  test/e2e/broker_default_test.go
  test/test_images/filterevents/main.go
  test/test_images/heartbeats/main.go
  test/test_images/sendevents/main.go
  test/test_images/sequencestepper/main.go
  test/test_images/transformevents/main.go
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/M

#2299 Performance test infra issue fixes and improvements
  test/common/performance/aggregator/aggregator.go
  test/common/performance/common/pace.go
  test/common/performance/receiver/receiver.go
  test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml
  test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/L

#2327 golang format tools
  test/e2e/broker_default_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2326 Add chizhg to eventing productivity approvers
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#2331 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/tools/tools.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#2332 update to cloudevents sdk 0.10.2
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#2334 secret copy is a failure, return error
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/M

#2270 Minor refactor for broker ingress, adding unittests.
  cmd/broker/ingress/main.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/stats_reporter.go
  pkg/broker/filter/stats_reporter_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
  pkg/broker/ingress/stats_reporter.go
  pkg/broker/ingress/stats_reporter_test.go
  pkg/broker/ttl.go
  pkg/broker/ttl_test.go
  pkg/channel/event_dispatcher.go
  pkg/kncloudevents/good_client.go
Labels: approved, cla: yes, lgtm, size/L

#2340 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
Labels: approved, cla: yes, lgtm, size/M

#2343 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/test/gke/fake/credentials.json
  vendor/knative.dev/pkg/test/spoof/spoof.go
Labels: approved, cla: yes, lgtm, size/M

#2087 Cleanup eventing spec to use Destination and apis.URL.
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/M
