Repository knative/eventing, pull requests merged in 2019-04, with the labels that each got.

#990 Reformat the permission lists to make them easier to read.
  config/200-controller-clusterrole.yaml
  config/200-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/L

#1003 Adding Pong util, and updating CloudEvents sdk.
  Gopkg.lock
  Gopkg.toml
  cmd/pong/kodata/HEAD
  cmd/pong/kodata/LICENSE
  cmd/pong/kodata/VENDOR-LICENSE
  cmd/pong/main.go
  cmd/sendevent/main.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
Labels: approved, cla: yes, lgtm, size/L

#995 Add Age as a column when listing in kubectl.
  config/300-broker.yaml
  config/300-channel.yaml
  config/300-clusterchannelprovisioner.yaml
  config/300-subscription.yaml
  config/300-trigger.yaml
Labels: approved, cla: yes, lgtm, size/S

#1014 Refactor trigger reconciler to use resource subdir.
  pkg/reconciler/v1alpha1/trigger/resources/labels.go
  pkg/reconciler/v1alpha1/trigger/resources/service.go
  pkg/reconciler/v1alpha1/trigger/resources/subscription.go
  pkg/reconciler/v1alpha1/trigger/resources/virtual_service.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
  pkg/reconciler/v1alpha1/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1017 golang format tools
  cmd/pong/main.go
  cmd/sendevent/main.go
  pkg/reconciler/v1alpha1/trigger/resources/virtual_service.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
  pkg/reconciler/v1alpha1/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/S

#1016 Using a larger default TTL until we make it settable.
  cmd/broker/ingress/main.go
Labels: approved, cla: yes, lgtm, size/XS

#1013 Introduce addressable resolver aggregated cluster role
  config/200-addressable-resolvers-clusterrole.yaml
  config/200-controller-clusterrole.yaml
  config/201-clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/L

#1020 Update release docs with new automated procedures
  hack/release.md
Labels: approved, cla: yes, lgtm, size/L

#992 No Kafka yaml vendoring
  contrib/kafka/config/README.md
  contrib/kafka/config/broker/README.md
  contrib/kafka/config/broker/kafka-broker.yaml
Labels: approved, cla: yes, lgtm, size/L

#1023 Format markdown
  contrib/kafka/config/README.md
  hack/release.md
Labels: approved, cla: yes, lgtm, size/S

#1026 Fix NATSS CCP flaky test "deleted_clusterChannelProvisioner"
  contrib/natss/pkg/controller/clusterchannelprovisioner/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1028 Update dep for test-infra
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#976 Add e2e test cases for Channel-Subscription model
  test/crd.go
  test/e2e-tests.sh
  test/e2e/broker_trigger_test.go
  test/e2e/channel_chain_test.go
  test/e2e/e2e.go
  test/e2e/event_transformation_test.go
  test/e2e/single_event_test.go
  test/test_images/logevents/main.go
  test/test_images/transformevents/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1024 Refactor eventing api group lifecycle hooks
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/channel_lifecycle.go
  pkg/apis/eventing/v1alpha1/channel_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/subscription_lifecycle.go
  pkg/apis/eventing/v1alpha1/subscription_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
Labels: approved, cla: yes, lgtm, size/XL

#996 Add documentation for Brokers changing channel provisioners.
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, size/S

#1049 Format markdown
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#1052 Update CloudEvents SDK to 0.6.0
  Gopkg.lock
  Gopkg.toml
  pkg/broker/receiver_test.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/content_type.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/context/logger.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/data_content_encoding.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_interface.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_writer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01_writer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02_writer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03_writer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/extensions.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
Labels: approved, cla: yes, lgtm, size/XXL

#1045 Triggers working via path, rather than host
  pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
  pkg/broker/receiver.go
  pkg/broker/receiver_test.go
  pkg/reconciler/v1alpha1/broker/resources/filter.go
  pkg/reconciler/v1alpha1/subscription/subscription.go
  pkg/reconciler/v1alpha1/trigger/path/path.go
  pkg/reconciler/v1alpha1/trigger/resources/labels.go
  pkg/reconciler/v1alpha1/trigger/resources/service.go
  pkg/reconciler/v1alpha1/trigger/resources/subscription.go
  pkg/reconciler/v1alpha1/trigger/resources/virtual_service.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
  pkg/reconciler/v1alpha1/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1048 Add custom reporter for ImmutableField validation errors
  Gopkg.lock
  Gopkg.toml
  pkg/apis/eventing/v1alpha1/channel_validation.go
  pkg/apis/eventing/v1alpha1/subscribable_channelable_validation_test.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation.go
  test/e2e/channel_chain_test.go
  test/e2e/e2e.go
  test/e2e/event_transformation_test.go
  test/e2e/single_event_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go17.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go18.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/format.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/github.com/google/go-cmp/cmp/report_value.go
  vendor/github.com/google/go-cmp/cmp/reporter.go
  vendor/github.com/knative/pkg/apis/condition_set.go
  vendor/github.com/knative/pkg/apis/contexts.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/kmp/diff.go
  vendor/github.com/knative/pkg/kmp/reporters.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/spoof/error_checks.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#1044 Remove Istio dependency from Eventing (Part - 1)
  cmd/broker/ingress/main.go
  cmd/controller/main.go
  cmd/fanoutsidecar/main.go
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  contrib/kafka/cmd/controller/main.go
  contrib/kafka/main.go
  contrib/natss/pkg/controller/clusterchannelprovisioner/reconcile_test.go
  pkg/channelwatcher/channel_watcher.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/inmemory/channel/controller.go
  pkg/provisioners/inmemory/channel/reconcile.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
  pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile.go
  pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile_test.go
  pkg/provisioners/inmemory/controller/main.go
  pkg/provisioners/provisioner_util.go
  pkg/provisioners/provisioner_util_test.go
  pkg/reconciler/v1alpha1/broker/resources/ingress.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/sidecar/swappable/swappable_test.go
  test/crd.go
  third_party/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XXL

#1056 update test-infra: allow handling stock out with retries
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/M

#1046 Fix errors in test readme
  test/README.md
Labels: approved, cla: yes, lgtm, size/L

#1042 Run e2e tests in parallel and refactoring
  test/README.md
  test/builders.go
  test/clients.go
  test/crd.go
  test/e2e-tests.sh
  test/e2e/broker_trigger_test.go
  test/e2e/channel_chain_test.go
  test/e2e/e2e.go
  test/e2e/event_transformation_test.go
  test/e2e/main_test.go
  test/e2e/single_event_test.go
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XL

#1062 Add a Deprecated condition on 'in-memory-channel' Channels.
  pkg/apis/eventing/v1alpha1/channel_lifecycle.go
  pkg/apis/eventing/v1alpha1/channel_lifecycle_test.go
  pkg/provisioners/inmemory/channel/reconcile.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#1054 Take advantage of the package alias from cloudevents.
  Gopkg.lock
  cmd/broker/ingress/main.go
  cmd/pong/main.go
  cmd/sendevent/main.go
  pkg/broker/context.go
  pkg/broker/receiver.go
  pkg/broker/receiver_test.go
  pkg/broker/ttl.go
  test/test_images/logevents/main.go
  test/test_images/sendevent/main.go
  test/test_images/transformevents/main.go
  vendor/github.com/cloudevents/sdk-go/alias.go
Labels: approved, cla: yes, lgtm, size/L

#1064 Broker is not ready until its constituent pieces are ready.
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/reconciler/v1alpha1/broker/broker.go
  pkg/reconciler/v1alpha1/broker/broker_test.go
Labels: approved, cla: yes, lgtm, size/L

#1066 Add e2e testing support for gcp-pubsub CCP
  test/builders.go
  test/cleanup.go
  test/clients.go
  test/constants.go
  test/crd.go
  test/crd_checks.go
  test/e2e-tests.sh
  test/e2e/broker_trigger_test.go
  test/e2e/channel_chain_test.go
  test/e2e/e2e.go
  test/e2e/event_transformation_test.go
  test/e2e/main_test.go
  test/e2e/single_event_test.go
  test/e2e_flags.go
  test/states.go
  test/test_images/logevents/main.go
  test/test_images/sendevent/main.go
  test/test_images/transformevents/main.go
Labels: approved, cla: yes, lgtm, size/L

#1071 Trigger is not ready until its constituent pieces are ready.
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/test_helper.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
  pkg/reconciler/v1alpha1/broker/broker_test.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
  pkg/reconciler/v1alpha1/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1058 Remove Istio dependency from Eventing (Part - 2)
  cmd/fanoutsidecar/main.go
  contrib/gcppubsub/pkg/dispatcher/cmd/main.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver_test.go
  contrib/kafka/cmd/controller/main.go
  contrib/kafka/cmd/dispatcher/main.go
  contrib/kafka/config/kafka.yaml
  contrib/kafka/main.go
  contrib/kafka/pkg/controller/channel/provider.go
  contrib/kafka/pkg/controller/channel/reconcile.go
  contrib/kafka/pkg/controller/channel/reconcile_test.go
  contrib/kafka/pkg/dispatcher/dispatcher.go
  contrib/kafka/pkg/dispatcher/dispatcher_test.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  pkg/channelwatcher/channel_watcher.go
  pkg/channelwatcher/channel_watcher_test.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/message_receiver.go
  pkg/provisioners/message_receiver_test.go
  pkg/sidecar/fanout/fanout_handler.go
  pkg/sidecar/fanout/fanout_handler_test.go
  pkg/sidecar/multichannelfanout/config.go
  pkg/sidecar/multichannelfanout/config_test.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go
Labels: approved, cla: yes, lgtm, size/XXL

#1075 Add more logs, try to find the reason for e2e test flakiness
  test/e2e/broker_trigger_test.go
  test/e2e/channel_chain_test.go
  test/e2e/e2e.go
  test/e2e/event_transformation_test.go
  test/e2e/single_event_test.go
Labels: approved, cla: yes, lgtm, size/S

#1078 Fix imports for sub test.
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/L

#1086 Fix webhook controller RBAC policy
  config/200-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#1055 Update Trigger docs to match #1045.
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1091 Reduce test flakiness by checking default ServiceAccount creation
  test/e2e/e2e.go
Labels: approved, cla: yes, lgtm, size/S

#1088 Update Boilerplate to be 2019.
  hack/boilerplate/boilerplate.go.txt
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/broker.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/channel.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/clusterchannelprovisioner.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_broker.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_channel.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_clusterchannelprovisioner.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_subscription.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_trigger.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/subscription.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/trigger.go
  pkg/client/informers/externalversions/eventing/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/broker.go
  pkg/client/informers/externalversions/eventing/v1alpha1/channel.go
  pkg/client/informers/externalversions/eventing/v1alpha1/clusterchannelprovisioner.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/subscription.go
  pkg/client/informers/externalversions/eventing/v1alpha1/trigger.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/listers/eventing/v1alpha1/broker.go
  pkg/client/listers/eventing/v1alpha1/channel.go
  pkg/client/listers/eventing/v1alpha1/clusterchannelprovisioner.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
  pkg/client/listers/eventing/v1alpha1/subscription.go
  pkg/client/listers/eventing/v1alpha1/trigger.go
Labels: approved, cla: yes, lgtm, size/XS

#1079 Issue 734 Move trigger to knative/pkg/controller
  Gopkg.lock
  Gopkg.toml
  cmd/controller/main.go
  docs/broker/README.md
  pkg/broker/receiver.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/trigger.go
  pkg/reconciler/trigger/path/path.go
  pkg/reconciler/trigger/resources/subscription.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
  pkg/reconciler/v1alpha1/trigger/trigger_test.go
  vendor/github.com/knative/pkg/apis/deprecated.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/retired_targetable_types.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/github.com/knative/pkg/metrics/config.go
  vendor/github.com/knative/pkg/metrics/exporter.go
  vendor/github.com/knative/pkg/reconciler/testing/table.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/XXL

#1083 Move channel pkg/controller
  Gopkg.lock
  cmd/controller/main.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/v1alpha1/channel/channel.go
  pkg/reconciler/v1alpha1/channel/channel_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1094 Disable gcp pubsub e2e tests until we fix the flaky tests
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1090 Remove a few obsolete overrides
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/spf13/pflag/bytes.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/string_to_int.go
  vendor/github.com/spf13/pflag/string_to_string.go
Labels: approved, cla: yes, lgtm, size/L

#1089 keeping the original deployments as they were, just more on finalizers
  config/200-webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#1069 Move namespace controller to pkg/controller style.
  cmd/controller/main.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/namespace/resources/broker.go
  pkg/reconciler/namespace/resources/labels.go
  pkg/reconciler/namespace/resources/names.go
  pkg/reconciler/namespace/resources/role_binding.go
  pkg/reconciler/namespace/resources/service_account.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/namespace.go
  pkg/reconciler/v1alpha1/namespace/namespace.go
  pkg/reconciler/v1alpha1/namespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1097 add more unit tests for trigger reconcile.
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1098 update test-infra: skip e2e tests for non-code changes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#972 Kafka dispatcher no need for a statefulset
  contrib/kafka/config/README.md
  contrib/kafka/config/kafka.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1095 k8s forces additionalProperties to true, hence no need to set it ourselves
  config/300-broker.yaml
  config/300-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1074 Remove Istio dependency from Eventing (Part - 3) - Natss
  contrib/natss/config/broker/natss.yaml
  contrib/natss/config/provisioner.yaml
  contrib/natss/pkg/controller/channel/controller.go
  contrib/natss/pkg/controller/channel/reconcile.go
  contrib/natss/pkg/controller/channel/reconcile_test.go
  contrib/natss/pkg/controller/main.go
  contrib/natss/pkg/dispatcher/channel/reconcile.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  pkg/channelwatcher/channel_watcher.go
Labels: approved, cla: yes, lgtm, size/L

#1073 Broker controller new infrastructure
  Gopkg.lock
  cmd/controller/main.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/deployment.go
  pkg/reconciler/testing/service.go
  pkg/reconciler/testing/subscription.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
  pkg/reconciler/v1alpha1/broker/broker.go
  pkg/reconciler/v1alpha1/broker/broker_test.go
  pkg/reconciler/v1alpha1/broker/resources/filter.go
  pkg/reconciler/v1alpha1/broker/resources/ingress.go
Labels: approved, cla: yes, lgtm, size/XXL

#1033 Add OWNERS for the Channel implementations
  OWNERS_ALIASES
  contrib/gcppubsub/OWNERS
  contrib/kafka/OWNERS
  contrib/natss/OWNERS
Labels: approved, cla: yes, lgtm, size/M

#1103 Unit test that NewController doesn't return nil
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#1102 Consistency is king, use "" for the filter
  config/200-broker-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#1100 Add data validation for subscription in reconciler
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/S

#1107 Remove Istio dependency from Eventing (Part - 4) - gcp-pubsub
  config/200-controller-clusterrole.yaml
  contrib/gcppubsub/config/gcppubsub.yaml
  contrib/gcppubsub/pkg/controller/channel/controller.go
  contrib/gcppubsub/pkg/controller/channel/reconcile.go
  contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
  contrib/gcppubsub/pkg/controller/cmd/main.go
  contrib/gcppubsub/pkg/dispatcher/cmd/main.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/controller.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile_test.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver_test.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  pkg/channelwatcher/channel_watcher.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
  pkg/provisioners/inmemory/controller/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1112 compile-time assert numControllers == len(controllersArray)
  cmd/controller/main.go
  cmd/sources-controller/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1118 Fix for https://github.com/knative/eventing/issues/1109
  cmd/controller/main.go
  cmd/sources-controller/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1123 golang format tools
  cmd/broker/ingress/main.go
  cmd/pong/main.go
  cmd/sendevent/main.go
  cmd/sources-controller/main.go
  contrib/gcppubsub/pkg/controller/channel/names_test.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver_test.go
  contrib/gcppubsub/pkg/util/status.go
  contrib/kafka/pkg/dispatcher/dispatcher_test.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  pkg/broker/context.go
  pkg/broker/receiver.go
  pkg/broker/receiver_test.go
  pkg/broker/ttl.go
  pkg/kncloudevents/good_client.go
  pkg/logging/logging.go
  pkg/reconciler/containersource/resources/deployment.go
  pkg/reconciler/containersource/resources/deployment_test.go
  pkg/reconciler/cronjobsource/resources/receive_adapter.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/testing/containersource.go
  pkg/reconciler/testing/factory.go
  pkg/reconciler/testing/namespace.go
  test/e2e/main_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1124 Fix spelling errors
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1126 Enable e2e testing for NATSS
  test/e2e-tests.sh
  test/e2e/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#1127 Namespace Controller watching for Broker, ServiceAccount, and RoleBinding
  Gopkg.lock
  cmd/controller/main.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/M
