Repository knative/eventing, pull requests merged in 2019-03, with the labels that each got.

#845 Fix invalid log message format
  cmd/controller/main.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#846 Inform controller's metrics port is 9090
  config/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#844 Update invalid docs link for telemetry
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#850 Fix config map name for kafka channel dispatcher in README
  contrib/kafka/config/README.md
Labels: approved, cla: yes, lgtm, size/XS

#851 Fix flag parse error by calling flag.Parse from kafka channel dispatcher
  contrib/kafka/cmd/dispatcher/main.go
Labels: approved, cla: yes, lgtm, size/XS

#853 Remove namespace from cluster-scoped resources
  config/provisioners/in-memory-channel/in-memory-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#857 fix lint problems
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#817 add instructions on how to view roadmap
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#858 Adding myself as a reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#855 Use DeletionTimestamp field in subscription struct
  pkg/reconciler/v1alpha1/subscription/subscription.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#856 Use DeletionTimestamp field in channel struct
  contrib/kafka/pkg/controller/channel/reconcile.go
  contrib/kafka/pkg/controller/reconcile.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#861 Format markdown
  README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#843 Defaultcontroller
  Gopkg.lock
  cmd/controller/main.go
  pkg/apis/eventing/v1alpha1/channel_types.go
  pkg/apis/eventing/v1alpha1/channel_types_test.go
  pkg/reconciler/v1alpha1/channel/channel.go
  pkg/reconciler/v1alpha1/channel/channel_test.go
Labels: approved, cla: yes, lgtm, size/L

#842 Distinguish config-logging
  cmd/controller/main.go
  cmd/webhook/main.go
  config/500-controller.yaml
  config/500-webhook.yaml
  pkg/logconfig/config.go
Labels: approved, cla: yes, lgtm, size/M

#864 Fix typo in doc
  test/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#865 Allow {Add,Remove}Finalizers to work on all Objects, not just Channels.
  pkg/provisioners/channel_util.go
Labels: approved, cla: yes, lgtm, size/S

#866 Make ResolveSubscriberSpec a public method
  pkg/reconciler/v1alpha1/subscription/subscription.go
Labels: approved, cla: yes, lgtm, size/S

#869 Add replica config
  contrib/kafka/pkg/controller/channel/reconcile.go
  contrib/kafka/pkg/controller/channel/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/S

#874 Get the latest updates for automatic dot releases
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#875 Move the logging util out of contrib, in preparation for use by other…
  contrib/gcppubsub/pkg/controller/channel/reconcile.go
  contrib/gcppubsub/pkg/controller/clusterchannelprovisioner/reconcile.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver.go
  contrib/gcppubsub/pkg/util/creds.go
  contrib/gcppubsub/pkg/util/status.go
  pkg/logging/logging.go
Labels: approved, cla: yes, lgtm, size/S

#876 Subscription Controller uses zap.Logger
  cmd/controller/main.go
  contrib/gcppubsub/pkg/util/creds.go
  pkg/reconciler/v1alpha1/channel/channel.go
  pkg/reconciler/v1alpha1/subscription/subscription.go
  pkg/reconciler/v1alpha1/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/L

#878 Increase unit test coverage of the Channel reconciler
  pkg/reconciler/v1alpha1/channel/channel_test.go
Labels: approved, cla: yes, lgtm, size/M

#877 Channel Controller uses zap.Logger
  Gopkg.lock
  pkg/reconciler/v1alpha1/channel/channel.go
  pkg/reconciler/v1alpha1/channel/channel_test.go
Labels: approved, cla: yes, lgtm, size/M

#871 Do not call Fatal log during reconciling of kafka channel controller
  contrib/kafka/config/kafka.yaml
  contrib/kafka/pkg/controller/channel/reconcile.go
  contrib/kafka/pkg/controller/channel/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/M

#884 Remove unnecessary printing format
  contrib/kafka/pkg/controller/channel/reconcile.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#887 Update knative/pkg
  Gopkg.lock
  Gopkg.toml
  test/cleanup.go
  test/e2e/e2e.go
  test/e2e/single_event_test.go
  test/e2e_flags.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/logging/config.go
  vendor/github.com/knative/pkg/test/cleanup.go
  vendor/github.com/knative/pkg/test/clients.go
  vendor/github.com/knative/pkg/test/e2e_flags.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/logging/logging.go
  vendor/github.com/knative/pkg/test/monitoring/doc.go
  vendor/github.com/knative/pkg/test/monitoring/monitoring.go
  vendor/github.com/knative/pkg/test/request.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/doc.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
  vendor/github.com/knative/pkg/webhook/certs.go
Labels: approved, cla: yes, lgtm, size/XL

#889 Return exit code in kafka controller to call logger.Sync()
  contrib/kafka/cmd/controller/main.go
Labels: approved, cla: yes, lgtm, size/S

#879 support partition consumer mode for kafka channel
  contrib/kafka/cmd/dispatcher/main.go
  contrib/kafka/main.go
  contrib/kafka/pkg/controller/types.go
  contrib/kafka/pkg/controller/util.go
  contrib/kafka/pkg/controller/util_test.go
  contrib/kafka/pkg/dispatcher/dispatcher.go
  contrib/kafka/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/L

#880 do not unsubscribe for existing consumers upon config map update
  contrib/kafka/pkg/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/S

#902 Create a mock dynamic client.
  pkg/reconciler/testing/mock_dynamic_client.go
  pkg/reconciler/testing/table.go
Labels: approved, cla: yes, lgtm, size/L

#907 Remove markdown lint presubmit check in favor of the sockpuppet.
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#862 Record the decision on Broker and Trigger
  docs/decisions/broker-trigger.md
Labels: approved, cla: yes, lgtm, size/L

#911 golang format tools
  contrib/kafka/main.go
  contrib/kafka/pkg/controller/types.go
  contrib/kafka/pkg/controller/util.go
  contrib/kafka/pkg/controller/util_test.go
  contrib/kafka/pkg/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#920 Updated the link for the eventing docs so it is pointing to the corre…
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#465 adding n3wscott to approvers.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#921 Set memory limits
  config/500-controller.yaml
  config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#919 New templates to create bug, customer issue and feature request
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: approved, area/test-and-release, cla: yes, kind/bug, kind/doc, kind/proposal, lgtm, size/M

#924 Migrate our usage of pkg/cloudevents to cloudevents sdk.
  Gopkg.lock
  Gopkg.toml
  cmd/sendevent/main.go
  test/test_images/logevents/main.go
  test/test_images/sendevent/main.go
  third_party/VENDOR-LICENSE
  vendor/github.com/cloudevents/sdk-go/LICENSE
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/receiver.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/content_type.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/context/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_response.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/encoding.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/message.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/message.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/allocate.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/timestamp.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/urlref.go
  vendor/github.com/knative/pkg/cloudevents/builder.go
  vendor/github.com/knative/pkg/cloudevents/client.go
  vendor/github.com/knative/pkg/cloudevents/doc.go
  vendor/github.com/knative/pkg/cloudevents/encoding_binary.go
  vendor/github.com/knative/pkg/cloudevents/encoding_structured.go
  vendor/github.com/knative/pkg/cloudevents/event.go
  vendor/github.com/knative/pkg/cloudevents/event_v01.go
  vendor/github.com/knative/pkg/cloudevents/event_v02.go
  vendor/github.com/knative/pkg/cloudevents/handler.go
Labels: approved, cla: yes, lgtm, size/XXL

#935 Use common test components defined in pkg/test
  Gopkg.lock
  test/cleanup.go
  test/clients.go
  test/crd.go
  test/e2e/broker_trigger_test.go
  test/e2e/e2e.go
  test/e2e/single_event_test.go
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/L

#917 Trigger responses are sent back into the Broker.
  Gopkg.lock
  cmd/broker/filter/main.go
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/broker_types_test.go
  pkg/broker/receiver.go
  pkg/broker/receiver_test.go
  pkg/reconciler/v1alpha1/broker/broker.go
  pkg/reconciler/v1alpha1/broker/broker_test.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
  pkg/reconciler/v1alpha1/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#941 Fix broken links to docs repo
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  docs/spec/README.md
Labels: approved, cla: yes, lgtm, size/S

#945 updated the link to WORKING-GROUPS.md in the README.md of the Eventin…
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#936 Tracing works with Broker and Trigger
  Gopkg.lock
  Gopkg.toml
  pkg/broker/receiver.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/context/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/context/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/observability/keys.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/observability/observer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/encoding.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/timestamp.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/urlref.go
Labels: approved, cla: yes, lgtm, size/XXL

#933 Switch the Broker's Ingress to use CloudEvents SDK
  cmd/broker/ingress/main.go
  pkg/broker/context.go
  pkg/broker/receiver.go
  pkg/broker/receiver_test.go
Labels: approved, cla: yes, lgtm, size/L

#942 User can specify webhook deployment name
  cmd/webhook/main.go
  config/500-webhook.yaml
  pkg/logconfig/config.go
Labels: approved, cla: yes, lgtm, size/M

#947 Point to new ko repo
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#952 Fix some broker vet and lint issues
  cmd/broker/ingress/main.go
  pkg/broker/receiver.go
Labels: approved, cla: yes, lgtm, size/M

#949 Trigger Reply Tracing
  Gopkg.lock
  Gopkg.toml
  pkg/broker/context.go
  pkg/broker/receiver.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/defaulters.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/jsoncodec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/codec/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/data.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_response.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/observability/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/observability/keys.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/observability/observer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/context.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/doc.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/encoding.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/message.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/message.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/types/allocate.go
Labels: approved, cla: yes, lgtm, size/XL

#954 Updating links to docs repo
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  docs/spec/README.md
  sample/README.md
Labels: approved, cla: yes, lgtm, size/S

#943 Adding broker/trigger to the spec.
  docs/spec/images/broker-trigger-overview.svg
  docs/spec/overview.md
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/L

#962 Format markdown
  CONTRIBUTING.md
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#965 golang format tools
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/channel_defaults.go
  pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_validation.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/apis/eventing/v1alpha1/trigger_validation.go
  test/test_images/logevents/main.go
  test/test_images/sendevent/main.go
Labels: approved, cla: yes, lgtm, size/S

#967 Passthrough the header 'b3'
  pkg/broker/context.go
  pkg/broker/receiver_test.go
Labels: approved, cla: yes, lgtm, size/S

#937 Basic Broker ingress metrics
  Gopkg.lock
  cmd/broker/ingress/main.go
  cmd/broker/ingress/metrics.go
  docs/metrics.md
  pkg/reconciler/v1alpha1/broker/resources/ingress.go
  pkg/utils/runnable_server.go
  pkg/utils/runnable_server_test.go
  vendor/go.opencensus.io/exporter/prometheus/prometheus.go
Labels: approved, cla: yes, lgtm, size/XL

#966 Remove a go vet issue and add comments to exported methods.
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  pkg/reconciler/v1alpha1/broker/broker.go
  pkg/reconciler/v1alpha1/broker/resources/filter.go
  pkg/reconciler/v1alpha1/broker/resources/ingress.go
  pkg/reconciler/v1alpha1/channel/channel.go
  pkg/reconciler/v1alpha1/channel/channel_test.go
  pkg/reconciler/v1alpha1/namespace/namespace.go
  pkg/reconciler/v1alpha1/subscription/provider_test.go
  pkg/reconciler/v1alpha1/subscription/subscription.go
  pkg/reconciler/v1alpha1/subscription/subscription_test.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#973 Adios old roadmap static file
  roadmap.md
Labels: approved, cla: yes, lgtm, size/M

#971 Update docs to reflect #917.
  docs/broker/README.md
Labels: approved, cla: yes, lgtm, size/S

#881 Configure natss url and cluster id via the environment
  contrib/natss/config/README.md
  contrib/natss/pkg/controller/clusterchannelprovisioner/controller.go
  contrib/natss/pkg/controller/main.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  contrib/natss/pkg/dispatcher/main.go
  contrib/natss/pkg/util/util.go
Labels: approved, cla: yes, lgtm, size/L

#974 remove the DeprecatedGeneration from Trigger/Broker
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
Labels: approved, cla: yes, lgtm, size/S

#970 Update comments and remove some test warnings.
  pkg/reconciler/names/names.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
  pkg/sidecar/configmap/parse.go
  pkg/sidecar/fanout/fanout_handler_test.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go
  pkg/sidecar/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/sidecar/swappable/swappable.go
  pkg/sidecar/swappable/swappable_test.go
  pkg/utils/blocking_start.go
  pkg/utils/resolve/subscriber.go
Labels: approved, cla: yes, lgtm, size/M

#975 Format markdown
  contrib/natss/config/README.md
  docs/broker/README.md
  docs/metrics.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#951 Add TTL to the Broker.
  cmd/broker/ingress/main.go
  pkg/broker/receiver.go
  pkg/broker/receiver_test.go
  pkg/broker/ttl.go
Labels: approved, cla: yes, lgtm, size/L

#979 Log event headers instead of data
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#908 Document consumer_mode for kafka consumer mode
  contrib/kafka/config/README.md
  contrib/kafka/config/kafka.yaml
  contrib/kafka/pkg/controller/util.go
  contrib/kafka/pkg/controller/util_test.go
Labels: approved, cla: yes, lgtm, size/S

#910 KNative sprint/release planning process
  docs/planning/images/featureplanning.png
  docs/planning/sprintplanning.md
Labels: approved, cla: yes, lgtm, size/M

#872 Explicit cluster roles for controller/webhook, not cluster-admin
  config/200-controller-clusterrole.yaml
  config/200-serviceaccount.yaml
  config/200-webhook-clusterrole.yaml
  config/201-clusterrolebinding.yaml
  config/500-webhook.yaml
Labels: approved, cla: yes, lgtm, size/L

#986 Rename the ClusterRoleBindings, as they no longer give admin privileges.
  config/201-clusterrolebinding.yaml
Labels: approved, cla: yes, lgtm, size/XS

#985 Change the special value representing 'allow all events' from 'Any' to the empty string
  docs/broker/README.md
  docs/broker/example_triggers.yaml
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/broker/receiver_test.go
  test/e2e/broker_trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#987 Change webhook rbac permission to use apps.deployments instead of extensions.deployments. Remove create for eventing.knative.dev resources
  Gopkg.lock
  Gopkg.toml
  config/200-webhook-clusterrole.yaml
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/github.com/knative/pkg/apis/field_error.go
  vendor/github.com/knative/pkg/test/ingress/ingress.go
  vendor/github.com/knative/pkg/test/kube_checks.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/webhook/webhook.go
Labels: approved, cla: yes, lgtm, size/L

#988 Add OpenAPI schema to Broker and Trigger.
  config/300-broker.yaml
  config/300-trigger.yaml
Labels: approved, cla: yes, lgtm, size/M

#994 Create subscriber.uri and deprecate subscriber.dnsName
  pkg/apis/eventing/v1alpha1/channel_validation_test.go
  pkg/apis/eventing/v1alpha1/subscription_types.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/apis/eventing/v1alpha1/subscription_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/v1alpha1/broker/broker_test.go
  pkg/utils/resolve/subscriber.go
  pkg/utils/resolve/subscriber_test.go
Labels: approved, cla: yes, lgtm, size/L

#998 Add OpenAPI schema to Channels.
  config/300-channel.yaml
Labels: approved, cla: yes, lgtm, size/M

#1001 Update gengo
  Gopkg.lock
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/informers/externalversions/eventing/v1alpha1/broker.go
  pkg/client/informers/externalversions/eventing/v1alpha1/channel.go
  pkg/client/informers/externalversions/eventing/v1alpha1/clusterchannelprovisioner.go
  pkg/client/informers/externalversions/eventing/v1alpha1/subscription.go
  pkg/client/informers/externalversions/eventing/v1alpha1/trigger.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/plural_namer.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/k8s.io/gengo/types/types.go
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XXL

#1000 OpenAPI schema for Subscriptions.
  config/300-subscription.yaml
Labels: approved, cla: yes, lgtm, size/M

#989 Format markdown
  docs/broker/README.md
  docs/planning/sprintplanning.md
Labels: approved, cla: yes, lgtm, size/L

#997 Fix indentation of Broker schema YAML.
  config/300-broker.yaml
Labels: approved, cla: yes, lgtm, size/XS

#999 Add subscriber.uri to Trigger's OpenAPI schema, to match #994.
  config/300-trigger.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1006 Address pkg struct renaming
  Gopkg.lock
  Gopkg.toml
  cmd/controller/main.go
  contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
  contrib/kafka/pkg/controller/channel/reconcile_test.go
  contrib/natss/pkg/controller/channel/reconcile_test.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
  pkg/provisioners/message_receiver.go
  pkg/reconciler/v1alpha1/trigger/trigger.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/destinationrule_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/gateway_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/github.com/knative/pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/test/spoof/error_checks.go
  vendor/github.com/knative/pkg/test/spoof/spoof.go
  vendor/github.com/knative/pkg/test/zipkin/util.go
Labels: approved, cla: yes, lgtm, size/L

#1008 Use the CloudEvent client to send.
  cmd/broker/ingress/main.go
  pkg/broker/receiver.go
Labels: approved, cla: yes, lgtm, size/S

#981 Fix patch merge on channel subscribers.
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/reconciler/v1alpha1/subscription/subscription.go
  pkg/reconciler/v1alpha1/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/M

#1007 Add a label knative.dev/crd-install to CRDs to allow installing CRDs in a separate pass.
  config/300-broker.yaml
  config/300-channel.yaml
  config/300-clusterchannelprovisioner.yaml
  config/300-subscription.yaml
  config/300-trigger.yaml
Labels: approved, cla: yes, lgtm, size/S

#1004 Address multiple lint errors.
  pkg/apis/eventing/logkey/constants.go
  pkg/apis/eventing/v1alpha1/channel_validation.go
  pkg/apis/eventing/v1alpha1/subscription_validation.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile_test.go
  pkg/reconciler/v1alpha1/subscription/subscription.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher.go
  pkg/sidecar/multichannelfanout/parse.go
Labels: approved, cla: yes, lgtm, size/M
