Repository knative/eventing, pull requests merged in 2019-02, with the labels that each got.

#763 adding link to roadmap
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#708 refactor in-memory channel to support sync and async handlers
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  pkg/controller/eventing/inmemory/channel/reconcile.go
  pkg/controller/eventing/inmemory/channel/reconcile_test.go
  pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile.go
  pkg/controller/eventing/inmemory/clusterchannelprovisioner/reconcile_test.go
  pkg/controller/eventing/inmemory/controller/main.go
  pkg/sidecar/fanout/fanout_handler.go
  pkg/sidecar/fanout/fanout_handler_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#778 Mention Channel provisioners in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#776 Update test-infra to fix release script
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#775 Adding RateLimiter to GCP PubSub channel to backoff retries on dispatch failures
  Gopkg.lock
  contrib/gcppubsub/pkg/dispatcher/dispatcher/controller.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#774 make config snippet more readable
  contrib/kafka/config/README.md
Labels: approved, cla: yes, lgtm, size/S

#780 Update test infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#783 golang format tools
  contrib/gcppubsub/pkg/controller/channel/controller.go
  contrib/gcppubsub/pkg/controller/channel/reconcile.go
  contrib/gcppubsub/pkg/controller/clusterchannelprovisioner/reconcile.go
  contrib/gcppubsub/pkg/controller/cmd/main.go
  contrib/gcppubsub/pkg/dispatcher/cmd/main.go
  contrib/gcppubsub/pkg/util/status.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#789 change the use of map[string]bool to use k8s string sets.
  contrib/kafka/pkg/dispatcher/dispatcher.go
  contrib/kafka/pkg/dispatcher/dispatcher_test.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  pkg/provisioners/message.go
  pkg/provisioners/message_dispatcher.go
  pkg/provisioners/message_receiver.go
  pkg/sidecar/fanout/fanout_handler.go
Labels: approved, cla: yes, lgtm, size/L

#797 Clean up unit tests to use actual domain name
  contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile_test.go
  contrib/gcppubsub/pkg/dispatcher/receiver/receiver_test.go
  contrib/kafka/pkg/controller/channel/reconcile_test.go
  contrib/natss/pkg/controller/channel/reconcile_test.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
  pkg/provisioners/message_receiver_test.go
  pkg/reconciler/names/names_test.go
  pkg/reconciler/v1alpha1/subscription/subscription_test.go
  pkg/sidecar/configmap/filesystem/filesystem_watcher_test.go
  pkg/sidecar/configmap/parse_test.go
  pkg/sidecar/multichannelfanout/parse_test.go
Labels: approved, cla: yes, lgtm, size/L

#793 Manually fixup prettier.io bugs.
  DEVELOPMENT.md
  contrib/gcppubsub/config/README.md
  contrib/kafka/config/README.md
Labels: approved, cla: yes, lgtm, size/M

#795 Adding corev1.Events to GCP PubSub channel for easier debugging
  contrib/gcppubsub/config/gcppubsub.yaml
  contrib/gcppubsub/pkg/controller/channel/reconcile.go
  contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
  contrib/gcppubsub/pkg/controller/clusterchannelprovisioner/reconcile.go
  contrib/gcppubsub/pkg/controller/clusterchannelprovisioner/reconcile_test.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/reconcile_test.go
Labels: approved, cla: yes, lgtm, size/L

#800 Use new test image names in E2E tests
  test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#801 Adding verbs to emit corev1.Events to gcp-pubsub dispatcher.
  contrib/gcppubsub/config/gcppubsub.yaml
Labels: approved, cla: yes, lgtm, size/XS

#802 Update test infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.json
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#805 update deps:test-infra for fixing release.yaml not found error
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#806 Opt knative-eventing into Istio injection
  config/100-namespace.yaml
Labels: approved, cla: yes, lgtm, size/XS

#803 golang format tools
  contrib/kafka/pkg/controller/channel/reconcile.go
  contrib/kafka/pkg/controller/reconcile_test.go
  contrib/natss/pkg/controller/channel/reconcile.go
  contrib/natss/pkg/controller/clusterchannelprovisioner/reconcile_test.go
  pkg/provisioners/inmemory/channel/controller_test.go
  pkg/provisioners/inmemory/clusterchannelprovisioner/controller_test.go
  pkg/provisioners/inmemory/clusterchannelprovisioner/reconcile_test.go
  pkg/provisioners/inmemory/controller/main.go
  pkg/reconciler/names/names_test.go
  pkg/reconciler/v1alpha1/subscription/provider_test.go
  pkg/reconciler/v1alpha1/subscription/subscription.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#794 Adding header to the message being published
  Gopkg.lock
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  pkg/provisioners/message.go
  vendor/go.uber.org/zap/zaptest/observer/logged_entry.go
  vendor/go.uber.org/zap/zaptest/observer/observer.go
Labels: approved, cla: yes, lgtm, size/L

#810 Update README.md
  contrib/kafka/config/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#813 Bump knative/pkg - we drop webhook logic that increments spec.generation
  Gopkg.lock
  Gopkg.toml
  pkg/apis/eventing/v1alpha1/implements_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/generational_types.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/register.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/interfaces.go
  vendor/github.com/knative/pkg/webhook/webhook.go
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, cla: yes, lgtm, size/XL

#812 golang format tools
  cmd/controller/main.go
  contrib/gcppubsub/pkg/controller/channel/reconcile_test.go
  contrib/gcppubsub/pkg/controller/clusterchannelprovisioner/reconcile_test.go
  contrib/kafka/pkg/controller/channel/reconcile_test.go
  contrib/natss/pkg/controller/channel/reconcile_test.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/channel_util_test.go
  pkg/provisioners/inmemory/channel/controller.go
  pkg/provisioners/inmemory/channel/reconcile_test.go
  pkg/provisioners/message_receiver_test.go
  pkg/provisioners/provisioner_util.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#790 Switch the default channel provisioner from 'in-memory-channel' to 'in-memory'
  config/400-default-channel-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#758 Customize markdown checks
  test/markdown-lint-config.rc
Labels: approved, cla: yes, lgtm, size/XS

#796 Restart dispatcher on connection loss
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
  contrib/natss/pkg/stanutil/stanutil.go
Labels: approved, cla: yes, lgtm, size/L

#820 update dep for github.com/knative/test-infra along with fixes
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#819 Replace DOCKER_REPO_OVERRIDE by KO_DOCKER_REPO in test folder
  test/README.md
  test/e2e_flags.go
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, size/S

#821 Switch to a non blocking send
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#824 Fix `env` var indentation and grouping in contrib yamls
  contrib/gcppubsub/config/gcppubsub.yaml
  contrib/natss/config/provisioner.yaml
Labels: approved, cla: yes, lgtm, size/M

#782 Add Harwayne as an approver.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#832 golang format tools
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS

#828 ConfigMapWatcher.Start() blocks, rather than eagerly returning nil
  Gopkg.lock
  cmd/fanoutsidecar/main.go
  config/provisioners/in-memory-channel/in-memory-channel.yaml
  contrib/kafka/cmd/dispatcher/main.go
  contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go
  contrib/natss/pkg/dispatcher/main.go
  pkg/utils/blocking_start.go
  pkg/utils/blocking_start_test.go
  test/cleanup.go
  test/e2e/single_event_test.go
Labels: approved, cla: yes, lgtm, size/L

#838 golang format tools
  pkg/utils/blocking_start_test.go
Labels: approved, cla: yes, lgtm, size/XS

#829 Add labels to the stateful set.
  contrib/natss/config/broker/natss.yaml
Labels: approved, cla: yes, lgtm, size/XS

#839 remove inlined and scothis from reviewers and approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#834 Remove fake ListOptions
  contrib/kafka/pkg/controller/channel/reconcile.go
  pkg/provisioners/channel_util.go
  pkg/provisioners/inmemory/channel/reconcile.go
  pkg/reconciler/v1alpha1/subscription/subscription.go
Labels: approved, cla: yes, lgtm, size/M

#835 Simplify Channel Watch
  contrib/gcppubsub/pkg/dispatcher/cmd/main.go
  contrib/gcppubsub/pkg/dispatcher/dispatcher/controller.go
Labels: approved, cla: yes, lgtm, size/M

#840 Update test-infra
  Gopkg.lock
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L
