Repository knative/eventing, pull requests merged in 2020-07, with the labels that each got.

#3453 Add nlopezgi to reviewers list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3450 deal with malformed events as errors
  docs/spec/broker.md
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/filter/filter_handler_test.go
Labels: approved, cla: yes, lgtm, size/L

#3456 [release-0.15] Add configuration options to the temp files for Probe tests (#3420)
  test/e2e-upgrade-tests.sh
  test/e2e_flags.go
  test/upgrade/probe_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3439 Adding broker cleaner script to post-0.16.0 install
  cmd/v0.16/broker-cleanup/README.md
  cmd/v0.16/broker-cleanup/injection.go
  cmd/v0.16/broker-cleanup/main.go
  config/post-install/v0.16.0/broker-cleanup.yaml
  config/post-install/v0.16.0/dummy.go
  go.mod
  hack/release.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#3181 mt bits for 3162
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Labels: approved, cla: yes, lgtm, size/S

#3454 flows v1 e2e tests
  pkg/reconciler/testing/v1/parallel.go
  pkg/reconciler/testing/v1/sequence.go
  test/e2e/helpers/parallel_test_helper.go
  test/e2e/helpers/sequence_test_helper.go
  test/e2e/parallel_test.go
  test/e2e/sequence_test.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3457 do not create a combined upgrade.yaml file
  hack/release.sh
Labels: approved, cla: yes, lgtm

#3460 Expand the variadic args.
  pkg/apis/messaging/v1/subscription_lifecycle.go
  pkg/apis/messaging/v1beta1/subscription_lifecycle.go
Labels: approved, cla: yes, lgtm, size/XS

#3470 add a hack to work around knative-monitoring ns missing
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3468 Do not default trigger.spec.broker for v1.Trigger
  config/core/resources/trigger.yaml
  pkg/apis/eventing/v1/trigger_defaults.go
  pkg/apis/eventing/v1/trigger_defaults_test.go
Labels: approved, cla: yes, lgtm, size/M

#3465 add cluster role for bindings
  config/core/roles/clusterrole-namespaced.yaml
Labels: approved, cla: yes, lgtm, size/S

#3461 bump channel,imc,subscription to v1, add e2e tests
  config/channels/in-memory-channel/300-in-memory-channel.yaml
  config/core/resources/channel.yaml
  config/core/resources/subscription.yaml
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
  pkg/apis/messaging/v1/channel_types.go
  pkg/apis/messaging/v1beta1/channel_conversion.go
  pkg/apis/messaging/v1beta1/channel_conversion_test.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go
  pkg/reconciler/subscription/subscription.go
  test/conformance/helpers/channel.go
  test/conformance/helpers/channel_spec_test_helper.go
  test/conformance/helpers/channel_status_subscriber_test_helper.go
  test/conformance/helpers/channel_status_test_helper.go
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
  test/e2e/channel_chain_test.go
  test/e2e/channel_dls_test.go
  test/e2e/channel_event_transformation_test.go
  test/e2e/channel_single_event_test.go
  test/e2e/helpers/channel_chain_test_helper.go
  test/e2e/helpers/channel_dls_test_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/e2e/helpers/channel_single_event_helper.go
  test/lib/creation.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#3471 Make SubscribableStatus implement apis.Convertible
  pkg/apis/duck/v1/subscribable_types.go
  pkg/apis/duck/v1/subscribable_types_conversion.go
  pkg/apis/duck/v1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1beta1/subscribable_types.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
  pkg/apis/messaging/v1beta1/channel_conversion.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
Labels: approved, cla: yes, lgtm, size/L

#3496 use consistent version with tracker/lister
  pkg/reconciler/subscription/subscription.go
Labels: approved, cla: yes, lgtm, size/XS

#3492 [master] golang format tools
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go
Labels: approved, cla: yes, lgtm, size/M

#3509 Add aliok to reviewers list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#3400 pluggable leader election strategy
  config/core/configmaps/leader-election.yaml
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_message.go
  pkg/leaderelection/context.go
  pkg/leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/L

#3472 Make SubscribableSpec implement apis.Convertible
  pkg/apis/duck/v1/subscribable_types.go
  pkg/apis/duck/v1/subscribable_types_conversion.go
  pkg/apis/duck/v1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1beta1/subscribable_types.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
  pkg/apis/messaging/v1beta1/channel_conversion.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
Labels: approved, cla: yes, lgtm, size/L

#3507 Validate brokerclass exists
  pkg/apis/eventing/v1/broker_validation.go
  pkg/apis/eventing/v1/broker_validation_test.go
  pkg/apis/eventing/v1beta1/broker_validation.go
  pkg/apis/eventing/v1beta1/broker_validation_test.go
  pkg/reconciler/mtnamespace/resources/broker.go
Labels: approved, cla: yes, lgtm, size/L

#3511 fix bad merge
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3081 mtping reports general error and timeout
  pkg/adapter/v2/cloudevents.go
Labels: approved, cla: yes, lgtm, size/XS

#3473 Make SubscriberSpec implement apis.Convertible
  pkg/apis/duck/v1/subscribable_types.go
  pkg/apis/duck/v1/subscribable_types_conversion.go
  pkg/apis/duck/v1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1beta1/subscribable_types.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#3514 drop use of unsupported resource locks from the leaderelection example config
  config/core/configmaps/leader-election.yaml
  pkg/leaderelection/leader_election_test.go
Labels: approved, cla: yes, lgtm, size/S

#3475 Make SubscriberStatus implement apis.Convertible
  pkg/apis/duck/v1/subscribable_types.go
  pkg/apis/duck/v1/subscribable_types_conversion.go
  pkg/apis/duck/v1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1beta1/subscribable_types.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
Labels: approved, cla: yes, lgtm, size/M

#3522 actually make subscription.spec.channel immutable
  pkg/apis/messaging/v1/subscription_validation.go
  pkg/apis/messaging/v1/subscription_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#3520 actually make channel.spec.channelspec immutable
  pkg/apis/messaging/v1/channel_validation.go
  pkg/apis/messaging/v1/channel_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#3523 actually make brokerclass immutable
  pkg/apis/eventing/v1/broker_validation.go
  pkg/apis/eventing/v1/broker_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#3517 actually make trigger.spec.broker immutable
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#3519 Adapter main now inject standard elector builder
  pkg/adapter/v2/config_test.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_message.go
  pkg/adapter/v2/main_message_test.go
  pkg/adapter/v2/main_test.go
Labels: approved, cla: yes, lgtm, size/M

#3405 apply k8s leader election graceful release fix in vendor
  hack/k8s-client-go.patch
  hack/update-deps.sh
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3528 v1beta1 still defaults broker
  config/core/resources/trigger.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3476 Improve error handling at conversion of Subscribable subtypes
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
Labels: approved, cla: yes, lgtm, size/M

#3525 Use string consts for annotation key/values
  pkg/reconciler/sugar/resources/broker.go
Labels: approved, cla: yes, lgtm, size/XS

#3527 [master] golang format tools
  test/e2e/helpers/broker_test_helper.go
  test/e2e/source_api_server_test.go
  test/e2e/source_ping_test.go
  test/e2e/trigger_dependency_annotation_test.go
  test/upgrade/prober/configuration.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3539 Use the standard resource creation libs for upgrade tests.
  test/upgrade/prober/configuration.go
  test/upgrade/prober/prober.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3543 nil check on addressable
  test/lib/duck/resource_inspectors.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3536 Rename the migration yaml names into eventing-pre- and eventing-post-install-jobs
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3537 remove unnecessary patch
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3494 remove the v1alpha1 api versions all together
  config/channels/in-memory-channel/300-in-memory-channel.yaml
  config/core/resources/broker.yaml
  config/core/resources/channel.yaml
  config/core/resources/parallel.yaml
  config/core/resources/sequence.yaml
  config/core/resources/subscription.yaml
  config/core/resources/trigger.yaml
Labels: approved, cla: yes, lgtm, size/L

#3547 remove the channel-broker configs and release files
  config/brokers/channel-broker/500-controller.yaml
  config/brokers/channel-broker/deployments/controller.yaml
  config/brokers/channel-broker/deployments/dummy.go
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3542 Update the job name and label into storage-version-migration-eventing
  config/pre-install/v0.16.0/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3548 Remove channel-broker from tests
  test/e2e-common.sh
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3534 Adding istio annotation
  config/post-install/v0.15.0/storage-version-migration.yaml
  config/pre-install/v0.16.0/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3477 Subscribable types and subtypes v1<>v1alpha1 conversion
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#3556 adding istio annotation
  config/post-install/v0.15.0/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3560 Migrate the source CRD reconciler to use genreconciler.
  pkg/reconciler/source/crd/controller.go
  pkg/reconciler/source/crd/crd.go
  pkg/reconciler/source/crd/crd_test.go
  pkg/reconciler/testing/customresourcedefinition.go
  pkg/reconciler/testing/factory.go
  pkg/reconciler/testing/listers.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/fake/fake.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#3562 Without this RBAC, leaderelection cannot be enabled.
  config/core/roles/controller-clusterroles.yaml
  config/core/roles/webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/S

#3545 Allow registering custom conditions for the Broker
  pkg/apis/eventing/v1/broker_lifecycle.go
  pkg/apis/eventing/v1/broker_lifecycle_mt.go
  pkg/apis/eventing/v1/broker_lifecycle_test.go
  pkg/apis/eventing/v1beta1/broker_lifecycle.go
  pkg/apis/eventing/v1beta1/broker_lifecycle_mt.go
  pkg/apis/eventing/v1beta1/broker_lifecycle_test.go
  pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  pkg/reconciler/mtbroker/controller.go
Labels: approved, cla: yes, lgtm, size/L

#3557 adding istion annotation (#3534)
  config/post-install/v0.15.0/storage-version-migration.yaml
  config/pre-install/v0.16.0/storage-version-migration.yaml
  test/lib/duck/resource_inspectors.go
  test/upgrade/prober/configuration.go
  test/upgrade/prober/prober.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#3563 Fix checksums
  config/core/configmaps/leader-election.yaml
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3390 Showing eventing errors to user
  config/core/configmaps/observability.yaml
  pkg/adapter/mtping/controller.go
  pkg/adapter/mtping/pingsource.go
  pkg/adapter/mtping/pingsource_test.go
  pkg/adapter/mtping/runner.go
  pkg/adapter/mtping/runner_test.go
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/util/crstatusevent/eventsstatus.go
  pkg/adapter/v2/util/crstatusevent/eventsstatus_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3564 Enable HA by default
  cmd/webhook/main.go
  config/core/configmaps/leader-election.yaml
  go.mod
  go.sum
  pkg/adapter/v2/config.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_message.go
  pkg/adapter/v2/main_message_test.go
  pkg/adapter/v2/main_test.go
  pkg/leaderelection/context.go
  pkg/leaderelection/context_test.go
  pkg/leaderelection/leader_election.go
  pkg/leaderelection/leader_election_test.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/google.golang.org/api/container/v1beta1/container-api.json
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/trace.pb.go
  vendor/google.golang.org/genproto/googleapis/devtools/cloudtrace/v2/tracing.pb.go
  vendor/knative.dev/pkg/apis/duck/ducktypes/ducktypes.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1_tests.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#3586 generate reconcilers for flows.* v1 resources
  pkg/apis/flows/v1/parallel_types.go
  pkg/apis/flows/v1/sequence_types.go
  pkg/client/injection/reconciler/flows/v1/parallel/controller.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/controller.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3576 Remove the resource lock since it's going away in pkg
  config/core/configmaps/observability.yaml
  go.mod
  go.sum
  pkg/adapter/v2/config.go
  pkg/leaderelection/context.go
  pkg/leaderelection/context_test.go
  pkg/leaderelection/leader_election_test.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1_tests.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/binding_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1_tests.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3587 reconcile eventing with v1 resources, generate v1 dependent resources
  pkg/apis/duck/v1/register.go
  pkg/apis/duck/v1/register_test.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/config.go
  pkg/reconciler/mtbroker/config_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/controller_test.go
  pkg/reconciler/mtbroker/resources/channel.go
  pkg/reconciler/mtbroker/resources/channel_test.go
  pkg/reconciler/mtbroker/resources/subscription.go
  pkg/reconciler/mtbroker/resources/subscription_test.go
  pkg/reconciler/mtbroker/trigger.go
  pkg/reconciler/sugar/trigger/path/path.go
  pkg/reconciler/testing/v1/broker.go
  pkg/reconciler/testing/v1/configmap.go
  pkg/reconciler/testing/v1/endpoints.go
  pkg/reconciler/testing/v1/factory.go
  pkg/reconciler/testing/v1/listers.go
  pkg/reconciler/testing/v1/trigger.go
  pkg/reconciler/testing/v1/unstructured.go
Labels: approved, cla: yes, lgtm, size/XXL

#3592 Make the mtbroker use the recorder off context.
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#3593 Drop vestigial lister
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#3597 don't force using /bin/bash
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3596 Set a high terminationGracePeriodSeconds on webhook
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3574 add roundtrip tests
  go.mod
  pkg/apis/duck/v1/fuzzer.go
  pkg/apis/duck/v1beta1/delivery_conversion.go
  pkg/apis/duck/v1beta1/delivery_conversion_test.go
  pkg/apis/eventing/v1/fuzzer.go
  pkg/apis/eventing/v1/roundtrip_test.go
  pkg/apis/eventing/v1beta1/roundtrip_test.go
  pkg/apis/flows/v1/fuzzer.go
  pkg/apis/flows/v1/roundtrip_test.go
  pkg/apis/flows/v1beta1/roundtrip_test.go
  pkg/apis/messaging/v1/fuzzer.go
  pkg/apis/messaging/v1/roundtrip_test.go
  pkg/apis/messaging/v1beta1/channel_conversion.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1beta1/roundtrip_test.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/codec.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/fuzzer.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer/valuefuzz.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/compatibility.go
  vendor/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#3600 use configmaplister
  pkg/reconciler/pingsource/pingsource.go
Labels: approved, cla: yes, lgtm, size/XS

#3575 SinkBinding v1beta1 defaults & conversion
  cmd/webhook/main.go
  config/core/resources/sinkbindings.yaml
  go.mod
  go.sum
  pkg/apis/sources/v1alpha1/sinkbinding_conversion.go
  pkg/apis/sources/v1alpha1/sinkbinding_conversion_test.go
  pkg/apis/sources/v1alpha2/sinkbinding_conversion.go
  pkg/apis/sources/v1alpha2/sinkbinding_conversion_test.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/leaderelection/ordinal.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#3601 dump failed objects to aid in debugging
  test/lib/operation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3595 use git apply instead of patch
  hack/k8s-client-go.patch
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3577 SinkBinding v1beta1 Reconciler & E2E test
  pkg/reconciler/sinkbinding/controller.go
  pkg/reconciler/testing/sinkbinding.go
  test/e2e/source_sinkbinding_v1beta1_test.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3610 manually upgrade deps
  go.mod
  go.sum
  vendor/cloud.google.com/go/CHANGES.md
  vendor/cloud.google.com/go/container/apiv1/doc.go
  vendor/cloud.google.com/go/go.mod
  vendor/cloud.google.com/go/go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/version/version.go
  vendor/cloud.google.com/go/trace/apiv2/doc.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3609 configmaplister, reduce trigger status churn
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/controller_test.go
  pkg/reconciler/mtbroker/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#3608 Return an error if the test client cannot getTracingConfig
  test/lib/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3617 Conversion webhook for ContainerSources v1beta1
  cmd/webhook/main.go
  config/core/resources/containersource.yaml
  pkg/apis/sources/v1alpha2/container_conversion.go
  pkg/apis/sources/v1alpha2/container_conversion_test.go
  pkg/apis/sources/v1beta1/container_conversion.go
  pkg/apis/sources/v1beta1/container_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#3619 DeliverySpec.BackoffDelay accept ISO8601 duration
  docs/delivery/README.md
  go.mod
  go.sum
  pkg/apis/duck/v1/delivery_types.go
  pkg/apis/duck/v1/delivery_types_test.go
  pkg/apis/duck/v1beta1/delivery_types.go
  pkg/apis/duck/v1beta1/delivery_types_test.go
  third_party/VENDOR-LICENSE/github.com/rickb777/date/period/LICENSE
  third_party/VENDOR-LICENSE/github.com/rickb777/plural/LICENSE
  vendor/github.com/rickb777/date/LICENSE
  vendor/github.com/rickb777/date/period/doc.go
  vendor/github.com/rickb777/date/period/format.go
  vendor/github.com/rickb777/date/period/marshal.go
  vendor/github.com/rickb777/date/period/parse.go
  vendor/github.com/rickb777/date/period/period.go
  vendor/github.com/rickb777/plural/.gitignore
  vendor/github.com/rickb777/plural/.travis.yml
  vendor/github.com/rickb777/plural/LICENSE
  vendor/github.com/rickb777/plural/README.md
  vendor/github.com/rickb777/plural/build+test.sh
  vendor/github.com/rickb777/plural/doc.go
  vendor/github.com/rickb777/plural/go.mod
  vendor/github.com/rickb777/plural/plural.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#3620 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3616 Apiserversource defaults conversion
  cmd/webhook/main.go
  config/core/resources/apiserversource.yaml
  pkg/apis/sources/v1alpha1/apiserver_conversion.go
  pkg/apis/sources/v1alpha1/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha2/apiserver_conversion.go
  pkg/apis/sources/v1alpha2/apiserver_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#3612 MT Broker ingress knows custom channel addresses
  cmd/mtbroker/ingress/main.go
  config/brokers/mt-channel-broker/roles/ingress-clusterrole.yaml
  pkg/apis/eventing/v1beta1/broker_conversion_test.go
  pkg/mtbroker/ingress/ingress_handler.go
  pkg/mtbroker/ingress/ingress_handler_test.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/testing/v1/broker.go
Labels: approved, cla: yes, lgtm, size/L

#3627 Apiseversource reconciler and e2e for v1beta1
  pkg/adapter/apiserver/config.go
  pkg/adapter/apiserver/delegate_test.go
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/filter_test.go
  pkg/adapter/apiserver/ref_test.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/apiserversource/controller_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
  pkg/reconciler/testing/apiserversource.go
  pkg/reconciler/testing/v1beta1/listers.go
  test/e2e/source_api_server_v1alpha2_test.go
  test/e2e/source_api_server_v1beta1_test.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#3624 Drop vestigial kubeclient.
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#3634 Pull in the new fancier webhook drain from knative/pkg.
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/doc.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3632 add knobs for overriding qps / burst
  cmd/mtchannel_broker/main.go
Labels: approved, cla: yes, lgtm, size/S

#3643 remove event emit for normal trigger reconcile
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
Labels: approved, cla: yes, lgtm, size/M

#3603 EventTrasformationForTriggerTest can run with any Broker
  test/e2e/broker_event_transformation_test.go
  test/e2e/broker_with_many_triggers_test.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/e2e/helpers/broker_test_helper.go
  test/e2e/helpers/trigger_no_broker_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3641 Validate the categories for CRDs
  config/core/resources/apiserversource.yaml
  config/core/resources/containersource.yaml
  config/core/resources/parallel.yaml
  config/core/resources/pingsource.yaml
  config/core/resources/sequence.yaml
  config/core/resources/sinkbindings.yaml
  config/core/resources/subscription.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3661 Reconciler and e2e tests for ContainerSource V1Beta1
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/containersource/controller.go
  pkg/reconciler/containersource/controller_test.go
  pkg/reconciler/containersource/resources/deployment.go
  pkg/reconciler/containersource/resources/deployment_test.go
  pkg/reconciler/containersource/resources/names.go
  pkg/reconciler/containersource/resources/sinkbinding.go
  pkg/reconciler/containersource/resources/sinkbinding_test.go
  pkg/reconciler/testing/containersource.go
  pkg/reconciler/testing/listers.go
  test/e2e/source_container_v1alpha2_test.go
  test/e2e/source_container_v1beta1_test.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3531 Add Broker Data Plane Conformance tests for the Ingress and Consumer
  test/conformance/broker_data_plane_test.go
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/main_test.go
  test/e2e_flags.go
  test/flags/eventing_environment.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2932 IMC and Multi-Tenant Channel Based Broker retries
  go.mod
  go.sum
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/multichannelfanout/parse_test.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/message_sender.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  test/e2e/broker_redelivery_test.go
  test/e2e/helpers/broker_redelivery_helper.go
  test/lib/dropevents/dropeventsfibonacci/fibonacci.go
  test/lib/dropevents/dropeventsfirst/sequence.go
  test/lib/dropevents/receiver.go
  test/lib/recordevents/event_info_store.go
  test/test_images/recordevents/main.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/github.com/hashicorp/go-cleanhttp/LICENSE
  vendor/github.com/hashicorp/go-cleanhttp/README.md
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-cleanhttp/doc.go
  vendor/github.com/hashicorp/go-cleanhttp/go.mod
  vendor/github.com/hashicorp/go-cleanhttp/handlers.go
  vendor/github.com/hashicorp/go-retryablehttp/.gitignore
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XXL

#3671 Rename RetryConfig
  pkg/channel/fanout/fanout_message_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: approved, cla: yes, lgtm, size/XS

#3670 add step for installing sugar for e2e
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#3668 add broker developers as system integrator personas
  docs/personas.md
Labels: approved, cla: yes, lgtm, size/XS

#3676 Drop the event emission on every reconcile
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3677 Assorted linting fixes.
  pkg/adapter/mtping/config_test.go
  pkg/adapter/v2/util/crstatusevent/eventsstatus.go
  pkg/adapter/v2/util/crstatusevent/eventsstatus_test.go
  pkg/apis/eventing/v1beta1/trigger_conversion.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  pkg/mtbroker/filter/filter_handler_test.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/trigger.go
  pkg/reconciler/source/crd/crd.go
  test/conformance/helpers/channel_data_plane_helper.go
  test/lib/dropevents/dropeventsfirst/sequence.go
  test/lib/sender/resources.go
  test/upgrade/prober/configuration.go
  test/upgrade/prober/receiver.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3678 retry on webhook failures
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3683 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.mod
  vendor/contrib.go.opencensus.io/exporter/ocagent/go.sum
  vendor/contrib.go.opencensus.io/exporter/ocagent/ocagent.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/options.go
  vendor/contrib.go.opencensus.io/exporter/ocagent/transform_stats_to_metrics.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/errors.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.proto
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#3685 dont overwrite the resource we are trying to create during retry.
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3684 Prefix channelAddress annotation with knative.dev/
  pkg/apis/eventing/register.go
  pkg/apis/eventing/v1beta1/broker_conversion_test.go
  pkg/mtbroker/ingress/ingress_handler.go
  pkg/mtbroker/ingress/ingress_handler_test.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/testing/v1/broker.go
Labels: approved, cla: yes, lgtm, size/S

#3687 Export logs from knative-eventing namespace
  test/conformance/main_test.go
  test/conformance/source_crd_metadata_test.go
  test/e2e/main_test.go
  test/lib/config.go
  test/lib/logexporter.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3692 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/state.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/state.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/state.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/state.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/state.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/state.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/state.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/state.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/state.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/state.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/state.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/state.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/state.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/state.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/state.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/state.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/state.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/state.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/state.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/state.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/state.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/state.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#3693 Drop ApiServerSource always produce reconciler events per reconciler loop.
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/stub/controller.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/stub/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1/broker/stub/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1/trigger/stub/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/stub/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/stub/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/stub/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/stub/controller.go
  pkg/client/injection/reconciler/flows/v1/parallel/stub/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/stub/controller.go
  pkg/client/injection/reconciler/flows/v1/sequence/stub/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/stub/controller.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/stub/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/stub/controller.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1/channel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1/subscription/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/stub/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/stub/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/stub/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/stub/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/stub/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/stub/reconciler.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
Labels: approved, cla: yes, lgtm, size/S

#3695 remove reconciled normal event from subscriptions
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/XS

#3698 remove reconciled normal event from parallel
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
Labels: approved, cla: yes, lgtm, size/M

#3697 remove reconciled normal event from mtbroker
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
Labels: approved, cla: yes, lgtm, size/S

#3696 remove reconciled normal event from eventtypes
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/eventtype/eventtype_test.go
Labels: approved, cla: yes, lgtm, size/S

#3694 Remove reconciled normal event from channel
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
Labels: approved, cla: yes, lgtm, size/S

#3699 Do not produce reconciled-normal events always. - PingSource and Sequence
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/sugar/namespace/namespace.go
  pkg/reconciler/sugar/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#3713 Remove unused code that parsed multichannelfanout.Config from a string.
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/parse.go
  pkg/channel/multichannelfanout/parse_test.go
Labels: approved, cla: yes, lgtm, size/L

#3711 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_openbsd_arm64.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3680 Add PingSource conformance tests initialization
  test/conformance/helpers/sources/source_status_test_helper.go
  test/conformance/main_test.go
  test/conformance/source_status_test.go
  test/lib/config.go
  test/lib/resources/constants.go
  test/lib/setupclientoptions/sources.go
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3729 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#3703 Decoupled fanout config from ducktypes
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/multichannelfanout/config.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: approved, cla: yes, lgtm, size/L

#3715 Make easier to run knative code locally for testing and development
  pkg/adapter/v2/config.go
Labels: approved, cla: yes, lgtm, size/XS

#3728 [master] golang format tools
  test/conformance/helpers/sources/source_crd_metadata_test_helper.go
  test/lib/config.go
  test/lib/resources/constants.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3731 Retry in case of update conflicts
  test/conformance/helpers/broker_control_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3734 replace fatalf with logf in retry loop
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3740 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/proxy.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/controller/helper.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3741 Copy additional information as extensions of CE in APIServerSource
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
Labels: approved, cla: yes, lgtm, size/M

#3599 enable broker chaos, add debug logging for tests for MT Broker.
  cmd/mtchannel_broker/main.go
  pkg/apis/eventing/register.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/trigger/controller.go
  pkg/reconciler/mtbroker/trigger/controller_test.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/testing/v1/broker.go
  pkg/reconciler/testing/v1/trigger.go
  test/config/chaosduck.yaml
  test/config/config-logging.yaml
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#3745 Update CloudEvents SDK to v2.2.0
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_validation.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/result.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#3746 reenable HA for mtping
  cmd/mtping/main.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_message.go
Labels: approved, cla: yes, lgtm, size/M

#3744 PingSource conversion v1beta1, and crd.
  cmd/webhook/main.go
  config/core/resources/pingsource.yaml
  pkg/apis/sources/v1alpha2/ping_conversion.go
  pkg/apis/sources/v1alpha2/ping_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#3733 Reflect created sources API versions in setupclientoptions
  test/conformance/main_test.go
  test/lib/setupclientoptions/sources.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3751 put the waiting of kresources in a retry loop for webhook failures
  test/lib/operation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3743 Delay ending pod to give cron jobs time to send.#3664
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/runner.go
  pkg/adapter/mtping/runner_test.go
  pkg/adapter/v2/test/test_client.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#3754 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3747 add support for seconds in pingsource - for running tests only!
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/runner.go
  pkg/reconciler/pingsource/pingsource.go
Labels: approved, cla: yes, lgtm, size/M

#3755 Broker control plane conformance test can run with any Broker
  test/conformance/broker_control_plane_test.go
  test/conformance/helpers/broker_control_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3742 devel receive adapter doc
  docs/source/README.md
  docs/source/receive-adapter.md
Labels: approved, cla: yes, lgtm, size/L

#3759 [master] Auto-update dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/state.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/state.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/state.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/state.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/state.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/state.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/state.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/state.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/state.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/state.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/state.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/state.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/state.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/state.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/state.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/state.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/state.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/state.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/state.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/state.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/state.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/state.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/state.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3753 [master] golang format tools
  pkg/adapter/apiserver/events/events_test.go
Labels: approved, cla: yes, lgtm, size/S

#3763 Fix the test for go 1.15
  pkg/leaderelection/leader_election_test.go
Labels: approved, cla: yes, lgtm, size/S
