Repository knative/eventing, pull requests merged in 2020-03, with the labels that each got.

#2679 golang format tools
  pkg/apis/messaging/config/channel_defaults_test.go
  pkg/apis/sources/v1alpha1/apiserver_conversion.go
  pkg/apis/sources/v1alpha1/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha2/apiserver_validation.go
  pkg/apis/sources/v1alpha2/apiserver_validation_test.go
  pkg/reconciler/broker/config.go
Labels: approved, cla: yes, lgtm, size/S

#2678 add support for referencing v1beta1 channels in subscription
  pkg/reconciler/subscription/subscription.go
Labels: approved, cla: yes, lgtm, size/S

#2683 Add an `--upgrade` flag to `./hack/update-deps.sh`
  hack/update-deps.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2598 Add Broker conformance spec
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/M

#2687 Format markdown
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/L

#2688 EventType reconciler was unable to make a status at v1alpha1
  config/core/resources/eventtype.yaml
Labels: approved, cla: yes, lgtm, size/M

#2692 Post v0.13 release, point pkg to master.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/metrics/README.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metricskey/constants.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/testdata/README.md
  vendor/knative.dev/pkg/metrics/testdata/client-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/client-key.pem
  vendor/knative.dev/pkg/metrics/testdata/server-cert.pem
  vendor/knative.dev/pkg/metrics/testdata/server-key.pem
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/logging/logging.go
Labels: approved, cla: yes, lgtm, size/L

#2696 fixing that triggers can actually have no filters...
  pkg/apis/eventing/v1alpha1/trigger_conversion.go
Labels: approved, cla: yes, lgtm, size/XS

#2691 Update channel.md (spec) for v1beta specific details
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/M

#2700 fixing that triggers can actually have no filters...
  pkg/apis/eventing/v1alpha1/trigger_conversion.go
  test/e2e/trigger_dependency_annotation_test.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2703 Similar to PR2700: make trigger conversion attribute length variable
  pkg/apis/eventing/v1alpha1/trigger_conversion.go
Labels: approved, cla: yes, lgtm, size/XS

#2702 Updates to test without filter
  test/e2e/trigger_dependency_annotation_test.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2694 Use Listers in Namespace Reconciler
  pkg/reconciler/namespace/controller.go
  pkg/reconciler/namespace/controller_test.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/M

#2707 Remove sources controller deployment yaml now that it has release scaled to zero.
  config/core/deployments/sources-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#2663 E2E event receiver pod with REST endpoint
  Gopkg.lock
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/lib/checkevents.go
  test/lib/checkevents_test.go
  test/lib/requests.go
  test/lib/resources/kube.go
  test/lib/validation.go
  test/test_images/eventdetails/main.go
  test/test_images/recordevents/README.md
  test/test_images/recordevents/eventstore.go
  test/test_images/recordevents/eventstore_test.go
  test/test_images/recordevents/main.go
  test/test_images/recordevents/pod.yaml
  third_party/VENDOR-LICENSE
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2710 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
Labels: approved, cla: yes, lgtm, size/S

#2708 Format markdown
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/M

#2709 golang format tools
  pkg/reconciler/broker/broker_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2509 Add schemaData field to EventType to allow for a CloudEvent schema to…
  pkg/apis/eventing/v1beta1/eventtype_types.go
  pkg/apis/eventing/v1beta1/eventtype_validation.go
  pkg/apis/eventing/v1beta1/eventtype_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#2717 Use ko's strict mode for better errors messages
  config/brokers/channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/500-controller.yaml
  config/channels/in-memory-channel/500-dispatcher.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/webhook.yaml
  hack/release.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2719 avoid leaking ctx
  test/performance/infra/aggregator/aggregator.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XS

#2722 fix: composite literal uses unkeyed fields
  pkg/apis/flows/v1alpha1/parallel_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/S

#2723 fix: composite literal uses unkeyed fields, defaults
  pkg/apis/eventing/v1alpha1/broker_defaults.go
  pkg/apis/flows/v1alpha1/parallel_defaults.go
  pkg/apis/flows/v1alpha1/sequence_defaults.go
  pkg/apis/flows/v1beta1/parallel_defaults.go
  pkg/apis/flows/v1beta1/sequence_defaults.go
  pkg/apis/messaging/v1alpha1/channel_defaults.go
Labels: approved, cla: yes, lgtm, size/S

#2720 fix: composite literal uses unkeyed fields
  pkg/apis/flows/v1alpha1/sequence_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/S

#2726 Switch test images to strict mode
  test/performance/benchmarks/broker-imc/200-broker-perf.yaml
  test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml
  test/performance/benchmarks/channel-imc/200-channel-perf.yaml
  test/performance/benchmarks/channel-imc/continuous/200-channel-imc.yaml
  test/performance/direct/200-direct-perf.yaml
  test/test_images/eventdetails/pod.yaml
  test/test_images/filterevents/pod.yaml
  test/test_images/heartbeats/pod.yaml
  test/test_images/logevents/pod.yaml
  test/test_images/performance/pod.yaml
  test/test_images/print/pod.yaml
  test/test_images/recordevents/pod.yaml
  test/test_images/sendevents/pod.yaml
  test/test_images/sequencestepper/pod.yaml
  test/test_images/transformevents/pod.yaml
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/M

#2727 Update to latest pkg 0.13
  Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/XS

#2725 remove 0.2 from the sources spec
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/XS

#2734 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/metrics/exporter.go
Labels: approved, cla: yes, lgtm, size/XS

#2744 Drop use of deprecated filter API
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/sequence/controller.go
Labels: approved, cla: yes, lgtm, size/S

#2747 For now, disable --strict mode for release
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2743 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#2748 Add conformance test outline to Broker spec
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/M

#2751 Format markdown
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/M

#2716 Multitenant PingSource
  cmd/controller/main.go
  cmd/ping/adapter/kodata/refs
  cmd/ping/adapter/main.go
  cmd/ping/jobrunner/kodata/HEAD
  cmd/ping/jobrunner/kodata/LICENSE
  cmd/ping/jobrunner/kodata/VENDOR-LICENSE
  cmd/ping/jobrunner/kodata/refs
  cmd/ping/jobrunner/main.go
  cmd/ping/kodata/HEAD
  cmd/ping/kodata/LICENSE
  cmd/ping/kodata/VENDOR-LICENSE
  cmd/ping/kodata/refs
  config/200-jobrunner-clusterrole.yaml
  config/201-jobrunner-serviceaccount.yaml
  config/core/deployments/controller.yaml
  pkg/apis/eventing/register.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_validation.go
  pkg/apis/messaging/v1beta1/in_memory_channel_validation.go
  pkg/apis/sources/v1alpha1/ping_validation.go
  pkg/apis/sources/v1alpha1/ping_validation_test.go
  pkg/apis/sources/v1alpha2/ping_validation.go
  pkg/apis/sources/v1alpha2/ping_validation_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  pkg/reconciler/pingsource/controller/controller.go
  pkg/reconciler/pingsource/controller/controller_test.go
  pkg/reconciler/pingsource/controller/doc.go
  pkg/reconciler/pingsource/controller/pingsource.go
  pkg/reconciler/pingsource/controller/pingsource_test.go
  pkg/reconciler/pingsource/controller/resources/eventtype.go
  pkg/reconciler/pingsource/controller/resources/eventtype_test.go
  pkg/reconciler/pingsource/controller/resources/jobrunner.go
  pkg/reconciler/pingsource/controller/resources/jobrunner_service.go
  pkg/reconciler/pingsource/controller/resources/jobrunner_service_test.go
  pkg/reconciler/pingsource/controller/resources/jobrunner_test.go
  pkg/reconciler/pingsource/controller/resources/labels.go
  pkg/reconciler/pingsource/controller/resources/receive_adapter.go
  pkg/reconciler/pingsource/controller/resources/receive_adapter_test.go
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/controller_test.go
  pkg/reconciler/pingsource/jobrunner/pingsource.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
  pkg/reconciler/pingsource/jobrunner/runner.go
  pkg/reconciler/pingsource/jobrunner/runner_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/pingsource.go
  test/e2e/source_ping_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2754 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/fake/fake.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/core/v1/secret/secret.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/factory.go
  vendor/knative.dev/pkg/injection/clients/namespacedkube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/test/prow/env.go
  vendor/knative.dev/pkg/test/prow/prow.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#2752 Relax Tracing Conformance Tests to Allow Trace Trees With Matching Subtrees
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
  test/conformance/helpers/tracing/traces_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2762 update trigger dependency test to use latest ping source
  test/e2e/trigger_dependency_annotation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2758 stash for the latest version
  config/core/configmaps/default-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2684 Update Cloudevents SDK to v1.1.2
  Gopkg.lock
  Gopkg.toml
  pkg/channel/event_dispatcher_test.go
  third_party/VENDOR-LICENSE
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/client.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/client/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/json/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/datacodec/xml/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/event_observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v01.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v02.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/extensions/distributed_tracing_extension.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/observability/observer.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/codec.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/observability.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/options.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/transport.go
  vendor/github.com/lightstep/tracecontext.go/LICENSE
  vendor/github.com/lightstep/tracecontext.go/traceparent/package.go
  vendor/github.com/lightstep/tracecontext.go/tracestate/package.go
  vendor/go.opencensus.io/plugin/ochttp/propagation/tracecontext/propagation.go
Labels: approved, cla: yes, lgtm, size/XXL

#2763 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2769 Port channel fanout code to bindings
  pkg/channel/fanout/fanout_handler_binding.go
  pkg/channel/fanout/fanout_handler_binding_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler_binding.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler_binding_test.go
  pkg/channel/swappable/swappable_binding.go
  pkg/channel/swappable/swappable_binding_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2771 Add lberk to reviewers list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2766 Make Broker availability based on the Endpoints not Deployments.
  config/core/roles/controller-clusterroles.yaml
  pkg/apis/duck/lifecycle_helper.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/test_helper.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/resources/filter.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/trigger.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/endpoints.go
Labels: approved, cla: yes, lgtm, size/XL

#2773 Now MessageReceiver serves unbuffered messages and fanout buffers them
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/swappable/swappable_message_handler.go
  pkg/channel/swappable/swappable_message_handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#2760 first cut at multi-tenant broker
  cmd/mtbroker/config.go
  cmd/mtbroker/filter/kodata/HEAD
  cmd/mtbroker/filter/kodata/LICENSE
  cmd/mtbroker/filter/kodata/VENDOR-LICENSE
  cmd/mtbroker/filter/kodata/refs
  cmd/mtbroker/filter/main.go
  cmd/mtbroker/ingress/kodata/HEAD
  cmd/mtbroker/ingress/kodata/LICENSE
  cmd/mtbroker/ingress/kodata/VENDOR-LICENSE
  cmd/mtbroker/ingress/kodata/refs
  cmd/mtbroker/ingress/main.go
  cmd/mtchannel_broker/main.go
  config/README.md
  config/brokers/mt-channel-broker/200-filter-clusterrole.yaml
  config/brokers/mt-channel-broker/200-filter-serviceaccount.yaml
  config/brokers/mt-channel-broker/200-ingress-clusterrole.yaml
  config/brokers/mt-channel-broker/200-ingress-serviceaccount.yaml
  config/brokers/mt-channel-broker/201-filter-clusterrolebinding.yaml
  config/brokers/mt-channel-broker/201-ingress-clusterrolebinding.yaml
  config/brokers/mt-channel-broker/500-broker-filter.yaml
  config/brokers/mt-channel-broker/500-broker-ingress.yaml
  config/brokers/mt-channel-broker/500-mt-broker-controller.yaml
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/brokers/mt-channel-broker/roles/filter-clusterrole.yaml
  config/brokers/mt-channel-broker/roles/filter-clusterrolebinding.yaml
  config/brokers/mt-channel-broker/roles/filter-serviceaccount.yaml
  config/brokers/mt-channel-broker/roles/ingress-clusterrole.yaml
  config/brokers/mt-channel-broker/roles/ingress-clusterrolebinding.yaml
  config/brokers/mt-channel-broker/roles/ingress-serviceaccount.yaml
  pkg/apis/eventing/register.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/filter/filter_handler_test.go
  pkg/mtbroker/filter/stats_reporter.go
  pkg/mtbroker/filter/stats_reporter_test.go
  pkg/mtbroker/ingress/ingress_handler.go
  pkg/mtbroker/ingress/ingress_handler_test.go
  pkg/mtbroker/ingress/stats_reporter.go
  pkg/mtbroker/ingress/stats_reporter_test.go
  pkg/mtbroker/metrics.go
  pkg/mtbroker/ttl.go
  pkg/mtbroker/ttl_test.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/config.go
  pkg/reconciler/mtbroker/config_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/controller_test.go
  pkg/reconciler/mtbroker/resources/channel.go
  pkg/reconciler/mtbroker/resources/channel_test.go
  pkg/reconciler/mtbroker/resources/subscription.go
  pkg/reconciler/mtbroker/resources/subscription_test.go
  pkg/reconciler/mtbroker/testdata/config-broker.yaml
  pkg/reconciler/mtbroker/trigger.go
  pkg/reconciler/testing/broker.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XXL

#2774 Removed unused code
  test/lib/resources/constants.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2777 release mt-channel-broker pieces
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2785 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2779 Adjust the Endpoints Informer events.
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/controller.go
Labels: approved, cla: yes, lgtm, size/M

#2789 Wait for dependency annotation test subscriber to become ready
  test/e2e/trigger_dependency_annotation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2788 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/L

#2790 remove unused cruft
  pkg/reconciler/mtnamespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/S

#2791 remove unused cruft
  cmd/mtbroker/filter/main.go
  cmd/mtbroker/ingress/main.go
Labels: approved, cla: yes, lgtm, size/M

#2792 Fix context threading for Broker signal handling.
  pkg/broker/filter/filter_handler.go
  pkg/mtbroker/filter/filter_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#2793 add simple hpa for filter/ingress deployments
  config/brokers/mt-channel-broker/hpa.yaml
Labels: approved, cla: yes, lgtm, size/M

#2795 Updated to sdk-go v2.0.0-preview6
  Gopkg.lock
  Gopkg.toml
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/message_dispatcher.go
  pkg/kncloudevents/utils.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/binary_buffer_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/copy_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/struct_buffer_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/chan.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/spec/attributes.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/spec/spec.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_transformer.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_unknown_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/transformer.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/write.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/codec.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/codec_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/json/data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/json/data_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/text/data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/text/data_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/text/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/text/observability.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/xml/data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/xml/data_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_marshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_writer.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_writer.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_writer.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/message.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/result.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/outbound.go
  vendor/github.com/cloudevents/sdk-go/v2/types/value.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
Labels: approved, cla: yes, lgtm, size/XL

#2770 Reconcile EventTypes within Source Duck controller
  Gopkg.lock
  cmd/controller/main.go
  config/core/resources/eventtype.yaml
  pkg/apis/eventing/register.go
  pkg/apis/eventing/v1alpha1/eventtype_types.go
  pkg/apis/eventing/v1alpha1/eventtype_validation.go
  pkg/apis/eventing/v1alpha1/eventtype_validation_test.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  pkg/apis/eventing/v1beta1/eventtype_defaults_test.go
  pkg/apis/eventing/v1beta1/eventtype_types.go
  pkg/apis/eventing/v1beta1/eventtype_validation.go
  pkg/apis/eventing/v1beta1/eventtype_validation_test.go
  pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  pkg/apis/sources/register.go
  pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  pkg/apis/sources/v1alpha1/apiserver_lifecycle_test.go
  pkg/apis/sources/v1alpha1/apiserver_types.go
  pkg/apis/sources/v1alpha1/ping_conversion.go
  pkg/apis/sources/v1alpha1/ping_conversion_test.go
  pkg/apis/sources/v1alpha1/ping_lifecycle.go
  pkg/apis/sources/v1alpha1/ping_lifecycle_test.go
  pkg/apis/sources/v1alpha1/ping_types.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/apiserversource/resources/eventtype.go
  pkg/reconciler/eventtype/controller.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/pingsource/controller/controller.go
  pkg/reconciler/pingsource/controller/pingsource.go
  pkg/reconciler/pingsource/controller/pingsource_test.go
  pkg/reconciler/pingsource/controller/resources/eventtype.go
  pkg/reconciler/pingsource/controller/resources/eventtype_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/source/crd/controller.go
  pkg/reconciler/source/crd/crd.go
  pkg/reconciler/source/duck/controller.go
  pkg/reconciler/source/duck/duck.go
  pkg/reconciler/source/duck/resources/eventtype.go
  pkg/reconciler/source/duck/resources/labels.go
  pkg/reconciler/testing/apiserversource.go
  pkg/reconciler/testing/pingsource.go
  test/e2e/source_api_server_test.go
  test/e2e/source_ping_test.go
  test/lib/resources/eventing.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2798 first cut of surgically inserting mt e2e tests
  config/brokers/mt-channel-broker/400-config-br-defaults.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/broker_channel_flow_test.go
  test/e2e/broker_config_test.go
  test/e2e/broker_dls_test.go
  test/e2e/broker_event_transformation_test.go
  test/e2e/channel_defaulter_test.go
  test/e2e/configmappropagation_default_test.go
  test/e2e/helpers/broker_channel_flow_test_helper.go
  test/e2e/helpers/broker_dls_test_helper.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/e2e/helpers/broker_with_config_helper.go
  test/e2e/helpers/channel_defaulter_test_helper.go
  test/e2e/main_test.go
  test/e2e/trigger_dependency_annotation_test.go
  test/e2e_flags.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2812 migrate sequence off reconciler.Base
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
Labels: approved, cla: yes, lgtm, size/M

#2811 Migrate parallel off reconciler.Base
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
Labels: approved, cla: yes, lgtm, size/M

#2814 Migrate source duck and crd controller off reconciler.Base
  pkg/reconciler/source/crd/controller.go
  pkg/reconciler/source/crd/crd.go
  pkg/reconciler/source/duck/controller.go
  pkg/reconciler/source/duck/duck.go
Labels: approved, cla: yes, lgtm, size/M

#2821 migrate mtbroker off reconciler.Base
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/trigger.go
Labels: approved, cla: yes, lgtm, size/L

#2823 prevent a panic when we have CRDS labeled as sources without correct RBAC.
  pkg/reconciler/source/crd/crd.go
Labels: approved, cla: yes, lgtm, size/S

#2817 migrate subscription off reconciler.Base
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/S

#2818 migrate pingsource off reconciler.Base
  pkg/reconciler/pingsource/controller/controller.go
  pkg/reconciler/pingsource/controller/pingsource.go
  pkg/reconciler/pingsource/controller/pingsource_test.go
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/pingsource.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
Labels: approved, cla: yes, lgtm, size/L

#2822 migrate imc dispatcher to recgen, move imc off reconciler.Base
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/L

#2816 fix pingsource label and add jobrunner grafana dashboard
  config/monitoring/metrics/grafana/100-grafana-dash-eventing.yaml
  config/monitoring/metrics/prometheus/100-prometheus-scrape-kn-eventing.yaml
Labels: approved, cla: yes, lgtm, size/L

#2787 [master] Auto-update dependencies
  Gopkg.lock
  third_party/VENDOR-LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
Labels: approved, cla: yes, lgtm, size/XXL

#2826 [master] golang format tools
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2825 Fix mtbroker trace exporting by fixing service names.
  cmd/mtbroker/filter/main.go
  cmd/mtbroker/ingress/main.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/names/mtbroker.go
Labels: approved, cla: yes, lgtm, size/M

#2834 migrate apiserversource off reconciler.Base
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
Labels: approved, cla: yes, lgtm, size/M

#2832 migrate configmappropagation to genreconciler and drop reconciler.Base.
  pkg/apis/configs/v1alpha1/configmappropagation_types.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/controller.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/stub/controller.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/stub/reconciler.go
  pkg/reconciler/configmappropagation/configmappropagation.go
  pkg/reconciler/configmappropagation/configmappropagation_test.go
  pkg/reconciler/configmappropagation/controller.go
Labels: approved, cla: yes, lgtm, size/L

#2780 Switch trace propagation from B3 to W3C format
  Gopkg.lock
  cmd/broker/ingress/main.go
  pkg/broker/filter/filter_handler.go
  pkg/channel/event_dispatcher.go
  pkg/channel/event_dispatcher_test.go
  pkg/channel/event_receiver.go
  pkg/channel/message_dispatcher_test.go
  pkg/kncloudevents/good_client.go
  pkg/kncloudevents/message_client.go
  test/conformance/helpers/channel_header_single_event_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/lib/validation.go
  test/test_images/sendevents/main.go
  vendor/go.opentelemetry.io/otel/LICENSE
  vendor/go.opentelemetry.io/otel/api/core/doc.go
  vendor/go.opentelemetry.io/otel/api/core/key.go
  vendor/go.opentelemetry.io/otel/api/core/number.go
  vendor/go.opentelemetry.io/otel/api/core/numberkind_string.go
  vendor/go.opentelemetry.io/otel/api/core/rawhelpers.go
  vendor/go.opentelemetry.io/otel/api/core/span_context.go
  vendor/go.opentelemetry.io/otel/api/core/valuetype_string.go
  vendor/go.opentelemetry.io/otel/api/propagation/doc.go
  vendor/go.opentelemetry.io/otel/api/propagation/propagation.go
  vendor/go.opentelemetry.io/otel/api/trace/always_sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/api.go
  vendor/go.opentelemetry.io/otel/api/trace/b3_propagator.go
  vendor/go.opentelemetry.io/otel/api/trace/context.go
  vendor/go.opentelemetry.io/otel/api/trace/doc.go
  vendor/go.opentelemetry.io/otel/api/trace/never_sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_span.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_trace.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_trace_provider.go
  vendor/go.opentelemetry.io/otel/api/trace/sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/trace_context_propagator.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2828 Adding missing UTs for Source reconcilers
  Gopkg.lock
  pkg/apis/sources/register.go
  pkg/reconciler/source/crd/controller.go
  pkg/reconciler/source/crd/controller_test.go
  pkg/reconciler/source/crd/crd_test.go
  pkg/reconciler/source/duck/controller.go
  pkg/reconciler/source/duck/controller_test.go
  pkg/reconciler/source/duck/duck_test.go
  pkg/reconciler/source/duck/resources/eventtype_test.go
  pkg/reconciler/testing/customresourcedefinition.go
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/XL

#2829 Update cloudevents sdk to release v2.0.0-prevew7
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2820 migrate mtnamespace off reconciler.Base
  pkg/reconciler/mtnamespace/controller.go
  pkg/reconciler/mtnamespace/controller_test.go
  pkg/reconciler/mtnamespace/namespace.go
  pkg/reconciler/mtnamespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/M

#2830 symlink for the mtbroker bits
  config/brokers/mt-channel-broker/400-config-br-defaults.yaml
  config/brokers/mt-channel-broker/configmaps/default-broker.yaml
  config/brokers/mt-channel-broker/deployments/hpa.yaml
  config/brokers/mt-channel-broker/hpa.yaml
Labels: approved, cla: yes, lgtm, size/L

#2815 migrate trigger controller to genreconciler and off reconciler.Base
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/client/injection/reconciler/eventing/v1alpha1/trigger/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/trigger/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/trigger/stub/reconciler.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#2838 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/kvstore/kvstore.go
  vendor/knative.dev/pkg/kvstore/kvstore_cm.go
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/L

#2839 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/S

#2837 Remove Implementation Specific Checks From Tracing Conformance Tests
  cmd/mtbroker/ingress/main.go
  pkg/mtbroker/filter/filter_handler.go
  test/conformance/broker_tracing_test.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
  test/conformance/main_test.go
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#2819 migrate namespace controller off reconciler.Base
  pkg/reconciler/namespace/controller.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/L

#2800 GeneratedNames: fix generated names not being RFC 1123 compliant
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2827 Rename Trigger condition Subscribed to SubscriptionReady
  pkg/apis/eventing/v1alpha1/trigger_lifecycle.go
  pkg/apis/eventing/v1alpha1/trigger_lifecycle_test.go
  pkg/apis/eventing/v1beta1/trigger_lifecycle.go
  pkg/apis/eventing/v1beta1/trigger_lifecycle_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#2844 migrate broker off reconciler.Base
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/trigger.go
  pkg/reconciler/mtbroker/trigger.go
Labels: approved, cla: yes, lgtm, size/L

#2843 use generated reconciler
  pkg/apis/sources/v1alpha2/ping_types.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/stub/reconciler.go
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/pingsource.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
Labels: approved, cla: yes, lgtm, size/M

#2845 Reduce sleep time from minute to 5 seconds
  test/conformance/helpers/tracing/zipkin.go
  test/e2e/helpers/channel_defaulter_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2846 Mark reconciler.Base deprecated
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/eventtype/eventtype_test.go
  pkg/reconciler/reconciler.go
Labels: approved, cla: yes, lgtm, size/M

#2847 Fixed FanoutMessageHandler and improved coverage
  pkg/channel/event_receiver.go
  pkg/channel/fanout/fanout_handler_test.go
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2759 add pingsource finalizer
  config/200-jobrunner-clusterrole.yaml
  pkg/reconciler/pingsource/controller/pingsource.go
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/pingsource.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
  pkg/reconciler/testing/pingsource.go
Labels: approved, cla: yes, lgtm, size/L

#2854 rejigger files so they live in brokers/channel-broker
  config/200-channel-broker-binding.yaml
  config/200-channel-broker-clusterrole.yaml
  config/300-configmappropagation.yaml
  config/400-config-br-default-channel.yaml
  config/400-config-br-defaults.yaml
  config/500-broker-controller.yaml
  config/brokers/channel-broker/200-channel-broker-clusterrole.yaml
  config/brokers/channel-broker/300-configmappropagation.yaml
  config/brokers/channel-broker/400-config-br-default-channel.yaml
  config/brokers/channel-broker/400-config-br-defaults.yaml
  config/brokers/channel-broker/500-broker-controller.yaml
  config/brokers/channel-broker/configmaps/default-broker.yaml
  config/brokers/channel-broker/configmaps/default-imc.yaml
  config/brokers/mt-channel-broker/200-channel-broker-binding.yaml
  config/brokers/mt-channel-broker/400-config-br-default-channel.yaml
  config/brokers/mt-channel-broker/configmaps/default-imc.yaml
  hack/release.sh
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2855 relax the validation logic to allow for more broker classes
  config/core/resources/broker.yaml
Labels: approved, cla: yes, lgtm, size/L

#2858 [master] golang format tools
  pkg/adapter/v2/cloudevents_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2859 update broker impl docs
  docs/broker/README.md
  pkg/reconciler/broker/broker.go
Labels: approved, cla: yes, lgtm, size/L

#2863 rename subscription condition reference to references resolved
  pkg/apis/messaging/v1alpha1/subscription_lifecycle.go
  pkg/apis/messaging/v1beta1/subscription_lifecycle.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#2871 Fix performance tests by installing broker
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2870 Updated sdk-go to preview8
  Gopkg.lock
  Gopkg.toml
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
  pkg/adapter/v2/test/test_client.go
  vendor/github.com/cloudevents/sdk-go/v1/cloudevents/extensions/distributed_tracing_extension.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/codec.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/codec_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/json/data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/json/data_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/text/data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/text/data_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/xml/data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/datacodec/xml/data_observed.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_data.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_interface.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_marshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/message.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/result.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_responsewriter.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/result.go
Labels: approved, cla: yes, lgtm, size/XL

#2852 Make broker stats reporter args public.
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/stats_reporter.go
  pkg/broker/filter/stats_reporter_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/stats_reporter.go
  pkg/broker/ingress/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/M

#2875 Remove all category from internal API ...
  config/brokers/channel-broker/resources/configmappropagation.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2878 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2877 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#2885 oops, use the cluster domain name
  pkg/mtbroker/ingress/ingress_handler.go
Labels: approved, cla: yes, lgtm, size/XS
