Repository knative/eventing, pull requests merged in 2020-04, with the labels that each got.

#2861 Generate names with kmeta.ChildName. Delete deprecated named resources
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/resources/subscription.go
  pkg/reconciler/broker/resources/subscription_test.go
  pkg/reconciler/broker/trigger.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/resources/subscription.go
  pkg/reconciler/mtbroker/trigger.go
  pkg/reconciler/pingsource/controller/pingsource.go
  pkg/reconciler/pingsource/controller/pingsource_test.go
  pkg/reconciler/pingsource/controller/resources/receive_adapter.go
  pkg/reconciler/testing/apiserversource.go
  pkg/utils/utils.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2874 Always pass zaptest logger with AddCaller to SUT in unit tests
  Gopkg.lock
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/ingress/ingress_handler_test.go
  pkg/channel/event_dispatcher_test.go
  pkg/channel/event_receiver_test.go
  pkg/channel/fanout/fanout_handler_test.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/message_dispatcher_test.go
  pkg/channel/message_receiver_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/multichannelfanout/parse_test.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/channel/swappable/swappable_test.go
  pkg/mtbroker/filter/filter_handler_test.go
  pkg/mtbroker/ingress/ingress_handler_test.go
Labels: approved, cla: yes, lgtm, size/M

#2886 Migrate mtnamespace to genreconciler
  pkg/reconciler/mtnamespace/controller.go
  pkg/reconciler/mtnamespace/namespace.go
  pkg/reconciler/mtnamespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/L

#2873 Remove Traceparent Extension Handling
  Gopkg.lock
  docs/spec/channel.md
  hack/set-span-id.patch
  hack/update-deps.sh
  pkg/broker/filter/filter_handler_test.go
  pkg/channel/event_receiver_test.go
  pkg/channel/message_receiver_test.go
  pkg/kncloudevents/good_client.go
  pkg/mtbroker/filter/filter_handler_test.go
  pkg/tracing/traceparent.go
  pkg/tracing/traceparent_test.go
  pkg/tracing/traceparent_transformer.go
  pkg/tracing/traceparent_transformer_test.go
  vendor/go.opencensus.io/trace/trace.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2876 Port fanout.Config to SubscriberSpec v1beta1
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1beta1/subscribable_types.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  pkg/channel/fanout/fanout_handler.go
  pkg/channel/fanout/fanout_handler_test.go
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/multichannelfanout/parse_test.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/channel/swappable/swappable_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: approved, cla: yes, lgtm, size/XL

#2887 Move CMP to knative-internal category
  config/brokers/channel-broker/resources/configmappropagation.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2891 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2867 Migrate jobrunner to cloudevent v2
  pkg/adapter/ping/adapter.go
  pkg/adapter/ping/adapter_test.go
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/metrics/metrics.go
  pkg/adapter/v2/metrics/metrics_test.go
  pkg/adapter/v2/test/test_client.go
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
  pkg/reconciler/pingsource/jobrunner/runner.go
  pkg/reconciler/pingsource/jobrunner/runner_test.go
  pkg/reconciler/testing/mock_stats_reporter.go
Labels: approved, cla: yes, lgtm, size/L

#2890 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#2894 Improve leader election CM handling.
  config/core/configmaps/leader-election.yaml
  pkg/leaderelection/leader_election.go
  pkg/leaderelection/leader_election_test.go
  pkg/leaderelection/testdata/config-leader-election.yaml
Labels: approved, cla: yes, lgtm, size/L

#2872 ApiServerSource serve v1alpha2
  Gopkg.lock
  cmd/apiserver_receive_adapter/main.go
  config/core/resources/apiserversource.yaml
  pkg/adapter/apiserver/adapter.go
  pkg/adapter/apiserver/adapter_injection.go
  pkg/adapter/apiserver/adapter_injection_test.go
  pkg/adapter/apiserver/adapter_test.go
  pkg/adapter/apiserver/config.go
  pkg/adapter/apiserver/delegate.go
  pkg/adapter/apiserver/delegate_test.go
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
  pkg/adapter/apiserver/filter.go
  pkg/adapter/apiserver/filter_test.go
  pkg/adapter/apiserver/ref.go
  pkg/adapter/apiserver/ref_test.go
  pkg/adapter/apiserver/resource.go
  pkg/adapter/ping/adapter_test.go
  pkg/adapter/v2/test/test_client.go
  pkg/apis/sources/v1alpha1/apiserver_conversion.go
  pkg/apis/sources/v1alpha1/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha1/apiserver_types.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/sources/v1alpha2/apiserver_defaults.go
  pkg/apis/sources/v1alpha2/apiserver_types.go
  pkg/apis/sources/v1alpha2/apiserver_validation_test.go
  pkg/apis/sources/v1alpha2/register.go
  pkg/apis/sources/v1alpha2/register_test.go
  pkg/apis/sources/v1alpha2/zz_generated.deepcopy.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/stub/reconciler.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/apiserversource/controller_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
  pkg/reconciler/testing/apiserversource.go
  pkg/reconciler/testing/listers.go
  test/e2e/source_api_server_test.go
  test/lib/creation.go
  test/lib/resources/kube.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2893 Added channel reviews OWNERS
  OWNERS_ALIASES
  pkg/channel/OWNERS
Labels: approved, cla: yes, lgtm, size/S

#2896 Api server source requires ApiVersion and kind.
  pkg/adapter/apiserver/adapter.go
  pkg/apis/sources/v1alpha1/apiserver_conversion.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/sources/v1alpha2/apiserver_types.go
  pkg/apis/sources/v1alpha2/apiserver_validation.go
  pkg/apis/sources/v1alpha2/apiserver_validation_test.go
  pkg/apis/sources/v1alpha2/zz_generated.deepcopy.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
  test/e2e/source_api_server_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2897 Fix nil in MessageDispatcher
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/L

#2898 remove unused stats reporter
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
  pkg/adapter/v2/metrics/metrics.go
  pkg/adapter/v2/metrics/metrics_test.go
  pkg/adapter/v2/test/test_client.go
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
  pkg/reconciler/pingsource/jobrunner/runner.go
  pkg/reconciler/pingsource/jobrunner/runner_test.go
  pkg/reconciler/testing/mock_stats_reporter.go
Labels: approved, cla: yes, lgtm, size/L

#2899 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/performance/performance.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
Labels: approved, cla: yes, lgtm, size/L

#2862 Addressing tracing issues in FanoutMessageHandler & MessageReceiver
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/kncloudevents/message_client.go
Labels: approved, cla: yes, lgtm, size/M

#2902 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2903 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2904 Add a way to make the `mtnamespace` controller behave like `namespace`.
  config/brokers/mt-channel-broker/deployments/controller.yaml
  pkg/reconciler/mtnamespace/controller.go
  pkg/reconciler/mtnamespace/namespace.go
  pkg/reconciler/mtnamespace/namespace_test.go
Labels: approved, cla: yes, lgtm, size/L

#2908 RBAC: Adding 'update' for the channel/finalizer, like on IMC
  config/core/roles/addressable-resolvers-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2906 Remove unused code and fix a few simple linter warnings.
  pkg/apis/eventing/v1alpha1/broker_lifecycle_test.go
  pkg/apis/flows/v1alpha1/sequence_defaults_test.go
  pkg/apis/flows/v1beta1/sequence_defaults_test.go
  pkg/apis/flows/v1beta1/test_helpers.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle_test.go
  pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle_test.go
  pkg/broker/filter/filter_handler.go
  pkg/channel/fanout/fanout_handler.go
  pkg/channel/message_receiver.go
  pkg/duck/subscriber_test.go
  pkg/kncloudevents/message_client.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/ingress/ingress_handler_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/configmappropagation/configmappropagation.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/eventtype/controller.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtnamespace/controller.go
  pkg/reconciler/mtnamespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/pingsource/controller/controller.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/source/duck/duck.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#2905 Added PopulateSpan transformer
  Gopkg.lock
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_receiver_test.go
  pkg/kncloudevents/message_client.go
  pkg/tracing/traceparent_transformer.go
  pkg/tracing/transformers.go
  pkg/tracing/transformers_test.go
Labels: approved, cla: yes, lgtm, size/L

#2916 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/config.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/create.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/actions/delete.go
  vendor/knative.dev/pkg/testutils/metahelper/client/client.go
  vendor/knative.dev/pkg/testutils/metahelper/main.go
Labels: approved, cla: yes, lgtm, size/L

#2907 Rewrite eventing/v1alpha1 validation tests using unused CRDTest framework.
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/apis/eventing/v1alpha1/eventtype_validation_test.go
  pkg/apis/eventing/v1alpha1/trigger_validation_test.go
Labels: approved, cla: yes, lgtm, size/L

#2909 jobrunner rbac files are now symlinks
  config/200-jobrunner-clusterrole.yaml
  config/201-jobrunner-serviceaccount.yaml
  config/core/200-jobrunner-serviceaccount.yaml
  config/core/roles/jobrunner-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/L

#2910 Upgrade script for patching broker annotation
  cmd/upgrade/v0.14.0/main.go
  config/upgrade/v0.14.0/README.md
  config/upgrade/v0.14.0/upgrade.yaml
  hack/release.sh
  pkg/upgrader/broker/v0.14.0/upgrader.go
  pkg/upgrader/broker/v0.14.0/upgrader_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2917 Tracing fix for MessageDispatcher
  pkg/channel/message_dispatcher.go
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
Labels: approved, cla: yes, lgtm, size/M

#2920 [release-0.13] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/L

#2921 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/metrics/monitored_resources.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/cmd/command.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/testgrid/testgrid.go
  vendor/knative.dev/pkg/testing/resource.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/gke.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/setup.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/util.go
  vendor/knative.dev/pkg/testutils/clustermanager/prow-cluster-operation/options/options.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
  vendor/knative.dev/test-infra/tools/dep-collector/imports.go
  vendor/knative.dev/test-infra/tools/dep-collector/licenses.go
Labels: approved, cla: yes, lgtm, size/XXL

#2922 Add Broker installation instructions to DEV doc
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#2813 Migrate inmemorychannel to use v2 cloudevents bindings
  config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
  pkg/inmemorychannel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/M

#2925 Preparing for v0.14 release, point pkg to release-0.14.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/images/Knative-Duck0.png
Labels: approved, cla: yes, lgtm, size/L

#2928 Soften requirement on Serving in DEV doc
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/S

#2929 change to https based auth
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#2931 point to release
  config/upgrade/v0.14.0/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2938 Remove unused ReconcilerName const from reconcilers
  pkg/reconciler/broker/controller.go
  pkg/reconciler/eventtype/controller.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtnamespace/controller.go
  pkg/reconciler/pingsource/controller/controller.go
Labels: approved, cla: yes, lgtm, size/M

#2618 Document version of common data plane contract for eventing
  docs/spec/data-plane.md
Labels: approved, cla: yes, lgtm, size/L

#2927 Include empty list of validating callbacks
  cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/XS

#2941 remove trailing slash
  config/upgrade/v0.14.0/upgrade.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2939 [master] Auto-update dependencies
  Gopkg.lock
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/L

#2936 Remove duplicated default configmaps, and stash them in core
  config/400-config-br-default-channel.yaml
  config/400-config-br-defaults.yaml
  config/brokers/channel-broker/400-config-br-default-channel.yaml
  config/brokers/channel-broker/400-config-br-defaults.yaml
  config/brokers/channel-broker/configmaps/default-broker.yaml
  config/brokers/mt-channel-broker/400-config-br-default-channel.yaml
  config/brokers/mt-channel-broker/400-config-br-defaults.yaml
  config/brokers/mt-channel-broker/configmaps/default-imc.yaml
  hack/release.sh
  test/config/mt-channel-broker.yaml
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2947 Move broker defaults into core
  config/400-config-br-default-channel.yaml
  config/400-config-br-defaults.yaml
  config/core/configmaps/default-broker-channel.yaml
  config/core/configmaps/default-broker.yaml
Labels: approved, cla: yes, lgtm, size/L

#2948 Adapter V2: Typo var rename. logger --> metrictag
  pkg/adapter/v2/cloudevents.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#2944 Added a test to check if IMC dispatcher works
  pkg/inmemorychannel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/message_receiver.go
  pkg/kncloudevents/message_sender.go
Labels: approved, cla: yes, lgtm, size/L

#2946 Disable the autogenerated 'default' mt broker
  config/brokers/mt-channel-broker/deployments/controller.yaml
  pkg/reconciler/mtnamespace/controller.go
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2953 Add the missing label eventing.knative.dev/release to the ConfigMaps
  config/core/configmaps/default-broker-channel.yaml
  config/core/configmaps/default-broker.yaml
  config/core/configmaps/default-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2955 Bump zipkin polling timeout to 5 minutes in tracing tests
  test/conformance/helpers/channel_tracing_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2952 [release-0.13] Pin test-infra to release branch
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/kballard/go-shellquote/LICENSE
  vendor/github.com/kballard/go-shellquote/doc.go
  vendor/github.com/kballard/go-shellquote/quote.go
  vendor/github.com/kballard/go-shellquote/unquote.go
  vendor/knative.dev/test-infra/tools/dep-collector/gobuild.go
Labels: approved, cla: yes, lgtm, size/L

#2964 Fixes the aggregated cluster roles for PodSpecable.
  config/core/roles/podspecable-binding-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2968 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2971 Point test-infra to release-0.14 in prep for 0.14 release
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2973 Add namespace to Trigger's structural schema
  config/core/resources/trigger.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2975 Remove unneeded dep overrides
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/S

#2976 Updating pkg to master post 0.14 release.
  Gopkg.lock
  Gopkg.toml
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/RELEASING.md
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#2966 Channel name suffix conformance test
  test/conformance/channel_crd_name_test.go
  test/conformance/helpers/channel_crd_name_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2986 Fix channel subscribers patching
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#2943 Drop reconciler.Base from eventing.
  Gopkg.lock
  pkg/channel/message_receiver_test.go
  pkg/reconciler/reconciler.go
  pkg/reconciler/stats_reporter.go
  pkg/reconciler/stats_reporter_test.go
Labels: approved, cla: yes, lgtm, size/L

#3000 Status conformance tests for channels
  test/conformance/channel_status_test.go
  test/conformance/helpers/channel.go
  test/conformance/helpers/channel_status_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3001 fix map read-write race bug
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/pingsource.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
Labels: approved, cla: yes, lgtm, size/S

#3004 Use imc v1beta1 for default broker channel (not v1alpha1)
  config/core/configmaps/default-broker-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3005 fix map read-write race bug (#3001)
  pkg/reconciler/pingsource/jobrunner/controller.go
  pkg/reconciler/pingsource/jobrunner/pingsource.go
  pkg/reconciler/pingsource/jobrunner/pingsource_test.go
Labels: approved, cla: yes, lgtm, size/S

#2995 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/DEVELOPMENT.md
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/test/helpers/name.go
Labels: approved, cla: yes, lgtm, size/M

#2951 Clean up pkg/channel
  pkg/channel/config.go
  pkg/channel/event_dispatcher.go
  pkg/channel/event_dispatcher_test.go
  pkg/channel/event_receiver.go
  pkg/channel/event_receiver_test.go
  pkg/channel/fanout/fanout_handler.go
  pkg/channel/fanout/fanout_handler_test.go
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/history.go
  pkg/channel/history_test.go
  pkg/channel/history_transformer.go
  pkg/channel/history_transformer_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  pkg/channel/message_receiver.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_handler_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/references.go
  pkg/channel/references_test.go
  pkg/channel/swappable/swappable.go
  pkg/channel/swappable/swappable_message_handler.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/channel/swappable/swappable_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#3007 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
Labels: approved, cla: yes, lgtm, size/M

#3013 Fixing subscriberUri path in additionalPrinterColumns
  config/core/resources/trigger.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3015 0.14 patch: Fixing subscriberUri path in additionalPrinterColumns
  config/core/resources/trigger.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3010 Fixing upgrade job so it will work with istio auto-injection
  config/upgrade/v0.14.0/upgrade.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3018 Fixing upgrade job so it will work with istio auto-injection
  config/upgrade/v0.14.0/upgrade.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3017 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/cached.go
Labels: approved, cla: yes, lgtm, size/M

#3022 do not specify replicas
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3024 [release-0.14] do not specify replicas (#3022)
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3008 Moved MessageDispatcher initialization and configuration
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/swappable/swappable_message_handler.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/inmemorychannel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/L

#3021 [release-0.13] Fix channel subscribers patching for v1alpha1 channels. (#2986)
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/S

#3020 [release-0.14] Fix channel subscribers patching for v1alpha1 channels. (#2986)
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/S

#3025 IMC Dispatcher microbenchmark
  pkg/channel/message_dispatcher.go
  pkg/channel/swappable/swappable_message_handler.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/L

#2506 only update ConfigMap namespace for zipkin if not already set
  test/conformance/helpers/tracing/zipkin.go
  test/conformance/testdata/config-tracing.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3027 [master] Format markdown
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/S

#3028 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2954 Allow the webhook to patch namespaces (rbac)
  config/core/roles/webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3030 Add PodLister to reconciler test listers
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/XS

#3031 Revert "Add PodLister to reconciler test listers"
  pkg/reconciler/testing/listers.go
Labels: approved, cla: yes, lgtm, size/XS

#2963 Add channel metadata conformance tests
  Gopkg.lock
  test/conformance/channel_crd_metadata_test.go
  test/conformance/helpers/channel_crd_metadata_test_helper.go
  test/lib/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3038 Conformance test for channelable-manipulator ClusterRole
  config/core/roles/channelable-manipulator-clusterrole.yaml
  test/conformance/channel_channelable_manipulator_cluster_role_test.go
  test/conformance/helpers/channel_channelable_manipulator_cluster_role_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3046 Update sinkbinding webhook with namespace lister
  Gopkg.lock
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/controller.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/broker/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/trigger/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/trigger/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/reconciler/sinkbinding/controller.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
Labels: approved, cla: yes, lgtm, size/L

#3040 add owner ref to mtping deployment
  config/core/deployments/controller.yaml
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/controller_test.go
  pkg/reconciler/pingsource/resources/mt_receive_adapter.go
  pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/M

#3049 fix issue 3014
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go
  pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  pkg/reconciler/subscription/subscription.go
  test/e2e/channel_single_event_test.go
  test/e2e/helpers/channel_single_event_helper.go
  test/lib/duck/resource_checks.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3053 Use correct names for the containers
  config/brokers/channel-broker/deployments/controller.yaml
  config/brokers/mt-channel-broker/deployments/controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3055 [master] Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1beta1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/webhook-apicoverage/resourcetree/basictypekindnode.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#3057 allow the eventing controller to set Deployment owner ref
  config/core/roles/controller-clusterroles.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3059 remove resources (issue 3036)
  config/channels/in-memory-channel/500-dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3052 fix issue 3014 (#3049)
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go
  pkg/apis/messaging/v1beta1/in_memory_channel_defaults.go
  pkg/reconciler/subscription/subscription.go
  test/e2e/channel_single_event_test.go
  test/e2e/helpers/channel_single_event_helper.go
  test/lib/duck/resource_checks.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3060 remove resources (issue 3036)
  config/channels/in-memory-channel/500-dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3062 fix go modules issues
  go.mod
  go.sum
  hack/tools.go
  hack/update-deps.sh
  third_party/VENDOR-LICENSE
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3026 Configuration for tracing in sources
  pkg/adapter/config.go
  pkg/adapter/config_test.go
  pkg/adapter/main.go
  pkg/adapter/main_message_adapter.go
  pkg/adapter/v2/config.go
  pkg/adapter/v2/config_test.go
  pkg/adapter/v2/main.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/apiserversource/controller_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#3068 [cmd/controller]: use LICENSE and VENDOR-LICENSE
  cmd/controller/kodata/LICENSE
  cmd/controller/kodata/VENDOR-LICENSE
Labels: approved, cla: yes, lgtm, size/XS

#3070 Reconcile channel / inmemorychannel using v1beta1.
  go.mod
  go.sum
  pkg/apis/eventing/v1alpha1/broker_conversion_test.go
  pkg/apis/messaging/v1alpha1/channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  pkg/apis/messaging/v1beta1/channel_types.go
  pkg/apis/messaging/v1beta1/in_memory_channel_types.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/stub/reconciler.go
  pkg/duck/listable.go
  pkg/duck/listable_test.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/channel/controller_test.go
  pkg/reconciler/channel/resources/channel.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/controller_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/controller/resources/service.go
  pkg/reconciler/inmemorychannel/controller/resources/service_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/inmemorychannel.go
  pkg/reconciler/testing/listers.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/metrics/doc.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#3064 Backport: Adding webhook details to eventtypes CRD
  config/core/resources/eventtype.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3063 Adding webhook details to eventtypes CRD
  config/core/resources/eventtype.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3073 remove GO111MODULE=on in release.sh
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS
