Repository knative/eventing, pull requests merged in 2020-02, with the labels that each got.

#2483 document the sink binding runtime contract.
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/S

#2481 Adding CloudEvents Overrides to SinkBinding.
  .gitignore
  pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1alpha1/sinkbinding_lifecycle_test.go
  pkg/reconciler/testing/containersource.go
  test/e2e/source_sinkbinding_test.go
  test/test_images/heartbeats/main.go
  test/test_images/logevents/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2486 E2E test for ConfigMapPropagation
  test/e2e/configmappropagation_default_test.go
  test/lib/creation.go
  test/lib/resources/eventing.go
  test/lib/validation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2495 golang format tools
  test/test_images/heartbeats/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2496 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
Labels: approved, cla: yes, lgtm, size/M

#2488 Clean up e2e test code
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_header_single_event_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/e2e-common.sh
  test/e2e/broker_default_test.go
  test/e2e/helpers/broker_channel_flow_test_helper.go
  test/e2e/helpers/broker_dls_test_helper.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/e2e/helpers/channel_chain_test_helper.go
  test/e2e/helpers/channel_defaulter_test_helper.go
  test/e2e/helpers/channel_dls_test_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/e2e/helpers/channel_single_event_helper.go
  test/e2e/legacy_sinkbinding_test.go
  test/e2e/legacy_source_api_server_test.go
  test/e2e/parallel_test.go
  test/e2e/sequence_test.go
  test/e2e/source_api_server_test.go
  test/e2e/source_container_test.go
  test/e2e/source_cron_job_test.go
  test/e2e/source_ping_test.go
  test/e2e/source_sinkbinding_test.go
  test/lib/creation.go
  test/lib/operation.go
  test/lib/test_runner.go
  test/test_images/logevents/kodata/LICENSE
  test/test_images/logevents/kodata/VENDOR-LICENSE
  test/test_images/logevents/kodata/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2498 Make the release number and slack show in README.
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#2503 Cache compiled trace parent regexp in global variable.
  pkg/tracing/traceparent.go
Labels: approved, cla: yes, lgtm, size/XS

#2504 Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#2505 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeclient.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeduck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakefactory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fakeinformer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/namesystems.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: approved, cla: yes, lgtm, size/XL

#2508 Trigger conversion function (v1alpha1 <-> v1beta1)
  pkg/apis/eventing/v1alpha1/trigger_conversion.go
  pkg/apis/eventing/v1alpha1/trigger_conversion_test.go
  pkg/apis/eventing/v1alpha1/trigger_types.go
  pkg/apis/eventing/v1beta1/broker_lifecycle.go
  pkg/apis/eventing/v1beta1/test_helper.go
  pkg/apis/eventing/v1beta1/trigger_conversion.go
  pkg/apis/eventing/v1beta1/trigger_conversion_test.go
  pkg/apis/eventing/v1beta1/trigger_lifecycle.go
  pkg/apis/eventing/v1beta1/trigger_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/L

#2512 ObjectReference -> KReference
  Gopkg.lock
  pkg/apis/eventing/v1beta1/broker_types.go
  pkg/apis/eventing/v1beta1/broker_validation.go
  pkg/apis/eventing/v1beta1/broker_validation_test.go
  pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/test/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/L

#2513 ObjectReference -> KReference
  pkg/apis/messaging/v1beta1/channel_types.go
  pkg/apis/messaging/v1beta1/channel_validation.go
  pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XS

#2440 Namespace reconcile
  pkg/reconciler/namespace/controller.go
  pkg/reconciler/namespace/namespace.go
  pkg/reconciler/namespace/namespace_test.go
  pkg/reconciler/namespace/resources/broker.go
  pkg/reconciler/namespace/resources/configmappropagation.go
  pkg/reconciler/namespace/resources/role_binding.go
  pkg/reconciler/namespace/resources/service_account.go
  pkg/utils/secret_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#2515 ObjectReference -> KReference
  pkg/apis/duck/v1beta1/channelable_types.go
  pkg/apis/duck/v1beta1/delivery_types.go
  pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/XS

#2514 Add missing type tests...
  pkg/apis/eventing/v1beta1/broker_types_test.go
  pkg/apis/eventing/v1beta1/eventtype_types_test.go
  pkg/apis/eventing/v1beta1/trigger_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#2521 Update pull-request-template.md
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/XS

#2522 Update test-infra,pkg to latest
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/release.sh
Labels: approved, cla: yes, lgtm, size/M

#2450 Add documentation on how to enable profiling.
  config/core/configmaps/observability.yaml
  test/performance/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#2524 Format markdown
  test/performance/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2525 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/library.sh
Labels: approved, cla: yes, lgtm, size/XS

#2517 Adding delivery spec and status conversion methods.
  Gopkg.lock
  pkg/apis/duck/v1alpha1/delivery_conversion.go
  pkg/apis/duck/v1alpha1/delivery_conversion_test.go
  pkg/apis/duck/v1beta1/delivery_conversion.go
  pkg/apis/duck/v1beta1/delivery_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#2526 SPEC: Adding duck/addressable label to channel CRD
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/XS

#2492 ConfigMapPropagation should keep other owner references when abandoning a copy configmap
  pkg/reconciler/configmappropagation/configmappropagation.go
  pkg/reconciler/configmappropagation/configmappropagation_test.go
  pkg/reconciler/testing/configmap.go
  pkg/reconciler/testing/configmappropagation.go
Labels: approved, cla: yes, lgtm, size/M

#2456 Combine broker / trigger reconciler loop. Except for namespace labeling, broker reconciles triggers.
  cmd/channel_broker/main.go
  cmd/controller/main.go
  pkg/apis/eventing/v1alpha1/broker_lifecycle.go
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/apis/eventing/v1alpha1/eventtype_lifecycle_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/subscription.go
  pkg/reconciler/broker/resources/subscription_test.go
  pkg/reconciler/broker/trigger.go
  pkg/reconciler/trigger/controller.go
  pkg/reconciler/trigger/trigger.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#2530 Godoc seem deprecated
  README.md
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/S

#2531 golang format tools
  pkg/apis/duck/v1alpha1/delivery_conversion_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2532 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#2518 Add Broker v1alpha1 <-> v1beta1 converters
  pkg/apis/duck/v1alpha1/delivery_conversion_test.go
  pkg/apis/eventing/v1alpha1/broker_conversion.go
  pkg/apis/eventing/v1alpha1/broker_conversion_test.go
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1beta1/broker_conversion.go
  pkg/apis/eventing/v1beta1/broker_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#2527 Knative flows namespaced admin
  config/core/roles/clusterrole-namespaced.yaml
Labels: approved, cla: yes, lgtm, size/S

#2533 Migrate PingSource to generated reconcilers.
  Gopkg.lock
  pkg/apis/sources/v1alpha1/ping_types.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/stub/reconciler.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
Labels: approved, cla: yes, lgtm, size/L

#2529 Adding section on event delivery
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/S

#2535 ping used 'legacysources'
  pkg/adapter/ping/adapter.go
Labels: approved, cla: yes, lgtm, size/XS

#2538 Migrating flows.Sequence to generated reconcilers.
  pkg/apis/flows/v1alpha1/sequence_types.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/stub/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/stub/reconciler.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2539 Add liu-cong to reviewer list.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2537 Migrating flows.Parallel to generated reconcilers.
  pkg/apis/flows/v1alpha1/parallel_types.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/stub/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/stub/reconciler.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
Labels: approved, cla: yes, lgtm, size/L

#2542 Add yolocs (cshou) to the reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2541 Migrate EventType to pure generated reconciler.
  pkg/apis/eventing/v1alpha1/eventtype_types.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/stub/reconciler.go
  pkg/reconciler/eventtype/controller.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/eventtype/eventtype_test.go
Labels: approved, cla: yes, lgtm, size/L

#2540 Migrate in memory controller to use generated reconciler.
  pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/stub/reconciler.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/L

#2545 Channel spec: Data Plane updates
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/M

#2547 Format markdown
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/S

#2548 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, cla: yes, lgtm, size/L

#2543 Migrate Subscription to use generated reconcilers.
  pkg/apis/messaging/v1alpha1/subscription_types.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/stub/reconciler.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/L

#2546 golang format tools
  pkg/apis/eventing/v1alpha1/broker_conversion.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
Labels: approved, cla: yes, lgtm, size/XS

#2550 Migrate Channels to generated reconcilers.
  Gopkg.lock
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/stub/reconciler.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/testing/channel.go
  third_party/VENDOR-LICENSE
  vendor/gomodules.xyz/jsonpatch/LICENSE
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/testing/testing.go
Labels: approved, cla: yes, lgtm, size/XXL

#2553 Adding a recommendation to use 1.0 for source implementors
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/XS

#2558 requeue broker when subscriptions to its triggers change
  pkg/reconciler/broker/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#2552 Remove commented out test code
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/S

#2563 Updating DeliverySpec/Status to latest types
  docs/delivery/README.md
Labels: approved, cla: yes, lgtm, size/S

#2560 Format markdown
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/S

#2565 update deps
  Gopkg.lock
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/stub/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/stub/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/stub/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/stub/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/stub/controller.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/stub/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/stub/controller.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/stub/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/stub/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/stub/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/reconciler/configstore.go
Labels: approved, cla: yes, lgtm, size/L

#2566 Adding references on Source/Channel delivery
  docs/delivery/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2557 Avoid counting "unwanted" events in Triggers
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#2569 dump events in a namespace when tearing down
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2572 Use original namespace in label on copy ConfigMap
  pkg/reconciler/configmappropagation/configmappropagation_test.go
  pkg/reconciler/configmappropagation/resources/configmap.go
  pkg/reconciler/configmappropagation/resources/configmap_test.go
Labels: approved, cla: yes, lgtm, size/S

#2567 Adding types tests
  pkg/apis/flows/v1beta1/parallel_types_test.go
  pkg/apis/sources/v1alpha1/apiserver_types_test.go
  pkg/apis/sources/v1alpha1/ping_types_test.go
  pkg/apis/sources/v1alpha1/sinkbinding_types_test.go
Labels: approved, cla: yes, lgtm, size/L

#2576 reconcile broker instead of trigger when dep changes
  pkg/reconciler/broker/trigger.go
Labels: approved, cla: yes, lgtm, size/XS

#2578 Format markdown
  docs/delivery/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2583 add Alek (aslom) to list of reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#2579 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#2554 Stage the place for CRD OpenAPI that differs between versions
  config/300-flows-parallel.yaml
  config/300-flows-sequence.yaml
  config/core/resources/apiserversource.yaml
  config/core/resources/broker.yaml
  config/core/resources/channel.yaml
  config/core/resources/eventtype.yaml
  config/core/resources/flows-parallel.yaml
  config/core/resources/flows-sequence.yaml
  config/core/resources/parallel.yaml
  config/core/resources/pingsource.yaml
  config/core/resources/sequence.yaml
  config/core/resources/sinkbindings.yaml
  config/core/resources/subscription.yaml
  config/core/resources/trigger.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#2585 Reconcile subscriptions via triggers
  Gopkg.lock
  pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/reconciler.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/testutils/clustermanager/e2e-tests/boskos/boskos.go
Labels: approved, cla: yes, lgtm, size/L

#2590 follow up to 2585. introduce a const for broker label/class
  pkg/apis/eventing/register.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/resources/filter.go
  pkg/reconciler/broker/resources/ingress.go
  pkg/reconciler/broker/resources/subscription.go
  pkg/reconciler/broker/resources/subscription_test.go
Labels: approved, cla: yes, lgtm, size/M

#2591 remove now no longer necessary things, moved to broker
  pkg/reconciler/trigger/resources/subscription.go
  pkg/reconciler/trigger/resources/subscription_test.go
  pkg/reconciler/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#2592 Format markdown
  config/channels/in-memory-channel-ns/README.md
Labels: approved, cla: yes, lgtm, size/S

#2574 Create service accounts strictly after roles.
  config/201-eventing-serviceaccount.yaml
  config/201-webhook-serviceaccount.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2577 Broker / Trigger v1alpha1<->v1beta1
  Gopkg.lock
  cmd/webhook/main.go
  config/core/resources/broker.yaml
  config/core/resources/trigger.yaml
  config/core/roles/webhook-clusterrole.yaml
  pkg/apis/eventing/register.go
  test/e2e/broker_default_test.go
  test/lib/creation.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2564 Using duckv1 for Destination API
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/XS

#2593 E2E test for DependencyAnnotation in Triggers
  test/e2e/trigger_dependency_annotation_test.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2589 Forward Context Through IMC Dispatcher
  Gopkg.lock
  Gopkg.toml
  pkg/broker/filter/filter_handler.go
  pkg/broker/ingress/ingress_handler.go
  pkg/channel/event_dispatcher.go
  pkg/channel/event_receiver.go
  pkg/channel/fanout/fanout_handler.go
  pkg/utils/context.go
  vendor/github.com/cloudevents/sdk-go/alias.go
  vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/context.go
Labels: approved, cla: yes, lgtm, size/M

#2600 Auto-update dependencies
  Gopkg.lock
  pkg/client/injection/reconciler/eventing/v1alpha1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1alpha1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1alpha1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha1/pingsource/reconciler.go
  vendor/knative.dev/pkg/.gitignore
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/test/example/register.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/foo_types.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/test/example/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/test/pub/register.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/bar_types.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/doc.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/test/pub/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/update-test-codegen.sh
  vendor/knative.dev/test-infra/scripts/README.md
Labels: approved, cla: yes, lgtm, size/XL

#2604 Contribution guidelines for user facing PRs
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#2601 Add docs link to PR template
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#2605 Added link to contribution guidelines after tests
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#2612 Format markdown
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#2608 add delivery options to sequence v1beta1 (API only)
  pkg/apis/flows/v1alpha1/sequence_defaults.go
  pkg/apis/flows/v1alpha1/sequence_defaults_test.go
  pkg/apis/flows/v1alpha1/sequence_types.go
  pkg/apis/flows/v1alpha1/sequence_validation.go
  pkg/apis/flows/v1alpha1/sequence_validation_test.go
  pkg/apis/flows/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/flows/v1beta1/sequence_defaults.go
  pkg/apis/flows/v1beta1/sequence_defaults_test.go
  pkg/apis/flows/v1beta1/sequence_types.go
  pkg/apis/flows/v1beta1/sequence_validation.go
  pkg/apis/flows/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/sequence/resources/subscription.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/testing/sequence.go
  test/e2e/sequence_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2615 Update pkg to latest
  Gopkg.lock
  pkg/apis/messaging/v1alpha1/channel_lifecycle_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_lifecycle_test.go
  pkg/apis/messaging/v1beta1/channel_lifecycle_test.go
  pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle_test.go
  test/e2e_flags.go
  third_party/VENDOR-LICENSE
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/logr.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/Gopkg.toml
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/conditions_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/conditions/fake/fake.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#2617 use go.dev image from sheilds.io
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#2602 EventType conversion v1alpha1 <--> v1beta1
  cmd/webhook/main.go
  config/core/resources/eventtype.yaml
  pkg/apis/eventing/register.go
  pkg/apis/eventing/v1alpha1/eventtype_conversion.go
  pkg/apis/eventing/v1alpha1/eventtype_conversion_test.go
  pkg/apis/eventing/v1beta1/eventtype_conversion.go
  pkg/apis/eventing/v1beta1/eventtype_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#2621 imc v1alpha1 <=> v1beta1
  cmd/webhook/main.go
  config/channels/in-memory-channel/300-in-memory-channel.yaml
  pkg/apis/messaging/register.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_types.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go
Labels: approved, cla: yes, lgtm, size/XL

#2616 Subscription Controller only patches channels.
  Gopkg.lock
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/messaging/v1alpha1/channel_validation.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
  pkg/apis/messaging/v1beta1/channel_validation.go
  pkg/apis/messaging/v1beta1/channel_validation_test.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/controller_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/inmemorychannel.go
  pkg/reconciler/testing/subscription.go
Labels: approved, cla: yes, lgtm, size/XXL

#2623 Auto-update dependencies
  Gopkg.lock
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#2620 Adding temp file to scale old sources controller to zero.
  config/core/deployments/sources-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#2556 Move webhooks onto new sharedmain methods
  Gopkg.lock
  cmd/webhook/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
Labels: approved, cla: yes, lgtm, size/L

#2622 Stage dropping the stats reported from Eventing
  Gopkg.lock
  pkg/reconciler/testing/factory.go
  vendor/knative.dev/pkg/reconciler/testing/stats.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/webhook/testing/factory.go
Labels: approved, cla: yes, lgtm, size/M

#2625 clean up channeltemplate and delivery
  cmd/webhook/main.go
  pkg/apis/eventing/v1alpha1/broker_conversion.go
  pkg/apis/eventing/v1alpha1/broker_conversion_test.go
  pkg/apis/eventing/v1alpha1/broker_defaults.go
  pkg/apis/eventing/v1alpha1/broker_defaults_test.go
  pkg/apis/eventing/v1alpha1/broker_types.go
  pkg/apis/eventing/v1alpha1/broker_validation.go
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1alpha1/channel_conversion.go
  pkg/apis/messaging/v1alpha1/channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/channel_defaults.go
  pkg/apis/messaging/v1alpha1/channel_defaults_test.go
  pkg/apis/messaging/v1alpha1/channel_types.go
  pkg/apis/messaging/v1alpha1/channel_validation.go
  pkg/apis/messaging/v1alpha1/channel_validation_test.go
  pkg/apis/messaging/v1alpha1/subscription_conversion.go
  pkg/apis/messaging/v1alpha1/subscription_conversion_test.go
  pkg/apis/messaging/v1alpha1/subscription_types.go
  pkg/apis/messaging/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1beta1/channel_validation.go
  pkg/defaultchannel/channel_defaulter.go
  pkg/defaultchannel/channel_defaulter_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/config.go
  pkg/reconciler/broker/config_test.go
  pkg/reconciler/broker/resources/channel.go
  pkg/reconciler/broker/resources/channel_test.go
  pkg/reconciler/broker/resources/subscription.go
  pkg/reconciler/broker/resources/subscription_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/testing/broker.go
  pkg/reconciler/testing/channel.go
  pkg/reconciler/testing/subscription.go
  test/e2e/helpers/channel_defaulter_test_helper.go
  test/lib/resources/eventing.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2626 make namespace reconciler work for broker recreation
  pkg/reconciler/namespace/controller.go
  test/e2e/broker_default_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2627 remove now unused v1alpha1.channeltemplatespec and v1alpha1.deliveryspec
  cmd/webhook/main.go
  pkg/apis/duck/v1alpha1/channel_defaulter.go
  pkg/apis/duck/v1alpha1/channel_template_types.go
  pkg/apis/duck/v1alpha1/channelable_types.go
  pkg/apis/duck/v1alpha1/channelable_types_test.go
  pkg/apis/duck/v1alpha1/delivery_conversion.go
  pkg/apis/duck/v1alpha1/delivery_conversion_test.go
  pkg/apis/duck/v1alpha1/delivery_types.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/channel/resources/channel.go
  pkg/reconciler/parallel/resources/channel.go
  pkg/reconciler/sequence/resources/channel.go
  test/lib/duck/resource_creators.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2630 golang format tools
  pkg/reconciler/testing/inmemorychannel.go
Labels: approved, cla: yes, lgtm, size/XS

#2632 Rename ConvertUp/Down to ConvertTo/From
  Gopkg.lock
  cmd/webhook/main.go
  pkg/apis/duck/v1beta1/delivery_conversion.go
  pkg/apis/duck/v1beta1/delivery_conversion_test.go
  pkg/apis/eventing/v1alpha1/broker_conversion.go
  pkg/apis/eventing/v1alpha1/broker_conversion_test.go
  pkg/apis/eventing/v1alpha1/eventtype_conversion.go
  pkg/apis/eventing/v1alpha1/eventtype_conversion_test.go
  pkg/apis/eventing/v1alpha1/trigger_conversion.go
  pkg/apis/eventing/v1alpha1/trigger_conversion_test.go
  pkg/apis/eventing/v1beta1/broker_conversion.go
  pkg/apis/eventing/v1beta1/broker_conversion_test.go
  pkg/apis/eventing/v1beta1/eventtype_conversion.go
  pkg/apis/eventing/v1beta1/eventtype_conversion_test.go
  pkg/apis/eventing/v1beta1/trigger_conversion.go
  pkg/apis/eventing/v1beta1/trigger_conversion_test.go
  pkg/apis/flows/v1alpha1/parallel_conversion.go
  pkg/apis/flows/v1alpha1/parallel_conversion_test.go
  pkg/apis/flows/v1alpha1/parallel_lifecycle.go
  pkg/apis/flows/v1alpha1/sequence_conversion.go
  pkg/apis/flows/v1alpha1/sequence_conversion_test.go
  pkg/apis/flows/v1alpha1/sequence_lifecycle.go
  pkg/apis/flows/v1beta1/parallel_conversion.go
  pkg/apis/flows/v1beta1/parallel_conversion_test.go
  pkg/apis/flows/v1beta1/sequence_conversion.go
  pkg/apis/flows/v1beta1/sequence_conversion_test.go
  pkg/apis/messaging/v1alpha1/channel_conversion.go
  pkg/apis/messaging/v1alpha1/channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1alpha1/in_memory_channel_conversion_test.go
  pkg/apis/messaging/v1alpha1/subscription_conversion.go
  pkg/apis/messaging/v1alpha1/subscription_conversion_test.go
  pkg/apis/messaging/v1beta1/channel_conversion.go
  pkg/apis/messaging/v1beta1/channel_conversion_test.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion.go
  pkg/apis/messaging/v1beta1/in_memory_channel_conversion_test.go
  pkg/apis/messaging/v1beta1/subscription_conversion.go
  pkg/apis/messaging/v1beta1/subscription_conversion_test.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/convert.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/apis/testing/conditions.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/knative.dev/pkg/apis/testing/v1/conditions.go
  vendor/knative.dev/pkg/apis/testing/v1beta1/conditions.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/internal/types.go
Labels: approved, cla: yes, lgtm, size/XL

#2635 Preparing for v0.13 release, point pkg to release-0.13.
  Gopkg.lock
  Gopkg.toml
Labels: approved, cla: yes, lgtm, size/XS

#2638 Subscription controller needs to track Channels directly, when used.
  pkg/duck/listable.go
  pkg/duck/sinks.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#2639 Update to latest pkg.
  Gopkg.lock
  vendor/knative.dev/pkg/webhook/psbinding/contexts.go
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
Labels: approved, cla: yes, lgtm, size/L

#2645 add our types for v1beta1 so we get defaults
  cmd/webhook/main.go
Labels: approved, cla: yes, lgtm, size/XS

#2634 Add an option to specify sinkbinding webhook selector.
  cmd/webhook/main.go
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/M

#2653 Adding namespace and configmappropagations finalizers for the configmappropagations
  config/brokers/channel-broker/roles/controller-clusterroles.yaml
Labels: approved, cla: yes, lgtm, size/S

#2654 Format markdown
  config/channels/in-memory-channel/README.md
Labels: approved, cla: yes, lgtm, size/XS

#2649 E2e tests pingsource v1a2
  config/core/resources/pingsource.yaml
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/testing/pingsource.go
  test/e2e/source_ping_test.go
  test/e2e/trigger_dependency_annotation_test.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2659 add ngiraldo to mako configs
  test/performance/benchmarks/broker-imc/dev.config
  test/performance/benchmarks/broker-imc/prod.config
  test/performance/benchmarks/channel-imc/dev.config
  test/performance/benchmarks/channel-imc/prod.config
  test/performance/config/config-mako.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2662 Pick a better name for the sinkbinding selector env var.
  cmd/webhook/main.go
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#2501 Add leader election
  Gopkg.lock
  cmd/channel_broker/main.go
  cmd/in_memory/channel_controller/main.go
  cmd/in_memory/channel_dispatcher/main.go
  cmd/webhook/main.go
  config/brokers/channel-broker/roles/controller-clusterroles.yaml
  config/channels/in-memory-channel/200-controller-clusterrole.yaml
  config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
  config/config-leader-election.yaml
  config/core/configmaps/leader-election.yaml
  pkg/apis/configs/validation/leader_election.go
  pkg/apis/configs/validation/leader_election_test.go
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/knative.dev/pkg/Gopkg.lock
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
Labels: approved, cla: yes, lgtm, size/XXL

#2640 No wait in ko delete for performance tests
  test/performance/performance-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#2667 golang format tools
  pkg/apis/config/defaults_test.go
  pkg/apis/sources/v1alpha1/sinkbinding_conversion.go
  pkg/apis/sources/v1alpha1/sinkbinding_conversion_test.go
  pkg/apis/sources/v1alpha2/sinkbinding_conversion.go
  pkg/reconciler/testing/pingsource.go
  test/e2e/source_ping_test.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#2673 re adding CR char that got accidentally removed
  config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#2674 Rename leader election config package/methods
  cmd/webhook/main.go
  pkg/leaderelection/leader_election.go
  pkg/leaderelection/leader_election_test.go
Labels: approved, cla: yes, lgtm, size/S

#2670 migrate broker config to look like channel config
  config/core/configmaps/default-imc.yaml
  pkg/apis/eventing/v1alpha1/broker_validation_test.go
  pkg/reconciler/broker/config.go
  pkg/reconciler/broker/config_test.go
  pkg/reconciler/broker/testdata/config-broker.yaml
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#2676 Remove Subscription's finalizer if the Channel was deleted first
  pkg/apis/messaging/v1alpha1/subscription_lifecycle.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/subscription.go
Labels: approved, cla: yes, lgtm, size/M

#2675 Add webhook and validation config to EventType
  config/core/resources/eventtype.yaml
Labels: approved, cla: yes, lgtm, size/S
