Repository knative/eventing, pull requests merged in 2020-11, with the labels that each got.

#4445 Migrate wathola components to use deployment
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4448 checks out
  pkg/channel/fanout/fanout_message_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#4451 drop vendoring pkg/testutils
  hack/tools.go
  vendor/google.golang.org/api/container/v1beta1/container-api.json
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/knative.dev/pkg/test/gke/addon.go
  vendor/knative.dev/pkg/test/gke/client.go
  vendor/knative.dev/pkg/test/gke/endpoint.go
  vendor/knative.dev/pkg/test/gke/location.go
  vendor/knative.dev/pkg/test/gke/request.go
  vendor/knative.dev/pkg/test/gke/wait.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4452 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#4454 Retry on network failures
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/M

#4456 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#4458 [release-0.17] Retry on network failures (#4454)
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/L

#4457 [release-0.18] Retry on network failures (#4454)
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/L

#4447 rename to fuzzer_test otherwise still included
  pkg/apis/duck/v1/test/fuzzer.go
  pkg/apis/eventing/v1beta1/roundtrip_test.go
  pkg/apis/flows/v1beta1/roundtrip_test.go
  pkg/apis/messaging/v1beta1/roundtrip_test.go
Labels: approved, cla: yes, lgtm, size/L

#4463 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#4465 kncloudevents now uses a singleton http client
  cmd/mtbroker/ingress/main.go
  pkg/adapter/v2/main_message.go
  pkg/channel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/http_client.go
  pkg/kncloudevents/http_client_test.go
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/ingress/ingress_handler_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: approved, cla: yes, lgtm, size/L

#4467 [0.17] Backport #4465
  cmd/mtbroker/ingress/main.go
  pkg/kncloudevents/http_client.go
  pkg/kncloudevents/http_client_test.go
  pkg/kncloudevents/message_sender.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, cla: yes, lgtm, size/L

#4468 [0.18] Backport #4465
  cmd/mtbroker/ingress/main.go
  pkg/kncloudevents/http_client.go
  pkg/kncloudevents/http_client_test.go
  pkg/kncloudevents/message_sender.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, cla: yes, lgtm, size/L

#4466 Remove double invocations to responseWriter.WriteHeader in filter handler
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/filter/filter_handler_test.go
Labels: approved, cla: yes, lgtm, size/L

#4470 [0.17] Backport #4466
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/filter/filter_handler_test.go
Labels: approved, cla: yes, lgtm, size/L

#4471 [0.18] Backport #4466
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/filter/filter_handler_test.go
Labels: approved, cla: yes, lgtm, size/L

#4477 fixed wrong marshall in apiserversouece which will fix the missing ceOverrides extension
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4479 [0.17] Backport #4475 (#4477)
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4480 [0.18] Backport #4475 (#4477)
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4472 fix error during upgrade from 0.17 to 0.18
  config/core/deployments/pingsource-mt-adapter.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4484 Backport https://github.com/knative/eventing/pull/4472
  config/core/deployments/pingsource-mt-adapter.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4482 [0.17] Readyness probe in broker ingress
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  pkg/mtbroker/ingress/ingress_handler.go
Labels: approved, cla: yes, lgtm, size/S

#4478 Adding readynessProbe
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Labels: approved, cla: yes, lgtm, size/S

#4483 [0.18] Readyness probe in broker ingress
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  pkg/mtbroker/ingress/ingress_handler.go
Labels: approved, cla: yes, lgtm, size/S

#4460 Refactor fetching of wathola receiver's delivery report using special batch Job
  test/lib/nodes/address.go
  test/lib/nodes/address_test.go
  test/lib/nodes/kind.go
  test/lib/nodes/logger_test.go
  test/lib/nodes/nodes.go
  test/lib/nodes/nodes_test.go
  test/test_images/wathola-fetcher/main.go
  test/test_images/wathola-fetcher/main_test.go
  test/test_images/wathola-fetcher/pod.yaml
  test/upgrade/README.md
  test/upgrade/prober/prober.go
  test/upgrade/prober/verify.go
  test/upgrade/prober/wathola/fetcher/operations.go
  test/upgrade/prober/wathola/fetcher/types.go
  test/upgrade/prober/wathola/receiver/services.go
  test/upgrade/prober/wathola/receiver/types.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#4485 [Automated] Format markdown
  test/upgrade/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4487 Fix emoji
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#4489 Fix typo in verify.go
  test/upgrade/prober/verify.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4434 Enable more sources on e2e test cfg
  test/e2e-conformance-tests.sh
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4490 clean up out of date docs
  docs/spec/overview.md
Labels: approved, cla: yes, lgtm, size/XS

#4492 Change Channel.spec.channelTemplate.spec type from string to object in OpenAPI schema
  config/core/resources/channel.yaml
  config/pre-install/v0.18.0/channel.yaml
  pkg/apis/messaging/config/channel_defaults_test.go
  test/e2e/namespace_default_channel_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4497 dump the actual state of the pod when waiting for readiness.
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4499 Some code optimization in the test
  pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  pkg/channel/fanout/fanout_message_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/M

#4500 Refactor TestChannelNamespaceDefaulting
  test/e2e/namespace_default_channel_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4504 [Automated] Format markdown
  docs/spec/overview.md
Labels: approved, cla: yes, lgtm, size/XS

#4507 add imc dispatcher probe
  config/channels/in-memory-channel/deployments/dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/S

#4508 run kind e2e every 2 hours
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4493 Reorg of trigger filtering code
  pkg/eventfilter/attributes/filter.go
  pkg/eventfilter/attributes/filter_test.go
  pkg/eventfilter/filter.go
  pkg/eventfilter/filter_test.go
  pkg/mtbroker/filter/filter_handler.go
Labels: approved, cla: yes, lgtm, size/L

#4439 Relax empty logging config tests
  pkg/reconciler/source/config_watcher_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4502 [master] Remove prejob install
  config/pre-install/v0.16.0/broker.yaml
  config/pre-install/v0.16.0/clusterrole.yaml
  config/pre-install/v0.16.0/pingsource.yaml
  config/pre-install/v0.16.0/placeholder.go
  config/pre-install/v0.16.0/serviceaccount.yaml
  config/pre-install/v0.16.0/storage-version-migration.yaml
  config/pre-install/v0.18.0/apiserversource.yaml
  config/pre-install/v0.18.0/broker.yaml
  config/pre-install/v0.18.0/channel.yaml
  config/pre-install/v0.18.0/clusterrole.yaml
  config/pre-install/v0.18.0/containersource.yaml
  config/pre-install/v0.18.0/in-memory-channel.yaml
  config/pre-install/v0.18.0/parallel.yaml
  config/pre-install/v0.18.0/pingsource.yaml
  config/pre-install/v0.18.0/placeholder.go
  config/pre-install/v0.18.0/sequence.yaml
  config/pre-install/v0.18.0/serviceaccount.yaml
  config/pre-install/v0.18.0/sinkbindings.yaml
  config/pre-install/v0.18.0/storage-version-migration.yaml
  config/pre-install/v0.18.0/subscription.yaml
  config/pre-install/v0.18.0/trigger.yaml
  hack/release.sh
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4510 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4516 Fix a few more occurrences of divisive language
  docs/broker/README.md
  docs/decisions/broker-trigger.md
  docs/decisions/discovery-and-faas-support.md
  pkg/adapter/mtping/adapter_test.go
  pkg/adapter/mtping/controller_test.go
  pkg/adapter/mtping/pingsource_test.go
  pkg/apis/sources/v1/apiserver_conversion_test.go
  pkg/apis/sources/v1/container_conversion_test.go
  pkg/apis/sources/v1/sinkbinding_conversion_test.go
  pkg/apis/sources/v1alpha1/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha1/sinkbinding_conversion_test.go
  pkg/apis/sources/v1alpha2/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha2/container_conversion_test.go
  pkg/apis/sources/v1alpha2/ping_conversion_test.go
  pkg/apis/sources/v1alpha2/sinkbinding_conversion_test.go
  pkg/apis/sources/v1beta1/apiserver_conversion_test.go
  pkg/apis/sources/v1beta1/container_conversion_test.go
  pkg/apis/sources/v1beta1/ping_conversion_test.go
  pkg/apis/sources/v1beta1/sinkbinding_conversion_test.go
  pkg/channel/testdata/config-event-dispatcher-1.yaml
  pkg/channel/testdata/config-event-dispatcher-2.yaml
  pkg/channel/testdata/config-event-dispatcher-3.yaml
  pkg/channel/testdata/config-event-dispatcher-4.yaml
  pkg/reconciler/mtbroker/broker_test.go
  test/e2e/helpers/channel_chain_test_helper.go
  test/e2e/helpers/channel_defaulter_test_helper.go
  test/e2e/helpers/channel_dls_test_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/e2e/helpers/channel_single_event_helper.go
  test/e2e/helpers/parallel_test_helper.go
  test/e2e/helpers/sequence_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4517 Microbenchmark for Trigger Filter
  pkg/eventfilter/benchmarks/attributes_benchmark_test.go
  pkg/eventfilter/benchmarks/common_benchmark_test.go
Labels: approved, cla: yes, lgtm, size/L

#4459 Recordevent now sends events too
  test/e2e/helpers/broker_redelivery_helper.go
  test/e2e/helpers/channel_single_event_helper.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/event_info_matchers.go
  test/lib/recordevents/event_info_store.go
  test/lib/recordevents/event_log.go
  test/lib/recordevents/receiver/receiver.go
  test/lib/recordevents/receiver/reply.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/lib/recordevents/resources.go
  test/lib/recordevents/sender/sender.go
  test/lib/sender/resources.go
  test/test_images/recordevents/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#4503 [0.19] Remove prejob install
  config/pre-install/v0.16.0/broker.yaml
  config/pre-install/v0.16.0/clusterrole.yaml
  config/pre-install/v0.16.0/pingsource.yaml
  config/pre-install/v0.16.0/placeholder.go
  config/pre-install/v0.16.0/serviceaccount.yaml
  config/pre-install/v0.16.0/storage-version-migration.yaml
  config/pre-install/v0.18.0/apiserversource.yaml
  config/pre-install/v0.18.0/broker.yaml
  config/pre-install/v0.18.0/channel.yaml
  config/pre-install/v0.18.0/clusterrole.yaml
  config/pre-install/v0.18.0/containersource.yaml
  config/pre-install/v0.18.0/in-memory-channel.yaml
  config/pre-install/v0.18.0/parallel.yaml
  config/pre-install/v0.18.0/pingsource.yaml
  config/pre-install/v0.18.0/placeholder.go
  config/pre-install/v0.18.0/sequence.yaml
  config/pre-install/v0.18.0/serviceaccount.yaml
  config/pre-install/v0.18.0/sinkbindings.yaml
  config/pre-install/v0.18.0/storage-version-migration.yaml
  config/pre-install/v0.18.0/subscription.yaml
  config/pre-install/v0.18.0/trigger.yaml
  hack/release.sh
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4522 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#4524 Log error returned by adapter.Start at error level
  pkg/adapter/v2/main.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#4520 Various small test nits
  pkg/adapter/mtping/controller_test.go
  pkg/apis/sources/v1/container_conversion_test.go
  pkg/apis/sources/v1alpha2/container_conversion_test.go
  pkg/apis/sources/v1beta1/container_conversion_test.go
  pkg/apis/sources/v1beta1/ping_conversion_test.go
Labels: approved, cla: yes, lgtm, size/M

#4429 Add gcp-project-id option to test/e2e-tests.sh command in test/README.md
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4526 [Automated] Format markdown
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4525 use kn style parse configmap
  pkg/channel/config.go
  pkg/configmap/reader.go
Labels: approved, area/test-and-release, cla: yes, kind/cleanup, lgtm, size/M

#4341 generate yaml
  hack/generate-yamls.sh
  hack/release.sh
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4531 fill out remaining 2020 schedule
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/M

#4511 fix 4509, remove finalizer
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/L

#4533 fix generate yaml comments
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4536 Move Ali to the last 2 weeks of the year
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4535 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4537 Fix nits in PingSource v1beta2
  config/core/resources/pingsource.yaml
  pkg/adapter/mtping/runner.go
  pkg/apis/sources/v1beta1/ping_conversion.go
  pkg/apis/sources/v1beta2/ping_types.go
  pkg/apis/sources/v1beta2/ping_validation.go
Labels: approved, cla: yes, lgtm, size/M

#4541 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-k8s-deps.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4546 fix eventing nightly release
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4550 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#4551 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4552 Remove latest_version function
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, kind/cleanup, lgtm, size/XS

#4554 Removing nachocano from approvers and reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4557 Adding a first pass smoke test for broker using the reconciler-test framework.
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
  pkg/reconciler/inmemorychannel/controller/resources/service.go
  pkg/reconciler/mtbroker/resources/channel.go
  test/e2e-tests.sh
  test/rekt/features/broker/broker_feature.go
  test/rekt/ko_publish_test.go
  test/rekt/main_test.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/broker/broker.yaml
  test/rekt/smoke_test.go
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE
  vendor/knative.dev/reconciler-test/LICENSE
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/level.go
  vendor/knative.dev/reconciler-test/pkg/feature/name.go
  vendor/knative.dev/reconciler-test/pkg/feature/states.go
  vendor/knative.dev/reconciler-test/pkg/feature/timing.go
  vendor/knative.dev/reconciler-test/pkg/images/cmd.go
  vendor/knative.dev/reconciler-test/pkg/images/ko.go
  vendor/knative.dev/reconciler-test/pkg/k8s/events.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/logs.go
  vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/knative.dev/reconciler-test/pkg/manifest/manifest.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/knative.dev/reconciler-test/pkg/manifest/yaml.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, kind/cleanup, lgtm, size/XXL

#4558 [Release 0.18] Fix MTBroker Channel and IMC Channel Services length issue.
  pkg/reconciler/inmemorychannel/controller/resources/service.go
  pkg/reconciler/mtbroker/resources/channel.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#4559 [Release 0.19] Fix MTBroker Channel and IMC Channel Services length issue.
  pkg/reconciler/inmemorychannel/controller/resources/service.go
  pkg/reconciler/mtbroker/resources/channel.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#4553 Remove some more woke warnings
  pkg/apis/sources/v1beta2/ping_conversion_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4561 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4575 Get webhook name from pkg
  cmd/webhook/main.go
  pkg/logconfig/config.go
Labels: approved, cla: yes, lgtm, size/XS

#4548 [0.18] Change Channel.spec.channelTemplate.spec type to object in OpenAPI schema
  config/core/resources/channel.yaml
  config/pre-install/v0.18.0/channel.yaml
  pkg/apis/messaging/config/channel_defaults_test.go
  test/e2e/namespace_default_channel_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4564 Smoke test trigger based on the reconciler-test framework
  test/rekt/features/broker/broker_feature.go
  test/rekt/features/broker_feature.go
  test/rekt/features/defaults.go
  test/rekt/features/trigger_feature.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/broker/broker.yaml
  test/rekt/resources/broker/broker_test.go
  test/rekt/resources/parser.go
  test/rekt/resources/svc/service.go
  test/rekt/resources/svc/service.yaml
  test/rekt/resources/svc/service_test.go
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger.yaml
  test/rekt/resources/trigger/trigger_test.go
  test/rekt/smoke_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#3448 Channel spec clarification about Channel not found behaviour
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/XS

#4580 Use IsReady and IsAddressable from reconciler-test.
  go.mod
  go.sum
  test/rekt/README.md
  test/rekt/resources/broker/broker.go
  test/rekt/resources/broker/broker_test.go
  test/rekt/resources/parser.go
  test/rekt/resources/svc/service_test.go
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger_test.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#4581 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#4438 Increasing parallel runs
  test/e2e-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4582 Making test config file changes like we do for real configs
  test/config/chaosduck.yaml
  test/config/chaosduck/chaosduck.yaml
  test/config/config-logging.yaml
  test/config/config-tracing.yaml
  test/config/configmaps/logging.yaml
  test/config/configmaps/tracing.yaml
  test/config/monitoring.yaml
  test/config/monitoring/monitoring.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4589 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/collapse.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#4583 Delete versioned directories for post-install jobs
  cmd/v0.16/broker-cleanup/README.md
  cmd/v0.16/broker-cleanup/injection.go
  cmd/v0.16/broker-cleanup/main.go
  cmd/v0.17/pingsource-cleanup/README.md
  cmd/v0.17/pingsource-cleanup/injection.go
  cmd/v0.17/pingsource-cleanup/main.go
  config/post-install/v0.15.0/clusterrole.yaml
  config/post-install/v0.15.0/placeholder.go
  config/post-install/v0.15.0/serviceaccount.yaml
  config/post-install/v0.15.0/storage-version-migration.yaml
  config/post-install/v0.16.0/broker-cleanup.yaml
  config/post-install/v0.16.0/placeholder.go
  config/post-install/v0.17.0/pingsource-cleanup.yaml
  config/post-install/v0.17.0/placeholder.go
Labels: approved, cla: yes, lgtm, size/XL

#4590 Remove deprecated function WebhookName
  pkg/logconfig/config.go
Labels: approved, cla: yes, lgtm, size/S

#4591 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4597 fix inconsistency between versions when updating PingSource
  pkg/apis/sources/v1beta1/ping_conversion.go
  pkg/apis/sources/v1beta1/ping_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#4519 Migrate upgrade tests to use new framework
  go.mod
  go.sum
  hack/generate-yamls.sh
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
  test/presubmit-tests.sh
  test/upgrade/continual.go
  test/upgrade/installation/git_head.go
  test/upgrade/installation/latest.go
  test/upgrade/installation/shell.go
  test/upgrade/main_test.go
  test/upgrade/postdowngrade.go
  test/upgrade/postdowngrade_test.go
  test/upgrade/postupgrade.go
  test/upgrade/postupgrade_test.go
  test/upgrade/preupgrade.go
  test/upgrade/probe_test.go
  test/upgrade/smoke.go
  test/upgrade/smoke_test.go
  test/upgrade/upgrade_test.go
  third_party/VENDOR-LICENSE/knative.dev/hack/shell/LICENSE
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/hack/shell/executor.go
  vendor/knative.dev/hack/shell/fail-example.sh
  vendor/knative.dev/hack/shell/prefixer.go
  vendor/knative.dev/hack/shell/project.go
  vendor/knative.dev/hack/shell/types.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/pkg/test/upgrade/vars.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4606 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4600 Add stub-sidecar dependency for performance test
  hack/tools.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/main.go
  vendor/knative.dev/pkg/test/mako/stub-sidecar/read_results.sh
  vendor/knative.dev/pkg/third_party/mako/LICENSE
  vendor/knative.dev/pkg/third_party/mako/proto/quickstore_go_proto/quickstore.pb.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#4556 feat/upgrade-test: Add configurable action in case of duplicated events
  test/test_images/wathola-fetcher/main_test.go
  test/upgrade/prober/configuration.go
  test/upgrade/prober/verify.go
  test/upgrade/prober/wathola/event/operations.go
  test/upgrade/prober/wathola/event/services.go
  test/upgrade/prober/wathola/event/services_test.go
  test/upgrade/prober/wathola/fetcher/operations.go
  test/upgrade/prober/wathola/receiver/services.go
  test/upgrade/prober/wathola/receiver/types.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L
