Repository knative/eventing, pull requests merged in 2020-09, with the labels that each got.

#3976 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3979 broker conf tests -- add wait on pod resource ready
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3980 Increase timeout for fake CM
  pkg/utils/cache/persisted_store_test.go
Labels: approved, cla: yes, lgtm, size/S

#3986 [master] Update GitHub Actions
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3988 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#3989 Harden delete tests to verify more things
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/source/duck/duck_test.go
Labels: approved, cla: yes, lgtm, size/M

#3165 Add lberk to approvers
  OWNERS
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3977 adding downstream tests for sample source and eventing-contrib
  .github/workflows/knative-downstream.yaml
  pkg/leaderelection/context_test.go
Labels: approved, cla: yes, lgtm, size/L

#3991 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3992 Fix race condition #3960
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
Labels: approved, cla: yes, lgtm, size/XS

#3996 remove unused triggerlister
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#3998 Use helpers, rather than manual resource ctor
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/source/duck/duck_test.go
Labels: approved, cla: yes, lgtm, size/S

#3999 remove unused code in mtping
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/controller.go
  pkg/adapter/mtping/pingsource.go
  pkg/adapter/mtping/pingsource_test.go
  pkg/adapter/mtping/runner.go
  pkg/adapter/mtping/runner_test.go
Labels: approved, cla: yes, lgtm, size/L

#3987 Eager pingsource adapter creation
  config/500-pingsource-mt-adapter.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/controller_test.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/pingsource/resources/receive_adapter.go
  pkg/reconciler/pingsource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#3997 remove useless scope test
  pkg/adapter/mtping/pingsource.go
Labels: approved, cla: yes, lgtm, size/XS

#4007 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3990 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#4015 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#4017 Format markdown manually
  docs/personas.md
  docs/source/README.md
  docs/spec/channel.md
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/M

#4019 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4018 Add linting config and fix issues.
  .golangci.yaml
  cmd/mtbroker/ingress/main.go
  pkg/adapter/mtping/runner_test.go
  pkg/adapter/v2/main.go
  pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/flows/v1/parallel_defaults.go
  pkg/apis/flows/v1/sequence_defaults.go
  pkg/apis/flows/v1beta1/parallel_defaults.go
  pkg/apis/flows/v1beta1/sequence_defaults.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/source/crd/controller.go
  pkg/reconciler/source/crd/crd_test.go
  pkg/reconciler/subscription/subscription_test.go
  test/conformance/helpers/sources/source_status_test_helper.go
  test/conformance/main_test.go
  test/lib/creation.go
  test/performance/infra/aggregator/aggregator.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XL

#4020 Upgrade checksum generator for eventing
  hack/update-checksums.sh
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4021 Refactor main functions to reuse helpers from package.
  cmd/mtbroker/filter/main.go
  cmd/mtbroker/ingress/main.go
Labels: approved, cla: yes, lgtm, size/M

#4022 Remove 'master' where not necessary and add tracking issues.
  pkg/adapter/v2/cloudevents_test.go
  test/lib/nodes/nodes.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4025 Remove unnecessary whitelist terminology.
  pkg/utils/headers.go
Labels: approved, cla: yes, lgtm, size/XS

#4030 fix log message
  pkg/reconciler/mtbroker/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/XS

#4032 Remove event source from dashboard
  config/monitoring/metrics/grafana/100-grafana-dash-eventing.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4033 Remove non-mt ping source panels from dashboard
  config/monitoring/metrics/grafana/100-grafana-dash-eventing.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4035 Better grouping of imc config files
  config/channels/in-memory-channel/100-config-event-dispatcher.yaml
  config/channels/in-memory-channel/200-addressable-resolver-clusterrole.yaml
  config/channels/in-memory-channel/200-channelable-manipulator-clusterrole.yaml
  config/channels/in-memory-channel/200-controller-clusterrole.yaml
  config/channels/in-memory-channel/200-controller-serviceaccount.yaml
  config/channels/in-memory-channel/200-dispatcher-clusterrole.yaml
  config/channels/in-memory-channel/200-dispatcher-service.yaml
  config/channels/in-memory-channel/201-controller-clusterrolebinding.yaml
  config/channels/in-memory-channel/300-in-memory-channel.yaml
  config/channels/in-memory-channel/500-controller.yaml
  config/channels/in-memory-channel/500-dispatcher.yaml
  config/channels/in-memory-channel/configmaps/event-dispatcher.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher-service.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/channels/in-memory-channel/roles/addressable-resolver-clusterrole.yaml
  config/channels/in-memory-channel/roles/channelable-manipulator-clusterrole.yaml
  config/channels/in-memory-channel/roles/controller-clusterrole.yaml
  config/channels/in-memory-channel/roles/dispatcher-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XL

#4036 Fix tests from knative.dev/pkg changes
  go.mod
  go.sum
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/subscription/subscription_test.go
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/ghutil/pullrequest.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3994 Added downstream test with eventing-kafka-broker
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/M

#4042 Propagate the entire delivery spec to the Channel
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/L

#4043 Increase timeout for persisted store test
  pkg/utils/cache/persisted_store_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4044 [release-0.17] Propagate the entire delivery spec to the Channel (#4042)
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/L

#4047 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4048 Moving constant
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4045 Add retries for webhook fails at conformance tests
  test/conformance/helpers/broker_control_plane_test_helper.go
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4046 [master] Update GitHub Actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#4054 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4008 mtping adapter controller can now be easily generated.
  go.mod
  go.sum
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/adapter_test.go
  pkg/adapter/mtping/config.go
  pkg/adapter/mtping/config_test.go
  pkg/adapter/mtping/controller.go
  pkg/adapter/mtping/controller_test.go
  pkg/adapter/mtping/pingsource.go
  pkg/adapter/mtping/pingsource_test.go
  pkg/adapter/mtping/runner.go
  pkg/adapter/mtping/runner_test.go
  pkg/adapter/v2/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#4053 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#4061 The V1 test should actually use V1 APIs
  test/e2e/channel_dls_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4062 Reflecting API caller on the name of the test
  test/e2e/channel_chain_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4067 Change link to GitHubSource
  docs/source/receive-adapter.md
Labels: approved, cla: yes, lgtm, size/XS

#4068 [master] Format markdown
  docs/source/receive-adapter.md
Labels: approved, cla: yes, lgtm, size/XS

#4069 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4000 Switch back to sharedmain.Main for MT Broker controller
  cmd/mtchannel_broker/main.go
Labels: approved, cla: yes, lgtm, size/S

#4072 Project pod name as env var in our deployments
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  config/core/deployments/webhook.yaml
  config/sugar/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#4082 Reflect versions on test func
  test/e2e/channel_event_transformation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4083 Proper logging for filter handler malformed response
  pkg/mtbroker/filter/filter_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#4009 mtping now uses bucket-based leader election
  cmd/mtping/main.go
  docs/source/receive-adapter.md
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/adapter_test.go
  pkg/adapter/mtping/controller.go
  pkg/adapter/v2/config.go
  pkg/adapter/v2/config_watcher.go
  pkg/adapter/v2/context.go
  pkg/adapter/v2/context_test.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_message.go
  pkg/adapter/v2/main_test.go
  pkg/leaderelection/context.go
  pkg/leaderelection/context_test.go
  pkg/leaderelection/leader_election.go
  pkg/leaderelection/leader_election_test.go
  pkg/leaderelection/testdata/config-leader-election.yaml
Labels: approved, cla: yes, lgtm, size/XL

#4089 remove persisted store
  pkg/utils/cache/persisted_store.go
  pkg/utils/cache/persisted_store_test.go
Labels: approved, cla: yes, lgtm, size/XL

#4090 remove reference to persisted store
  docs/source/receive-adapter.md
Labels: approved, cla: yes, lgtm, size/M

#4088 [master] Update GitHub Actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#4097 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4098 add secret lister
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/v1/listers.go
Labels: approved, cla: yes, lgtm, size/XS

#4096 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#4099 make pingsource adapter controller read-only
  pkg/adapter/mtping/controller.go
  pkg/adapter/mtping/pingsource.go
Labels: approved, cla: yes, lgtm, size/S

#4091 Update channel.md
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/XS

#4104 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/webhook/conversion.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4105 [Release] Pin upstreams for release 0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4095 Add pierDipi to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4102 Apply gosec and unparam to the codebase
  .golangci.yaml
  cmd/v0.16/broker-cleanup/main.go
  cmd/v0.17/pingsource-cleanup/main.go
  pkg/adapter/mtping/runner.go
  pkg/adapter/v2/cloudevents.go
  pkg/apis/duck/v1/fuzzer.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  pkg/apis/sources/v1alpha2/container_validation.go
  pkg/apis/sources/v1beta1/container_validation.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/source/crd/crd.go
  pkg/reconciler/source/duck/duck.go
  pkg/reconciler/source/duck/resources/eventtype.go
  pkg/reconciler/subscription/subscription.go
  pkg/tracing/setup.go
Labels: approved, cla: yes, lgtm, size/L

#4093 Use WaitForPodRunning instead of WaitForResourceReady on pods
  test/lib/duck/resource_checks.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4110 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
Labels: approved, cla: yes, lgtm, size/M

#4107 Fix metrics port mismatch between svc and deployment in broker manifests
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4109 adding test grid and fixing go doc link
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#4115 fix exponential backoff bug in RetryConfigFromDeliverySpec()
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4117 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4116 backporting fix for default exponential backoff calculation
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4112 Set check retry function
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
  test/e2e/helpers/broker_redelivery_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4114 [release-0.17] Set check retry function
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
  test/e2e/helpers/broker_redelivery_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4118 Add aliok to approvers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4156 Fix broken markdown links
  docs/decisions/broker-trigger.md
Labels: approved, cla: yes, lgtm, size/XS

#4123 [Automated] Fix misspellings
  config/core/deployments/webhook.yaml
  docs/decisions/broker-trigger.md
  docs/planning/bug_triage.md
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S
