Repository knative/eventing, pull requests merged in 2020-12, with the labels that each got.

#4618 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/hack/shell/project.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4621 integrate the gopath hacks to allow for codegen anywhere
  hack/update-codegen.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4625 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4636 Add newline to GetGenericObject log line in testing
  test/lib/duck/resource_getters.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4607 feat/perf-test: update README and broker-imc benchmark
  test/performance/README.md
  test/performance/benchmarks/broker-imc/200-broker-perf.yaml
  test/performance/benchmarks/broker-imc/continuous/200-broker-imc.yaml
  test/performance/benchmarks/broker-imc/dev.config
  test/performance/benchmarks/broker-imc/prod.config
  test/performance/benchmarks/channel-imc/dev.config
  test/performance/benchmarks/channel-imc/prod.config
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4640 Add soft Pod anti-affinity to IMC dispatchers
  config/channels/in-memory-channel/deployments/dispatcher.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4642 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#4644 fix illegal byte sequence on Mac when running e2e tests
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4622 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#4647 add tests using k8s 1.20
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4648 Revert "add tests using k8s 1.20"
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4639 [Automated] Format markdown
  test/performance/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4650 Fix spec issue as discussed in #4057
  docs/spec/channel.md
  pkg/apis/duck/v1/channelable_types.go
Labels: approved, cla: yes, lgtm, size/S

#4653 Bump k8s deps to 0.18.12 and drop LeaderElection patch
  go.mod
  go.sum
  hack/k8s-client-go.patch
  hack/update-deps.sh
  hack/update-k8s-deps.sh
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4656 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/source/source_labels.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/knative.dev/pkg/test/upgrade/functions.go
  vendor/knative.dev/pkg/test/upgrade/private_types.go
  vendor/knative.dev/pkg/test/upgrade/steps.go
  vendor/knative.dev/pkg/test/upgrade/suite_execution.go
  vendor/knative.dev/pkg/test/upgrade/types.go
  vendor/knative.dev/pkg/test/upgrade/vars.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4660 [Automated] Format markdown
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/S

#4661 [0.19] Backport https://github.com/knative/pkg/pull/1963
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#4663 Update test/conformance/README
  test/conformance/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4664 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#4665 [Automated] Format markdown
  test/conformance/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4666 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4670 Remove the field spec.replicas=1 for deployments
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/webhook.yaml
  config/sugar/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4668 Fix module usage of vegeta and bump version
  go.mod
  go.sum
  test/performance/infra/sender/http_load_generator.go
  test/performance/infra/sender/http_load_generator_test.go
  third_party/VENDOR-LICENSE/github.com/tsenart/vegeta/v12/lib/LICENSE
  vendor/github.com/mailru/easyjson/.gitignore
  vendor/github.com/mailru/easyjson/.travis.yml
  vendor/github.com/mailru/easyjson/Makefile
  vendor/github.com/mailru/easyjson/README.md
  vendor/github.com/mailru/easyjson/go.mod
  vendor/github.com/mailru/easyjson/helpers.go
  vendor/github.com/mailru/easyjson/raw.go
  vendor/github.com/tsenart/vegeta/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/LICENSE
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/github.com/tsenart/vegeta/v12/lib/attack_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/histogram.go
  vendor/github.com/tsenart/vegeta/v12/lib/metrics.go
  vendor/github.com/tsenart/vegeta/v12/lib/pacer.go
  vendor/github.com/tsenart/vegeta/v12/lib/reporters.go
  vendor/github.com/tsenart/vegeta/v12/lib/results.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/target.schema.json
  vendor/github.com/tsenart/vegeta/v12/lib/targets.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/util_fuzz.go
  vendor/modules.txt
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XXL

#4652 Implement #4057 Channeleable.Delivery
  pkg/apis/messaging/v1/channel_template_types.go
  pkg/apis/messaging/v1/zz_generated.deepcopy.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/resources/channel.go
  pkg/reconciler/mtbroker/resources/channel.go
  pkg/reconciler/parallel/resources/channel.go
  pkg/reconciler/sequence/resources/channel.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/channel.go
  pkg/reconciler/testing/v1/inmemorychannel.go
  test/e2e/channel_dls_test.go
  test/e2e/helpers/channel_dls_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4676 Use the ko 0.6.0 release
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4675 Implement ReadOnlyInterface in IMC dispatcher
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: approved, cla: yes, kind/bug, lgtm, size/S

#4677 Prepare for splitting configmap package.
  cmd/mtbroker/filter/main.go
  cmd/mtbroker/ingress/main.go
  go.mod
  go.sum
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  vendor/knative.dev/pkg/configmap/informer/informed_watcher.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/mako/config/slack.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4680 Channel single event helper, send events via sendeventtoaddressable
  test/e2e/helpers/channel_single_event_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4681 [Automated] Update actions
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4673 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/nostackdriver.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/stackdriver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4686 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS
