Repository knative/eventing, pull requests merged in 2020-08, with the labels that each got.

#3768 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#3767 Retry on conflict in TestChannelSpec
  test/conformance/helpers/channel_spec_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3776 Do not fail when subscription already exists
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3779 Migrate inmemorychannel reconciler to use messaging.* v1 resources
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/controller_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/controller/resources/service.go
  pkg/reconciler/inmemorychannel/controller/resources/service_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/testing/v1/inmemorychannel.go
Labels: approved, cla: yes, lgtm, size/L

#3780 Now eventTracker.Cleanup() is invoked behind the hood
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/helpers/channel_header_single_event_helper.go
  test/conformance/helpers/tracing_test_helper.go
  test/e2e/helpers/broker_channel_flow_helper.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/e2e/helpers/broker_redelivery_helper.go
  test/e2e/helpers/broker_test_helper.go
  test/e2e/helpers/channel_chain_test_helper.go
  test/e2e/helpers/channel_defaulter_test_helper.go
  test/e2e/helpers/channel_dls_test_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/e2e/helpers/channel_single_event_helper.go
  test/e2e/helpers/parallel_test_helper.go
  test/e2e/helpers/sequence_test_helper.go
  test/e2e/helpers/trigger_no_broker_test_helper.go
  test/e2e/source_api_server_v1alpha2_test.go
  test/e2e/source_api_server_v1beta1_test.go
  test/e2e/source_container_v1alpha2_test.go
  test/e2e/source_container_v1beta1_test.go
  test/e2e/source_ping_test.go
  test/e2e/source_sinkbinding_v1alpha1_test.go
  test/e2e/source_sinkbinding_v1alpha2_test.go
  test/e2e/source_sinkbinding_v1beta1_test.go
  test/e2e/trigger_dependency_annotation_test.go
  test/lib/recordevents/event_info_store.go
  test/lib/recordevents/event_info_store_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3778 Skip the subtests in strict mode for ComponentsTestRunner
  test/conformance/main_test.go
  test/e2e-conformance-tests.sh
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3787 Migrate sequence reconciler to use messaging.* v1 resources
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/controller_test.go
  pkg/reconciler/sequence/resources/channel.go
  pkg/reconciler/sequence/resources/subscription.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
Labels: approved, cla: yes, lgtm, size/L

#3790 fix: spell error
  pkg/apis/sources/v1beta1/ping_types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#3794 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3788 Migrate parallel reconciler to use messaging.* v1 resources
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/parallel/controller_test.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/parallel/resources/channel.go
  pkg/reconciler/parallel/resources/subscription.go
Labels: approved, cla: yes, lgtm, size/L

#3795 Add anti-affinity to our control plane deployments
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/M

#3813 Adding permission to view binding APIs
  config/core/roles/clusterrole-namespaced.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3807 Wait Trigger ready in broker control plane conformance test
  test/conformance/helpers/broker_control_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3803 Fix ChannelableCombined and SubscribableTypes for v1 migration
  pkg/apis/duck/v1alpha1/channelable_combined_types.go
  pkg/apis/duck/v1alpha1/channelable_combined_types_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types_test.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/L

#3770 Regroup additional printer columns
  config/channels/in-memory-channel/300-in-memory-channel.yaml
  config/core/resources/apiserversource.yaml
  config/core/resources/broker.yaml
  config/core/resources/channel.yaml
  config/core/resources/containersource.yaml
  config/core/resources/parallel.yaml
  config/core/resources/pingsource.yaml
  config/core/resources/sequence.yaml
  config/core/resources/sinkbindings.yaml
  config/core/resources/subscription.yaml
  config/core/resources/trigger.yaml
  docs/spec/sources.md
Labels: approved, cla: yes, lgtm, size/L

#3815 Adding ttlSecondsAfterFinished to broker clean up…
  config/post-install/v0.16.0/broker-cleanup.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3762 fix bad context key in v2/adapter
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_test.go
Labels: approved, cla: yes, lgtm, size/M

#3814 Add sources and bindings to edit view aggregation
  config/core/roles/clusterrole-namespaced.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3817 pingsource v1beta1 e2e tests
  pkg/apis/sources/v1beta1/ping_lifecycle.go
  pkg/apis/sources/v1beta1/register.go
  pkg/apis/sources/v1beta1/register_test.go
  pkg/reconciler/testing/pingsource.go
  test/e2e/source_ping_v1beta1_test.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3786 Add community contact rotation for Eventing.
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/M

#3818 Pin knative/pkg and knative/test-infra to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3820 Clean-up of old borker deployments…
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
Labels: approved, cla: yes, lgtm, size/L

#3822 Adding Copyright headers for the hpa file
  config/brokers/mt-channel-broker/deployments/hpa.yaml
Labels: approved, cla: yes, lgtm, size/S

#3824 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3829 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3828 Test Client now has a Cleanup method
  test/lib/client.go
  test/lib/recordevents/event_info_store.go
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3833 Remove unused variables from ApiServerSource Reconciler
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
Labels: approved, cla: yes, lgtm, size/S

#3837 remove pingsource v1alpha1
  cmd/webhook/main.go
  config/core/resources/pingsource.yaml
  pkg/apis/sources/v1alpha1/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha1/implements_test.go
  pkg/apis/sources/v1alpha1/ping_conversion.go
  pkg/apis/sources/v1alpha1/ping_conversion_test.go
  pkg/apis/sources/v1alpha1/ping_defaults.go
  pkg/apis/sources/v1alpha1/ping_defaults_test.go
  pkg/apis/sources/v1alpha1/ping_lifecycle.go
  pkg/apis/sources/v1alpha1/ping_lifecycle_test.go
  pkg/apis/sources/v1alpha1/ping_types.go
  pkg/apis/sources/v1alpha1/ping_types_test.go
  pkg/apis/sources/v1alpha1/ping_validation.go
  pkg/apis/sources/v1alpha1/ping_validation_test.go
  pkg/apis/sources/v1alpha1/register.go
  pkg/apis/sources/v1alpha1/register_test.go
  pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_pingsource.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/pingsource.go
  pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/sources/v1alpha1/interface.go
  pkg/client/informers/externalversions/sources/v1alpha1/pingsource.go
  pkg/client/injection/informers/sources/v1alpha1/pingsource/fake/fake.go
  pkg/client/injection/informers/sources/v1alpha1/pingsource/pingsource.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/stub/reconciler.go
  pkg/client/listers/sources/v1alpha1/expansion_generated.go
  pkg/client/listers/sources/v1alpha1/pingsource.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/pingsource.go
  pkg/reconciler/testing/v1/listers.go
  pkg/reconciler/testing/v1beta1/listers.go
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#3834 Poll for EventTypes, rather than assume they are available as soon as…
  test/e2e/source_api_server_v1alpha2_test.go
  test/e2e/source_api_server_v1beta1_test.go
  test/e2e/source_ping_test.go
  test/e2e/source_ping_v1beta1_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3844 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3848 kubectl explain for Broker
  config/core/resources/broker.yaml
Labels: approved, cla: yes, lgtm, size/L

#3849 kubectl explain for PingSource
  config/core/resources/pingsource.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3845 kubectl explain for Trigger
  config/core/resources/trigger.yaml
  pkg/apis/eventing/v1/broker_types.go
  pkg/apis/eventing/v1/trigger_types.go
Labels: approved, cla: yes, lgtm, size/M

#3831 delay when to shutdown the mtping adapter
  cmd/mtping/main.go
  go.mod
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/context.go
  pkg/adapter/mtping/context_test.go
  pkg/adapter/mtping/runner.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/pingsource/resources/mt_receive_adapter.go
  pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3855 Remove required broker.status.address.url
  config/core/resources/broker.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3851 kubectl explain for APIServerSource
  config/core/resources/apiserversource.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3836 add post 017 job to remove pingsource finalizer
  cmd/v0.17/pingsource-cleanup/README.md
  cmd/v0.17/pingsource-cleanup/injection.go
  cmd/v0.17/pingsource-cleanup/main.go
  config/post-install/v0.17.0/dummy.go
  config/post-install/v0.17.0/pingsource-cleanup.yaml
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#3846 kubectl explain for sinkbindings
  config/core/resources/sinkbindings.yaml
Labels: approved, cla: yes, lgtm, size/L

#3847 kubectl explain for Subscription
  config/core/resources/subscription.yaml
Labels: approved, cla: yes, lgtm, size/L

#3857 kubectl explain for EventType
  config/core/resources/eventtype.yaml
  pkg/apis/eventing/v1beta1/eventtype_types.go
Labels: approved, cla: yes, lgtm, size/M

#3870 add channel v1 duck type to spec
  docs/spec/channel.md
Labels: approved, cla: yes, lgtm, size/M

#3884 Remove the old release-0.16 pre- and post- install jobs.
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3887 Force the latest version to be v0.16.1.
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3879 Adding small test for util
  pkg/utils/headers_test.go
Labels: approved, cla: yes, lgtm, size/M

#3872 Add docs on how to run conf tests against preexisting broker
  test/conformance/README.md
  test/conformance/broker_data_plane_test.go
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3882 unpin knative deps for post-0.17 release
  go.mod
  go.sum
  hack/release.sh
  hack/update-deps.sh
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/reconciler.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/kmp/diff.go
  vendor/knative.dev/pkg/kmp/reporters.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#3889 Remove outdated Broker docs
  docs/broker/README.md
  docs/broker/example_brokers.yaml
  docs/broker/example_triggers.yaml
Labels: approved, cla: yes, lgtm, size/L

#3880 Remove deprecated and have only the fqn for injection
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/trigger_types.go
  pkg/apis/eventing/v1beta1/trigger_validation.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  pkg/reconciler/sugar/filters_test.go
  pkg/reconciler/sugar/labels.go
  pkg/reconciler/sugar/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#3871 Migrate channel reconciler to use messaging.* v1 resources
  pkg/apis/duck/v1alpha1/channelable_combined_types.go
  pkg/apis/duck/v1alpha1/channelable_combined_types_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion.go
  pkg/apis/duck/v1alpha1/subscribable_types_conversion_test.go
  pkg/apis/duck/v1alpha1/subscribable_types_test.go
  pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/channel/controller_test.go
  pkg/reconciler/channel/resources/channel.go
  pkg/reconciler/testing/v1/channel.go
  test/conformance/helpers/channel.go
  test/conformance/helpers/channel_status_subscriber_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#3894 leverage source config watcher in PingSource controller
  pkg/adapter/v2/config.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/controller_test.go
  pkg/reconciler/pingsource/pingsource.go
Labels: approved, cla: yes, lgtm, size/L

#3793 Setting IMC/v1 as default
  config/core/configmaps/default-broker-channel.yaml
  config/core/configmaps/default-channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3893 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3897 do not use resp if it fails, use 0 instead
  pkg/mtbroker/filter/filter_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#3901 cp 3897
  pkg/mtbroker/filter/filter_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#3900 fix typo in the transformer-pod name
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3905 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#3916 kubectl explain for Channel
  config/core/resources/channel.yaml
Labels: approved, cla: yes, lgtm, size/L

#3869 kubectl explain for sequence
  config/core/resources/sequence.yaml
Labels: approved, cla: yes, lgtm, size/L

#3892 kubectl explain for parallel
  config/core/resources/parallel.yaml
Labels: approved, cla: yes, lgtm, size/L

#3918 broker conformance: Add wait for service endpoint (transformer pod)
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3915 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#3906 retry on webhook failures
  test/lib/duck/resource_getters.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3895 Add a job for migrating sinkbindings and containersource storage versions to v1beta1
  config/pre-install/v0.18.0/clusterrole.yaml
  config/pre-install/v0.18.0/containersource.yaml
  config/pre-install/v0.18.0/dummy.go
  config/pre-install/v0.18.0/serviceaccount.yaml
  config/pre-install/v0.18.0/sinkbindings.yaml
  config/pre-install/v0.18.0/storage-version-migration.yaml
Labels: approved, cla: yes, lgtm, size/L

#3914 Pingsource crontick minor enhancements #3913
  pkg/adapter/mtping/runner.go
Labels: approved, cla: yes, lgtm, size/S

#3926 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#3928 Release preinstall job yaml too
  hack/release.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3859 kubectl explain for ContainerSource
  config/core/resources/containersource.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#3899 Flags to configure eventing upgrade tests forwarder (ksvc)
  test/upgrade/README.md
  test/upgrade/prober/prober.go
  test/upgrade/prober/prober_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3932 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#3935 revert change to get PingSource specs from ConfigMaps
  cmd/mtping/main.go
  config/core/roles/pingsource-mt-adapter-clusterrole.yaml
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/controller.go
  pkg/adapter/mtping/controller_test.go
  pkg/adapter/mtping/pingsource.go
  pkg/adapter/mtping/pingsource_test.go
  pkg/reconciler/pingsource/controller.go
Labels: approved, cla: yes, lgtm, size/L

#3934 Refactor broker data plane consumer tests conf tests
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3930 Migrate Subscription reconciler to use messaging.* v1 resources
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/controller_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/service.go
  pkg/reconciler/testing/v1/subscription.go
Labels: approved, cla: yes, lgtm, size/XL

#3927 Use preinstall 0.18 in upgrade tests
  config/pre-install/v0.18.0/storage-version-migration.yaml
  test/e2e-common.sh
  test/e2e-upgrade-tests.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3943 Alias clusterrole verbs for 0.18.0 pre-install
  config/pre-install/v0.18.0/clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/M

#3940 revert change to get PingSource specs from ConfigMaps
  cmd/mtping/main.go
  config/core/roles/pingsource-mt-adapter-clusterrole.yaml
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/controller.go
  pkg/adapter/mtping/controller_test.go
  pkg/adapter/mtping/pingsource.go
  pkg/adapter/mtping/pingsource_test.go
  pkg/reconciler/pingsource/controller.go
Labels: approved, cla: yes, lgtm, size/L

#3919 Revert "Remove deprecated and have only the fqn for injection (#3880)"
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/trigger_types.go
  pkg/apis/eventing/v1beta1/trigger_validation.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  pkg/reconciler/sugar/filters_test.go
  pkg/reconciler/sugar/labels.go
  pkg/reconciler/sugar/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#3948 backport 3945 to .16
  pkg/apis/flows/v1/parallel_lifecycle.go
  pkg/apis/flows/v1/parallel_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/M

#3942 switch storage for containersource and sinkbinding to v1beta1
  config/core/resources/containersource.yaml
  config/core/resources/sinkbindings.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3946 fix issue 3945
  pkg/apis/flows/v1/parallel_lifecycle.go
  pkg/apis/flows/v1/parallel_lifecycle_test.go
Labels: approved, cla: yes, lgtm, size/M

#3944 Pingsource crontick minor enhancements #3913 (#3914)
  pkg/adapter/mtping/runner.go
Labels: approved, cla: yes, lgtm, size/S

#3947 backport issue 3945 to .17
  pkg/apis/flows/v1/parallel_lifecycle.go
  pkg/apis/flows/v1/parallel_lifecycle_test.go
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3885 Add explicit content encoding to event-senders in broker conf test
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3953 Fix another flake: If resource fails with alreadyexists, fetch it
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#3956 Updating broker to be v1
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3955 Revert "Force the latest version to be v0.16.1. (#3887)"
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3830 Use apis.HTTP()
  pkg/apis/flows/v1/parallel_lifecycle_test.go
  pkg/apis/flows/v1/sequence_lifecycle_test.go
  pkg/apis/flows/v1beta1/parallel_lifecycle_test.go
  pkg/apis/flows/v1beta1/sequence_lifecycle_test.go
  pkg/apis/sources/v1alpha1/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha1/sinkbinding_conversion_test.go
  pkg/apis/sources/v1alpha2/apiserver_conversion_test.go
  pkg/apis/sources/v1alpha2/container_conversion_test.go
  pkg/apis/sources/v1alpha2/ping_conversion_test.go
  pkg/apis/sources/v1beta1/apiserver_lifecycle_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/pingsource/pingsource_test.go
  test/conformance/helpers/channel_spec_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#3958 Updating broker to be v1
  test/e2e/broker_redelivery_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#3961 Fix go vet errors
  pkg/adapter/mtping/runner_test.go
Labels: approved, cla: yes, lgtm, size/XS

#3962 introduce a MAX_TTL env variable. fix 3524
  cmd/mtbroker/ingress/main.go
Labels: approved, cla: yes, lgtm, size/XS

#3954 introducing the test observer
  pkg/test/observer/doc.go
  pkg/test/observer/eventlog.go
  pkg/test/observer/http-vent/doc.go
  pkg/test/observer/http-vent/http.go
  pkg/test/observer/observation.go
  pkg/test/observer/observer.go
  pkg/test/observer/recorder-collector/collector.go
  pkg/test/observer/recorder-collector/doc.go
  pkg/test/observer/recorder-vent/constructor.go
  pkg/test/observer/recorder-vent/doc.go
  pkg/test/observer/recorder-vent/recorder.go
  pkg/test/observer/writer-vent/doc.go
  pkg/test/observer/writer-vent/writer.go
Labels: approved, cla: yes, lgtm, size/XL

#3964 drop eventing/pkg/logger and use pkg/logger
  pkg/adapter/mtping/pingsource.go
  pkg/adapter/mtping/runner_test.go
  pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1alpha2/sinkbinding_lifecycle.go
  pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  pkg/duck/subscriber.go
  pkg/logging/logging.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/containersource/containersource.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/mtbroker/config.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/source/config_watcher.go
  pkg/reconciler/source/crd/crd.go
  pkg/reconciler/source/duck/duck.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/sugar/namespace/namespace.go
  pkg/reconciler/sugar/trigger/controller.go
  pkg/utils/cache/persisted_store.go
Labels: approved, cla: yes, lgtm, size/L

#3966 Enqueue Triggers on Broker changes without Tracker
  pkg/reconciler/mtbroker/trigger/controller.go
  pkg/reconciler/mtbroker/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#3968 [release-0.17] Enqueue Triggers on Broker changes (#3966)
  pkg/reconciler/mtbroker/trigger/controller.go
  pkg/reconciler/mtbroker/trigger/trigger.go
Labels: approved, cla: yes, lgtm, size/M

#3896 First attempt to explain how config works in receive adapters
  docs/source/receive-adapter.md
Labels: approved, cla: yes, lgtm, size/L

#3941 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/testing/util.go
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/infra-library.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#3972 [master] Update GitHub Actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#3971 Retry channel spec update in conformance tests
  test/conformance/helpers/channel_spec_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#3975 remove the single-tenant PingSource adapter
  cmd/ping/kodata/HEAD
  cmd/ping/kodata/LICENSE
  cmd/ping/kodata/VENDOR-LICENSE
  cmd/ping/kodata/refs
  cmd/ping/main.go
  config/200-pingsource-adapter-clusterrole.yaml
  config/core/deployments/controller.yaml
  config/core/roles/pingsource-adapter-clusterrole.yaml
  pkg/adapter/ping/adapter.go
  pkg/adapter/ping/adapter_test.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/pingsource/resources/mt_receive_adapter.go
  pkg/reconciler/pingsource/resources/mt_receive_adapter_test.go
  pkg/reconciler/pingsource/resources/receive_adapter.go
  pkg/reconciler/pingsource/resources/receive_adapter_test.go
  pkg/reconciler/pingsource/resources/role_binding.go
  pkg/reconciler/pingsource/resources/role_binding_test.go
  pkg/reconciler/testing/pingsource.go
  test/e2e/source_ping_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL
