Repository knative/eventing, pull requests merged in 2020-10, with the labels that each got.

#4164 Add tommyreddad to reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4181 [Automated] Update actions
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/L

#4160 clean up redundancies code with knative/pkg
  cmd/sendevent/main.go
  pkg/channel/message_receiver_test.go
  pkg/mtbroker/ingress/ingress_handler.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/controller/resources/service.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/names/names.go
  pkg/reconciler/names/names_test.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/conformance/helpers/broker_tracing_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/L

#4168 Set initialDelaySeconds to 20 on webhook livenessProbe
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4187 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#4190 Just alias the interface and drop unimplemented methods.
  pkg/adapter/v2/util/crstatusevent/eventsstatus_test.go
  pkg/duck/listable_test.go
Labels: approved, cla: yes, lgtm, size/M

#4173 Revert the "Revert "Remove deprecated annotation"" PR
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/trigger_types.go
  pkg/apis/eventing/v1beta1/trigger_validation.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  pkg/reconciler/sugar/filters_test.go
  pkg/reconciler/sugar/labels.go
  pkg/reconciler/sugar/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#4191 Some final touches for today in fakes, etc
  pkg/adapter/mtping/adapter_test.go
  pkg/adapter/v2/util/crstatusevent/eventsstatus_test.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/message_dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/M

#4194 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#4197 Add zhongduo (Jimmy Lin) as a reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4193 [Automated] Format markdown
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/S

#4198 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#4154 enable source crd test
  pkg/reconciler/source/crd/crd_test.go
  pkg/reconciler/testing/customresourcedefinition.go
  pkg/reconciler/testing/factory.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4199 Add tests to sequence validation
  pkg/apis/flows/v1/sequence_validation.go
  pkg/apis/flows/v1/sequence_validation_test.go
  pkg/apis/flows/v1beta1/sequence_types_test.go
  pkg/apis/flows/v1beta1/sequence_validation.go
  pkg/apis/flows/v1beta1/sequence_validation_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#4209 Add tests to labels
  pkg/reconciler/apiserversource/resources/lavels_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4210 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4207 Increase code coverage for reconciler/sugar
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/sugar/filters_test.go
  pkg/reconciler/sugar/labels_test.go
  pkg/reconciler/sugar/resources/broker_test.go
  pkg/reconciler/sugar/resources/labels_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4216 Reject negative Retry config
  pkg/apis/duck/v1/delivery_types.go
  pkg/apis/duck/v1/delivery_types_test.go
  pkg/apis/duck/v1beta1/delivery_types.go
  pkg/apis/duck/v1beta1/delivery_types_test.go
Labels: approved, cla: yes, lgtm, size/M

#4126 SinkTimeout#4056
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  pkg/adapter/mtping/runner.go
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
  pkg/adapter/v2/config.go
  pkg/adapter/v2/config_test.go
  pkg/adapter/v2/main.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/pingsource/resources/receive_adapter.go
  pkg/reconciler/pingsource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#4220 Rename lavels_test.go -> labels_test.go
  pkg/reconciler/apiserversource/resources/labels_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4217 Use v1 to get addressable URI in tests
  test/lib/duck/resource_inspectors.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4215 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4222 [0.18] backport 4168
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4223 [0.17] backport 4168 to .17
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4225 [0.16] backport 4168 to .16
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4226 Added log on completed assertions in EventInfoStore
  test/lib/recordevents/event_info_store.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4227 SinkTimeout#4056 Backport PR4126
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  pkg/adapter/mtping/runner.go
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
  pkg/adapter/v2/config.go
  pkg/adapter/v2/config_test.go
  pkg/adapter/v2/main.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/pingsource/resources/receive_adapter.go
  pkg/reconciler/pingsource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#4228 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/helpers/dryrun.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/mako/config/environment.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/main.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4234 Http -> HTTP conversion
  test/performance/infra/sender/http_load_generator.go
  test/test_images/performance/main.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/S

#4236 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/binding_types.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4237 enable codecoverage reports
  .codecov.yaml
Labels: approved, cla: yes, lgtm, size/S

#3917 use drainer from pkg instead of our own health
  pkg/health/probes.go
  pkg/health/probes_test.go
  pkg/kncloudevents/message_receiver.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/ingress/ingress_handler.go
Labels: approved, cla: yes, lgtm, size/L

#4239 add badge for motivation
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#4240 Use correct linear backoff algorithm in RetryConfigFromDeliverySpec
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/S

#4245 Remove trailing whitespace
  .github/ISSUE_TEMPLATE/feature-request.md
  config/core/configmaps/logging.yaml
  config/core/resources/apiserversource.yaml
  config/core/resources/pingsource.yaml
  config/core/resources/sinkbindings.yaml
  config/pre-install/v0.18.0/apiserversource.yaml
  test/markdown-lint-config.rc
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4246 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#4247 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/fuzzer.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/mako/analyzer.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/cluster.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4243 Add tayarani as reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4260 Added downstream test with eventing-kafka
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/M

#4258 Fixing some wording
  test/test_images/performance/mako.config
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/XS

#4261 Removed downstream check for eventing-contrib
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/M

#4263 Fix Http=>HTTP and other stuff
  cmd/mtbroker/ingress/main.go
  pkg/adapter/v2/main_message.go
  pkg/adapter/v2/main_message_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_receiver.go
  pkg/inmemorychannel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/message_receiver.go
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
  pkg/kncloudevents/utils.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/ingress/ingress_handler.go
  pkg/mtbroker/ingress/ingress_handler_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4242 fix crash when pingsource adapter is scaled up without any sources
  config/core/deployments/pingsource-mt-adapter.yaml
  pkg/adapter/v2/config.go
  pkg/adapter/v2/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#4265 HTTTP -> HTTP
  cmd/mtbroker/ingress/main.go
  pkg/adapter/v2/main_message.go
  pkg/channel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/message_sender.go
  pkg/mtbroker/filter/filter_handler.go
  pkg/mtbroker/ingress/ingress_handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#4230 [release-0.18] Replacing port-forwarding with k8s events in recordevents
  go.mod
  test/conformance/helpers/broker_control_plane_test_helper.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_status_subscriber_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing_test_helper.go
  test/e2e/helpers/trigger_no_broker_test_helper.go
  test/lib/client.go
  test/lib/k8s_events.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/event_info_store.go
  test/lib/recordevents/event_info_store_test.go
  test/lib/recordevents/event_log.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/doc.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/lib/recordevents/resources.go
  test/lib/resources/kube.go
  test/test_images/recordevents/eventstore.go
  test/test_images/recordevents/eventstore_test.go
  test/test_images/recordevents/main.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4271 leverage test-infra go_update_deps
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4272 Use the IfNotPresent pull policy.
  test/e2e/source_container_v1alpha2_test.go
  test/e2e/source_container_v1beta1_test.go
  test/e2e/source_sinkbinding_v1alpha1_test.go
  test/e2e/source_sinkbinding_v1alpha2_test.go
  test/e2e/source_sinkbinding_v1beta1_test.go
  test/lib/recordevents/resources.go
  test/lib/resources/kube.go
  test/lib/sender/resources.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4277 Drop the hardcoded cluster.local
  test/e2e/trigger_dependency_annotation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4280 dispatcher should be readonly
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#4278 do not hardcode the URI, use ref instead
  test/e2e/trigger_dependency_annotation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4273 Test eventing on KinD 1.17-1.19
  .github/workflows/kind-e2e.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4266 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/mako/go/quickstore/BUILD
  vendor/github.com/google/mako/internal/go/common/BUILD
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4293 Use the new proper helper from pkg
  cmd/mtbroker/filter/main.go
  cmd/mtbroker/ingress/main.go
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4296 use Source informer instead of conditions
  pkg/apis/eventing/v1/trigger_lifecycle.go
  pkg/reconciler/mtbroker/trigger/controller.go
  pkg/reconciler/mtbroker/trigger/controller_test.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/mtbroker/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#4297 [0.18] backport 4280
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#4298 [0.17] backport 4280
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#4299 [0.16] backport 4280
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#4300 [0.18] use Source informer instead of conditions (#4296)
  pkg/apis/eventing/v1/trigger_lifecycle.go
  pkg/reconciler/mtbroker/trigger/controller.go
  pkg/reconciler/mtbroker/trigger/controller_test.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/mtbroker/trigger/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#4307 Remove test cfg for st-channel-broker
  test/config/st-channel-broker.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4270 Add conversion webhook, CRD for ContainerSource v1
  cmd/webhook/main.go
  config/core/resources/containersource.yaml
  pkg/apis/sources/v1/container_conversion.go
  pkg/apis/sources/v1/container_conversion_test.go
  pkg/apis/sources/v1alpha2/container_conversion.go
  pkg/apis/sources/v1alpha2/container_conversion_test.go
  pkg/apis/sources/v1beta1/container_conversion.go
  pkg/apis/sources/v1beta1/container_conversion_test.go
Labels: approved, cla: yes, lgtm, size/XL

#4291 Reuse recordevents as transformevents
  go.mod
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/lib/recordevents/event_info_store.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/observer/reply.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/resources.go
  test/test_images/recordevents/main.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4311 Add post-build diagnostics.
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/M

#4313 Using recordevents as sequencestepper
  test/e2e/helpers/sequence_test_helper.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/observer/reply.go
  test/lib/recordevents/resources.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4309 Remove transformevents usages
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/e2e/helpers/broker_channel_flow_helper.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/lib/recordevents/resources.go
  test/lib/resources/kube.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4318 remove unused cruft from reconciler split
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/controller.go
  pkg/reconciler/mtbroker/controller_test.go
Labels: approved, cla: yes, lgtm, size/S

#4321 update to k8s.Interface, new test/KubeClient from pkg.
  go.mod
  go.sum
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/helpers/channel_crd_metadata_test_helper.go
  test/conformance/helpers/rbac.go
  test/conformance/helpers/tracing/zipkin.go
  test/e2e/helpers/channel_defaulter_test_helper.go
  test/lib/client.go
  test/lib/creation.go
  test/lib/logexporter.go
  test/lib/operation.go
  test/lib/test_runner.go
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
  test/upgrade/prober/verify.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4326 Use well known config map names, rather than bespoke constants
  pkg/reconciler/apiserversource/controller_test.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
  pkg/reconciler/pingsource/controller_test.go
  test/lib/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4323 test all downstream eventing repos
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/L

#4327 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4316 Port tracing setup code to pkg
  cmd/mtbroker/filter/main.go
  cmd/mtbroker/ingress/main.go
  pkg/adapter/v2/config.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_receiver_test.go
  pkg/configmap/store.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/populate_span_transformer.go
  pkg/kncloudevents/populate_span_transformer_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/tracing/setup.go
  test/test_images/utils.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4329 change the test namespace to zipkin
  pkg/channel/message_receiver_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4317 use PullIfNotPresent so works with kind
  test/e2e/source_sinkbinding_v1_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4330 Remove the dependency on Serving's monitoring.yaml
  .github/workflows/kind-e2e.yaml
  test/config/config-tracing.yaml
  test/config/monitoring.yaml
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/zipkin.go
  test/conformance/helpers/tracing/zipkin_test.go
  test/conformance/helpers/tracing_test_helper.go
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4320 tracing ut
  pkg/tracing/attributes_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#4332 🧽replace resources.SystemNamespace with system.Namespace in e2e-test
  test/conformance/helpers/tracing/zipkin.go
  test/conformance/main_test.go
  test/e2e-common.sh
  test/e2e/helpers/channel_defaulter_test_helper.go
  test/e2e/main_test.go
  test/lib/client.go
  test/lib/resources/variables.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4328 config-br-defaults set delivery spec defaults
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/config/testdata/config-br-defaults.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/eventing/v1/broker_defaults.go
  pkg/apis/eventing/v1/broker_defaults_test.go
  pkg/apis/eventing/v1beta1/broker_defaults.go
  pkg/apis/eventing/v1beta1/broker_defaults_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XL

#4335 Spelling
  config/channels/in-memory-channel/README.md
  config/core/configmaps/leader-election.yaml
  docs/planning/bug_triage.md
  docs/spec/data-plane.md
  pkg/adapter/v2/cloudevents_test.go
  pkg/apis/duck/v1alpha1/subscribable_types.go
  pkg/apis/flows/v1/parallel_lifecycle_test.go
  pkg/apis/flows/v1/sequence_lifecycle_test.go
  pkg/apis/flows/v1beta1/parallel_lifecycle_test.go
  pkg/apis/flows/v1beta1/sequence_lifecycle_test.go
  pkg/apis/messaging/register.go
  pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  pkg/apis/sources/v1alpha2/container_defaults_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/reconciler/inmemorychannel/controller/resources/service_test.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/subscription/subscription.go
  test/README.md
  test/e2e/broker_channel_flow_test.go
  test/e2e/channel_event_transformation_test.go
  test/e2e/helpers/broker_channel_flow_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/lib/recordevents/event_info_store.go
  test/lib/typemeta.go
  test/performance/infra/receiver/receiver.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, needs-ok-to-test, size/M

#4331 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/reconciler.go
  vendor/knative.dev/pkg/apis/duck/README.md
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/two_lane_queue.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/ownerrefable_accessor.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/mako/alerter/github/issue.go
  vendor/knative.dev/pkg/test/mako/config/configmap.go
  vendor/knative.dev/pkg/test/mako/sidecar.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4340 [Automated] Format markdown
  docs/planning/bug_triage.md
Labels: approved, cla: yes, lgtm, size/XS

#4259 Add channel metrics support
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/history_transformer_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
  pkg/channel/metrics.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/stats_reporter.go
  pkg/channel/stats_reporter_test.go
  pkg/channel/swappable/swappable_message_handler.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/utils.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XL

#4333 imc dispatcher securitycontext
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4344 Removed sequence stepper usages
  test/e2e/helpers/parallel_test_helper.go
  test/lib/resources/kube.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4347 Remove filterevents usages
  test/e2e/helpers/parallel_test_helper.go
  test/lib/resources/kube.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4334 Add schedule information in retrieval output for Knative Eventing PingSource
  config/core/resources/pingsource.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4348 Cleanup test_images
  test/test_images/filterevents/main.go
  test/test_images/filterevents/pod.yaml
  test/test_images/sequencestepper/main.go
  test/test_images/sequencestepper/pod.yaml
  test/test_images/transformevents/main.go
  test/test_images/transformevents/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4352 Fix the nolint thingies
  pkg/adapter/mtping/runner.go
  pkg/apis/duck/v1/fuzzer.go
  pkg/reconciler/source/duck/resources/eventtype.go
Labels: approved, cla: yes, lgtm, size/S

#4354 Revert "Cleanup test_images"
  test/test_images/filterevents/main.go
  test/test_images/filterevents/pod.yaml
  test/test_images/sequencestepper/main.go
  test/test_images/sequencestepper/pod.yaml
  test/test_images/transformevents/main.go
  test/test_images/transformevents/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4351 update pkg to latest Oct-20
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/flags/e2e_flags.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4355 [0.17] Port recordevents
  go.sum
  test/conformance/helpers/broker_control_plane_test_helper.go
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_status_subscriber_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing_test_helper.go
  test/e2e/helpers/broker_channel_flow_helper.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/e2e/helpers/parallel_test_helper.go
  test/e2e/helpers/sequence_test_helper.go
  test/e2e/helpers/trigger_no_broker_test_helper.go
  test/lib/client.go
  test/lib/k8s_events.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/event_info_store.go
  test/lib/recordevents/event_info_store_test.go
  test/lib/recordevents/event_log.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/observer/reply.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/doc.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/lib/recordevents/resources.go
  test/lib/resources/kube.go
  test/test_images/recordevents/eventstore.go
  test/test_images/recordevents/eventstore_test.go
  test/test_images/recordevents/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4356 Rename dummy.go for woke
  config/brokers/mt-channel-broker/deployments/placeholder.go
  config/brokers/mt-channel-broker/placeholder.go
  config/brokers/mt-channel-broker/roles/placeholder.go
  config/channels/in-memory-channel/configmaps/placeholder.go
  config/channels/in-memory-channel/deployments/placeholder.go
  config/channels/in-memory-channel/placeholder.go
  config/channels/in-memory-channel/resources/placeholder.go
  config/channels/in-memory-channel/roles/placeholder.go
  config/core/configmaps/placeholder.go
  config/core/deployments/placeholder.go
  config/core/placeholder.go
  config/core/resources/placeholder.go
  config/core/roles/placeholder.go
  config/core/webhooks/placeholder.go
  config/post-install/v0.15.0/placeholder.go
  config/post-install/v0.16.0/placeholder.go
  config/post-install/v0.17.0/placeholder.go
  config/pre-install/v0.16.0/placeholder.go
  config/pre-install/v0.18.0/placeholder.go
  config/sugar/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#4350 Better k8s events log in e2e/conformance tests
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4342 Readiness checks get Pods
  test/lib/duck/resource_checks.go
  test/lib/duck/resource_checks_test.go
  test/lib/duck/resource_getters.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4365 Get rid of \" in favor of backticks
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/subscription/subscription_test.go
  test/e2e_flags.go
  test/flags/parsing.go
  test/lib/recordevents/event_info.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4361 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/testutils/clustermanager/perf-tests/pkg/benchmark.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4358 Cleanup test images
  test/test_images/filterevents/main.go
  test/test_images/filterevents/pod.yaml
  test/test_images/sequencestepper/main.go
  test/test_images/sequencestepper/pod.yaml
  test/test_images/transformevents/main.go
  test/test_images/transformevents/pod.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4370 Improved logging at debug level in filter handler
  pkg/mtbroker/filter/filter_handler.go
Labels: approved, cla: yes, lgtm, size/XS

#4371 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4161 Move sinkbinding WithContext resolver call to Do() function
  go.sum
  pkg/apis/sources/v1/sinkbinding_context.go
  pkg/apis/sources/v1/sinkbinding_context_test.go
  pkg/apis/sources/v1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1/sinkbinding_lifecycle_test.go
  pkg/apis/sources/v1/sinkbinding_types.go
  pkg/apis/sources/v1beta1/sinkbinding_context.go
  pkg/apis/sources/v1beta1/sinkbinding_context_test.go
  pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1beta1/sinkbinding_lifecycle_test.go
  pkg/apis/sources/v1beta1/sinkbinding_types.go
  pkg/reconciler/sinkbinding/controller.go
Labels: approved, cla: yes, lgtm, size/L

#4372 [0.18] Port recordevents updates
  go.mod
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/e2e/helpers/broker_channel_flow_helper.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/e2e/helpers/channel_event_tranformation_test_helper.go
  test/e2e/helpers/parallel_test_helper.go
  test/e2e/helpers/sequence_test_helper.go
  test/lib/recordevents/event_info_store.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/observer/reply.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/resources.go
  test/lib/resources/kube.go
  test/test_images/recordevents/main.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#4373 Publish manually events to avoid event correlator
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/resources.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4324 Enable the Conformance tests via GitHub Actions
  .github/workflows/kind-e2e.yaml
  test/conformance/helpers/broker_data_plane_test_helper.go
  test/conformance/helpers/tracing_test_helper.go
  test/lib/k8s_events.go
  test/lib/operation.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/event_info_store.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4377 Add status markers for sinkbinding in subresourcereconciler
  pkg/reconciler/sinkbinding/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#4379 Use a multiline YAML string to make viewing each individual flag clearer
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#4380 Fix logger usage with proper zap.Error calls
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/observer/reply.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4374 Return when URIResolver is not set to avoid nil pointer reference.
  pkg/apis/sources/v1/sinkbinding_lifecycle.go
Labels: approved, cla: yes, lgtm, size/XS

#4359 Refactor imc dispatcher
  config/channels/in-memory-channel/roles/dispatcher-clusterrole.yaml
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/multichannelfanout/config.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/channel/swappable/swappable_message_handler.go
  pkg/channel/swappable/swappable_message_handler_test.go
  pkg/inmemorychannel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/testing/v1/inmemorychannel.go
Labels: approved, cla: yes, lgtm, size/XXL

#4385 Some nits in our test-infra I've found during a burning debugging session
  test/lib/recordevents/event_info.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/resources.go
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4387 [0.18] Publish manually events to avoid event correlator (#4373)
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/resources.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4386 [0.17] Publish manually events to avoid event correlator (#4373)
  test/lib/recordevents/recorder_vent/constructor.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4383 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4390 Use network helper for service domain
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/controller/resources/service.go
  pkg/reconciler/inmemorychannel/controller/resources/service_test.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/broker_test.go
  pkg/reconciler/mtbroker/trigger/trigger.go
  pkg/reconciler/mtbroker/trigger/trigger_test.go
  pkg/reconciler/names/names.go
  pkg/reconciler/names/names_test.go
Labels: approved, cla: yes, lgtm, size/L

#4366 Remove Knative history extension
  pkg/channel/history_transformer.go
  pkg/channel/history_transformer_test.go
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
  test/conformance/helpers/channel_data_plane_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4392 Remove the outdated method
  go.mod
  go.sum
  pkg/adapter/v2/config.go
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/reconciler.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/source/config_watcher.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/conversion.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4397 Final Json -> JSON in eventing
  go.mod
  go.sum
  pkg/adapter/v2/config.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/source/config_watcher.go
  test/lib/client.go
  test/test_images/utils.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4391 Fix nil-pointer panic on reportError
  pkg/adapter/v2/cloudevents.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4384 [master] Upgrade to latest dependencies
  vendor/k8s.io/code-generator/generate-groups.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4396 Avoid plumbing suffix through tests
  test/conformance/helpers/broker_tracing_test_helper.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
  test/conformance/helpers/tracing/traces_test.go
  test/conformance/helpers/tracing/zipkin.go
  test/conformance/helpers/tracing/zipkin_test.go
  test/conformance/helpers/tracing_test_helper.go
  test/conformance/helpers/uri.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4395 Propagate config-logging in test images
  test/lib/client.go
  test/lib/creation.go
  test/test_images/recordevents/main.go
  test/test_images/utils.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4394 config-logging uses console encoding in tests
  test/config/config-logging.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4399 move fuzzer code to _test files
  pkg/apis/duck/v1/test/fuzzer.go
  pkg/apis/eventing/v1/fuzzer.go
  pkg/apis/eventing/v1/roundtrip_test.go
  pkg/apis/eventing/v1beta1/roundtrip_test.go
  pkg/apis/flows/v1/fuzzer.go
  pkg/apis/flows/v1/roundtrip_test.go
  pkg/apis/flows/v1beta1/roundtrip_test.go
  pkg/apis/messaging/v1/fuzzer.go
  pkg/apis/messaging/v1/roundtrip_test.go
  pkg/apis/messaging/v1beta1/roundtrip_test.go
Labels: approved, cla: yes, lgtm, size/L

#4389 emit a k8s event when dropping events
  test/lib/dropevents/receiver.go
  test/lib/recordevents/observer/observer.go
  test/test_images/recordevents/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4400 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/fuzzer.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4393 [recordevents] Removed EventBroadcaster usage and replaced with manual send
  test/lib/recordevents/event_info.go
  test/lib/recordevents/logger_vent/logger.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/test_images/recordevents/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4382 A few adjustments for actions.
  .github/workflows/kind-e2e.yaml
  test/config/config-tracing.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4403 [0.17] Ported recent test infra improvements
  test/lib/dropevents/receiver.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/logger_vent/logger.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/lib/test_runner.go
  test/test_images/recordevents/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4404 [0.18] Ported recent test infra improvements
  test/lib/dropevents/receiver.go
  test/lib/recordevents/event_info.go
  test/lib/recordevents/logger_vent/logger.go
  test/lib/recordevents/observer/observer.go
  test/lib/recordevents/recorder_vent/constructor.go
  test/lib/recordevents/recorder_vent/recorder.go
  test/lib/recordevents/resources.go
  test/lib/test_runner.go
  test/test_images/recordevents/main.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4401 backport sinkbinding resolver fix
  pkg/apis/sources/v1beta1/sinkbinding_context.go
  pkg/apis/sources/v1beta1/sinkbinding_context_test.go
  pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1beta1/sinkbinding_lifecycle_test.go
  pkg/apis/sources/v1beta1/sinkbinding_types.go
  pkg/reconciler/sinkbinding/controller.go
Labels: approved, cla: yes, lgtm, size/L

#4407 Remove last (again) Json items.
  test/lib/client.go
  test/test_images/utils.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4410 use the new hack repo.
  go.mod
  go.sum
  hack/release.sh
  hack/tools.go
  hack/update-checksums.sh
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  test/e2e-common.sh
  test/performance/performance-tests.sh
  test/presubmit-tests.sh
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/hack/LICENSE
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/hack/shellcheck-presubmit.sh
  vendor/knative.dev/pkg/hack/tools.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hack/update-deps.sh
  vendor/knative.dev/pkg/hack/verify-codegen.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/tracing/config/tracing.go
  vendor/knative.dev/test-infra/scripts/update-test-infra.sh
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4411 Simplify the fake by embedding the interface
  pkg/reconciler/source/config_watcher.go
Labels: approved, cla: yes, lgtm, size/S

#4412 add periodic e2e tests that post to slack on failure
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#4405 fix issue 4375
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/kncloudevents/message_sender.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/M

#4422 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blang/semver/v4/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/github.com/blang/semver/.travis.yml
  vendor/github.com/blang/semver/README.md
  vendor/github.com/blang/semver/package.json
  vendor/github.com/blang/semver/v4/LICENSE
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/blang/semver/v4/json.go
  vendor/github.com/blang/semver/v4/range.go
  vendor/github.com/blang/semver/v4/semver.go
  vendor/github.com/blang/semver/v4/sort.go
  vendor/github.com/blang/semver/v4/sql.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/LICENSE
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/gopkg.in/evanphx/json-patch.v4/errors.go
  vendor/gopkg.in/evanphx/json-patch.v4/merge.go
  vendor/gopkg.in/evanphx/json-patch.v4/patch.go
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/signals/signal.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#4423 Bump go-retryablehttp
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4426 Fix #4425
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/M

#4421 Eventing upgrade tests prober fully configurable
  test/upgrade/probe_test.go
  test/upgrade/prober/config.toml
  test/upgrade/prober/configuration.go
  test/upgrade/prober/forwarder.go
  test/upgrade/prober/prober.go
  test/upgrade/prober/prober_test.go
  test/upgrade/prober/receiver.go
  test/upgrade/prober/sender.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4427 [0.17] Fix #4425
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/M

#4428 [0.18] Fix #4425
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/M

#4431 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4408 Drop TEST_EVENTING_NAMESPACE
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4433 Fix data race in dispatcher.TestNew
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4436 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/knative.dev/pkg/metrics/stackdriver_exporter.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/gke/client.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#4424 [release-0.18] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/configs/v1alpha1/configmappropagation/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/trigger/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1beta1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1beta1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/M

#4435 Dispatcher updates subscriber statuses
  config/channels/in-memory-channel/roles/dispatcher-clusterrole.yaml
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, cla: yes, lgtm, size/L

#4443 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#4442 Reduce a prober test name length to prevent DNS label too long error
  test/upgrade/probe_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS
