Repository knative/eventing, pull requests merged in 2021-02, with the labels that each got.

#4817 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4654 Fix spec #4515
  config/core/resources/broker.yaml
  config/core/resources/trigger.yaml
  docs/spec/broker.md
  pkg/apis/eventing/v1/broker_types.go
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1beta1/trigger_conversion.go
  pkg/apis/eventing/v1beta1/trigger_types.go
  pkg/apis/eventing/v1beta1/trigger_validation.go
  pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
Labels: approved, cla: yes, kind/api-change, kind/enhancement, lgtm, size/L

#4823 [Automated] Format markdown
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/S

#4822 v1beta1.Trigger delivery should be v1.DeliverySpec
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/trigger_conversion.go
  pkg/apis/eventing/v1beta1/trigger_types.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
Labels: approved, cla: yes, lgtm, size/M

#4820 Call Fatal in shared main to propagate error to exit code
  pkg/adapter/v2/main.go
Labels: approved, cla: yes, lgtm, size/S

#4824 remove unused functions
  pkg/reconciler/testing/v1/broker.go
  pkg/reconciler/testing/v1beta1/broker.go
Labels: approved, cla: yes, lgtm, size/M

#4826 fix the link to head
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4829 [Automated] Format markdown
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4830 [#4796] Bump golang lint timeout to 10m
  .golangci.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4838 Use SHOULD for TriggerSpec to keep compatibility
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/XS

#4723 Adding Logline for when a cloudevent has been successfully sent from APIServerSource to the sink
  pkg/adapter/apiserver/delegate.go
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#4841 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4839 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4840 [Automated] Format markdown
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/XS

#4816 Add immutable fields validation to v1beta1 broker
  pkg/apis/eventing/v1beta1/broker_validation.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4828 Change trigger spec to indicate assigned broker should be immutable
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4846 [Automated] Format markdown
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, size/XS

#4850 switch Harwayne with antoineco
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4853 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/resource.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/go.opencensus.io/.travis.yml
  vendor/go.opencensus.io/go.mod
  vendor/go.opencensus.io/go.sum
  vendor/go.opencensus.io/metric/metricexport/reader.go
  vendor/go.opencensus.io/trace/basetypes.go
  vendor/go.opencensus.io/trace/spanstore.go
  vendor/go.opencensus.io/trace/trace.go
  vendor/go.opencensus.io/trace/trace_api.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/SECURITY.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_util.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/internal/grpcutil/target.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/resolver/config_selector.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#4855 Remvoing contrib refs
  DEVELOPMENT.md
  docs/decisions/broker-trigger.md
  docs/spec/overview.md
  test/e2e/helpers/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4854 Latest of kindst image for e2e tests w/ 1.20.2
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4858 Remove json-specific logic useless for binary mode
  pkg/adapter/mtping/runner.go
Labels: approved, cla: yes, lgtm, size/S

#4860 Remove Harwayne from OWNERS.
  OWNERS
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4857 [Automated] Format markdown
  DEVELOPMENT.md
  docs/spec/overview.md
  test/e2e/helpers/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4851 fix(PingSource): event consumer should receive base64-decoded dataBase64
  config/core/resources/pingsource.yaml
  pkg/adapter/mtping/runner.go
  pkg/adapter/mtping/runner_test.go
  pkg/apis/sources/v1beta2/ping_types.go
Labels: approved, cla: yes, lgtm, size/M

#4843 ut for trigger/broker updates check immutable
  pkg/apis/eventing/v1/broker_validation_test.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/eventing/v1beta1/broker_validation_test.go
  pkg/apis/eventing/v1beta1/trigger_validation.go
  pkg/apis/eventing/v1beta1/trigger_validation_test.go
  test/conformance/helpers/broker_control_plane_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4869 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4874 Update deps
  go.mod
  go.sum
  test/rekt/features/middleware_feature.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/doc.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4875 expose ChannelReference in UnknownChannelError
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#4842 tracing fixed for apiserversource
  pkg/adapter/v2/config.go
Labels: approved, cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#4827 Change broker spec to indicate brokerclass should be immutable
  docs/spec/broker.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#4878 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/event_info_matchers.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4879 Updates for kind (newer version and newer images)
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#4877 Setting tracing config for PingSource
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/resources/receive_adapter.go
  pkg/reconciler/pingsource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4883 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4882 s/Veroute/Version
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4885 Remove suffix, since it's already in the PDB kind
  config/core/deployments/webhook-hpa.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4880 Use ConfigAccessor's ToEnvVars method in PingSource
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/controller_test.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/pingsource/resources/receive_adapter.go
  pkg/reconciler/pingsource/resources/receive_adapter_test.go
Labels: approved, cla: yes, lgtm, size/L

#4233 jsonDataLimit#4055
  cmd/webhook/main.go
  config/400-config-ping-defaults.yaml
  config/core/configmaps/default-pingsource.yaml
  pkg/apis/sources/config/ping_defaults.go
  pkg/apis/sources/config/store.go
  pkg/apis/sources/v1alpha2/ping_validation.go
  pkg/apis/sources/v1alpha2/ping_validation_test.go
  pkg/apis/sources/v1beta1/ping_validation.go
  pkg/apis/sources/v1beta1/ping_validation_test.go
  pkg/apis/sources/v1beta2/ping_validation.go
  pkg/apis/sources/v1beta2/ping_validation_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#4888 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4886 [doc] Debugging Knative controllers and friends locally with Intellij Idea
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#4891 [Automated] Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#4890 Adding checkRetry from kafkaChannel
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/L

#4895 [trivial] update default-pingsource configmap checksum
  config/core/configmaps/default-pingsource.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4859 Ported Broker ingress conformance test to the new test framework
  test/rekt/broker_test.go
  test/rekt/features/broker/ingress.go
  test/rekt/features/broker/readyness.go
  test/rekt/features/broker/source_to_sink.go
  test/rekt/features/broker_feature.go
  test/rekt/features/defaults.go
  test/rekt/resources/broker/broker.go
  test/rekt/smoke_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4897 Adding check for -1 status code for the default retry impl
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, cla: yes, lgtm, size/XS

#4900 swap lberk/vaikas shifts for community support
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4845 Add unit tests for parallel_validation_test
  pkg/apis/flows/v1/parallel_validation_test.go
  pkg/apis/flows/v1beta1/parallel_validation_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4978 add more ut coverage
  pkg/reconciler/mtbroker/config.go
  pkg/reconciler/mtbroker/config_test.go
Labels: approved, cla: yes, lgtm, size/M

#4863 Add roadmap for 2021 for Eventing, Eventing Sources and Event Delivery WGs
  docs/roadmap-2021.md
Labels: approved, cla: yes, lgtm, size/L

#4979 refactor for better testability, add ut
  pkg/reconciler/mtbroker/trigger/controller.go
  pkg/reconciler/mtbroker/trigger/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#4980 [Automated] Format markdown
  docs/roadmap-2021.md
Labels: approved, cla: yes, lgtm, size/M

#4908 mtping adapter now cleans up internal cache when it stops leading
  pkg/adapter/mtping/adapter.go
  pkg/adapter/mtping/controller.go
  pkg/adapter/mtping/controller_test.go
Labels: approved, cla: yes, lgtm, size/M

#4992 Add missing singular resource names to sources/sinkbinding crds
  config/core/resources/apiserversource.yaml
  config/core/resources/containersource.yaml
  config/core/resources/pingsource.yaml
  config/core/resources/sinkbindings.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
