Repository knative/eventing, pull requests merged in 2021-08, with the labels that each got.

#5596 Run conformance tests as project admin
  test/conformance/README.md
  test/conformance/broker_tracing_test.go
  test/conformance/channel_addressable_resolver_cluster_role_test.go
  test/conformance/channel_channelable_manipulator_cluster_role_test.go
  test/conformance/channel_crd_metadata_test.go
  test/conformance/channel_tracing_test.go
  test/conformance/create-namespace-rbac.sh
  test/conformance/main_test.go
  test/conformance/source_crd_metadata_test.go
  test/conformance/source_crd_rbac_test.go
  test/conformance/source_crd_registry_test.go
  test/lib/creation.go
  test/lib/recordevents/resources.go
  test/lib/setupclientoptions/sources.go
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5601 Only reconcile CRDs labeled with the duck key/value
  pkg/reconciler/source/crd/controller.go
Labels: approved, cla: yes, lgtm, size/XS

#5625 update deps
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/reconciler.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/subscription/subscription_test.go
  test/conformance/helpers/channel_tracing_test_helper.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5627 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5624 Prevent teardown in ugprade tests on failure
  test/upgrade/prober/prober.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5542 Enable OPTIONS and CloudEvent Webhook headers
  pkg/broker/filter/filter_handler.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
  pkg/channel/message_receiver.go
  pkg/channel/message_receiver_test.go
  test/conformance/helpers/broker_data_plane_test_helper.go
Labels: size/M, approved, lgtm, area/test-and-release, cla: yes

#5629 Fix ci
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  config/core/deployments/webhook.yaml
  config/post-install/storage-version-migrator.yaml
  config/sugar/500-controller.yaml
Labels: size/M, approved, lgtm, cla: yes

#5631 Add tracing support to eventdisplay and heartbeats
  cmd/event_display/main.go
  cmd/event_display/main_test.go
  cmd/heartbeats/main.go
Labels: size/M, approved, lgtm, cla: yes

#5632 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, cla: yes

#5634 Add trace exporting to mt broker
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
Labels: approved, size/XS, lgtm, cla: yes

#5637 Resurrect source spec
  docs/spec/sources.md
Labels: approved, size/L, lgtm, cla: yes

#5641 Be more explicit about the semantic of ceOverrides
  docs/spec/sources.md
Labels: approved, size/XS, lgtm, cla: yes

#5640 Add myself to support roster
  support/ROSTER
Labels: approved, size/XS, lgtm, cla: yes

#5644 Fix deprecation of controller.Run to controller.RunContext
  pkg/reconciler/source/crd/crd.go
Labels: approved, size/XS, lgtm, cla: yes

#5645 remove vaikas from roster
  support/ROSTER
Labels: approved, size/XS, lgtm, cla: yes

#5642 Fix DeadLetterSink on Trigger status
  config/core/resources/trigger.yaml
  docs/eventing-api.md
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/zz_generated.deepcopy.go
  pkg/reconciler/broker/trigger/trigger.go
  pkg/reconciler/testing/v1/trigger.go
Labels: approved, lgtm, size/S, cla: yes

#5650 Use v1 CRD clients in tests
  test/lib/client.go
Labels: approved, size/XS, lgtm, area/test-and-release, cla: yes

#5651 Create a new ListableTracker ctor taking a tracker.Interface
  pkg/duck/listable.go
  pkg/duck/listable_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/trigger/controller.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/subscription_test.go
Labels: size/M, approved, lgtm, cla: yes, kind/cleanup

#5647 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, cla: yes

#5652 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/controller.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/controller.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/controller.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/controller.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/controller.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/controller.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/controller.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/webhook/certificates/controller.go
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/psbinding/README.md
  vendor/knative.dev/pkg/webhook/psbinding/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/conversion/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, cla: yes

#5653 Generate new community contact table
  support/COMMUNITY_CONTACTS.md
  support/ROSTER
  support/support.rotation
Labels: approved, lgtm, size/S, cla: yes

#5656 Plumb through using the `controller.Impl` tracker.
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/trigger/controller.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/eventtype/controller.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sinkbinding/controller.go
  pkg/reconciler/subscription/controller.go
Labels: size/M, approved, lgtm, cla: yes, kind/cleanup

#5658 fixing minor things
  docs/eventing-api.md
  pkg/apis/messaging/v1/channel_types_test.go
  pkg/apis/messaging/v1/in_memory_channel_types.go
  pkg/apis/messaging/v1/in_memory_channel_types_test.go
Labels: approved, size/XS, lgtm, cla: yes

#5659 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, cla: yes

#5655 [IMC] Always consider ObservedGeneration to determine readiness
  pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  pkg/apis/messaging/v1/in_memory_channel_lifecycle_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: approved, lgtm, size/S, cla: yes

#5660 Handful more cleanups
  pkg/adapter/mtping/controller.go
  pkg/adapter/v2/main_injection_test.go
  pkg/apis/sources/v1/sinkbinding_lifecycle_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/trigger/controller.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/containersource/controller.go
  pkg/reconciler/eventtype/controller.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/parallel/controller.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sinkbinding/controller.go
  pkg/reconciler/source/crd/controller.go
  pkg/reconciler/source/duck/controller.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/sugar/namespace/controller.go
  pkg/reconciler/sugar/trigger/controller.go
Labels: size/M, approved, lgtm, cla: yes, kind/cleanup

#5661 Use `controller.NewContext`
  pkg/reconciler/source/duck/controller.go
Labels: approved, size/XS, lgtm, cla: yes, kind/cleanup

#5662 Make usage of GetConditionSet, rather than direct access
  pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
Labels: approved, size/XS, lgtm, cla: yes

#5667 [Broker] Always consider ObservedGeneration to determine readiness
  pkg/apis/eventing/v1/broker_lifecycle.go
  pkg/apis/eventing/v1/broker_lifecycle_test.go
  pkg/reconciler/broker/trigger/trigger.go
  test/rekt/features/broker/control_plane.go
Labels: approved, lgtm, size/S, area/test-and-release, cla: yes

#5680 Add heartbeats image to released images
  config/tools/heartbeats/heartbeats.yaml
  hack/generate-yamls.sh
Labels: size/M, approved, lgtm, area/test-and-release, cla: yes

#5673 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, size/XS, lgtm, cla: yes

#5682 Validate broker spec config immutable
  pkg/apis/eventing/v1/broker_validation.go
  pkg/apis/eventing/v1/broker_validation_test.go
Labels: size/M, approved, lgtm, cla: yes

#5683 Add ability to specify heartbeat durations as a time.Duration
  cmd/heartbeats/main.go
Labels: approved, lgtm, size/S, cla: yes
