Repository knative/eventing, pull requests merged in 2021-10, with the labels that each got.

#5770 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/101-rbac.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: size/M, approved, lgtm, cla: yes

#5773 Forward prefer: reply header for brokers
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
Labels: size/M, approved, lgtm, cla: yes

#5777 Validate DeliverySpec in Channels & Subscriptions
  pkg/apis/messaging/v1/channel_validation.go
  pkg/apis/messaging/v1/channel_validation_test.go
  pkg/apis/messaging/v1/subscription_validation.go
  pkg/apis/messaging/v1/subscription_validation_test.go
Labels: approved, size/L, lgtm, cla: yes

#5784 [Post-Install] Go with a more minimal set of permissions
  config/post-install/clusterrole.yaml
Labels: approved, size/XS, lgtm, cla: yes

#5786 Adding finalizers/status subresources to NOOP migrator
  config/post-install/clusterrole.yaml
Labels: approved, lgtm, size/S, cla: yes

#5752 IMC dispatcher custom readiness probe
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/inmemorychannel/message_dispatcher.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/readiness.go
  pkg/reconciler/inmemorychannel/dispatcher/readiness_test.go
Labels: approved, size/L, lgtm, cla: yes
