Repository knative/eventing, pull requests merged in 2021-07, with the labels that each got.

#5556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#5568 Make apiserversource test watch for update events
  test/rekt/features/apiserversource/data_plane.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5551 Add DeadLetterURI to trigger status
  docs/eventing-api.md
  pkg/apis/eventing/v1/trigger_lifecycle.go
  pkg/apis/eventing/v1/trigger_lifecycle_test.go
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/zz_generated.deepcopy.go
  pkg/reconciler/broker/trigger/trigger.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/testing/v1/broker.go
  pkg/reconciler/testing/v1/trigger.go
Labels: approved, cla: yes, lgtm, size/L

#5557 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/S

#5569 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_log.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub_image.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#5575 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5457 apiServerSource now retries sending events
  pkg/adapter/apiserver/events/events.go
  test/rekt/apiserversource_test.go
  test/rekt/features/apiserversource/data_plane.go
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/M

#5583 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5586 drop use of upstream knative.dev/pkg/metric eventing keys
  pkg/broker/filter/stats_reporter.go
  pkg/broker/filter/stats_reporter_test.go
  pkg/broker/ingress/stats_reporter.go
  pkg/broker/ingress/stats_reporter_test.go
  pkg/broker/metrics.go
  pkg/channel/metrics.go
  pkg/channel/stats_reporter.go
  pkg/channel/stats_reporter_test.go
  pkg/metrics/metrics.go
Labels: approved, cla: yes, lgtm, size/L

#5585 [PingSource] disable @every
  pkg/apis/sources/v1/ping_validation.go
  pkg/apis/sources/v1/ping_validation_test.go
  pkg/apis/sources/v1beta2/ping_validation.go
  pkg/apis/sources/v1beta2/ping_validation_test.go
Labels: approved, cla: yes, lgtm, size/L

#5567 tracing fix for APIServerSource and PingSource
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#5587 Move knative.dev/pkg/source.StatsReporter to eventing/pkg/metrics/source.StatsReporting - 1/n
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_message.go
  pkg/adapter/v2/main_message_test.go
  pkg/metrics/metrics.go
  pkg/metrics/source/stats_reporter.go
Labels: approved, cla: yes, lgtm, size/M

#5592 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/controller.go
  pkg/client/injection/reconciler/flows/v1/parallel/controller.go
  pkg/client/injection/reconciler/flows/v1/sequence/controller.go
  pkg/client/injection/reconciler/messaging/v1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/controller.go
  pkg/client/injection/reconciler/messaging/v1/subscription/controller.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/controller.go
  pkg/client/injection/reconciler/sources/v1/containersource/controller.go
  pkg/client/injection/reconciler/sources/v1/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#5594 move source.StatsReporter from knative.dev/pkg
  pkg/metrics/source/stats_reporter.go
  pkg/metrics/source/stats_reporter_test.go
  vendor/knative.dev/pkg/source/doc.go
  vendor/knative.dev/pkg/source/source_labels.go
  vendor/knative.dev/pkg/source/source_stats_reporter.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#5600 Change Result->Reply in comments, left over cruft
  pkg/apis/messaging/v1/subscription_types.go
Labels: approved, cla: yes, lgtm, size/XS

#5603 if no kubeconfig use inclusterconfig test
  test/lib/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5608 Add health endpoint to event_display server
  cmd/event_display/main.go
  cmd/event_display/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#5610 Fix the link to the Working Group page.
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#5602 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5606 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5611 Improve security-related config in yaml files
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#5612 Improve security-related config in more yaml files
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/core/deployments/controller.yaml
  config/post-install/storage-version-migrator.yaml
  config/sugar/500-controller.yaml
Labels: approved, cla: yes, lgtm, size/M

#5613 Revert "if no kubeconfig use inclusterconfig test"
  test/lib/client.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5616 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: approved, cla: yes, lgtm, size/XS

#5615 Fix metrics md page
  docs/metrics.md
Labels: approved, cla: yes, lgtm, size/L
