Repository knative/eventing, pull requests merged in 2021-12, with the labels that each got.

#5943 Fix flaky Retry-After Header Test
  pkg/kncloudevents/message_sender_test.go
Labels: approved, lgtm, size/S, cla: yes

#5947 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, cla: yes

#5948 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm, cla: yes

#5946 Enhance Broker Filter to proxy Response Headers
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
Labels: size/M, approved, lgtm, cla: yes

#5945 CR's name in metrics' label for APIServerSource
  pkg/adapter/apiserver/adapter.go
  pkg/adapter/apiserver/adapter_test.go
  pkg/adapter/apiserver/delegate.go
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
Labels: size/M, approved, lgtm, cla: yes, ok-to-test

#5956 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, cla: yes

#5971 [release-1.0] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm, cla: yes

#5955 Fix channel template spec type for Sequence channel template field
  config/core/resources/sequence.yaml
  go.mod
  go.sum
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  test/rekt/features/parallel/readyness.go
  test/rekt/features/sequence/readyness.go
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/parallel/parallel.go
  test/rekt/resources/parallel/parallel.yaml
  test/rekt/resources/parallel/parallel_test.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/sequence/sequence.yaml
  test/rekt/resources/sequence/sequence_test.go
  test/rekt/smoke_test.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, area/test-and-release, cla: yes

#5978 [release-0.26] Fix channel template spec type for Sequence channel template field
  config/core/resources/sequence.yaml
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  test/rekt/features/parallel/readyness.go
  test/rekt/features/sequence/readyness.go
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/parallel/parallel.go
  test/rekt/resources/parallel/parallel.yaml
  test/rekt/resources/parallel/parallel_test.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/sequence/sequence.yaml
  test/rekt/resources/sequence/sequence_test.go
  test/rekt/smoke_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#5979 [release-0.25] Fix channel template spec type for Sequence channel template field
  config/core/resources/sequence.yaml
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  test/rekt/features/parallel/readyness.go
  test/rekt/features/sequence/readyness.go
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/parallel/parallel.go
  test/rekt/resources/parallel/parallel.yaml
  test/rekt/resources/parallel/parallel_test.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/sequence/sequence.yaml
  test/rekt/resources/sequence/sequence_test.go
  test/rekt/smoke_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#5974 Update MT Broker design doc link to public accessible doc
  docs/broker/README.md
Labels: approved, size/XS, lgtm

#5981 Refactor Retry-After backoff tests
  pkg/kncloudevents/message_sender_test.go
Labels: approved, size/L, lgtm

#5977 [release-1.0] Fix channel template spec type for Sequence channel template field
  config/core/resources/sequence.yaml
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
  test/rekt/features/parallel/readyness.go
  test/rekt/features/sequence/readyness.go
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/parallel/parallel.go
  test/rekt/resources/parallel/parallel.yaml
  test/rekt/resources/parallel/parallel_test.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/sequence/sequence.yaml
  test/rekt/resources/sequence/sequence_test.go
  test/rekt/smoke_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#5973 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#5984 Using k8s 1.23 for GH Action e2e workflow
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#5986 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#5991 Refactor filter receiver tests
  pkg/broker/filter/filter_handler_test.go
Labels: approved, size/L, lgtm

#5997 Use in-cluster kube config as a fallback
  test/lib/client.go
  test/lib/test_runner.go
Labels: approved, lgtm, size/S, area/test-and-release

#5999 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#5998 Add SchedulerFunc type implementing Scheduler as func
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/M, approved, lgtm

#6001 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#6009 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#6008 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/reconciler-test/pkg/environment/interfaces.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_composite.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6016 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, size/XS, lgtm
