Repository knative/eventing, pull requests merged in 2021-06, with the labels that each got.

#5459 Added tristate flags and changed experimental config map name
  config/400-config-experimental-features.yaml
  config/400-config-features.yaml
  config/core/configmaps/features.yaml
  docs/experimental-features.md
  pkg/apis/feature/api_validation.go
  pkg/apis/feature/api_validation_test.go
  pkg/apis/feature/features.go
  pkg/apis/feature/features_test.go
  pkg/apis/feature/flag_names.go
  pkg/apis/feature/store.go
  pkg/apis/feature/store_test.go
  pkg/apis/feature/testdata/config-features.yaml
  test/experimental/main_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5461 Added broker.WithConfig
  test/rekt/resources/broker/broker.go
  test/rekt/resources/broker/broker_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5462 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5465 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#5466 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#5468 Fix lint: Use the non-deprecated version
  test/rekt/resources/broker/broker.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5467 remove v1beta1 task as it has been done
  docs/roadmap-2021.md
Labels: approved, cla: yes, lgtm, size/S

#5470 Update Knative dependency for release-0.23
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#5469 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5464 Adapter's `StartReceiver()` method implemented
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
Labels: approved, cla: yes, lgtm, size/L

#5471 add conformance test for trigger delivery DLQ
  test/rekt/features/broker/control_plane.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5418 Removing the skip on PingSource rek-test
  test/rekt/apiserversource_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5478 Make eventing channel metrics generic enough to be used by other impl
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/stats_reporter.go
Labels: approved, cla: yes, lgtm, size/S

#5481 Expose dispatch result to be used by other implementations
  pkg/channel/fanout/fanout_message_handler.go
Labels: approved, cla: yes, lgtm, size/S

#5477 setup proper schemes in the fake dynamic client used in unit tests
  pkg/broker/filter/filter_handler_test.go
  pkg/duck/listable_test.go
  pkg/duck/subscriber_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/containersource/containersource_test.go
  pkg/reconciler/eventtype/eventtype_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/source/crd/crd_test.go
  pkg/reconciler/source/duck/controller_test.go
  pkg/reconciler/source/duck/duck_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/sugar/namespace/namespace_test.go
  pkg/reconciler/sugar/trigger/trigger_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/scheme/scheme.go
  pkg/reconciler/testing/v1/factory.go
  pkg/reconciler/testing/v1/listers.go
  pkg/reconciler/testing/v1beta1/factory.go
  pkg/reconciler/testing/v1beta1/listers.go
Labels: approved, cla: yes, lgtm, size/L

#5479 Modify experimental features e2e test setup
  .github/workflows/kind-e2e.yaml
  test/experimental/config/features.yaml
  test/experimental/main_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5476 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5480 KIND Updates
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#5475 Use embed package for rekt resource templates
  test/rekt/resources/account_role/role.go
  test/rekt/resources/apiserversource/apiserversource.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/channel/channel.go
  test/rekt/resources/channel_impl/channel_impl.go
  test/rekt/resources/containersource/containersource.go
  test/rekt/resources/deployment/deployment.go
  test/rekt/resources/eventlibrary/eventlibrary.go
  test/rekt/resources/flaker/flaker.go
  test/rekt/resources/parallel/parallel.go
  test/rekt/resources/pingsource/pingsource.go
  test/rekt/resources/pod/pod.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/sinkbinding/sinkbinding.go
  test/rekt/resources/subscription/subscription.go
  test/rekt/resources/svc/service.go
  test/rekt/resources/trigger/trigger.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5445 Port SingleEventWithEncoding tests to rekt
  test/e2e/channel_single_event_test.go
  test/e2e/helpers/channel_single_event_helper.go
  test/rekt/channel_test.go
  test/rekt/features/channel/features.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5487 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5486 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5490 Retry install_knative_eventing on 502 errors from GitHub
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5491 drop deprecated kubeclient
  test/lib/client.go
  test/lib/creation.go
  test/lib/logexporter.go
  test/lib/resources/serving.go
  test/performance/infra/image_helpers.go
Labels: approved, area/performance, area/test-and-release, cla: yes, lgtm, size/M

#5488 clean up extra With call
  pkg/reconciler/source/duck/controller_test.go
Labels: approved, cla: yes, lgtm, size/XS

#5492 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#5489 Fix tests relying on non-existent services
  pkg/reconciler/subscription/subscription_test.go
Labels: approved, cla: yes, lgtm, size/XS

#5493 Remove self from community contacts and add to NON_ROSTER
  support/COMMUNITY_CONTACTS.md
  support/NON_ROSTER
Labels: approved, cla: yes, lgtm, size/XS

#5502 Reorganized kncloudevents retries code
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
  pkg/kncloudevents/retries.go
  pkg/kncloudevents/retries_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#5505 Use transformers efficiently for extracting info for metrics in Kafka Channel
  pkg/channel/message_dispatcher.go
Labels: approved, cla: yes, lgtm, size/XS

#5509 Try to fix more flaky tests
  test/rekt/features/broker/source_to_sink.go
  test/rekt/features/channel/features.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5508 Remove flaky test
  pkg/adapter/v2/cloudevents_test.go
Labels: approved, cla: yes, lgtm, size/L

#5512 Pass transformers to executeRequest
  pkg/channel/message_dispatcher.go
Labels: approved, cla: yes, lgtm, size/S

#5498 Fix tests
  test/conformance/helpers/channel_status_subscriber_test_helper.go
  test/rekt/features/broker/readyness.go
  test/rekt/features/channel/features.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5501 Add permission to update namespaces/finalizer
  config/core/roles/webhook-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5513 Drop --strict flag on ko
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5504 Add API doc generation to codegen
  docs/eventing-api.md
  go.mod
  go.sum
  hack/reference-docs-gen-config.json
  hack/tools.go
  hack/update-codegen.sh
  hack/update-reference-docs.sh
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.gitignore
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.goreleaser.yml
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/.travis.yml
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/LICENSE
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/README.md
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/example-config.json
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/go.mod
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/go.sum
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/main.go
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/members.tpl
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/pkg.tpl
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/placeholder.go
  vendor/github.com/ahmetb/gen-crd-api-reference-docs/template/type.tpl
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/go.mod
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/github.com/shurcooL/sanitized_anchor_name/.travis.yml
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/README.md
  vendor/github.com/shurcooL/sanitized_anchor_name/go.mod
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#5514 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#5337 Use test namespaces with numeric suffix
  test/conformance/main_test.go
  test/e2e/main_test.go
  test/e2e_flags.go
  test/flags/eventing_environment.go
  test/lib/test_runner.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5440 Implement `KReference.Group` resolution for `Subscriber.Ref`
  cmd/webhook/main.go
  config/core/configmaps/features.yaml
  config/core/resources/subscription.yaml
  pkg/apis/feature/flag_names.go
  pkg/apis/feature/store.go
  pkg/apis/messaging/v1/subscription_validation_test.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/controller_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/factory.go
  pkg/reconciler/testing/v1/subscription.go
  test/experimental/config/features.yaml
  test/experimental/features/kreference_group/channel_to_channel.go
  test/experimental/kreference_group_test.go
  vendor/knative.dev/pkg/kref/knative_reference.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#5531 Fix subtest client scope
  test/conformance/helpers/channel_spec_test_helper.go
  test/conformance/helpers/channel_status_subscriber_test_helper.go
  test/conformance/helpers/channel_status_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5519 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#5530 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5520 Support `KReference.Group` in `Subscription.Spec.Channel`
  config/core/resources/subscription.yaml
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/subscription.go
  test/experimental/features/kreference_group/sub_channel.go
  test/experimental/kreference_group_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5149 Delivery timeout
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/configmaps/features.yaml
  config/core/resources/broker.yaml
  config/core/resources/channel.yaml
  config/core/resources/parallel.yaml
  config/core/resources/sequence.yaml
  config/core/resources/subscription.yaml
  docs/eventing-api.md
  pkg/apis/duck/v1/delivery_types.go
  pkg/apis/duck/v1/delivery_types_test.go
  pkg/apis/duck/v1/zz_generated.deepcopy.go
  pkg/apis/duck/v1beta1/delivery_conversion.go
  pkg/apis/duck/v1beta1/delivery_types.go
  pkg/apis/duck/v1beta1/delivery_types_test.go
  pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  pkg/apis/feature/flag_names.go
Labels: approved, cla: yes, lgtm, size/L

#5539 Add IMC webhook the permission to update namespaces/finalizers
  config/channels/in-memory-channel/roles/controller-clusterrole.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5503 RetryConfig.RequestTimeout to configure the timeout of a single request
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
  pkg/kncloudevents/retries.go
Labels: approved, cla: yes, lgtm, size/M

#5541 Bump deps, fix tests
  go.mod
  go.sum
  test/rekt/features/apiserversource/data_plane.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/recorder_vent/recorder.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5540 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5545 ./hack/update-deps.sh --upgrade
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5547 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#5507 Glue Delivery.Timeout to RetryConfig.RequestTimeout
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/resources/channel.yaml
  pkg/channel/fanout/fanout_message_handler.go
  pkg/kncloudevents/message_sender_test.go
  pkg/kncloudevents/retries.go
  pkg/kncloudevents/retries_test.go
  pkg/reconciler/subscription/subscription.go
  test/experimental/config/features.yaml
  test/experimental/delivery_timeout_test.go
  test/experimental/features/delivery_timeout/channel.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5538 Extend rotation calendar
  support/COMMUNITY_CONTACTS.md
  support/NON_ROSTER
  support/ROSTER
  support/VOLUNTEERS
  support/support.rotation
Labels: approved, cla: yes, lgtm, size/M

#5549 [PingSource] Degrade warning to normal event
  pkg/adapter/mtping/pingsource.go
  pkg/adapter/mtping/pingsource_test.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
Labels: approved, cla: yes, lgtm, size/M

#5550 Knativehistory was removed
  test/rekt/features/channel/data_plane.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5546 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5553 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#5555 [QE] Removing deprecated code from test/upgrade
  test/upgrade/prober/configuration.go
  test/upgrade/prober/prober.go
  test/upgrade/prober/prober_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5537 Fix flakiness & slowness of imc dispatcher test
  pkg/inmemorychannel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_test.go
Labels: approved, cla: yes, lgtm, size/XS
