Repository knative/eventing, pull requests merged in 2021-01, with the labels that each got.

#4690 Update spec.md fix render typo on DeliverySpec
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/XS

#4616 feat/upgrade-test: Add configurable broker deployment options
  test/upgrade/prober/configuration.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4695 [Automated] Format markdown
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/S

#4694 Update test README.md for go test commands
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4672 Add enableServiceLinks:false to webhook yaml
  config/core/deployments/webhook.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4684 Webhook has only namespaced Secret permissions, rather than cluster-wide.
  config/200-webhook-role.yaml
  config/core/200-webhook-serviceaccount.yaml
  config/core/roles/webhook-clusterrole.yaml
  config/core/roles/webhook-role.yaml
Labels: approved, cla: yes, lgtm, size/M

#4689 [#4506] Update e2e test name to be clearer
  test/e2e/channel_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4691 Add zhongduo (Jimmy Lin) as an approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4698 Update COMMUNITY_CONTACTS.md
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4701 Remove myself from reviewers
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4702 Remove yolocs from reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#4615 feat/upgrade-test: Use configurable template file path
  test/upgrade/prober/configuration.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4655 ApiServerSource stored version v1 and migration tool
  config/core/resources/apiserversource.yaml
  config/post-install/clusterrole.yaml
  config/post-install/placeholder.go
  config/post-install/serviceaccount.yaml
  config/post-install/storage-version-migrator.yaml
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4692 update oncall schedule
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/M

#4704 [Automated] Format markdown
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4705 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#4703 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4406 Removed pkg/test/observer
  pkg/test/observer/doc.go
  pkg/test/observer/eventlog.go
  pkg/test/observer/http-vent/doc.go
  pkg/test/observer/http-vent/http.go
  pkg/test/observer/observation.go
  pkg/test/observer/observer.go
  pkg/test/observer/recorder-collector/collector.go
  pkg/test/observer/recorder-collector/doc.go
  pkg/test/observer/recorder-vent/constructor.go
  pkg/test/observer/recorder-vent/doc.go
  pkg/test/observer/recorder-vent/recorder.go
  pkg/test/observer/writer-vent/doc.go
  pkg/test/observer/writer-vent/writer.go
Labels: approved, cla: yes, lgtm, size/XL

#4699 Update community support roster, extend to eventing reviewers
  support/COMMUNITY_CONTACTS.md
  support/NON_ROSTER
  support/VOLUNTEERS
Labels: approved, cla: yes, lgtm, size/M

#4657 ContainerSource stored version v1 and migration tool
  config/core/resources/containersource.yaml
  config/post-install/clusterrole.yaml
  config/post-install/storage-version-migrator.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4658 SinkBinding stored version v1 and migration tool
  config/core/resources/sinkbindings.yaml
  config/post-install/clusterrole.yaml
  config/post-install/storage-version-migrator.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4708 [Automated] Format markdown
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/S

#4693 [#4506] Add e2e test for broker webhook defaults
  test/e2e/broker_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4711 Fix panic in the TestBrokerNamespaceDefaulting
  test/e2e/broker_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4713 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4712 Fix panic in the TestChannelNamespaceDefaulting
  test/e2e/channel_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4716 bump the name of the broker on each iter
  test/e2e/broker_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4707 message receiver supports customized liveness and readiness check
  go.mod
  go.sum
  pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4724 Updates
  go.mod
  go.sum
  pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4714 Disabling servicelinks in all the components
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  config/sugar/500-controller.yaml
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#4722 [#4721] Update e2e broker default webhook test
  test/e2e/broker_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4730 Re-submit #4707
  go.mod
  go.sum
  pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4727 Use the v1 api package...
  test/e2e/helpers/broker_channel_flow_helper.go
  test/e2e/helpers/broker_test_helper.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4594 Update spec.md with v1 API
  docs/spec/helper.md
  docs/spec/spec.md
  docs/spec/spec_v1alpha1.md
Labels: approved, cla: yes, lgtm, size/XL

#4734 [Automated] Format markdown
  docs/spec/spec.md
Labels: approved, cla: yes, lgtm, size/XS

#4733 Add a note about implementation helper.md that it only pertains to this repo.
  docs/spec/helper.md
Labels: approved, cla: yes, lgtm, size/XS

#4543 Now the config-imc-event-dispatcher values are injected to the dispatcher through envs
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  pkg/reconciler/inmemorychannel/controller/config/config.go
  pkg/reconciler/inmemorychannel/controller/config/config_test.go
  pkg/reconciler/inmemorychannel/controller/config/testdata/config-event-dispatcher-1.yaml
  pkg/reconciler/inmemorychannel/controller/config/testdata/config-event-dispatcher-2.yaml
  pkg/reconciler/inmemorychannel/controller/config/testdata/config-event-dispatcher-3.yaml
  pkg/reconciler/inmemorychannel/controller/config/testdata/config-event-dispatcher-4.yaml
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/controller_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/testing/v1/factory.go
Labels: approved, cla: yes, lgtm, size/L

#4667 Unify usage of YAML libraries
  go.mod
  pkg/apis/config/defaults.go
  pkg/reconciler/mtbroker/config.go
  test/e2e/broker_defaults_webhook_test.go
  test/e2e/channel_defaults_webhook_test.go
  test/e2e/helpers/channel_defaulter_test_helper.go
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#4720 [#4717] Update e2e broker defaults webhook test
  test/e2e/broker_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4740 [Automated] Format markdown
  docs/spec/helper.md
Labels: approved, cla: yes, lgtm, size/XS

#4741 Use wait_for_pods instead of kubectl wait for pods. Fix #4725
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4659 Add Open Telemetry Spec attributes to IMC Dispatcher span
  docs/spec/channel.md
  pkg/channel/message_dispatcher.go
  pkg/tracing/populate_span_transformer.go
  pkg/tracing/populate_span_transformer_test.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4560 Add event reply header to spec
  docs/spec/data-plane.md
Labels: approved, cla: yes, lgtm, size/S

#4746 [Automated] Format markdown
  docs/spec/data-plane.md
Labels: approved, cla: yes, lgtm, size/S

#4729 KIND: run with 1.19.4 and 1.20.0
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#4749 Cleanup channel template internal types
  pkg/apis/messaging/v1/channel_template_types.go
  pkg/apis/messaging/v1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1beta1/channel_template_types.go
  pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  pkg/duck/channel.go
  pkg/duck/channel_test.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/resources/channel.go
  pkg/reconciler/mtbroker/broker.go
  pkg/reconciler/mtbroker/resources/channel.go
  pkg/reconciler/mtbroker/resources/channel_test.go
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/resources/channel.go
  pkg/reconciler/sequence/resources/channel.go
  pkg/reconciler/sequence/sequence.go
  test/lib/duck/resource_creators.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#4755 [#4744] Bump test zipkin version
  test/config/monitoring/monitoring.yaml
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4756 [#4744] Update conformance test helper
  test/conformance/helpers/tracing/traces.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4750 use v1beta2 as the storage version of PingSource
  config/core/resources/pingsource.yaml
  config/post-install/clusterrole.yaml
  config/post-install/storage-version-migrator.yaml
Labels: approved, cla: yes, lgtm, size/S

#4765 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#4766 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4770 Use KO_YAML_FLAGS for multi-platform build
  hack/generate-yamls.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4763 Allow to specify build platform for test images
  test/README.md
  test/upload-test-images.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/S

#4764 test(sources): add roundtrip tests for sources v1 types
  pkg/apis/sources/v1/roundtrip_test.go
Labels: approved, cla: yes, lgtm, size/M

#4779 Expose the function RunMainTest
  test/upgrade/upgrade.go
  test/upgrade/upgrade_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#4784 [Automated] Format markdown
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4785 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/generators/tags.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/webhook/certificates/certificates.go
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#4786 Upgrade otel
  go.mod
  go.sum
  test/conformance/helpers/tracing_test_helper.go
  third_party/VENDOR-LICENSE/github.com/stretchr/testify/LICENSE
  third_party/VENDOR-LICENSE/go.opentelemetry.io/otel/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/LICENSE
  third_party/VENDOR-LICENSE/gopkg.in/yaml.v3/NOTICE
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/go.opentelemetry.io/otel/api/core/key.go
  vendor/go.opentelemetry.io/otel/api/core/number.go
  vendor/go.opentelemetry.io/otel/api/core/numberkind_string.go
  vendor/go.opentelemetry.io/otel/api/core/rawhelpers.go
  vendor/go.opentelemetry.io/otel/api/core/span_context.go
  vendor/go.opentelemetry.io/otel/api/core/valuetype_string.go
  vendor/go.opentelemetry.io/otel/api/propagation/doc.go
  vendor/go.opentelemetry.io/otel/api/propagation/propagation.go
  vendor/go.opentelemetry.io/otel/api/trace/always_sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/api.go
  vendor/go.opentelemetry.io/otel/api/trace/b3_propagator.go
  vendor/go.opentelemetry.io/otel/api/trace/context.go
  vendor/go.opentelemetry.io/otel/api/trace/doc.go
  vendor/go.opentelemetry.io/otel/api/trace/never_sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_span.go
  vendor/go.opentelemetry.io/otel/api/trace/noop_trace_provider.go
  vendor/go.opentelemetry.io/otel/api/trace/sampler.go
  vendor/go.opentelemetry.io/otel/api/trace/trace_context_propagator.go
  vendor/go.opentelemetry.io/otel/codes/codes.go
  vendor/go.opentelemetry.io/otel/codes/doc.go
  vendor/go.opentelemetry.io/otel/internal/baggage/baggage.go
  vendor/go.opentelemetry.io/otel/internal/rawhelpers.go
  vendor/go.opentelemetry.io/otel/label/doc.go
  vendor/go.opentelemetry.io/otel/label/encoder.go
  vendor/go.opentelemetry.io/otel/label/iterator.go
  vendor/go.opentelemetry.io/otel/label/key.go
  vendor/go.opentelemetry.io/otel/label/kv.go
  vendor/go.opentelemetry.io/otel/label/set.go
  vendor/go.opentelemetry.io/otel/label/type_string.go
  vendor/go.opentelemetry.io/otel/label/value.go
  vendor/go.opentelemetry.io/otel/propagation/baggage.go
  vendor/go.opentelemetry.io/otel/propagation/doc.go
  vendor/go.opentelemetry.io/otel/propagation/propagation.go
  vendor/go.opentelemetry.io/otel/propagation/trace_context.go
  vendor/go.opentelemetry.io/otel/trace/config.go
  vendor/go.opentelemetry.io/otel/trace/doc.go
  vendor/go.opentelemetry.io/otel/trace/trace.go
  vendor/go.opentelemetry.io/otel/trace/trace_noop.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XXL

#4789 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#4790 [#4739] Update e2e channel defaults webhook test
  test/e2e/channel_defaults_webhook_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#4792 Adding HPA for eventing-webhook
  config/core/deployments/webhook-hpa.yaml
  config/hpa-webhook.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#4793 Set failure policy to ignore for webhook
  config/core/webhooks/config-validation.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4760 new cloudevent extension attribute with dispatch error
  pkg/channel/attributes/knative_error.go
  pkg/channel/attributes/knative_error_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#4795 go 1.15 in go.mod, drop k8s 1.17 e2e tests
  .github/workflows/kind-e2e.yaml
  go.mod
Labels: approved, cla: yes, lgtm, size/XS

#4797 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_matchers.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/step.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#4780 Adding new source conformance testcase for CRD Source Registry Spec
  test/conformance/helpers/metadata.go
  test/conformance/helpers/sources/source_crd_registry_test_helper.go
  test/conformance/source_crd_registry_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4798 Update COMMUNITY_CONTACTS.md test grid link
  support/COMMUNITY_CONTACTS.md
Labels: approved, cla: yes, lgtm, size/XS

#4787 Adding new source conformance testcase for CRD RBAC
  test/conformance/helpers/sources/source_crd_rbac_test_helper.go
  test/conformance/source_crd_rbac_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4811 Patch HPA eventing-webhook min replicas
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#4555 Add availability rate to upgrade test report
  test/e2e-upgrade-tests.sh
  test/test_images/wathola-fetcher/main_test.go
  test/upgrade/prober/verify.go
  test/upgrade/prober/wathola/config/defaults.go
  test/upgrade/prober/wathola/config/structure.go
  test/upgrade/prober/wathola/event/operations.go
  test/upgrade/prober/wathola/event/services.go
  test/upgrade/prober/wathola/event/services_test.go
  test/upgrade/prober/wathola/event/types.go
  test/upgrade/prober/wathola/event/types_test.go
  test/upgrade/prober/wathola/fetcher/operations.go
  test/upgrade/prober/wathola/receiver/services.go
  test/upgrade/prober/wathola/receiver/services_test.go
  test/upgrade/prober/wathola/receiver/types.go
  test/upgrade/prober/wathola/sender/operations.go
  test/upgrade/prober/wathola/sender/services.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#4808 Bump golang linter version and timeout
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4794 sinkbinding implements bindable
  pkg/apis/sources/v1/sinkbinding_types.go
Labels: approved, cla: yes, lgtm, size/XS
