Repository knative/eventing, pull requests merged in 2021-04, with the labels that each got.

#5192 Add devl instructions on receiving traffic with telepresence
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#5206 [Automated] Format markdown
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#5210 add t to Assert helpers from rekt
  go.mod
  go.sum
  test/rekt/features/broker/data_plane.go
  test/rekt/features/knconf/data_plane.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/test_images/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5153 fix(PingSource): remove annotation based conversion logic
  pkg/apis/sources/v1beta1/ping_conversion.go
  pkg/apis/sources/v1beta1/ping_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#5234 fix(PingSource): remove annotation based conversion logic
  pkg/apis/sources/v1beta1/ping_conversion.go
  pkg/apis/sources/v1beta1/ping_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#5233 fix(PingSource): remove annotation based conversion logic
  pkg/apis/sources/v1beta1/ping_conversion.go
  pkg/apis/sources/v1beta1/ping_conversion_test.go
Labels: approved, cla: yes, lgtm, size/L

#5251 [Automated] Format markdown
  test/rekt/resources/eventlibrary/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5261 update to new release of golang sdk for cloudevents 2.4.1
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5265 Do not panic prober if report fetched too early (#5264)
  test/upgrade/prober/prober.go
  test/upgrade/prober/verify.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5262 Adding dataplane conformance tests for Delivery Specs for Brokers.
  go.mod
  go.sum
  test/rekt/features/broker/control_plane.go
  test/rekt/features/broker/control_plane_test.go
  test/rekt/features/broker/data_plane.go
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#5267 make sure the mtchannelbasedbroker uses trigger.spec.delivery
  pkg/reconciler/broker/trigger/trigger.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/testing/v1/trigger.go
Labels: approved, cla: yes, lgtm, size/L

#5263 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5276 Remove KafkaChannel upgrade hack
  pkg/apis/messaging/v1/subscription_defaults.go
  pkg/apis/messaging/v1/subscription_validation.go
  pkg/apis/messaging/v1/subscription_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#5273 Filtering fix for consistency in handling empty string as value
  pkg/eventfilter/attributes/filter.go
  pkg/eventfilter/attributes/filter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5268 test trigger delivery specs fully
  test/rekt/features/broker/control_plane.go
  test/rekt/resources/trigger/trigger_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5280 Do events end where they should
  go.mod
  go.sum
  test/rekt/features/broker/control_plane.go
  test/rekt/features/broker/control_plane_test.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XL

#5282 add test with reply
  test/rekt/features/broker/control_plane.go
  test/rekt/features/broker/control_plane_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L

#5278 [Rekt] Add polling on inner channel subscriber status
  test/rekt/features/channel/control_plane.go
  test/rekt/features/channel/helpers.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5281 Add tests for additional ingress error cases
  pkg/broker/ingress/ingress_handler_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#5284 [Rekt] adding more polling for channel tests
  test/rekt/features/channel/control_plane.go
  test/rekt/features/channel/data_plane.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5287 Custom type and reply
  test/rekt/features/broker/control_plane.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5288 Improve performance of eventfilter lookups
  pkg/eventfilter/attributes/filter.go
  pkg/eventfilter/attributes/filter_test.go
Labels: approved, cla: yes, lgtm, size/M

#5184 Add pre-review checklist to PR template
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#5275 Running validation for events on broker ingress
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
Labels: approved, cla: yes, lgtm, size/S

#5272 event type v1beta1
  config/core/resources/eventtype.yaml
Labels: approved, cla: yes, lgtm, size/S

#5279 [Rekt] Channel Delivery Spec data plane tests.
  go.mod
  go.sum
  test/rekt/features/broker/control_plane_test.go
  test/rekt/features/channel/data_plane.go
  test/rekt/features/channel/topology.go
  test/rekt/features/channel/topology_test.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter.go
  vendor/knative.dev/reconciler-test/pkg/milestone/factory.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#5289 Clean up resources created by Feature tests
  go.mod
  go.sum
  test/rekt/features/broker/control_plane.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/context.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/manifest/installer.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/M

#5290 Another unit test for channel to increase coverage
  pkg/reconciler/channel/channel_test.go
Labels: approved, cla: yes, lgtm, size/S

#5295 Move eventing-contrib/cmd/* here
  cmd/appender/main.go
  cmd/event_display/main.go
  cmd/heartbeats/main.go
  cmd/heartbeats_receiver/main.go
  cmd/websocketsource/main.go
  config/tools/appender/appender.yaml
  config/tools/event-display/event-display.yaml
  config/tools/websocket-source/websocket-source.yaml
  go.mod
  go.sum
  hack/generate-yamls.sh
  third_party/VENDOR-LICENSE/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/client_clone.go
  vendor/github.com/gorilla/websocket/client_clone_legacy.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/conn_write.go
  vendor/github.com/gorilla/websocket/conn_write_legacy.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/go.mod
  vendor/github.com/gorilla/websocket/go.sum
  vendor/github.com/gorilla/websocket/join.go
  vendor/github.com/gorilla/websocket/json.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/mask_safe.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/trace.go
  vendor/github.com/gorilla/websocket/trace_17.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/modules.txt
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#5297 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#5303 Drop --strict flag on ko
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5299 [v1] Doing version bumps for some files to v1
  pkg/apis/sources/v1/container_validation_test.go
  pkg/apis/sources/v1beta1/container_validation_test.go
  pkg/broker/filter/filter_handler_test.go
  pkg/reconciler/source/duck/duck_test.go
  test/e2e_flags.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/S

#5300 [v1] Lifting some apis to more recent level
  pkg/apis/messaging/config/channel_defaults_test.go
  pkg/apis/messaging/config/testdata/default-ch-webhook.yaml
Labels: approved, cla: yes, lgtm, size/S

#5306 Increase Trigger validation test coverage
  pkg/apis/eventing/v1/trigger_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#5305 Increase Subscription validation test coverage
  pkg/apis/messaging/v1/subscription_validation_test.go
Labels: approved, cla: yes, lgtm, size/S

#5298 [v1] Tidy up the InMemoryChannel CRD to remove the v1beta1
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
Labels: approved, cla: yes, lgtm, size/S

#5302 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1alpha2/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/reconciler.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#5310 [V1] Fixing versions and api groups for subscription validation test
  pkg/apis/messaging/v1/subscription_validation_test.go
Labels: approved, cla: yes, lgtm, size/XS

#5313 CreatePodOrFail retry on "No API token found"
  test/lib/creation.go
Labels: approved, area/test-and-release, cla: yes, lgtm, needs-ok-to-test, size/XS

#5307 [V1] Adding API description (e.g. for k explain) for IMC and generic Channel
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/resources/channel.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5314 [V1] Remove some vbeta1 IMC configs in tests
  pkg/apis/messaging/config/channel_defaults_test.go
Labels: approved, cla: yes, lgtm, size/S

#5315 [v1] Add flows yaml desc
  config/core/resources/parallel.yaml
  config/core/resources/sequence.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5316 More v1
  pkg/adapter/apiserver/adapter.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/flows/v1/sequence_lifecycle_test.go
  pkg/apis/messaging/v1/subscribable_channelable_validation_test.go
  pkg/apis/sources/v1/apiserver_defaults_test.go
  pkg/apis/sources/v1/apiserver_validation_test.go
  pkg/apis/sources/v1/container_validation_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/config_test.go
  pkg/reconciler/broker/testdata/config-broker.yaml
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/listers.go
  pkg/reconciler/testing/v1/listers.go
Labels: approved, cla: yes, lgtm, size/M

#5304 Increase ApiServerSource validation coverage
  pkg/apis/sources/v1/apiserver_validation_test.go
Labels: approved, cla: yes, lgtm, size/M

#5296 [Rekt] Let Channel and Broker tests use a common test pattern
  test/rekt/features/broker/control_plane.go
  test/rekt/features/broker/data_plane.go
  test/rekt/features/broker/topology.go
  test/rekt/features/broker/topology_test.go
  test/rekt/features/channel/data_plane.go
  test/rekt/features/channel/topology.go
  test/rekt/features/channel/topology_test.go
  test/rekt/features/knconf/event_patterns.go
  test/rekt/features/knconf/event_patterns_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XXL

#5311 Enable to scale chaosduck down to zero for prow test
  test/README.md
  test/e2e-common.sh
Labels: approved, area/test-and-release, cla: yes, lgtm, ok-to-test, size/XS

#5320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#5328 Pointing to the proper v1 api, as the copy
  pkg/apis/messaging/config/channel_template_types.go
Labels: approved, cla: yes, lgtm, size/XS

#5326 [Automated] Format markdown
  test/README.md
Labels: approved, area/test-and-release, cla: yes, lgtm, size/XS

#5331 Add containersource smoke test
  test/rekt/features/containersource/readyness.go
  test/rekt/resources/containersource/containersource.go
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/smoke_test.go
Labels: approved, area/test-and-release, cla: yes, lgtm, size/L
