Repository knative/eventing, pull requests merged in 2022-05, with the labels that each got.

#6360 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate/main.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6369 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6365 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6372 Export trace for events that exceed allowed unavailable period
  test/upgrade/prober/verify.go
  test/upgrade/prober/wathola/event/services.go
  test/upgrade/prober/wathola/event/services_test.go
  test/upgrade/prober/wathola/event/types.go
  test/upgrade/prober/wathola/sender/services.go
Labels: size/M, approved, lgtm, area/test-and-release

#6371 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/schema/schema/generate_schema.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6379 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6378 adding util for adding custom annotation values to different broker implementation usage
  test/lib/resources/eventing.go
Labels: approved, lgtm, size/S, area/test-and-release

#6382 Remove the namespae for the imc
  config/channels/in-memory-channel/100-namespace.yaml
Labels: approved, lgtm, size/S

#6370 Adding retry for 408 (Request Timeout) http status code
  pkg/kncloudevents/retries.go
  pkg/kncloudevents/retries_test.go
Labels: approved, lgtm, size/S

#6380 Remove calling 'ExecuteLocalYAML', b/c it is deprecated
  test/rekt/resources/account_role/role_test.go
  test/rekt/resources/apiserversource/apiserversource_test.go
  test/rekt/resources/broker/broker_test.go
  test/rekt/resources/channel/channel_test.go
  test/rekt/resources/channel_impl/channel_impl_test.go
  test/rekt/resources/containersource/containersource_test.go
  test/rekt/resources/delivery/delivery_test.go
  test/rekt/resources/deployment/deployment_test.go
  test/rekt/resources/eventlibrary/eventlibrary_test.go
  test/rekt/resources/flaker/flaker_test.go
  test/rekt/resources/parallel/parallel_test.go
  test/rekt/resources/pingsource/pingsource_test.go
  test/rekt/resources/pod/pod_test.go
  test/rekt/resources/sequence/sequence_test.go
  test/rekt/resources/sinkbinding/sinkbinding_test.go
  test/rekt/resources/subscription/subscription_test.go
  test/rekt/resources/svc/service_test.go
  test/rekt/resources/trigger/trigger_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6357 Only proxy some headers from the reply in MTBroker filter
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
Labels: approved, size/L, lgtm

#6389 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/manifest/templates.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6390 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#6391 Propagate log level to env var in sources `ConfigWatcher`
  pkg/reconciler/source/config_watcher.go
  pkg/reconciler/source/config_watcher_test.go
Labels: size/M, approved, lgtm

#6398 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm
