Repository knative/eventing, pull requests merged in 2022-01, with the labels that each got.

#6014 Remove skipped Trigger no Broker test
  test/e2e/helpers/trigger_no_broker_test_helper.go
  test/e2e/trigger_no_broker_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6015 Remove useless logconfig package
  pkg/logconfig/config.go
Labels: approved, lgtm, size/S

#6006 Fixing Broker DLQ flaky tests
  test/rekt/broker_test.go
  test/rekt/features/broker/source_to_sink.go
  test/rekt/features/trigger/trigger_sink_resolution.go
  test/rekt/trigger_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6003 Rename "pingsource" component
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/resources/receive_adapter.go
  pkg/reconciler/pingsource/resources/receive_adapter_test.go
Labels: approved, lgtm, size/S

#5928 Add k8s trace attribute to PingSource
  pkg/adapter/mtping/runner.go
  pkg/adapter/v2/cloudevents.go
  pkg/observability/attributes.go
  pkg/observability/attributes_test.go
  pkg/observability/client/observability_service.go
  pkg/observability/client/observability_service_test.go
  pkg/observability/client/observable.go
  pkg/observability/context.go
  pkg/observability/context_test.go
Labels: approved, size/L, lgtm, cla: yes

#6030 Fix broken links in docs
  docs/eventing-api.md
  hack/reference-docs-gen-config.json
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#6037 Update support Volunteers
  support/VOLUNTEERS
Labels: approved, size/XS, lgtm

#6038 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6040 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#6041 fix wrong date.
  support/support.rotation
Labels: approved, size/XS, lgtm

#6042 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm

#6049 Make event-library test image 'vendorable'
  test/test_images/event-library/kodata/events
  test/test_images/event-library/kodata/events/doc.go
  test/test_images/event-library/kodata/events/three.ce
Labels: size/M, approved, lgtm, area/test-and-release

#6044 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/level.go
  vendor/knative.dev/reconciler-test/pkg/feature/states.go
  vendor/knative.dev/reconciler-test/pkg/feature/timing.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/knative.dev/reconciler-test/pkg/state/kvstore.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6047 Set missing event type on CloudEvent in a test helper
  test/rekt/features/channel/features.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6053 Fix test helpers for subscription that abuse Subscription's `spec.reply`
  test/rekt/channel_test.go
  test/rekt/features/channel/features.go
Labels: size/M, approved, lgtm, area/test-and-release

#6056 Dump resources when failed to wait for them to become ready
  test/e2e-tests.sh
  test/lib/client.go
  test/lib/operation.go
Labels: approved, lgtm, size/S, area/test-and-release

#6060 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/user_info.go
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6057 fix vulnerabilities
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#6063 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#6062 Increase timeout for rekt tests
  test/e2e-rekt-tests.sh
Labels: approved, size/XS, lgtm, area/test-and-release

#6011 Change default Broker delivery spec
  config/core/configmaps/default-broker.yaml
  go.mod
  test/rekt/broker_test.go
  test/rekt/features/broker/control_plane.go
  test/rekt/features/broker/delivery.go
  test/rekt/resources/broker/broker.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, area/test-and-release

#6043 Use time encoder with human-readable timestamps for upgrade tests
  test/upgrade/prober/wathola/config/logger.go
Labels: approved, size/XS, lgtm, area/test-and-release

#5995 Implement Subscriptions API Filters in MTChannelBroker
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/eventfilter/attributes/filter.go
  pkg/eventfilter/filter.go
  pkg/eventfilter/filter_test.go
  pkg/eventfilter/subscriptionsapi/all_filter.go
  pkg/eventfilter/subscriptionsapi/all_filter_test.go
  pkg/eventfilter/subscriptionsapi/any_filter.go
  pkg/eventfilter/subscriptionsapi/any_filter_test.go
  pkg/eventfilter/subscriptionsapi/cesql_filter.go
  pkg/eventfilter/subscriptionsapi/cesql_filter_test.go
  pkg/eventfilter/subscriptionsapi/exact_filter.go
  pkg/eventfilter/subscriptionsapi/exact_filter_test.go
  pkg/eventfilter/subscriptionsapi/not_filter.go
  pkg/eventfilter/subscriptionsapi/not_filter_test.go
  pkg/eventfilter/subscriptionsapi/prefix_filter.go
  pkg/eventfilter/subscriptionsapi/prefix_filter_test.go
  pkg/eventfilter/subscriptionsapi/suffix_filter.go
  pkg/eventfilter/subscriptionsapi/suffix_filter_test.go
  test/experimental/config/features.yaml
  test/experimental/features/new_trigger_filters/filters.go
  test/experimental/new_trigger_filters_test.go
  test/rekt/features/broker/readyness.go
  test/rekt/resources/trigger/trigger.yaml
Labels: approved, lgtm, size/XXL, area/test-and-release, area/eventing

#6067 Update and rename roadmap-2021.md to roadmap.md
  docs/roadmap-2021.md
  docs/roadmap.md
Labels: approved, size/L, lgtm

#6065 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_log.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6050 Upgrade test waits for sender deletion
  test/upgrade/prober/sender.go
Labels: size/M, approved, lgtm, area/test-and-release

#6075 Update zipkin image to :2 version to fix the CVE
  test/config/monitoring/monitoring.yaml
Labels: approved, size/XS, lgtm, area/test-and-release

#6068 Remove k8s 1.20 APIs
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#6074 Prober waits until receiver state != active or timeout
  test/upgrade/prober/configuration.go
  test/upgrade/prober/prober.go
  test/upgrade/prober/verify.go
Labels: size/M, approved, lgtm, area/test-and-release

#6089 Enable features configmap watching and fix mt broker filter subscriptions API implementation
  cmd/broker/filter/main.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/eventfilter/subscriptionsapi/all_filter.go
  pkg/eventfilter/subscriptionsapi/any_filter.go
Labels: size/M, approved, lgtm

#6082 Fixing docs eventing spec details
  docs/metrics.md
  docs/spec/broker.md
  docs/spec/channel.md
  docs/spec/helper.md
  docs/spec/interfaces.md
  docs/spec/spec.md
Labels: approved, lgtm, size/S

#6097 Upgrade knative.dev/pkg@main and fix test errors
  go.mod
  go.sum
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/inmemorychannel.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6105 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#6109 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm
