Repository knative/eventing, pull requests merged in 2022-07, with the labels that each got.

#6435 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6436 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/client.go
  vendor/knative.dev/pkg/client/injection/apiextensions/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/customresourcedefinition.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/apiextensions/v1/customresourcedefinition/fake/fake.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/apiextensions/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/state.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/conditions.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/conditions/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/podspecable/podspecable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/fake/fake.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/source/source.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1alpha1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1beta1/addressable/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/mutatingwebhookconfiguration/mutatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/admissionregistration/v1/validatingwebhookconfiguration/validatingwebhookconfiguration.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/deployment.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/configmap.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/configmap/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/service.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/serviceaccount/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/serviceaccount/serviceaccount.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/rbac/v1/rolebinding/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/rbac/v1/rolebinding/rolebinding.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6434 Add validation methods for ingress feature in broker conformance test
  test/rekt/features/broker/data_plane.go
Labels: approved, size/L, lgtm, area/test-and-release

#6443 Bump prom client version for CVE-2022-21698
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/cespare/xxhash/v2/LICENSE.txt
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/expvar_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_windows.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#6446 Refactor tracing helper to be reusable
  pkg/adapter/v2/test/test_client.go
  pkg/channel/fanout/fanout_message_handler.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
  test/conformance/helpers/tracing/zipkin.go
  test/conformance/helpers/tracing_test_helper.go
Labels: size/M, approved, lgtm, area/test-and-release

#6447 Increase initialDelaySeconds to 120 for webhooks
  config/channels/in-memory-channel/deployments/controller.yaml
  config/core/deployments/webhook.yaml
Labels: approved, size/XS, lgtm

#6448 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#6449 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6452 🧹 Remove dead variables & config for presubmit markdown checking
  test/markdown-lint-config.rc
  test/presubmit-tests.sh
Labels: approved, size/XS, lgtm, area/test-and-release
