Repository knative/eventing, pull requests merged in 2022-11, with the labels that each got.

#6586 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#6587 [release-1.8] Upgrade dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#6589 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6593 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6600 Add Ansu as scheduler approver
  pkg/scheduler/OWNERS
Labels: approved, size/XS, lgtm

#6599 [Scheduler] Handle permanent pending pods
  pkg/scheduler/state/state.go
  pkg/scheduler/state/state_test.go
  pkg/scheduler/statefulset/scheduler.go
Labels: approved, size/L, lgtm

#6609 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6612 Decrease exportTraceLimit to 100
  test/upgrade/prober/verify.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6608 Remove strict subscriber feature flag
  config/core/configmaps/features.yaml
  pkg/apis/feature/flag_names.go
  pkg/apis/messaging/v1/subscription_validation.go
  pkg/apis/messaging/v1/subscription_validation_test.go
  pkg/reconciler/subscription/subscription_test.go
  test/experimental/config/features.yaml
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test

#6569 Knative enhance failed events extensions in mt channel broker
  pkg/broker/err_extension.go
  pkg/broker/filter/filter_handler.go
  pkg/channel/message_dispatcher.go
  pkg/inmemorychannel/message_dispatcher_test.go
  test/rekt/broker_test.go
  test/rekt/channel_test.go
  test/rekt/features/broker/feature.go
  test/rekt/features/channel/features.go
Labels: approved, size/L, lgtm, area/test-and-release

#6614 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6611 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#6616 Remove k8s 1.23 kind
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#6617 Use pointer.XYZ() function instead of deprecated pointer.XYZPtr()
  pkg/apis/duck/v1/delivery_types_test.go
  pkg/apis/duck/v1beta1/delivery_types_test.go
  pkg/apis/duck/v1beta1/subscribable_types_conversion_test.go
  pkg/apis/eventing/v1/broker_defaults_test.go
  pkg/duck/channel_test.go
  pkg/kncloudevents/message_sender_test.go
  pkg/kncloudevents/retries_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher.go
  pkg/reconciler/inmemorychannel/controller/resources/dispatcher_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/subscription/subscription_test.go
  test/e2e/broker_redelivery_test.go
  test/e2e/helpers/channel_dls_test_helper.go
  test/experimental/features/retry_after/channel.go
  test/rekt/smoke_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6620 Bump kind and k8s
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S
