Repository knative/eventing, pull requests merged in 2022-08, with the labels that each got.

#6469 [release-1.5] Refactor tracing helper to be reusable
  pkg/adapter/v2/test/test_client.go
  pkg/channel/fanout/fanout_message_handler.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
  test/conformance/helpers/tracing/zipkin.go
  test/conformance/helpers/tracing_test_helper.go
Labels: size/M, approved, lgtm, area/test-and-release

#6468 [release-1.4] Refactor tracing helper to be reusable
  pkg/adapter/v2/test/test_client.go
  pkg/channel/fanout/fanout_message_handler.go
  test/conformance/helpers/channel_tracing_test_helper.go
  test/conformance/helpers/tracing/traces.go
  test/conformance/helpers/tracing/zipkin.go
  test/conformance/helpers/tracing_test_helper.go
Labels: size/M, approved, lgtm, area/test-and-release

#6463 Port Pingsource test to rekt
  test/e2e/source_ping_v1_test.go
  test/e2e/source_ping_v1beta2_test.go
  test/rekt/features/pingsource/features.go
  test/rekt/pingsource_test.go
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test

#6306 Adds receiver options for configuring read and write timeouts message receiver
  pkg/kncloudevents/message_receiver.go
  pkg/kncloudevents/message_receiver_test.go
Labels: size/M, approved, lgtm

#6458 add k8s trace attribute to ApiServerSource
  pkg/adapter/apiserver/events/events.go
Labels: approved, lgtm, size/S, ok-to-test

#6471 Ignore trailing slashes for Broker requests
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
Labels: approved, lgtm, size/S

#6460 chore: update sugar controller ConfigMap example
  config/core/configmaps/sugar.yaml
Labels: approved, lgtm, size/S

#6472 Promote delivery timeout to beta
  config/core/configmaps/features.yaml
  test/rekt/delivery_timeout_test.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6473 Promote strict subscriber to beta
  config/core/configmaps/features.yaml
  docs/eventing-api.md
  pkg/apis/messaging/v1/subscription_types.go
  test/experimental/config/features.yaml
  test/rekt/channel_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#6470 use go 1.18
  .github/workflows/knative-downstream.yaml
  DEVELOPMENT.md
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#6477 Remove the filter restriction of only containing exactly one attribute
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
Labels: size/M, approved, lgtm

#6476 Knative port source at event types test to rekt
  test/e2e/source_api_server_v1_test.go
  test/e2e/source_ping_v1_test.go
  test/e2e/source_ping_v1beta2_test.go
  test/rekt/apiserversource_test.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/pingsource/features.go
  test/rekt/pingsource_test.go
  test/rekt/resources/eventtype/eventtype.go
Labels: approved, lgtm, size/XL, area/test-and-release, ok-to-test

#6479 Knative port sink binding v1 deployment test to rekt
  test/e2e/source_sinkbinding_v1_test.go
  test/rekt/features/sinkbinding/feature.go
  test/rekt/resources/deployment/deployment.go
  test/rekt/resources/deployment/deployment.yaml
  test/rekt/resources/deployment/deployment_test.go
  test/rekt/resources/sinkbinding/sinkbinding.go
  test/rekt/sink_binding_test.go
  test/rekt/smoke_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6480 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6481 Knative port sink binding v1 job test to rekt
  test/e2e/source_sinkbinding_v1_test.go
  test/rekt/features/sinkbinding/feature.go
  test/rekt/resources/job/job.go
  test/rekt/resources/job/job.yaml
  test/rekt/resources/job/job_test.go
  test/rekt/sink_binding_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6482 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6483 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, size/XS, lgtm, skip-review

#6485 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6486 Increase max namespace count for e2e test runner
  test/lib/test_runner.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6487 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6489 Remove deprecated functions from test/upgrade package
  test/upgrade/prober/configuration.go
  test/upgrade/prober/wathola/sender/services.go
  test/upgrade/prober/wathola/sender/types.go
Labels: size/M, approved, lgtm, area/test-and-release

#6474 Make sure tracer is shut down across components
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  cmd/event_display/main.go
  cmd/heartbeats/main.go
  cmd/mtchannel_broker/main.go
  pkg/adapter/v2/config.go
  pkg/adapter/v2/configurator_configmap.go
  pkg/adapter/v2/configurator_environment.go
  pkg/adapter/v2/main.go
  pkg/adapter/v2/main_message.go
  pkg/channel/message_receiver_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  test/test_images/event-sender/main.go
  test/test_images/recordevents/main.go
  test/test_images/utils.go
  test/test_images/wathola-forwarder/main.go
  test/test_images/wathola-receiver/main.go
  test/test_images/wathola-sender/main.go
  test/upgrade/prober/wathola/config/tracing.go
  test/upgrade/prober/wathola/forwarder/services.go
  test/upgrade/prober/wathola/receiver/services.go
  test/upgrade/prober/wathola/sender/operations.go
  test/upgrade/prober/wathola/sender/services.go
  test/upgrade/prober/wathola/sender/services_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6491 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#6492 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6493 [release-1.7] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#6495 [release-1.7] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#6494 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#6502 nit: Remove v1 check for ConfigMap
  pkg/reconciler/broker/broker.go
Labels: approved, size/XS, lgtm
