Repository knative/eventing, pull requests merged in 2022-09, with the labels that each got.

#6506 Knative trigger dependency annotations test to rekt
  test/e2e/trigger_dependency_annotation_test.go
  test/rekt/features/trigger/feature.go
  test/rekt/resources/pingsource/pingsource.go
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger.yaml
  test/rekt/trigger_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6507 Knative containersource test to rekt
  test/e2e/main_test.go
  test/e2e/source_container_v1_test.go
  test/rekt/container_source_test.go
  test/rekt/features/containersource/features.go
  test/rekt/resources/containersource/containersource.go
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/resources/containersource/containersource_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6499 Knative port prefer header check test to rekt
  test/e2e/broker_prefer_reply_header_test.go
  test/e2e/channel_prefer_reply_header_test.go
  test/e2e/helpers/broker_prefer_reply_header_helper.go
  test/e2e/helpers/channel_prefer_reply_header_helper.go
  test/rekt/broker_test.go
  test/rekt/channel_test.go
  test/rekt/features/broker/feature.go
  test/rekt/features/channel/features.go
Labels: approved, size/L, lgtm, area/test-and-release

#6510 Make some broker conformance tests decoratable with broker options
  test/rekt/features/broker/control_plane.go
  test/rekt/features/broker/topology.go
Labels: size/M, approved, lgtm, area/test-and-release

#6511 InMemoryChannel receiver validates received events
  pkg/channel/message_receiver.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  test/rekt/features/channel/data_plane.go
Labels: approved, size/L, lgtm, area/test-and-release

#6520 :broom: Quarterly release cadence
  docs/planning/sprintplanning.md
Labels: approved, lgtm, size/S

#6522 Knative port broker redelivery test to rekt
  test/e2e/broker_redelivery_test.go
  test/e2e/helpers/broker_redelivery_helper.go
  test/rekt/broker_test.go
  test/rekt/features/broker/feature.go
Labels: approved, size/L, lgtm, area/test-and-release

#6524 Remove strict check in scorer plugins and respect maxskew, requeue when no pods available rather than fail Scheduler
  pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority.go
  pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority_test.go
  pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority.go
  pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, size/L, lgtm

#6533 Enhance PodSecurityPolicy for restricted namespace
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  config/core/deployments/webhook.yaml
  config/post-install/storage-version-migrator.yaml
  config/tools/appender/appender.yaml
  config/tools/event-display/event-display.yaml
  config/tools/heartbeats/heartbeats.yaml
  config/tools/recordevents/recordevents.yaml
  config/tools/websocket-source/websocket-source.yaml
Labels: size/M, approved, lgtm

#6537 Do not use v1b1 from Cronjobs
  test/lib/creation.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6525 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/reconciler.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6521 Fix error bodyofMessage in executeRequest not read
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_various_response_benchmark_test.go
Labels: approved, size/L, lgtm

#6550 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6552 Bump cloudevents/sdk-go to v2.12
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observability_service.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observable.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/reporter.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/trace_attributes.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/http/http.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6548 Remove kind 1.22 testing, since we will min-version 1.23 soon
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm
