Repository knative/eventing, pull requests merged in 2022-06, with the labels that each got.

#6406 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6413 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6414 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6416 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6418 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6419 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6381 Upgrade test reports last error for unavailability periods
  test/upgrade/prober/wathola/event/services.go
  test/upgrade/prober/wathola/event/types.go
  test/upgrade/prober/wathola/sender/services.go
Labels: size/M, approved, lgtm, area/test-and-release

#6423 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6427 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#6428 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#6431 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6424 Bump PodDisruptionBudget to policy/v1
  config/core/deployments/webhook-hpa.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#6432 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm
