Repository knative/eventing, pull requests merged in 2023-09, with the labels that each got.

#7218 [main] Format Go code
  pkg/scheduler/state/state_test.go
Labels: size/M, approved, lgtm

#7220 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7233 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7232 Add more benchmark test for All filter
  pkg/eventfilter/benchmarks/all_filter_benchmark_test.go
Labels: approved, size/L, lgtm

#7234 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7244 Add Audience field in CRDs
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/resources/broker.yaml
  config/core/resources/channel.yaml
  config/core/resources/parallel.yaml
  config/core/resources/sequence.yaml
Labels: size/M, approved, lgtm, ok-to-test

#7237 Expose a Brokers audience in its status
  pkg/apis/eventing/v1/broker_lifecycle.go
  pkg/apis/eventing/v1/broker_lifecycle_test.go
  pkg/apis/eventing/v1/test_helper.go
  pkg/auth/audience.go
  pkg/auth/audience_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/testing/v1/broker.go
  test/experimental/auth_test.go
  test/experimental/config/features.yaml
  test/experimental/features/auth/features.go
  test/rekt/resources/addressable/addressable.go
Labels: approved, size/L, lgtm, area/test-and-release

#7246 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7245 Fixed eventtype create-delete loop on built in sources
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/source/duck/duck.go
  pkg/reconciler/source/duck/duck_test.go
  test/rekt/features/apiserversource/data_plane.go
Labels: approved, size/L, lgtm, area/test-and-release

#7252 Added clotributor link to readme
  README.md
Labels: approved, size/XS, lgtm

#7255 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7231 Added hostnames to tls certificates
  config/brokers/mt-channel-broker-tls/broker-filter-tls-certificate.yaml
  config/brokers/mt-channel-broker-tls/broker-ingress-tls-certificate.yaml
  config/channels/in-memory-channel-tls/imc-dispatcher-tls-certificate.yaml
Labels: approved, size/XS, lgtm

#7248 Have link to adopters form in issue/PR templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/issue-template.md
  .github/pull-request-template.md
Labels: approved, lgtm, size/S

#7262 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/benbjohnson/clock/LICENSE
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/doc.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/github.com/benbjohnson/clock/LICENSE
  vendor/github.com/benbjohnson/clock/README.md
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/github.com/benbjohnson/clock/context.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/array.go
  vendor/go.uber.org/zap/array_go118.go
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/error.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/internal/stacktrace/stack.go
  vendor/go.uber.org/zap/internal/ztest/clock.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sink.go
  vendor/go.uber.org/zap/writer.go
  vendor/go.uber.org/zap/zapcore/core.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/lazy_with.go
  vendor/google.golang.org/api/internal/creds.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/grpc/dial_appengine.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/google.golang.org/api/transport/http/dial_appengine.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.pb.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.proto
  vendor/google.golang.org/appengine/socket/doc.go
  vendor/google.golang.org/appengine/socket/socket_classic.go
  vendor/google.golang.org/appengine/socket/socket_vm.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7263 Adding description for the built-in event types of our duck sources
  config/core/resources/apiserversource.yaml
  config/core/resources/pingsource.yaml
Labels: size/M, approved, lgtm

#7267 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7269 Option to specify different namespace for resources
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/delivery/delivery.yaml
  test/rekt/resources/pingsource/pingsource.yaml
  test/rekt/resources/pingsource/pingsource_test.go
  test/rekt/resources/source/source.go
  test/rekt/resources/subscription/subscription.go
  test/rekt/resources/subscription/subscription.yaml
Labels: size/M, approved, lgtm, area/test-and-release

#7271 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7272 Subscription allows overriding namespace for Subscriber and Reply
  test/rekt/resources/subscription/subscription.go
  test/rekt/resources/subscription/subscription.yaml
Labels: approved, size/XS, lgtm, area/test-and-release

#7275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7279 Fail when ApiServerSource adapter can't retrieve resources
  pkg/adapter/apiserver/adapter.go
Labels: approved, size/XS, lgtm

#7280 Fix event dispatcher library data race
  pkg/kncloudevents/event_dispatcher.go
Labels: approved, size/XS, lgtm

#7281 Scheduler: fix reserved replicas handling, blocking autoscaler and overcommitted pods
  pkg/scheduler/state/state.go
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, size/L, lgtm

#7213 Filters created once
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/eventfilter/attributes/filter.go
  pkg/eventfilter/filter.go
  pkg/eventfilter/subscriptionsapi/all_filter.go
  pkg/eventfilter/subscriptionsapi/all_filter_test.go
  pkg/eventfilter/subscriptionsapi/any_filter.go
  pkg/eventfilter/subscriptionsapi/cesql_filter.go
  pkg/eventfilter/subscriptionsapi/exact_filter.go
  pkg/eventfilter/subscriptionsapi/filters_map.go
  pkg/eventfilter/subscriptionsapi/filters_map_test.go
  pkg/eventfilter/subscriptionsapi/no_filter.go
  pkg/eventfilter/subscriptionsapi/no_filter_test.go
  pkg/eventfilter/subscriptionsapi/not_filter.go
  pkg/eventfilter/subscriptionsapi/prefix_filter.go
  pkg/eventfilter/subscriptionsapi/suffix_filter.go
Labels: approved, size/L, lgtm

#7274 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#7286 Fixed logic to choose whether to use filter or filters for a trigger
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
Labels: approved, lgtm, size/S

#7243 Moved new trigger filters tests to rekt from experimental
  config/core/configmaps/features.yaml
  test/experimental/eventtype_autocreate_test.go
  test/rekt/features/new_trigger_filters/feature.go
  test/rekt/features/new_trigger_filters/filters.go
  test/rekt/new_trigger_filters_test.go
  test/rekt/resources/broker/broker.go
Labels: size/M, approved, lgtm, area/test-and-release

#7297 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/api/internal/s2a.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/option/internaloption/internaloption.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7296 Add audience field for Subscriber and Reply to `SubscriberSpec` and `SubscriptionStatusPhysicalSubscription`
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/resources/channel.yaml
  config/core/resources/subscription.yaml
  docs/eventing-api.md
  pkg/apis/duck/v1/subscribable_types.go
  pkg/apis/duck/v1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1/subscription_types.go
  pkg/apis/messaging/v1/zz_generated.deepcopy.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/subscription.go
Labels: approved, size/L, lgtm

#7278 Add helpers to work with service accounts for OIDC
  pkg/auth/serviceaccount.go
  pkg/auth/serviceaccount_test.go
Labels: approved, size/L, lgtm

#7301 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/github.com/googleapis/enterprise-certificate-proxy/client/client.go
  vendor/github.com/googleapis/enterprise-certificate-proxy/client/util/util.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/knative.dev/hack/README.md
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7287 Add AuthStatus to OIDC identity providing resources
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/resources/apiserversource.yaml
  config/core/resources/channel.yaml
  config/core/resources/containersource.yaml
  config/core/resources/parallel.yaml
  config/core/resources/pingsource.yaml
  config/core/resources/sequence.yaml
  config/core/resources/sinkbindings.yaml
  config/core/resources/subscription.yaml
  config/core/resources/trigger.yaml
  docs/eventing-api.md
  pkg/apis/duck/v1/subscribable_types.go
  pkg/apis/duck/v1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/zz_generated.deepcopy.go
  pkg/apis/flows/v1/parallel_types.go
  pkg/apis/flows/v1/sequence_types.go
  pkg/apis/flows/v1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1/subscription_types.go
  pkg/apis/messaging/v1/zz_generated.deepcopy.go
Labels: approved, size/L, lgtm, ok-to-test

#7312 Improved suffix benchmark performance
  pkg/eventfilter/subscriptionsapi/suffix_filter.go
Labels: approved, lgtm, size/S

#7300 All filter optimization
  pkg/eventfilter/benchmarks/all_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/common_benchmark_test.go
  pkg/eventfilter/subscriptionsapi/all_filter.go
Labels: size/M, approved, lgtm

#7299 Trigger create and expose OIDC service account
  pkg/apis/eventing/v1/trigger_lifecycle.go
  pkg/apis/eventing/v1/trigger_lifecycle_test.go
  pkg/auth/serviceaccount.go
  pkg/auth/serviceaccount_test.go
  pkg/reconciler/broker/trigger/controller.go
  pkg/reconciler/broker/trigger/controller_test.go
  pkg/reconciler/broker/trigger/trigger.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/testing/v1/trigger.go
Labels: approved, size/L, lgtm

#7205 Any filter optimization
  pkg/eventfilter/benchmarks/all_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/any_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/attributes_benchmark_test.go
  pkg/eventfilter/benchmarks/common_benchmark_test.go
  pkg/eventfilter/benchmarks/exact_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/not_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/prefix_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/suffix_filter_benchmark_test.go
  pkg/eventfilter/subscriptionsapi/any_filter.go
Labels: approved, size/L, lgtm

#7318 Add audience field in Destinations to CRDs
  config/core/resources/apiserversource.yaml
  config/core/resources/containersource.yaml
  config/core/resources/pingsource.yaml
  config/core/resources/sinkbindings.yaml
  config/core/resources/subscription.yaml
  config/core/resources/trigger.yaml
Labels: approved, lgtm, size/S
