Repository knative/eventing, pull requests merged in 2023-10, with the labels that each got.

#7317 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/istio_quit.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7316 Add marker for Trigger to mark `OIDCIdentity` condition as not supported
  pkg/apis/eventing/v1/trigger_lifecycle.go
  pkg/apis/eventing/v1/trigger_lifecycle_test.go
  pkg/reconciler/testing/v1/trigger.go
Labels: approved, lgtm, size/S

#7319 Use `mt-broker-filter` as the Audience of a Triggers Subscriptions Subscriber
  pkg/reconciler/broker/trigger/trigger.go
  pkg/reconciler/broker/trigger/trigger_test.go
Labels: size/M, approved, lgtm

#7315 Add library for OIDC token management
  go.mod
  go.sum
  hack/create-kind-cluster.sh
  pkg/auth/token_provider.go
  pkg/auth/token_verifier.go
  third_party/VENDOR-LICENSE/github.com/coreos/go-oidc/v3/oidc/LICENSE
  third_party/VENDOR-LICENSE/github.com/coreos/go-oidc/v3/oidc/NOTICE
  third_party/VENDOR-LICENSE/github.com/go-jose/go-jose/v3/LICENSE
  third_party/VENDOR-LICENSE/github.com/go-jose/go-jose/v3/json/LICENSE
  vendor/github.com/coreos/go-oidc/v3/LICENSE
  vendor/github.com/coreos/go-oidc/v3/NOTICE
  vendor/github.com/coreos/go-oidc/v3/oidc/jose.go
  vendor/github.com/coreos/go-oidc/v3/oidc/jwks.go
  vendor/github.com/coreos/go-oidc/v3/oidc/oidc.go
  vendor/github.com/coreos/go-oidc/v3/oidc/verify.go
  vendor/github.com/go-jose/go-jose/v3/.gitignore
  vendor/github.com/go-jose/go-jose/v3/.golangci.yml
  vendor/github.com/go-jose/go-jose/v3/.travis.yml
  vendor/github.com/go-jose/go-jose/v3/BUG-BOUNTY.md
  vendor/github.com/go-jose/go-jose/v3/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v3/LICENSE
  vendor/github.com/go-jose/go-jose/v3/README.md
  vendor/github.com/go-jose/go-jose/v3/asymmetric.go
  vendor/github.com/go-jose/go-jose/v3/cipher/cbc_hmac.go
  vendor/github.com/go-jose/go-jose/v3/cipher/concat_kdf.go
  vendor/github.com/go-jose/go-jose/v3/cipher/ecdh_es.go
  vendor/github.com/go-jose/go-jose/v3/cipher/key_wrap.go
  vendor/github.com/go-jose/go-jose/v3/crypter.go
  vendor/github.com/go-jose/go-jose/v3/doc.go
  vendor/github.com/go-jose/go-jose/v3/encoding.go
  vendor/github.com/go-jose/go-jose/v3/json/LICENSE
  vendor/github.com/go-jose/go-jose/v3/json/README.md
  vendor/github.com/go-jose/go-jose/v3/json/decode.go
  vendor/github.com/go-jose/go-jose/v3/json/encode.go
  vendor/github.com/go-jose/go-jose/v3/json/indent.go
  vendor/github.com/go-jose/go-jose/v3/json/scanner.go
  vendor/github.com/go-jose/go-jose/v3/json/stream.go
  vendor/github.com/go-jose/go-jose/v3/json/tags.go
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jwk.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/github.com/go-jose/go-jose/v3/opaque.go
  vendor/github.com/go-jose/go-jose/v3/shared.go
  vendor/github.com/go-jose/go-jose/v3/signing.go
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, area/test-and-release

#7332 Update Kubernetes min version in KinD e2e tests to 1.26.6
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#7309 Prefix filter optimizations
  pkg/eventfilter/filter.go
  pkg/eventfilter/subscriptionsapi/prefix_filter.go
Labels: size/M, approved, lgtm

#7311 Optimized the exact filter performance
  pkg/eventfilter/subscriptionsapi/exact_filter.go
Labels: approved, lgtm, size/S

#7337 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7335 Use expiring cache with the OIDC tokens
  pkg/auth/token_provider.go
Labels: approved, lgtm, size/S

#7340 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7342 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7325 Remove unnecessary filter accumulation logic
  pkg/eventfilter/filter.go
  pkg/eventfilter/subscriptionsapi/all_filter.go
  pkg/eventfilter/subscriptionsapi/any_filter.go
Labels: size/M, approved, lgtm

#7328 Update `kncloudevents.Dispatcher` to add a JWT
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
  pkg/channel/fanout/fanout_event_handler.go
  pkg/channel/fanout/fanout_event_handler_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_event_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_event_handler_test.go
  pkg/inmemorychannel/event_dispatcher_test.go
  pkg/kncloudevents/event_dispatcher.go
  pkg/kncloudevents/event_dispatcher_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#7345 Workaround for cert-manager update spec issue
  config/brokers/mt-channel-broker-tls/broker-filter-tls-certificate.yaml
  config/brokers/mt-channel-broker-tls/broker-ingress-tls-certificate.yaml
  config/channels/in-memory-channel-tls/imc-dispatcher-tls-certificate.yaml
Labels: approved, lgtm, size/S

#7346 [release-1.11] TLS certificate rotation tests (#7103)
  test/config-transport-encryption/features.yaml
  test/e2e-common.sh
  test/e2e-rekt-tests.sh
  test/e2e-upgrade-tests.sh
  test/rekt/broker_test.go
  test/rekt/channel_test.go
  test/rekt/features/broker/eventing_tls_feature.go
  test/rekt/features/channel/eventing_tls_feature.go
  test/rekt/features/featureflags/featureflags.go
  test/rekt/resources/addressable/addressable.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/channel_impl/channel_impl.go
  test/rekt/resources/subscription/subscription.go
  test/rekt/resources/subscription/subscription.yaml
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/LICENSE
  vendor/knative.dev/reconciler-test/resources/certificate/certificate.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, area/test-and-release

#7347 Update dependencies
  go.mod
  go.sum
  test/rekt/features/apiserversource/webhook_validation_smoke.go
  test/rekt/features/broker/data_plane.go
  test/rekt/features/broker/feature.go
  test/rekt/features/channel/data_plane.go
  test/rekt/features/channel/features.go
  test/rekt/features/knconf/data_plane.go
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets.go
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/filecredsource.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/header.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/urlcredsource.go
  vendor/golang.org/x/oauth2/google/internal/externalaccountauthorizeduser/externalaccountauthorizeduser.go
  vendor/golang.org/x/oauth2/google/internal/stsexchange/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/stsexchange/sts_exchange.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/manifest/manifest.go
  vendor/knative.dev/reconciler-test/pkg/resources/serviceaccount/serviceaccount.go
  vendor/knative.dev/reconciler-test/pkg/resources/serviceaccount/serviceaccount.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, area/test-and-release

#7357 Remove unneeded configmapinformer in sinkbinding controller
  pkg/reconciler/sinkbinding/controller.go
Labels: approved, lgtm, size/S

#7366 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7369 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7370 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/iam/apiv1/iampb/policy.pb.go
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#7338 Support auto generation of Subscriptions identity service account and…
  pkg/apis/eventing/v1/test_helper.go
  pkg/apis/flows/v1/sequence_lifecycle_test.go
  pkg/apis/messaging/v1/subscription_lifecycle.go
  pkg/apis/messaging/v1/subscription_lifecycle_test.go
  pkg/reconciler/subscription/controller.go
  pkg/reconciler/subscription/controller_test.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/subscription.go
Labels: approved, size/L, lgtm, ok-to-test

#7330 OIDC - Support auto generation of ApiServerSource identity service account and expose in AuthStatus
  pkg/apis/sources/v1/apiserver_lifecycle.go
  pkg/apis/sources/v1/apiserver_lifecycle_test.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/apiserversource/controller_test.go
  pkg/reconciler/testing/v1/apiserversouce.go
Labels: approved, size/L, lgtm

#7372 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7378 Update dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7355 Increase expiration buffer time of OIDCTokenProviders cache to 5 minutes
  pkg/auth/token_provider.go
Labels: approved, size/XS, lgtm, ok-to-test

#7336 mt-broker-ingress check audience of received token
  cmd/broker/ingress/main.go
  pkg/auth/utils.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
  test/auth/features/oidc/addressable_oidc_conformance.go
  test/auth/features/oidc/broker.go
  test/auth/features/oidc/features.go
  test/auth/oidc_test.go
  test/rekt/resources/addressable/addressable.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/channel_impl/channel_impl.go
Labels: approved, size/L, lgtm, area/test-and-release

#7344 OIDC - Support auto generation of PingSource identity service account and expose in AuthStatus
  pkg/adapter/mtping/pingsource_test.go
  pkg/apis/sources/v1/ping_lifecycle.go
  pkg/apis/sources/v1/ping_lifecycle_test.go
  pkg/reconciler/pingsource/controller.go
  pkg/reconciler/pingsource/pingsource.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/testing/v1/pingsource.go
Labels: approved, size/L, lgtm

#7350 Added test for multiple sinks, multiple triggers
  test/rekt/features/new_trigger_filters/feature.go
  test/rekt/new_trigger_filters_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#7379 Don't override default values when applying partial features.yaml configmap
  pkg/apis/feature/features.go
  pkg/apis/feature/features_test.go
Labels: size/M, approved, lgtm

#7388 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7367 Shell executor logs through testing.T in upgrade tests
  test/upgrade/installation/git_head.go
  test/upgrade/installation/latest.go
  test/upgrade/installation/shell.go
  third_party/VENDOR-LICENSE/knative.dev/hack/shell/LICENSE
  vendor/knative.dev/pkg/test/upgrade/shell/executor.go
  vendor/knative.dev/pkg/test/upgrade/shell/fail-example.sh
  vendor/knative.dev/pkg/test/upgrade/shell/prefixer.go
  vendor/knative.dev/pkg/test/upgrade/shell/project.go
  vendor/knative.dev/pkg/test/upgrade/shell/types.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, area/test-and-release

#7389 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/feature/logging.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7394 Support for seconds field in PingSource schedule
  pkg/adapter/mtping/adapter.go
  pkg/apis/sources/v1/ping_validation.go
  pkg/apis/sources/v1/ping_validation_test.go
  pkg/apis/sources/v1beta2/ping_validation.go
  pkg/apis/sources/v1beta2/ping_validation_test.go
  test/rekt/features/pingsource/features.go
  test/rekt/pingsource_test.go
  test/rekt/resources/pingsource/pingsource_test.go
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test

#7419 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_linux.go
  vendor/github.com/golang/glog/glog_file_other.go
  vendor/github.com/golang/glog/glog_file_posix.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_picker.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_util.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/manual/manual.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/101-rbac.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7397 Refactored new filter tests to all use the same helper functions
  test/rekt/features/new_trigger_filters/feature.go
Labels: size/M, approved, lgtm, area/test-and-release
