Repository knative/eventing, pull requests merged in 2023-02, with the labels that each got.

#6709 Port BrokerWorkFlowWithTranformation test to rekt and code cleanup
  test/e2e/broker_event_transformation_test.go
  test/e2e/helpers/broker_event_transformation_test_helper.go
  test/rekt/broker_test.go
  test/rekt/features/broker/feature.go
Labels: approved, size/L, lgtm, area/test-and-release

#6710 Remove UNUSED and deprecated test helpers
  test/e2e/helpers/channel_chain_test_helper.go
  test/e2e/helpers/channel_dls_test_helper.go
Labels: approved, size/L, lgtm, area/test-and-release

#6705 Set scheduler logging to debug
  pkg/scheduler/statefulset/scheduler.go
Labels: approved, size/XS, lgtm

#6701 Default a subscriptions subscriber and reply in webhook
  go.mod
  go.sum
  pkg/apis/messaging/v1/subscription_defaults.go
  pkg/apis/messaging/v1/subscription_defaults_test.go
  pkg/reconciler/subscription/subscription.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6716 Removing deprecated and unused func
  pkg/kncloudevents/message_sender.go
Labels: approved, size/XS, lgtm

#6718 Removing one more deprecated, unused func
  pkg/duck/listable.go
Labels: approved, size/XS, lgtm

#6724 Revert "Change subscription patch logic to ensure resource version (#6670)
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/subscription.go
Labels: approved, size/L, lgtm

#6725 [release-1.9] Revert "Change subscription patch logic to ensure resource version (#6670)
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/subscription.go
Labels: approved, size/L, lgtm

#6727 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#6723 Added Broker class in `kubectl get -o wide`
  config/core/resources/broker.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#6726 Scheduler doesn't reschedule vpods that are scheduled on unscehdulable pods
  pkg/scheduler/state/state.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
Labels: size/M, approved, lgtm

#6729 Improve scheduler logging for state and pending vpods
  pkg/scheduler/scheduler.go
  pkg/scheduler/state/state.go
  pkg/scheduler/statefulset/scheduler.go
Labels: size/M, approved, lgtm

#6737 Add function to check if a broker resource is `NotReady`
  test/rekt/resources/broker/broker.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6736 Extract scheduler config in a dedicate struct instead of many parameters
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/autoscaler_test.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, size/L, lgtm

#6715 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/shell/executor.go
  vendor/knative.dev/reconciler-test/pkg/k8s/job.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.go
  vendor/knative.dev/reconciler-test/pkg/resources/service/service.yaml
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/knative.dev/reconciler-test/resources/svc/service.yaml
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6696 Adds apiVersion as an extension to api source events
  pkg/adapter/apiserver/events/events.go
  pkg/adapter/apiserver/events/events_test.go
  test/rekt/features/apiserversource/data_plane.go
Labels: size/M, approved, lgtm, area/test-and-release

#6743 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6752 [release-1.7] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/clock/clock.go
  vendor/knative.dev/pkg/apis/duck/v1alpha1/legacy_targetable_types.go
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/apis/testing/fuzzer/fuzzer.go
  vendor/knative.dev/pkg/apis/testing/roundtrip/roundtrip.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/hash-gen/main.go
  vendor/knative.dev/pkg/configmap/load.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/configmap/testing/configmap.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/ghutil/client.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/mako/config/benchmark.go
  vendor/knative.dev/pkg/test/slackutil/http.go
  vendor/knative.dev/pkg/test/slackutil/message_read.go
  vendor/knative.dev/pkg/test/slackutil/message_write.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/testing/zipkin.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/webhook/psbinding/doc.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#6751 Remove unused event-library
  test/test_images/event-library/kodata/events/doc.go
  test/test_images/event-library/kodata/events/three.ce
  test/test_images/event-library/main.go
Labels: size/M, approved, lgtm, area/test-and-release

#6750 Remove event flaker since eventshub offers an equivalent feature
  test/rekt/features/broker/source_to_sink.go
  test/rekt/resources/flaker/flaker.go
  test/rekt/resources/flaker/flaker.yaml
  test/rekt/resources/flaker/flaker_test.go
  test/test_images/event-flaker/main.go
Labels: approved, size/L, lgtm, area/test-and-release

#6747 Deprecate `test/rekt/resources/pod` package
  go.mod
  go.sum
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/resources/pod/pod.go
  test/rekt/resources/pod/pod.yaml
  test/rekt/resources/pod/pod_test.go
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/pkg/LICENSE
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/reconciler-test/pkg/eventshub/prober.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/pod/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/pod/pod.go
  vendor/knative.dev/reconciler-test/pkg/resources/pod/pod.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/service/options.go
  vendor/knative.dev/reconciler-test/resources/svc/service.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, area/test-and-release

#6753 Update dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/images.go
  vendor/knative.dev/reconciler-test/pkg/environment/standard.go
  vendor/knative.dev/reconciler-test/pkg/images/file/file.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6748 Deprecate `test/rekt/resources/deployment`
  test/rekt/features/sinkbinding/feature.go
  test/rekt/resources/deployment/deployment.go
  test/rekt/resources/deployment/deployment.yaml
  test/rekt/resources/deployment/deployment_test.go
  test/rekt/sink_binding_test.go
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/deployment.go
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/deployment.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/options.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, area/test-and-release

#6742 Deprecate `test/rekt/resources/svc`
  test/rekt/resources/svc/service.go
  test/rekt/resources/svc/service.yaml
  test/rekt/resources/svc/service_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6756 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6744 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/reconciler.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/environment/istio.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/standard.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/deployment.go
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/pod/pod.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6762 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6765 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/k8s/wait.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#6764 Allow event display to log requests
  cmd/event_display/main.go
  cmd/event_display/main_test.go
Labels: approved, size/L, lgtm

#6767 Exclusive access to tracing flag for upgrade prober
  test/upgrade/prober/verify.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6769 Pass EnvConfig to Broker conformance tests
  test/rekt/broker_test.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6770 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/controller.go
  pkg/client/injection/reconciler/eventing/v1/trigger/controller.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/controller.go
  pkg/client/injection/reconciler/flows/v1/parallel/controller.go
  pkg/client/injection/reconciler/flows/v1/sequence/controller.go
  pkg/client/injection/reconciler/messaging/v1/channel/controller.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/controller.go
  pkg/client/injection/reconciler/messaging/v1/subscription/controller.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/controller.go
  pkg/client/injection/reconciler/sources/v1/containersource/controller.go
  pkg/client/injection/reconciler/sources/v1/pingsource/controller.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/controller.go
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6780 Remove deprecated usage of ZipkinTracingEnabled
  test/upgrade/prober/verify.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6758 Fixes issue where a CE response is truncated
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  test/rekt/broker_test.go
  test/rekt/features/broker/feature.go
Labels: approved, size/L, lgtm, area/test-and-release

#6783 [release-1.8] Fixes issue where a CE response is truncated #6782
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  test/rekt/broker_test.go
  test/rekt/features/broker/feature.go
Labels: approved, size/L, lgtm, area/test-and-release

#6784 [release-1.9] Fixes issue where a CE response is truncated
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  test/rekt/broker_test.go
  test/rekt/features/broker/feature.go
Labels: approved, size/L, lgtm, area/test-and-release
