Repository knative/eventing, pull requests merged in 2023-08, with the labels that each got.

#7132 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7125 Watch config-features in IMC controller
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/controller_test.go
Labels: size/M, approved, lgtm

#7126 Global resync brokers on config-features changes
  pkg/reconciler/broker/controller.go
Labels: approved, lgtm, size/S

#7136 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#7092 Refactor kncloudevents and add `SendEvent` function
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/filter/server_manager.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/server_manager.go
  pkg/channel/event_receiver.go
  pkg/channel/event_receiver_test.go
  pkg/channel/fanout/fanout_event_handler.go
  pkg/channel/fanout/fanout_event_handler_test.go
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_various_response_benchmark_test.go
  pkg/channel/multichannelfanout/multi_channel_fanout_event_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_event_handler_test.go
  pkg/eventingtls/eventingtlstesting/eventingtlstesting.go
  pkg/eventingtls/servermanager_test.go
  pkg/inmemorychannel/event_dispatcher.go
  pkg/inmemorychannel/event_dispatcher_test.go
  pkg/kncloudevents/attributes/knative_error.go
  pkg/kncloudevents/attributes/knative_error_test.go
  pkg/kncloudevents/event_dispatcher.go
  pkg/kncloudevents/event_dispatcher_test.go
  pkg/kncloudevents/event_receiver.go
  pkg/kncloudevents/event_receiver_test.go
  pkg/kncloudevents/message_sender_new.go
  pkg/kncloudevents/utils.go
  pkg/kncloudevents/utils_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/readiness.go
  pkg/reconciler/inmemorychannel/dispatcher/readiness_test.go
  pkg/utils/headers.go
  third_party/VENDOR-LICENSE/github.com/valyala/bytebufferpool/LICENSE
Labels: approved, lgtm, size/XXL

#7131 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7140 Use correct cluster domain in e2e tests
  hack/create-kind-cluster.sh
  test/rekt/features/broker/feature.go
  test/rekt/features/channel/features.go
  test/upgrade/prober/configuration.go
  test/upgrade/prober/verify.go
Labels: approved, lgtm, size/S, area/test-and-release

#7103 TLS certificate rotation tests
  test/config-transport-encryption/features.yaml
  test/e2e-common.sh
  test/e2e-rekt-tests.sh
  test/e2e-upgrade-tests.sh
  test/rekt/broker_test.go
  test/rekt/channel_test.go
  test/rekt/features/broker/eventing_tls_feature.go
  test/rekt/features/channel/eventing_tls_feature.go
  test/rekt/features/featureflags/featureflags.go
  test/rekt/resources/addressable/addressable.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/channel_impl/channel_impl.go
  test/rekt/resources/subscription/subscription.go
  test/rekt/resources/subscription/subscription.yaml
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/LICENSE
  vendor/knative.dev/reconciler-test/resources/certificate/certificate.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, area/test-and-release

#7121 Benchmark Base SubscriptionsAPI filters
  pkg/eventfilter/benchmarks/exact_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/not_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/prefix_filter_benchmark_test.go
  pkg/eventfilter/benchmarks/suffix_filter_benchmark_test.go
Labels: approved, size/L, lgtm

#7144 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/102-service.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_log.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub_image.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/101-rbac.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/resources/knativeservice/ksvc.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7148 Fix retryAfter experimental e2e test
  test/experimental/features/retry_after/channel.go
Labels: approved, size/XS, lgtm, area/test-and-release

#7150 Install Kail from source in test_setup
  test/e2e-common.sh
Labels: approved, size/XS, lgtm, area/test-and-release

#7146 Remove deprecated kncloudevents.CloudEventsRequest
  go.mod
  go.sum
  pkg/kncloudevents/http_client.go
  pkg/kncloudevents/http_client_test.go
  pkg/kncloudevents/message_sender_new.go
  pkg/kncloudevents/message_sender_new_test.go
  pkg/kncloudevents/retries.go
  pkg/kncloudevents/retries_test.go
  pkg/kncloudevents/utils.go
  pkg/kncloudevents/utils_test.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/acks_before_finish_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/binary_buffer_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/copy_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/buffering/struct_buffer_message.go
  vendor/github.com/valyala/bytebufferpool/.travis.yml
  vendor/github.com/valyala/bytebufferpool/LICENSE
  vendor/github.com/valyala/bytebufferpool/README.md
  vendor/github.com/valyala/bytebufferpool/bytebuffer.go
  vendor/github.com/valyala/bytebufferpool/doc.go
  vendor/github.com/valyala/bytebufferpool/pool.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7152 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7137 Rename knative-sandbox to knative-extensions
  .github/workflows/knative-downstream.yaml
  DEVELOPMENT.md
  docs/decisions/broker-trigger.md
  docs/metrics.md
  docs/source/receive-adapter.md
  pkg/scheduler/README.md
  test/e2e/helpers/README.md
  test/rekt/README.md
Labels: approved, lgtm, size/S, area/test-and-release

#7155 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/105-certificate-service.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7138 Update to kind v0.20.0
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#7157 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/gobuffalo/flect/README.md
  vendor/github.com/gobuffalo/flect/SHOULDERS.md
  vendor/github.com/gobuffalo/flect/camelize.go
  vendor/github.com/gobuffalo/flect/custom_data.go
  vendor/github.com/gobuffalo/flect/humanize.go
  vendor/github.com/gobuffalo/flect/pascalize.go
  vendor/github.com/gobuffalo/flect/plural_rules.go
  vendor/github.com/gobuffalo/flect/pluralize.go
  vendor/github.com/gobuffalo/flect/rule.go
  vendor/github.com/gobuffalo/flect/singular_rules.go
  vendor/github.com/gobuffalo/flect/singularize.go
  vendor/github.com/gobuffalo/flect/titleize.go
  vendor/github.com/gobuffalo/flect/underscore.go
  vendor/github.com/gobuffalo/flect/version.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_loong64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7162 Added .env files to the gitignore
  .gitignore
Labels: approved, size/XS, lgtm

#7160 Fix unique name generator for auto-created EventType
  pkg/eventtype/eventtypes.go
  pkg/eventtype/eventtypes_test.go
Labels: kind/bug, approved, size/L, lgtm

#7151 Test ApiServerSource with Broker as sink
  test/rekt/apiserversource_test.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/resources/broker/broker.go
Labels: approved, size/L, lgtm, area/test-and-release

#7135 Create new trigger rekt helper functions
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger.yaml
  test/rekt/resources/trigger/trigger_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#7171 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7183 Add OIDC Authentication feature flag
  config/core/configmaps/features.yaml
  pkg/apis/feature/features.go
  pkg/apis/feature/flag_names.go
Labels: approved, size/XS, lgtm, ok-to-test

#7139 Add kind e2e tests for Kubernetes v1.27.3
  .github/workflows/kind-e2e.yaml
  hack/create-kind-cluster.sh
Labels: approved, lgtm, size/S, area/test-and-release

#7188 Switch to trigger.WithNewFilters() to set trigger filter
  test/experimental/features/new_trigger_filters/filters.go
Labels: size/M, approved, lgtm, area/test-and-release

#7179 change the deprecated string
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/pingsource/features.go
  test/rekt/resources/eventtype/eventtype.go
Labels: approved, size/XS, lgtm, area/test-and-release, ok-to-test

#7172 Eventing TLS: Test SinkBinding with Broker as sink
  test/rekt/features/sinkbinding/feature.go
  test/rekt/resources/sinkbinding/sinkbinding.go
  test/rekt/sink_binding_test.go
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#7190 Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/reconciler-test/pkg/manifest/options.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7195 Added benchmark for any filter
  pkg/eventfilter/benchmarks/any_filter_benchmark_test.go
Labels: size/M, approved, lgtm

#7161 Broker eventtype autocreate fixes
  cmd/broker/ingress/main.go
  pkg/broker/ingress/ingress_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: size/M, approved, lgtm

#7198 Added rekt test for channel event autocreate
  test/experimental/config/features.yaml
  test/experimental/eventtype_autocreate_test.go
  test/experimental/features/eventtype_autocreate/features.go
Labels: approved, size/L, lgtm, area/test-and-release

#7130 Add rekt test for "Any" filter
  test/experimental/features/new_trigger_filters/feature.go
  test/experimental/features/new_trigger_filters/filters.go
  test/experimental/new_trigger_filters_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#7201 [release-v1.11] Cherry pick eventtype autocreate fixes
  cmd/broker/ingress/main.go
  pkg/broker/ingress/ingress_handler.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: size/M, approved, lgtm

#7180 Move eventtype rekttest pingsource to experiment
  test/experimental/eventtype_autocreate_test.go
  test/experimental/features/eventtype_autocreate/features.go
  test/rekt/features/pingsource/features.go
  test/rekt/pingsource_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#7206 [main] Format Go code
  test/rekt/features/pingsource/features.go
Labels: approved, size/XS, lgtm, area/test-and-release

#7202 Added rekt test for broker eventtype autocreate
  test/experimental/eventtype_autocreate_test.go
  test/experimental/features/eventtype_autocreate/features.go
Labels: size/M, approved, lgtm, area/test-and-release

#7215 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/openzipkin/zipkin-go/.golangci.yml
  vendor/github.com/openzipkin/zipkin-go/README.md
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7027 Autoscaler considers reserved and pending replicas
  pkg/scheduler/state/state.go
  pkg/scheduler/state/state_test.go
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/autoscaler_test.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, size/L, lgtm
