Repository knative/eventing, pull requests merged in 2023-03, with the labels that each got.

#6722 Removes the deprecated DeadLetterChannel in ChannelableStatus
  docs/eventing-api.md
  pkg/apis/duck/v1/channelable_types.go
  pkg/apis/duck/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S, ok-to-test

#6789 No reason for API ServerSource adapter to not inject istio sidecar
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, size/XS, lgtm

#6788 SC settings for ApiServerSource's Receive Adapter's container/deployment
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: approved, lgtm, size/S

#6794 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/reconciler-test/pkg/environment/flags.go
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
  vendor/knative.dev/reconciler-test/pkg/environment/standard.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6800 Migrate to rekt cronjob package
  test/rekt/features/sinkbinding/feature.go
  test/rekt/resources/job/job.go
  test/rekt/resources/job/job.yaml
  test/rekt/resources/job/job_test.go
  test/rekt/sink_binding_test.go
  vendor/knative.dev/reconciler-test/pkg/resources/cronjob/cronjob.go
  vendor/knative.dev/reconciler-test/pkg/resources/cronjob/cronjob.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/cronjob/options.go
  vendor/knative.dev/reconciler-test/pkg/resources/job/job.go
  vendor/knative.dev/reconciler-test/pkg/resources/job/job.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/job/options.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, area/test-and-release

#6802 Fix pod annotations in containersource template
  test/rekt/features/containersource/features.go
  test/rekt/resources/containersource/containersource.yaml
Labels: approved, size/XS, lgtm, area/test-and-release

#6805 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6799 Add rekt based broker conformance test to ensure `broker.spec.config` is immutable
  test/rekt/features/broker/control_plane.go
Labels: size/M, approved, lgtm, area/test-and-release

#6804 Heartbeats: quit istio proxy when running in a job
  cmd/heartbeats/main.go
  test/rekt/features/sinkbinding/feature.go
Labels: approved, lgtm, size/S, area/test-and-release

#6809 Add basic retry support for hearthbeats utility
  cmd/heartbeats/main.go
Labels: approved, size/XS, lgtm

#6786 updated broken link
  docs/delivery/README.md
  docs/source/receive-adapter.md
  test/README.md
  test/performance/README.md
Labels: approved, lgtm, size/S, area/test-and-release, ok-to-test

#6808 Use released hearthbeats image for testing
  cmd/heartbeats/main.go
  test/rekt/features/sinkbinding/feature.go
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/resources/containersource/containersource_test.go
  test/rekt/resources/deployment/deployment.go
  test/test_images/heartbeats/main.go
  test/test_images/heartbeats/pod.yaml
Labels: approved, size/L, lgtm, area/test-and-release

#6812 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/env.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6814 Make autoscaler leader aware
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/autoscaler_test.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, size/L, lgtm

#6795 Removes replace and ran `go vendor`
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/README.md
  vendor/github.com/prometheus/client_golang/prometheus/build_info_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go117.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, ok-to-test

#6810 fix api docs generation with go1.20
  pkg/apis/doc.go
Labels: approved, lgtm, size/S

#6819 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#6817 Add sequence reconciler test
  test/rekt/features/parallel/features.go
  test/rekt/features/sequence/feature.go
  test/rekt/resources/channel_template/channel_template.go
  test/rekt/resources/parallel/parallel.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/sequence_test.go
  test/rekt/smoke_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6827 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#6828 parallel rekt test cleanup
  test/rekt/features/parallel/features.go
  test/rekt/parallel_test.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6816 Removes the deprecated packages
  test/rekt/resources/deployment/deployment.go
  test/rekt/resources/pod/pod.go
  test/rekt/resources/svc/service.go
  test/rekt/smoke_test.go
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test

#6830 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6832 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S
