Repository knative/eventing, pull requests merged in 2023-07, with the labels that each got.

#7077 Add tracing for TestBrokerWithManyTriggers
  test/rekt/broker_test.go
  test/rekt/features/broker/feature.go
  test/rekt/main_test.go
  vendor/knative.dev/reconciler-test/pkg/tracing/tracing.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, area/test-and-release

#7080 Fix flaky unit tests
  pkg/adapter/mtping/runner_test.go
  pkg/channel/message_dispatcher_test.go
  pkg/eventingtls/eventingtlstesting/utils.go
Labels: approved, size/L, lgtm

#7036 Updated mtping TLS cert test to bind to free port
  pkg/adapter/mtping/runner_test.go
Labels: approved, size/XS, lgtm

#7079 Add loopclosure linter
  .golangci.yaml
Labels: approved, size/XS, lgtm

#6986 feat!: Add tls support for ingress
  cmd/broker/ingress/main.go
  config/brokers/mt-channel-broker/200-ingress-roles.yaml
  config/brokers/mt-channel-broker/200-ingress-roles.yaml~cd5b396a2 (added tls support for ingress)
  config/brokers/mt-channel-broker/201-ingress-rolebinding.yaml
  config/brokers/mt-channel-broker/201-ingress-rolebinding.yaml~cd5b396a2 (added tls support for ingress)
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/brokers/mt-channel-broker/roles/ingress-role.yaml
  config/brokers/mt-channel-broker/roles/ingress-rolebinding.yaml
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
  pkg/broker/ingress/server_manager.go
Labels: approved, size/L, lgtm, area/test-and-release

#7081 Move ingress & filter TLS secret names into constants
  pkg/broker/filter/server_manager.go
  pkg/broker/ingress/server_manager.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/broker/trigger/trigger.go
  pkg/reconciler/broker/trigger/trigger_test.go
Labels: size/M, approved, lgtm

#7085 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7083 Revert "Add loopclosure linter"
  .golangci.yaml
Labels: approved, size/XS, lgtm

#7087 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7088 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7086 Convert tls secret names to constants
  pkg/broker/filter/server_manager.go
  pkg/broker/ingress/server_manager.go
  pkg/eventingtls/eventingtls.go
  pkg/reconciler/broker/trigger/trigger.go
  pkg/reconciler/broker/trigger/trigger_test.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: size/M, approved, lgtm

#7002 Function CopySecretWithName for creating secrets with specific name
  pkg/utils/secret.go
Labels: approved, lgtm, size/S

#7082 Re-enable PingSource TLS E2E test
  pkg/adapter/mtping/runner.go
  pkg/adapter/mtping/runner_test.go
  pkg/adapter/v2/cloudevents.go
  pkg/adapter/v2/cloudevents_test.go
  test/e2e-common.sh
  test/rekt/pingsource_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#7100 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_info_store.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7045 Tag line proposal
  README.md
Labels: approved, lgtm, size/S

#7104 Eventing TLS: Configure certificates to force rotate private keys
  config/brokers/mt-channel-broker-tls/broker-filter-tls-certificate.yaml
  config/brokers/mt-channel-broker-tls/broker-ingress-tls-certificate.yaml
  config/channels/in-memory-channel-tls/imc-dispatcher-tls-certificate.yaml
Labels: approved, size/XS, lgtm

#7109 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7105 Eventing TLS: Configure CRDs to have addresses and CA certs
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/resources/broker.yaml
  config/core/resources/channel.yaml
  config/core/resources/parallel.yaml
  config/core/resources/sequence.yaml
  config/core/resources/subscription.yaml
Labels: size/M, approved, lgtm

#7116 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7018 Remove deprecated httpclient msgsender
  pkg/inmemorychannel/message_dispatcher_benchmark_test.go
  pkg/inmemorychannel/message_dispatcher_test.go
  pkg/kncloudevents/http_client.go
  pkg/kncloudevents/http_client_new.go
  pkg/kncloudevents/http_client_new_test.go
  pkg/kncloudevents/http_client_test.go
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, lgtm, size/XL, ok-to-test

#7122 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/102-service.yaml
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#7123 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7117 Introduce a script to build and deploy Eventing for local development
  DEVELOPMENT.md
  hack/install.sh
Labels: size/M, approved, lgtm, area/test-and-release
