Repository knative/eventing, pull requests merged in 2023-05, with the labels that each got.

#6901 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6898 [main] Format Go code
  pkg/adapter/v2/test/test_client.go
Labels: approved, size/XS, lgtm

#6902 Remove sanitize HTTP body for `knativeerrordata` extension
  pkg/channel/message_dispatcher.go
  pkg/channel/message_dispatcher_test.go
  test/rekt/features/channel/features.go
Labels: size/M, approved, lgtm, area/test-and-release

#6903 More EventType v1beta2 work
  cmd/webhook/main.go
  config/core/resources/eventtype.yaml
  pkg/apis/eventing/v1beta1/eventtype_conversion.go
Labels: size/M, approved, lgtm

#6904 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6905 Remove eventing-natss from downstream tests
  .github/workflows/knative-downstream.yaml
Labels: approved, size/XS, lgtm

#6907 Remove unused test helper
  pkg/reconciler/testing/eventtype.go
Labels: approved, size/L, lgtm

#6906 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/cmd/eventshub/main.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/102-service.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/event_log.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/eventshub_image.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/sender/sender.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/knative.dev/reconciler-test/pkg/resources/knativeservice/ksvc.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#6881 Eventing TLS: support exposing https address in InMemoryChannel controller
  pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  pkg/apis/messaging/v1/in_memory_channel_lifecycle_test.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/controller_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/pingsource/pingsource_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/eventingtls.go
  pkg/reconciler/testing/v1/channel.go
  pkg/reconciler/testing/v1/inmemorychannel.go
Labels: approved, size/L, lgtm, needs-ok-to-test

#6897 Eventing TLS: Added Support for setting K_CA_CERTS in the ApiServerSource controller for the adapter
  pkg/adapter/v2/config.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
  pkg/reconciler/apiserversource/resources/receive_adapter_test.go
Labels: size/M, approved, lgtm

#6910 Install ko using setup-ko in kind e2e tests
  .github/workflows/kind-e2e.yaml
Labels: approved, lgtm, size/S

#6908 Adds ServerManager. Supports http/https message receivers
  pkg/apis/feature/features.go
  pkg/eventingtls/servermanager.go
  pkg/eventingtls/servermanager_test.go
  pkg/kncloudevents/message_receiver.go
  pkg/kncloudevents/message_receiver_test.go
Labels: approved, size/L, lgtm

#6912 less verbose logs on scheduler component
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/scheduler.go
Labels: approved, lgtm, size/S

#6922 two more for reducing to debug, instead of info
  pkg/scheduler/statefulset/scheduler.go
Labels: approved, size/XS, lgtm

#6927 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_tracing.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6919 Return error directly if one receiver of servermanager fails
  pkg/eventingtls/servermanager.go
  pkg/eventingtls/servermanager_test.go
Labels: size/M, approved, lgtm

#6928 Remove CA certs empty and non nil check, use URL scheme only
  pkg/adapter/v2/cloudevents.go
  pkg/eventingtls/eventingtls.go
Labels: approved, size/XS, lgtm

#6920 Added Support for K_CA_CERTS in the heartbeats
  cmd/heartbeats/main.go
Labels: size/M, approved, lgtm

#6930 Eventing TLS: support exposing https address in Broker controller
  pkg/apis/eventing/v1/broker_lifecycle.go
  pkg/apis/eventing/v1/broker_lifecycle_test.go
  pkg/eventingtls/eventingtls.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/broker/controller.go
  pkg/reconciler/broker/controller_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/testing/v1/broker.go
Labels: approved, size/L, lgtm

#6931 Eventing TLS: Support K_CA_CERTS env variable injection for SinkBinding subjects
  pkg/apis/sources/v1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1/sinkbinding_lifecycle_test.go
  pkg/reconciler/sinkbinding/controller.go
Labels: approved, size/L, lgtm

#6946 Updating rekt test resources for EventType v1b2
  test/rekt/resources/eventtype/eventtype.go
Labels: approved, lgtm, size/S, area/test-and-release

#6949 Using v1b2 in the reconciler
  pkg/reconciler/eventtype/controller.go
  pkg/reconciler/eventtype/controller_test.go
  pkg/reconciler/eventtype/eventtype.go
  pkg/reconciler/eventtype/eventtype_test.go
  pkg/reconciler/testing/v1/eventtype.go
  pkg/reconciler/testing/v1/listers.go
Labels: size/M, approved, lgtm

#6962 Adding source duck type to v1b2
  pkg/reconciler/source/crd/crd_test.go
  pkg/reconciler/source/duck/controller.go
  pkg/reconciler/source/duck/controller_test.go
  pkg/reconciler/source/duck/duck.go
  pkg/reconciler/source/duck/duck_test.go
  pkg/reconciler/source/duck/resources/eventtype.go
  pkg/reconciler/source/duck/resources/eventtype_test.go
  pkg/reconciler/testing/v1beta2/factory.go
  pkg/reconciler/testing/v1beta2/listers.go
Labels: approved, size/L, lgtm

#6956 Eventing TLS: Test ApiServerSource with eventshub TLS receiver as sink
  DEVELOPMENT.md
  config/core/resources/apiserversource.yaml
  test/rekt/apiserversource_test.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/apiserversource/readiness.go
  test/rekt/features/apiserversource/webhook_validation_smoke.go
  test/rekt/resources/apiserversource/apiserversource.go
  test/rekt/resources/apiserversource/apiserversource.yaml
  test/rekt/resources/apiserversource/apiserversource_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6959 Add field for subscribers & replys CA certs to `SubscriberSpec` and `SubscriptionStatusPhysicalSubscription`
  docs/eventing-api.md
  pkg/apis/duck/v1/subscribable_types.go
  pkg/apis/duck/v1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1/subscription_types.go
  pkg/apis/messaging/v1/zz_generated.deepcopy.go
  pkg/reconciler/subscription/subscription.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/subscription.go
  pkg/reconciler/testing/v1/unstructured.go
Labels: approved, size/L, lgtm

#6964 Add transport-encryption prerequisite for Addressable tests
  pkg/apis/feature/features.go
  test/rekt/features/featureflags/featureflags.go
Labels: size/M, approved, lgtm, area/test-and-release

#6968 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#6966 Do not parse flags in InitializeEventingFlags
  .github/workflows/kind-e2e.yaml
  test/conformance/main_test.go
  test/e2e-tests.sh
  test/e2e/main_test.go
  test/e2e_flags.go
  test/flags/eventing_environment.go
  test/upgrade/upgrade.go
  test/upgrade/upgrade_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#6967 Use random names in Channel tests
  test/rekt/features/channel/features.go
Labels: approved, size/XS, lgtm, area/test-and-release

#6970 Fix flaky PingSource TLS unit test
  pkg/adapter/mtping/runner_test.go
Labels: approved, lgtm, size/S

#6957 Eventing TLS: Test ContainerSource with eventshub TLS receiver as sink
  config/core/resources/containersource.yaml
  config/core/resources/sinkbindings.yaml
  test/rekt/container_source_test.go
  test/rekt/features/channel/features.go
  test/rekt/features/containersource/features.go
  test/rekt/features/containersource/readyness.go
  test/rekt/resources/channel_impl/channel_impl.go
  test/rekt/resources/containersource/containersource.go
  test/rekt/resources/containersource/containersource.yaml
  test/rekt/resources/containersource/containersource_test.go
  test/rekt/resources/sinkbinding/sinkbinding.yaml
Labels: approved, size/L, lgtm, area/test-and-release

#6977 Updated DEVELOPMENT.md to provide better instructions on setting up kubernetes
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm, ok-to-test

#6976 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/environment/magic.go
  vendor/knative.dev/reconciler-test/pkg/feature/feature.go
  vendor/knative.dev/reconciler-test/pkg/milestone/emitter_tracing.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6980 Make ServerManager independent from kncloudevents package
  pkg/eventingtls/servermanager.go
  pkg/eventingtls/servermanager_test.go
Labels: approved, lgtm, size/S

#6975 Rework kncloudevents library to support multiple clients
  pkg/kncloudevents/http_client.go
  pkg/kncloudevents/http_client_new.go
  pkg/kncloudevents/http_client_new_test.go
  pkg/kncloudevents/http_client_test.go
  pkg/kncloudevents/message_sender.go
  pkg/kncloudevents/message_sender_new.go
  pkg/kncloudevents/message_sender_new_test.go
  pkg/kncloudevents/message_sender_test.go
Labels: approved, lgtm, size/XXL

#6954 imc-dispatcher starts a TLS server, accepts host based routing on http receiver and path based routing on https receiver
  config/channels/in-memory-channel/200-imc-dispatcher-serviceaccount.yaml
  config/channels/in-memory-channel/deployments/dispatcher-service.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  pkg/channel/fanout/fanout_message_handler.go
  pkg/channel/fanout/fanout_message_handler_test.go
  pkg/channel/multichannelfanout/config.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
  pkg/eventingtls/eventingtls.go
  pkg/inmemorychannel/message_dispatcher.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/readiness.go
  pkg/reconciler/inmemorychannel/dispatcher/readiness_test.go
Labels: approved, size/L, lgtm

#6978 Add more items in the development getting started documentation
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm, needs-ok-to-test

#6982 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#6965 Test PingSource with eventshub TLS receiver as sink
  config/core/resources/pingsource.yaml
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/pingsource/features.go
  test/rekt/features/pingsource/readyness.go
  test/rekt/features/sequence/feature.go
  test/rekt/features/trigger/feature.go
  test/rekt/pingsource_test.go
  test/rekt/resources/pingsource/pingsource.go
  test/rekt/resources/pingsource/pingsource.yaml
  test/rekt/resources/pingsource/pingsource_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#6990 test update to newest version
  pkg/reconciler/pingsource/controller_test.go
Labels: approved, size/XS, lgtm
