Repository knative/eventing, pull requests merged in 2024-04, with the labels that each got.

#7818 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/iam/CHANGES.md
  vendor/cloud.google.com/go/iam/apiv1/iampb/iam_policy.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/options.pb.go
  vendor/cloud.google.com/go/iam/apiv1/iampb/policy.pb.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/reader.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#7824 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7804 CrossNamespace: updated namespace for subscription
  config/core/resources/subscription.yaml
  docs/eventing-api.md
  pkg/apis/messaging/v1/subscription_types.go
Labels: approved, size/XS, lgtm

#7828 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7826 Remove eventing-kafka from downstream tests as it's deprecated
  .github/workflows/knative-downstream.yaml
Labels: approved, size/XS, lgtm

#7665 Improve trust bundle propagation
  pkg/eventingtls/trust_bundle.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/controller.go
  pkg/reconciler/containersource/controller.go
  pkg/reconciler/sinkbinding/controller.go
Labels: approved, size/L, lgtm

#7836 Remove sinkbindings OIDC token secret when not needed and fix status setting
  pkg/reconciler/sinkbinding/sinkbinding.go
Labels: approved, size/XS, lgtm

#7831 [e2e] fix ManyTriggers possible starvation of Setup features
  test/rekt/features/broker/feature.go
Labels: size/M, approved, lgtm, area/test-and-release

#7782 feat: add initial pathfinding algorithm
  pkg/graph/lineage.go
  pkg/graph/lineage_test.go
  pkg/graph/types.go
Labels: size/M, approved, lgtm

#7843 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7845 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7850 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#7847 fix: remove duplicate configMaps
  config/channels/in-memory-channel/configmaps/observability.yaml
  config/channels/in-memory-channel/configmaps/tracing.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#7870 fix: imc dispatcher doesn't have duplicate reporting of metrics
  pkg/channel/fanout/fanout_event_handler.go
Labels: approved, size/XS, lgtm

#7876 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7812 Create validation function for cross namespace referencing
  config/core/roles/webhook-clusterrole.yaml
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/trigger_validation.go
  pkg/apis/eventing/v1/trigger_validation_test.go
  pkg/apis/messaging/v1/subscribable_channelable_validation.go
  pkg/apis/messaging/v1/subscribable_channelable_validation_test.go
  pkg/apis/messaging/v1/subscription_types.go
  pkg/apis/messaging/v1/subscription_validation.go
  pkg/apis/messaging/v1/subscription_validation_test.go
  pkg/crossnamespace/validation.go
Labels: approved, lgtm, size/XL
