Repository knative/eventing, pull requests merged in 2024-10, with the labels that each got.

#8215 update jobsink TLS comments
  pkg/reconciler/jobsink/jobsink.go
Labels: approved, size/XS, lgtm

#8214 Add Convertible interface to job sink
  pkg/apis/sinks/v1alpha1/job_sink_types.go
Labels: approved, size/XS, lgtm

#8233 workaround DeepDerivative CreationTimestamp comparison
  pkg/auth/serviceaccount.go
  pkg/auth/serviceaccount_test.go
Labels: size/M, approved, lgtm

#8237 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8255 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/internal/descopts/options.go
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/doc.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/map_entry.go
  vendor/google.golang.org/protobuf/internal/genid/wrappers.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/codec_unsafe.go
  vendor/google.golang.org/protobuf/internal/impl/convert.go
  vendor/google.golang.org/protobuf/internal/impl/encode.go
  vendor/google.golang.org/protobuf/internal/impl/equal.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_extension.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_pure.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/equal.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/methods.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_pure.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/runtime/protoiface/methods.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#8145 feat: make oidc discovery url configurable
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  cmd/jobsink/main.go
  pkg/apis/feature/features.go
  pkg/apis/feature/features_test.go
  pkg/apis/feature/flag_names.go
  pkg/apis/feature/testdata/config-features.yaml
  pkg/auth/verifier.go
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/ingress/ingress_handler_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
Labels: approved, size/L, lgtm

#8256 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8262 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/configmaps/controller.go
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#8276 feat: autocreate v1beta3 eventtypes
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  pkg/eventtype/eventtypes.go
  pkg/eventtype/eventtypes_test.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/controller_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/testing/v1beta3/eventtype.go
  pkg/reconciler/testing/v1beta3/factory.go
  pkg/reconciler/testing/v1beta3/listers.go
Labels: approved, size/L, lgtm

#8275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/M, approved, lgtm

#8287 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#8288 fix: et autocreate makes eventtype id required
  pkg/eventtype/eventtypes.go
Labels: approved, size/XS, lgtm

#8263 Schduler: MAXFILLUP strategy will spread vreplicas across multiple pods
  pkg/scheduler/README.md
  pkg/scheduler/doc.go
  pkg/scheduler/factory/registry.go
  pkg/scheduler/placement.go
  pkg/scheduler/placement_test.go
  pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority.go
  pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority_test.go
  pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority.go
  pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority_test.go
  pkg/scheduler/plugins/core/evenpodspread/even_pod_spread.go
  pkg/scheduler/plugins/core/evenpodspread/even_pod_spread_test.go
  pkg/scheduler/plugins/core/lowestordinalpriority/lowest_ordinal_priority.go
  pkg/scheduler/plugins/core/lowestordinalpriority/lowest_ordinal_priority_test.go
  pkg/scheduler/plugins/core/podfitsresources/pod_fits_resources.go
  pkg/scheduler/plugins/core/podfitsresources/pod_fits_resources_test.go
  pkg/scheduler/plugins/core/removewithavailabilitynodepriority/remove_with_availability_node_priority.go
  pkg/scheduler/plugins/core/removewithavailabilitynodepriority/remove_with_availability_node_priority_test.go
  pkg/scheduler/plugins/core/removewithavailabilityzonepriority/remove_with_availability_zone_priority.go
  pkg/scheduler/plugins/core/removewithavailabilityzonepriority/remove_with_availability_zone_priority_test.go
  pkg/scheduler/plugins/core/removewithevenpodspreadpriority/remove_with_even_pod_spread_priority.go
  pkg/scheduler/plugins/core/removewithevenpodspreadpriority/remove_with_even_pod_spread_priority_test.go
  pkg/scheduler/plugins/core/removewithhighestordinalpriority/remove_with_highest_ordinal_priority.go
  pkg/scheduler/plugins/core/removewithhighestordinalpriority/remove_with_highest_ordinal_priority_test.go
  pkg/scheduler/plugins/kafka/nomaxresourcecount/no_max_resource_count.go
  pkg/scheduler/plugins/kafka/nomaxresourcecount/no_max_resource_count_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/state/helpers.go
  pkg/scheduler/state/interface.go
  pkg/scheduler/state/interface_test.go
  pkg/scheduler/state/state.go
  pkg/scheduler/state/state_test.go
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/autoscaler_test.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
  pkg/scheduler/testing/client.go
  pkg/scheduler/testing/vpod.go
Labels: approved, lgtm, size/XXL

#8289 [main] Format Go code
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, size/L, lgtm
