Repository knative/eventing, pull requests merged in 2024-06, with the labels that each got.

#7956 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/k8s/steps.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7958 Bump rekt to main
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7964 JobSink: don't start informers twice
  cmd/jobsink/main.go
Labels: approved, size/XS, lgtm

#7943 fix: eventing clusterrole has correct knsubscribe permissions
  config/200-crossnamespace-clusterrole.yaml
  config/channels/in-memory-channel/roles/crossnamespace-clusterrole.yaml
  config/core/200-eventing-serviceaccount.yaml
  config/core/roles/crossnamespace-clusterrole.yaml
Labels: approved, size/L, lgtm

#7968 Adding mount path as env variable in container
  cmd/jobsink/main.go
Labels: approved, size/XS, lgtm, ok-to-test

#7965 Fix: Parallels updates subscription where possible, instead of recrea…
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
Labels: size/M, approved, lgtm, ok-to-test

#7986 Exclude core deployments from SinkBinding webhook injection
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/brokers/mt-channel-broker/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/core/deployments/controller.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  config/core/deployments/webhook.yaml
Labels: approved, size/XS, lgtm

#7987 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/auth/CHANGES.md
  vendor/cloud.google.com/go/auth/credentials/filetypes.go
  vendor/cloud.google.com/go/auth/grpctransport/grpctransport.go
  vendor/cloud.google.com/go/auth/httptransport/httptransport.go
  vendor/cloud.google.com/go/auth/internal/transport/cert/workload_cert.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/genproto/googleapis/type/date/date.pb.go
  vendor/google.golang.org/genproto/googleapis/type/expr/expr.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7967 fix: add comments and improve regex for attribute filter transform function
  pkg/graph/transforms.go
Labels: approved, lgtm, size/S

#7990 Add JobSink data plane symlink in config/
  config/500-job-sink.yaml
Labels: approved, size/XS, lgtm

#7991 Support arbitrary data for rekt configmap package
  test/rekt/resources/configmap/config-features.yaml
  test/rekt/resources/configmap/configmap.go
  test/rekt/resources/configmap/configmap_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#7962 JobSink: add webhook validation for spec.job
  cmd/webhook/main.go
  config/core/roles/webhook-clusterrole.yaml
  docs/sink/jobsink-invalid.yaml
  pkg/apis/sinks/register.go
  pkg/apis/sinks/v1alpha1/job_sink_validation.go
Labels: size/M, approved, lgtm

#7993 Move job sink certificate out of config core
  config/500-job-sink.yaml
  config/core-tls/job-sink-tls-certificate.yaml
  hack/generate-yamls.sh
Labels: approved, size/XS, lgtm, area/test-and-release

#7995 Add EventPolicy types
  cmd/schema/main.go
  config/core/resources/eventpolicy.yaml
  docs/eventing-api.md
  hack/update-codegen.sh
  pkg/apis/eventing/v1alpha1/doc.go
  pkg/apis/eventing/v1alpha1/eventpolicy_conversion.go
  pkg/apis/eventing/v1alpha1/eventpolicy_conversion_test.go
  pkg/apis/eventing/v1alpha1/eventpolicy_defaults.go
  pkg/apis/eventing/v1alpha1/eventpolicy_defaults_test.go
  pkg/apis/eventing/v1alpha1/eventpolicy_lifecycle.go
  pkg/apis/eventing/v1alpha1/eventpolicy_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/eventpolicy_types.go
  pkg/apis/eventing/v1alpha1/eventpolicy_types_test.go
  pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  pkg/apis/eventing/v1alpha1/eventpolicy_validation_test.go
  pkg/apis/eventing/v1alpha1/register.go
  pkg/apis/eventing/v1alpha1/register_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventpolicy.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventpolicy.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/eventing/interface.go
  pkg/client/informers/externalversions/eventing/v1alpha1/eventpolicy.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/injection/informers/eventing/v1alpha1/eventpolicy/eventpolicy.go
  pkg/client/injection/informers/eventing/v1alpha1/eventpolicy/fake/fake.go
  pkg/client/injection/informers/eventing/v1alpha1/eventpolicy/filtered/eventpolicy.go
  pkg/client/injection/informers/eventing/v1alpha1/eventpolicy/filtered/fake/fake.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventpolicy/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventpolicy/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventpolicy/state.go
  pkg/client/listers/eventing/v1alpha1/eventpolicy.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
Labels: approved, lgtm, size/XXL, area/test-and-release

#7996 Add `default-authorization-mode` feature flag
  config/core/configmaps/features.yaml
  pkg/apis/feature/features.go
  pkg/apis/feature/features_test.go
  pkg/apis/feature/flag_names.go
  pkg/apis/feature/testdata/config-features.yaml
Labels: size/M, approved, lgtm

#7999 Add `AppliedEventPoliciesStatus` type
  config/channels/in-memory-channel/resources/in-memory-channel.yaml
  config/core/resources/broker.yaml
  config/core/resources/parallel.yaml
  config/core/resources/sequence.yaml
  docs/eventing-api.md
  pkg/apis/duck/v1/eventpoliciesstatus_type.go
  pkg/apis/duck/v1/zz_generated.deepcopy.go
  pkg/apis/eventing/v1/broker_types.go
  pkg/apis/eventing/v1/zz_generated.deepcopy.go
  pkg/apis/flows/v1/parallel_types.go
  pkg/apis/flows/v1/sequence_types.go
  pkg/apis/flows/v1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1/in_memory_channel_lifecycle_test.go
  pkg/apis/messaging/v1/in_memory_channel_types.go
  pkg/apis/messaging/v1/zz_generated.deepcopy.go
Labels: approved, size/L, lgtm

#8004 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/authstatus/authstatus.go
  vendor/knative.dev/pkg/resolver/authenticatable_resolver.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#8005 Propagate read error correctly in event-dispatcher
  pkg/kncloudevents/event_dispatcher.go
Labels: approved, size/XS, lgtm

#8008 Add validation for EventPolicy sub suffix matching
  pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  pkg/apis/eventing/v1alpha1/eventpolicy_validation_test.go
Labels: size/M, approved, lgtm

#8002 Add authz library
  pkg/auth/event_policy.go
  pkg/auth/event_policy_test.go
Labels: approved, lgtm, size/XL

#8000 JobSink: Test OIDC support
  cmd/jobsink/main.go
  pkg/apis/feature/store.go
  test/rekt/features/jobsink/jobsink.go
  test/rekt/job_sink_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#8011 List applying policies in InMemoryChannels status
  config/channels/in-memory-channel/roles/controller-clusterrole.yaml
  pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  pkg/apis/messaging/v1/in_memory_channel_lifecycle_test.go
  pkg/auth/event_policy.go
  pkg/auth/event_policy_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/inmemorychannel/controller/controller.go
  pkg/reconciler/inmemorychannel/controller/controller_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/inmemorychannel/dispatcher/readiness_test.go
  pkg/reconciler/testing/v1/eventpolicy.go
  pkg/reconciler/testing/v1/inmemorychannel.go
  pkg/reconciler/testing/v1/listers.go
Labels: approved, lgtm, size/XL

#8020 Add JobSink to storage version migration
  config/post-install/clusterrole.yaml
  config/post-install/storage-version-migrator.yaml
Labels: approved, lgtm, size/S

#8022 Fix test case in TestCreateExpectedEventPatterns
  test/rekt/features/broker/topology_test.go
Labels: approved, size/XS, lgtm, area/test-and-release

#8023 Fix test case in `TestCreateExpectedEventDeliveryMap`
  test/rekt/features/broker/topology_test.go
Labels: approved, size/XS, lgtm, area/test-and-release

#8010 Add EventPolicy resource for rekt tests
  test/rekt/resources/eventpolicy/eventpolicy.go
  test/rekt/resources/eventpolicy/eventpolicy.yaml
  test/rekt/resources/eventpolicy/eventpolicy_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#8014 List applying policies in Channel and propagate EventPolicies to underlying channel
  config/core/resources/channel.yaml
  config/core/roles/controller-clusterroles.yaml
  docs/eventing-api.md
  pkg/apis/duck/v1/channelable_types.go
  pkg/apis/duck/v1/zz_generated.deepcopy.go
  pkg/apis/messaging/v1/channel_lifecycle.go
  pkg/apis/messaging/v1/channel_lifecycle_test.go
  pkg/apis/messaging/v1/in_memory_channel_types.go
  pkg/apis/messaging/v1/zz_generated.deepcopy.go
  pkg/auth/event_policy.go
  pkg/reconciler/channel/channel.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/controller.go
  pkg/reconciler/channel/controller_test.go
  pkg/reconciler/channel/resources/eventpolicy.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/subscription/subscription_test.go
  pkg/reconciler/testing/v1/channel.go
  pkg/reconciler/testing/v1/eventpolicy.go
Labels: approved, lgtm, size/XL

#8026 Updating RetryableHttp lib to latest
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-retryablehttp/.go-version
  vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
  vendor/github.com/hashicorp/go-retryablehttp/CODEOWNERS
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go119.go
  vendor/github.com/hashicorp/go-retryablehttp/cert_error_go120.go
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#8030 Event Type API: updated test name to avoid confusion
  pkg/apis/eventing/v1beta2/eventtype_defaults_test.go
  pkg/apis/eventing/v1beta3/eventtype_defaults_test.go
Labels: approved, lgtm, size/S

#8033 Remove unneeded replaces in go.mod
  go.mod
  vendor/modules.txt
Labels: approved, size/XS, lgtm

#8044 Use `knative/actions/setup-go` to be in sync with other projects
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-downstream.yaml
Labels: approved, size/XS, lgtm

#7942 Update Github actions automatically
  .github/.dependabot.yaml
Labels: approved, size/XS, lgtm

#8051 Avoid fatal errors for unknown features flags that can be added in a future release
  pkg/apis/feature/features.go
Labels: approved, size/XS, lgtm

#8024 Add EventPolicy Reconciler
  cmd/controller/main.go
  pkg/apis/eventing/v1alpha1/eventpolicy_lifecycle.go
  pkg/apis/eventing/v1alpha1/eventpolicy_lifecycle_test.go
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/eventpolicy/controller.go
  pkg/reconciler/eventpolicy/controller_test.go
  pkg/reconciler/eventpolicy/eventpolicy.go
  pkg/reconciler/eventpolicy/eventpolicy_test.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel_test.go
  pkg/reconciler/testing/v1/eventpolicy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/authstatus/fake/fake.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, ok-to-test
