Repository knative/eventing, pull requests merged in 2024-01, with the labels that each got.

#7533 Add reconciler test for EventType references
  pkg/reconciler/eventtype/eventtype_test.go
Labels: size/M, approved, lgtm

#7542 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7552 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/reconciler/eventing/v1/broker/reconciler.go
  pkg/client/injection/reconciler/eventing/v1/trigger/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta1/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta2/eventtype/reconciler.go
  pkg/client/injection/reconciler/eventing/v1beta3/eventtype/reconciler.go
  pkg/client/injection/reconciler/flows/v1/parallel/reconciler.go
  pkg/client/injection/reconciler/flows/v1/sequence/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/channel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/inmemorychannel/reconciler.go
  pkg/client/injection/reconciler/messaging/v1/subscription/reconciler.go
  pkg/client/injection/reconciler/sources/v1/apiserversource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/containersource/reconciler.go
  pkg/client/injection/reconciler/sources/v1/pingsource/reconciler.go
  pkg/client/injection/reconciler/sources/v1beta2/pingsource/reconciler.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/client/injection/apiextensions/reconciler/apiextensions/v1/customresourcedefinition/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/configmap/informer/synced_callback.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/hash/hash.go
  vendor/knative.dev/pkg/kflag/set.go
  vendor/knative.dev/pkg/leaderelection/chaosduck/main.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/knative.dev/pkg/webhook/psbinding/reconciler.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/deployment.yaml
  vendor/knative.dev/reconciler-test/pkg/resources/deployment/options.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7553 Provision PingSources sink OIDC audience in PingSource status
  config/core/resources/pingsource.yaml
  pkg/apis/sources/v1/ping_lifecycle.go
Labels: approved, size/XS, lgtm

#7567 Reload trust-bundle on new connections
  pkg/adapter/v2/cloudevents.go
  pkg/eventingtls/trust_bundle.go
  pkg/kncloudevents/http_client.go
Labels: size/M, approved, lgtm

#7554 added instructions to use e2e-debug.sh in the doc
  DEVELOPMENT.md
Labels: approved, lgtm, size/S, ok-to-test

#7568 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7572 Remove kubectl dependency in hack/update-cert-manager.sh
  hack/update-cert-manager.sh
  third_party/cert-manager/00-namespace.yaml
Labels: approved, lgtm, size/S, area/test-and-release

#7571 Update coreos/go-oidc to 3.9.0
  go.mod
  go.sum
  vendor/github.com/coreos/go-oidc/v3/oidc/jwks.go
  vendor/github.com/coreos/go-oidc/v3/oidc/oidc.go
  vendor/github.com/coreos/go-oidc/v3/oidc/verify.go
  vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7577 Fixed pull request workflow broken link in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm, ok-to-test

#7574 New Event Filtering: Add rekt test for multiple filters
  test/rekt/features/new_trigger_filters/feature.go
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#7579 Updated test example to use actual test instead of hypothetical example
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm, ok-to-test

#7585 Increase KinD test timeout to 90 minutes
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#7591 Set audience in .status.addresses fields too
  pkg/reconciler/broker/broker.go
  pkg/reconciler/inmemorychannel/controller/inmemorychannel.go
Labels: approved, lgtm, size/S

#7586 rekt test to verify only one EventType created for MTBroker
  test/experimental/features/eventtype_autocreate/features.go
  test/rekt/resources/eventtype/eventtype.go
Labels: approved, lgtm, size/S, area/test-and-release

#7590 Provision sequences CA cert in its status
  pkg/apis/flows/v1/sequence_lifecycle.go
Labels: approved, size/XS, lgtm

#7593 [release-1.12] Cherry-pick Provision sequences CA cert in its status
  pkg/apis/flows/v1/sequence_lifecycle.go
Labels: approved, size/XS, lgtm

#7592 [release-1.11] Cherry-pick Provision sequences CA cert in its status
  pkg/apis/flows/v1/sequence_lifecycle.go
Labels: approved, size/XS, lgtm

#7525 Authenticate requests from PingSources
  config/core/roles/pingsource-mt-adapter-clusterrole.yaml
  pkg/adapter/mtping/runner.go
  pkg/reconciler/pingsource/pingsource_test.go
  test/auth/features/oidc/pingsource.go
  test/auth/oidc_test.go
  test/rekt/resources/pingsource/pingsource.go
  test/rekt/resources/pingsource/pingsource.yaml
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test

#7551 Enable TLS for OIDC e2e tests
  test/auth/config/features.yaml
  test/auth/features/oidc/addressable_oidc_conformance.go
  test/auth/features/oidc/apiserversource.go
  test/auth/features/oidc/broker.go
  test/auth/features/oidc/channel.go
  test/auth/features/oidc/containersource.go
  test/auth/features/oidc/parallel.go
  test/auth/features/oidc/pingsource.go
  test/auth/features/oidc/sequence.go
  test/auth/oidc_test.go
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/subscription/subscription.go
Labels: approved, size/L, lgtm, area/test-and-release

#7601 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7600 Add TLS test for sequence
  test/rekt/features/sequence/feature.go
  test/rekt/sequence_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#7602 Bump Go to v1.21
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#7603 [release-1.12] Fix Sequence TLS support
  config/core/resources/sequence.yaml
  pkg/reconciler/sequence/resources/subscription.go
  test/rekt/features/sequence/feature.go
  test/rekt/resources/sequence/sequence.go
  test/rekt/resources/sequence/sequence.yaml
  test/rekt/sequence_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#7581 Eventing TLS: Add scheme label to metrics
  pkg/adapter/v2/cloudevents.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/stats_reporter.go
  pkg/broker/filter/stats_reporter_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/stats_reporter.go
  pkg/broker/ingress/stats_reporter_test.go
  pkg/channel/event_receiver.go
  pkg/channel/fanout/fanout_event_handler.go
  pkg/channel/stats_reporter.go
  pkg/channel/stats_reporter_test.go
  pkg/metrics/metrics.go
  pkg/metrics/source/stats_reporter.go
  pkg/metrics/source/stats_reporter_test.go
Labels: approved, size/L, lgtm, ok-to-test

#7570 Remove OIDC service account, when OIDC feature is disabled again
  pkg/auth/serviceaccount.go
  pkg/auth/serviceaccount_test.go
Labels: size/M, approved, lgtm, ok-to-test

#7611 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7609 Add a Prerequisite helper to check if the OIDC authentication feature flag is enabled
  test/rekt/features/featureflags/featureflags.go
Labels: approved, lgtm, size/S, area/test-and-release

#7594 Enable storage of EventType v1b2
  config/core/resources/eventtype.yaml
  test/e2e-common.sh
  test/upgrade/installation/git_head.go
Labels: approved, lgtm, size/S, area/test-and-release

#7612 Adding documentation and linking resources for go setup issues with Linux Ubuntu distribution (removed noisy commits)
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm, needs-ok-to-test

#7617 Generalize description of EventType in CRD.
  config/core/resources/eventtype.yaml
Labels: approved, size/XS, lgtm

#7616 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7584 support: nodeselector in apiserversource
  pkg/apis/feature/features.go
  pkg/apis/feature/features_test.go
  pkg/apis/feature/flag_names.go
  pkg/apis/feature/testdata/config-features.yaml
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/apiserversource/apiserversource_test.go
  pkg/reconciler/apiserversource/resources/receive_adapter.go
Labels: approved, size/L, lgtm, ok-to-test

#7622 Move OIDC tests to test/rekt
  .github/workflows/kind-e2e.yaml
  test/auth/main_test.go
  test/auth/oidc_test.go
  test/config-authentication-oidc/features.yaml
  test/e2e-rekt-tests.sh
  test/rekt/apiserversource_test.go
  test/rekt/broker_test.go
  test/rekt/channel_test.go
  test/rekt/container_source_test.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/apiserversource/oidc_feature.go
  test/rekt/features/broker/oidc_feature.go
  test/rekt/features/channel/oidc_feature.go
  test/rekt/features/containersource/oidc_feature.go
  test/rekt/features/oidc/addressable_oidc_conformance.go
  test/rekt/features/parallel/oidc_feature.go
  test/rekt/features/pingsource/oidc_feature.go
  test/rekt/features/sequence/oidc_feature.go
  test/rekt/parallel_test.go
  test/rekt/pingsource_test.go
  test/rekt/sequence_test.go
Labels: approved, lgtm, size/XL, area/test-and-release

#7630 Use projected volumes for sinkbinding trust bundles
  pkg/apis/sources/v1/sinkbinding_lifecycle_test.go
  pkg/eventingtls/eventingtls.go
  pkg/eventingtls/trust_bundle.go
Labels: approved, size/L, lgtm

#7614 Fix mtbroker-filter to proxy response headers
  pkg/broker/filter/filter_handler.go
Labels: approved, size/XS, lgtm

#7641 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/trace/trace.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/auxiliary.go
  vendor/cloud.google.com/go/storage/internal/apiv2/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storage_client.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/invoke.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/handshaker.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_others.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_windows.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#7643 Add helm as one of the development requirement
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm

#7644 Tiny trustbundle improvements
  pkg/eventingtls/trust_bundle.go
  pkg/reconciler/sinkbinding/controller.go
Labels: approved, lgtm, size/S
