Repository knative/eventing, pull requests merged in 2024-08, with the labels that each got.

#8124 Sequence reconciler reads and watch the config-features configmap
  pkg/reconciler/sequence/controller.go
  pkg/reconciler/sequence/sequence.go
Labels: size/M, approved, lgtm

#8130 update trust-manager to version 0.12.0
  hack/update-cert-manager.sh
  third_party/cert-manager/02-trust-manager.yaml
Labels: approved, size/L, lgtm, area/test-and-release

#8133 Default EventPolicy `.spec.from[].namespace` to EventPolicies namespace
  pkg/apis/eventing/v1alpha1/eventpolicy_defaults.go
  pkg/apis/eventing/v1alpha1/eventpolicy_defaults_test.go
Labels: kind/bug, size/M, approved, lgtm

#8134 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8132 Add e2e test for Broker authorization
  test/e2e-rekt-tests.sh
  test/rekt/broker_test.go
  test/rekt/features/broker/authz_feature.go
  test/rekt/resources/eventpolicy/eventpolicy.go
  test/rekt/resources/eventpolicy/eventpolicy_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#8143 Set UID in Brokers backing channels EventPolicies OwnerReference
  pkg/reconciler/broker/resources/eventpolicy.go
Labels: approved, size/XS, lgtm

#8106 Add EventPolicy reconciliation for Sequence
  pkg/auth/event_policy.go
  pkg/reconciler/sequence/resources/eventpolicy.go
  pkg/reconciler/sequence/sequence.go
  pkg/reconciler/sequence/sequence_test.go
Labels: approved, lgtm, size/XXL

#8144 Improve scheduler memory usage
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#8112 Add EventPolicy reconciliation for Parallel
  pkg/reconciler/parallel/parallel.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/parallel/resources/eventpolicy.go
Labels: approved, lgtm, size/XXL

#8096 added event format to dispatcher
  pkg/kncloudevents/event_dispatcher.go
  pkg/kncloudevents/event_dispatcher_test.go
Labels: approved, size/L, lgtm, ok-to-test

#8110 fix: tracker can track resources in different ns
  pkg/duck/listable.go
  pkg/reconciler/subscription/subscription.go
Labels: size/M, approved, lgtm

#8147 mt-broker-filter: Allow only requests from Triggers Subscriptions OIDC ID
  cmd/broker/filter/main.go
  config/brokers/mt-channel-broker/roles/filter-clusterrole.yaml
  pkg/auth/token_verifier.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/reconciler/broker/resources/subscription.go
Labels: approved, size/L, lgtm

#8153 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/options.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/receiver/receiver.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
  vendor/knative.dev/reconciler-test/pkg/eventshub/utils.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#8118 feat: reduced unnecessary creation of filters
  pkg/eventfilter/subscriptionsapi/all_filter.go
  pkg/eventfilter/subscriptionsapi/any_filter.go
Labels: approved, lgtm, size/S

#8159 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#8122 Add filters to event policy
  config/core/resources/eventpolicy.yaml
  docs/eventing-api.md
  pkg/adapter/apiserver/adapter.go
  pkg/adapter/apiserver/adapter_test.go
  pkg/adapter/apiserver/delegate_test.go
  pkg/apis/eventing/v1alpha1/eventpolicy_types.go
  pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  pkg/apis/eventing/v1alpha1/eventpolicy_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/auth/event_policy.go
  pkg/auth/event_policy_test.go
  pkg/auth/token_verifier.go
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/eventfilter/subscriptionsapi/create.go
  test/rekt/features/authz/addressable_authz_conformance.go
  test/rekt/resources/eventpolicy/eventpolicy.go
  test/rekt/resources/eventpolicy/eventpolicy.yaml
  test/rekt/resources/eventpolicy/eventpolicy_test.go
Labels: approved, lgtm, size/XL, area/test-and-release

#8163 Fix: propagate EventPolicy filter to underlying Channels EventPolicy
  pkg/reconciler/channel/channel_test.go
  pkg/reconciler/channel/resources/eventpolicy.go
  pkg/reconciler/parallel/parallel_test.go
  pkg/reconciler/parallel/resources/eventpolicy.go
  pkg/reconciler/sequence/resources/eventpolicy.go
  pkg/reconciler/sequence/sequence_test.go
  pkg/reconciler/testing/v1/eventpolicy.go
Labels: approved, size/L, lgtm

#8162 Support authorization in Channel ingress
  pkg/channel/event_receiver.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  test/rekt/channel_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#8167 Fix: Use correct readyness check in AuthZ conformance tests
  test/rekt/features/authz/addressable_authz_conformance.go
Labels: approved, size/XS, lgtm, area/test-and-release

#8168 Fix JobSink to have ObservedGeneration in status
  config/core/resources/jobsink.yaml
  test/rekt/features/jobsink/jobsink.go
Labels: approved, lgtm, size/S, area/test-and-release

#8169 JobSink: Reject unauthorized requests
  cmd/jobsink/main.go
  test/rekt/job_sink_test.go
  test/rekt/resources/jobsink/jobsink.go
Labels: size/M, approved, lgtm, area/test-and-release

#8151 Support dispatcher format for triggers
  config/core/resources/trigger.yaml
  pkg/broker/filter/filter_handler.go
  test/rekt/features/trigger/feature.go
  test/rekt/resources/delivery/delivery.go
  test/rekt/resources/trigger/trigger.go
  test/rekt/resources/trigger/trigger.yaml
  test/rekt/trigger_test.go
Labels: size/M, approved, lgtm, area/test-and-release

#8172 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/resources/secret/secret.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7631 Broker class based defaults
  pkg/apis/config/defaults.go
  pkg/apis/config/defaults_test.go
  pkg/apis/config/testdata/config-br-defaults.yaml
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/eventing/v1/broker_defaults.go
  pkg/apis/eventing/v1/broker_defaults_test.go
  pkg/apis/eventing/v1/broker_validation.go
  pkg/apis/eventing/v1/broker_validation_test.go
  pkg/reconciler/sugar/namespace/namespace_test.go
  pkg/reconciler/sugar/trigger/trigger_test.go
Labels: approved, lgtm, size/XXL

#8181 Split AuthZ e2e tests
  test/rekt/features/authz/addressable_authz_conformance.go
Labels: approved, lgtm, size/S, area/test-and-release

#8180 fix: set resource version for subscription in sequence reconciler
  pkg/reconciler/sequence/sequence.go
Labels: approved, size/XS, lgtm

#8173 AuthZ: Provide function to update AppliedEventPoliciesStatus based on a given list of applying policies
  pkg/auth/event_policy.go
Labels: approved, lgtm, size/S

#8125 Disable controller default health probes in the IMC dispatcher
  cmd/in_memory/channel_dispatcher/main.go
Labels: approved, size/XS, lgtm

#8183 Migrate to kube_codegen.sh
  hack/update-codegen.sh
  pkg/apis/messaging/v1/zz_generated.defaults.go
  pkg/apis/sinks/v1alpha1/zz_generated.defaults.go
  pkg/apis/sources/v1/zz_generated.defaults.go
  pkg/apis/sources/v1beta2/zz_generated.defaults.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/informers/externalversions/eventing/interface.go
  pkg/client/informers/externalversions/sources/interface.go
Labels: size/M, approved, lgtm, area/test-and-release
