Repository knative/eventing, pull requests merged in 2024-03, with the labels that each got.

#7650 e2e: channel/DataPlaneConformance
  test/rekt/features/channel/data_plane.go
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test

#7735 Revert "Run Prow tests on K8s 1.28 (#7714)"
  test/e2e-common.sh
  test/e2e-conformance-tests.sh
  test/e2e-rekt-tests.sh
  test/e2e-tests.sh
  test/e2e-upgrade-tests.sh
Labels: approved, lgtm, size/S, area/test-and-release

#7738 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7741 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/client.go
  vendor/cloud.google.com/go/storage/grpc_client.go
  vendor/cloud.google.com/go/storage/http_client.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/writer.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7731 feat: brokers can be added to event lineage graph
  pkg/graph/constructor.go
  pkg/graph/constructor_test.go
  pkg/graph/types.go
Labels: approved, size/L, lgtm

#7744 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7743 Fix the naming convention in the config-features.yaml
  pkg/apis/feature/flag_names.go
  pkg/apis/feature/testdata/config-features.yaml
  pkg/reconciler/apiserversource/apiserversource_test.go
  test/rekt/resources/configmap/config-features.yaml
Labels: approved, lgtm, size/S, area/test-and-release

#7745 feat: add channels to event lineage graph
  pkg/graph/constructor.go
  pkg/graph/constructor_test.go
Labels: approved, size/L, lgtm

#7747 Bump CloudEvents GO-SDK to 2.15.2
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7748 [release-1.13] Bump CloudEvents GO-SDK to 2.15.2
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/like_expression.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/logic_expressions.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/event_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/spec/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_binary_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_structured_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/client/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/context.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/message.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_retry.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/test/event_matchers.go
  vendor/github.com/cloudevents/sdk-go/v2/types/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/types/value.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7749 [release-1.12] Bump CloudEvents GO-SDK to 2.15.2
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/like_expression.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/logic_expressions.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/event_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/spec/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_binary_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_structured_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/client/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/context.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/message.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_retry.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/test/event_matchers.go
  vendor/github.com/cloudevents/sdk-go/v2/types/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/types/value.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7752 CrossNamespace: adding feature flag
  config/core/configmaps/features.yaml
  pkg/apis/feature/features.go
  pkg/apis/feature/flag_names.go
Labels: approved, lgtm, size/S

#7740 Fusion Hack
  hack/run.sh
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#7785 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7786 Replace all usages of deprecated wait.PollImmediate with wait.PollUntilContextTimeout
  pkg/adapter/mtping/runner_test.go
  pkg/adapter/v2/main.go
  pkg/scheduler/state/helpers.go
  pkg/scheduler/state/state.go
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/scheduler_test.go
  test/lib/await.go
  test/lib/duck/resource_checks.go
  test/lib/duck/serving_checks.go
  test/lib/recordevents/event_info_store.go
  test/lib/test_runner.go
  test/lib/tracker.go
  test/rekt/features/broker/control_plane.go
  test/rekt/features/channel/control_plane.go
  test/rekt/features/channel/data_plane.go
  test/rekt/features/knconf/control_plane.go
  test/rekt/resources/addressable/addressable.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/eventtype/eventtype.go
  test/upgrade/prober/sender.go
  test/upgrade/prober/verify.go
  test/upgrade/prober/wathola/receiver/services_test.go
  test/upgrade/prober/wathola/sender/services_test.go
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#7792 Reduce the scope for the Config validation webhook to only the `knative-eventing` namespace.
  config/core/webhooks/config-validation.yaml
Labels: kind/bug, approved, size/XS, lgtm

#7787 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7794 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/internal/.repo-metadata-full.json
  vendor/cloud.google.com/go/internal/trace/trace.go
  vendor/cloud.google.com/go/storage/CHANGES.md
  vendor/cloud.google.com/go/storage/doc.go
  vendor/cloud.google.com/go/storage/internal/apiv2/storagepb/storage.pb.go
  vendor/cloud.google.com/go/storage/internal/version.go
  vendor/cloud.google.com/go/storage/storage.go
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/github.com/golang/protobuf/jsonpb/encode.go
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/api/iamcredentials/v1/iamcredentials-api.json
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_behavior.pb.go
  vendor/google.golang.org/genproto/googleapis/api/tidyfix.go
  vendor/google.golang.org/genproto/internal/doc.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7800 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/104-forwarder.yaml
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#7746 feat: add triggers to event lineage graph
  pkg/graph/constructor.go
  pkg/graph/constructor_test.go
Labels: approved, size/L, lgtm

#7798 Adding broker namespace for triggers
  config/core/resources/trigger.yaml
  docs/eventing-api.md
  pkg/apis/eventing/v1/trigger_types.go
Labels: approved, lgtm, size/S

#7811 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/googleapis/gax-go/v2/.release-please-manifest.json
  vendor/github.com/googleapis/gax-go/v2/CHANGES.md
  vendor/github.com/googleapis/gax-go/v2/internal/version.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/api/annotations/field_info.pb.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7790 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm

#7817 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#7815 CrossNamespace: added brokerRef in trigger spec
  config/core/resources/trigger.yaml
  docs/eventing-api.md
  pkg/apis/eventing/v1/trigger_types.go
  pkg/apis/eventing/v1/zz_generated.deepcopy.go
Labels: size/M, approved, lgtm

#7708 Update eventtype v1beta3 type to reflect spec changes
  config/core/resources/eventtype.yaml
  docs/eventing-api.md
  pkg/apis/eventing/v1beta3/eventtype_defaults_test.go
  pkg/apis/eventing/v1beta3/eventtype_types.go
  pkg/apis/eventing/v1beta3/eventtype_validation.go
  pkg/apis/eventing/v1beta3/eventtype_validation_test.go
  pkg/apis/eventing/v1beta3/zz_generated.deepcopy.go
  pkg/graph/lineage_test.go
Labels: approved, lgtm, size/XL

#7819 [main] Format Go code
  pkg/apis/eventing/v1beta3/eventtype_defaults_test.go
Labels: approved, lgtm, size/S
