Repository knative/eventing, pull requests merged in 2024-11, with the labels that each got.

#8294 Allow imc-controller to list JobSinks
  config/channels/in-memory-channel/roles/controller-clusterrole.yaml
Labels: approved, size/XS, lgtm

#8298 Add jobsinks-addressable-resolver cluster role
  config/channels/in-memory-channel/roles/controller-clusterrole.yaml
  config/core/roles/addressable-resolvers-clusterrole.yaml
Labels: size/M, approved, lgtm

#8303 Use GetServiceHostname when passing URL to JobSink
  test/rekt/features/jobsink/jobsink.go
Labels: approved, lgtm, size/S, area/test-and-release

#8307 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8312 [chore] Use a generic access/secret key in the secret for AWS connections
  pkg/reconciler/integrationsource/resources/containersource.go
Labels: approved, lgtm, size/S

#8315 [chore] Do not generate SSL env vars for each struct entry, just once per containersource/image
  pkg/reconciler/integrationsource/resources/containersource.go
  pkg/reconciler/integrationsource/resources/containersource_test.go
Labels: approved, size/XS, lgtm

#8322 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#8326 fix: remove duplicated observedGeneration from jobsinks.sinks.knative.dev
  config/core/resources/jobsink.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#8311 Allow configuring (opt-in) IMC async handler
  pkg/apis/messaging/v1/in_memory_channel_types.go
  pkg/channel/fanout/fanout_event_handler.go
  pkg/reconciler/broker/broker.go
  pkg/reconciler/broker/broker_test.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/reconciler/testing/v1/broker.go
  test/rekt/broker_test.go
  test/rekt/channel_test.go
  test/rekt/features/broker/feature.go
  test/rekt/features/channel/features.go
  test/rekt/resources/broker/broker.go
  test/rekt/resources/broker/broker.yaml
  test/rekt/resources/broker/broker_test.go
  test/rekt/resources/channel_impl/channel_impl.go
  test/rekt/resources/channel_impl/channel_impl.yaml
Labels: approved, lgtm, size/XL, area/test-and-release

#8331 JobSink: Delete secrets associated with jobs when jobs are deleted
  cmd/jobsink/main.go
  cmd/jobsink/main_test.go
  hack/e2e-debug.sh
  test/rekt/features/jobsink/jobsink.go
  test/rekt/job_sink_test.go
Labels: approved, size/L, lgtm, area/test-and-release

#8321 Update Integration API and use custom tags on structs for better readability
  config/core/resources/integrationsource.yaml
  docs/eventing-api.md
  pkg/apis/sources/v1alpha1/integration_types.go
  pkg/apis/sources/v1alpha1/integration_types_test.go
  pkg/apis/sources/v1alpha1/integration_validation.go
  pkg/apis/sources/v1alpha1/integration_validation_test.go
  pkg/reconciler/integrationsource/resources/containersource.go
  pkg/reconciler/integrationsource/resources/containersource_test.go
Labels: approved, size/L, lgtm

#8328 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport_go122.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/source.go
  vendor/golang.org/x/tools/internal/imports/source_env.go
  vendor/golang.org/x/tools/internal/typeparams/free.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/golang.org/x/tools/internal/versions/types.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#8334 [main] Format Go code
  pkg/apis/sources/v1alpha1/integration_types_test.go
  pkg/apis/sources/v1alpha1/integration_validation_test.go
Labels: approved, size/XS, lgtm

#8327 Introducing common integration helper and change package name
  cmd/controller/main.go
  pkg/reconciler/integration/helper.go
  pkg/reconciler/integration/helper_test.go
  pkg/reconciler/integration/source/controller.go
  pkg/reconciler/integration/source/controller_test.go
  pkg/reconciler/integration/source/integrationsource.go
  pkg/reconciler/integration/source/integrationsource_test.go
  pkg/reconciler/integration/source/resources/containersource.go
  pkg/reconciler/integration/source/resources/containersource_test.go
  pkg/reconciler/integration/source/resources/names.go
  pkg/reconciler/integrationsource/resources/containersource.go
Labels: approved, lgtm, size/XL

#8336 chore: correct comments
  pkg/apis/sources/v1alpha1/integration_lifecycle.go
Labels: approved, size/XS, lgtm

#8335 fix: rename `job-sink` to `job_sink`
  cmd/jobsink/main.go
Labels: kind/bug, approved, size/XS, lgtm, ok-to-test

#8342 IntegrationSink: rek-test templating support for bool annotations
  test/rekt/resources/integrationsink/integrationsink.yaml
Labels: approved, size/XS, lgtm, area/test-and-release

#8346 JobSink: Inject a `KNATIVE_EXECUTION_MODE` environment variable with value `batch`
  cmd/jobsink/main.go
  pkg/apis/sinks/v1alpha1/job_sink_defaults.go
  pkg/apis/sinks/v1alpha1/job_sink_defaults_test.go
  pkg/apis/sinks/v1alpha1/job_sink_types.go
  pkg/reconciler/jobsink/jobsink_test.go
Labels: approved, size/L, lgtm

#8347 Update integrationsink crd
  config/core/resources/integrationsink.yaml
  docs/eventing-api.md
Labels: size/M, approved, lgtm

#8349 [main] Format Go code
  pkg/apis/sinks/v1alpha1/job_sink_defaults_test.go
Labels: size/M, approved, lgtm

#8354 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#8345 Avoid using twice hardcoded strings for the names of the Kube Secret keys, for AWS access/secret key vals
  pkg/apis/common/integration/v1alpha1/aws.go
  pkg/reconciler/integration/sink/resources/container_image.go
  pkg/reconciler/integration/source/resources/containersource.go
Labels: size/M, approved, lgtm

#8350 Change JobSink execution mode variable to `K_EXECUTION_MODE`
  pkg/apis/sinks/v1alpha1/job_sink_defaults_test.go
  pkg/apis/sinks/v1alpha1/job_sink_types.go
  pkg/reconciler/jobsink/jobsink_test.go
Labels: approved, lgtm, size/S

#8356 Add integrationsinks-addressable-resolver cluster role
  config/core/roles/addressable-resolvers-clusterrole.yaml
Labels: approved, lgtm, size/S

#8355 Align label generation and apply on container-source as well
  pkg/reconciler/integration/helper.go
  pkg/reconciler/integration/sink/integrationsink_test.go
  pkg/reconciler/integration/sink/resources/container_image.go
  pkg/reconciler/integration/sink/resources/labels.go
  pkg/reconciler/integration/source/integrationsource_test.go
  pkg/reconciler/integration/source/resources/containersource.go
  pkg/reconciler/integration/source/resources/containersource_test.go
Labels: size/M, approved, lgtm
