Repository knative/eventing, pull requests merged in 2024-02, with the labels that each got.

#7646 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7648 Remove empty labels
  config/core/configmaps/default-pingsource.yaml
Labels: approved, size/XS, lgtm

#7654 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7656 Update KinD for e2e tests to 0.21.0
  .github/workflows/kind-e2e.yaml
Labels: approved, size/XS, lgtm

#7651 Cache statefulset scale update/get requests
  pkg/scheduler/scheduler.go
  pkg/scheduler/state/state.go
  pkg/scheduler/state/state_test.go
  pkg/scheduler/statefulset/autoscaler.go
  pkg/scheduler/statefulset/autoscaler_test.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, size/L, lgtm

#7662 feat: replace yaml merge tags
  config/brokers/mt-channel-broker/deployments/broker-filter.yaml
  config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
  config/channels/in-memory-channel/deployments/controller.yaml
  config/channels/in-memory-channel/deployments/dispatcher.yaml
  config/channels/in-memory-channel/roles/controller-clusterrole.yaml
  config/core/deployments/pingsource-mt-adapter.yaml
  config/core/deployments/webhook.yaml
  config/core/resources/eventtype.yaml
  config/core/resources/parallel.yaml
  config/core/resources/pingsource.yaml
  config/core/roles/controller-clusterroles.yaml
  config/core/roles/sources-controller-clusterroles.yaml
  config/core/roles/webhook-clusterrole.yaml
Labels: approved, lgtm, size/XL, ok-to-test

#7627 e2e: nodeselector in apiserversauce
  test/rekt/apiserversource_test.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/resources/apiserversource/apiserversource.go
  test/rekt/resources/configmap/config-features.yaml
  test/rekt/resources/configmap/configmap.go
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test

#7666 Set default value for scale cache config values
  pkg/scheduler/scheduler.go
Labels: approved, lgtm, size/S

#7667 wathola receiver, annotate span by step number
  test/upgrade/prober/wathola/receiver/services.go
Labels: approved, size/XS, lgtm, area/test-and-release

#7671 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7669 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/google.golang.org/api/internal/settings.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/http/dial.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7672 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7640 Add rekt test for containersource autocreate
  test/experimental/eventtype_autocreate_test.go
  test/experimental/features/eventtype_autocreate/features.go
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#7703 Create SinkBindings token-secret only if sink has an audience set
  pkg/reconciler/sinkbinding/sinkbinding.go
Labels: size/M, approved, lgtm

#7711 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#7713 Update min K8s version to 1.28.x for KinD e2e tests
  .github/workflows/kind-e2e.yaml
  hack/create-kind-cluster.sh
Labels: approved, lgtm, size/S, area/test-and-release

#7697 Bump to latest CloudEvent lib
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/like_expression.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/expression/logic_expressions.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/encoding.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/event_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/format/format.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/spec/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_binary_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/test/mock_structured_message.go
  vendor/github.com/cloudevents/sdk-go/v2/binding/to_event.go
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/http_receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/client/invoker.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/client/receiver.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/context.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/message.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/options.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_retry.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/write_request.go
  vendor/github.com/cloudevents/sdk-go/v2/test/event_matchers.go
  vendor/github.com/cloudevents/sdk-go/v2/types/doc.go
  vendor/github.com/cloudevents/sdk-go/v2/types/value.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#7696 Add graph types
  pkg/graph/lineage.go
  pkg/graph/lineage_test.go
  pkg/graph/types.go
Labels: approved, size/L, lgtm

#7719 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#7723 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/zap/LICENSE
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/github.com/googleapis/gax-go/v2/.release-please-manifest.json
  vendor/github.com/googleapis/gax-go/v2/CHANGES.md
  vendor/github.com/googleapis/gax-go/v2/callctx/callctx.go
  vendor/github.com/googleapis/gax-go/v2/header.go
  vendor/github.com/googleapis/gax-go/v2/internal/version.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/config.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/version.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/common.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/handler.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/httpconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/semconvutil/netconv.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/transport.go
  vendor/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/version.go
  vendor/go.opentelemetry.io/otel/metric/noop/noop.go
  vendor/go.uber.org/zap/.golangci.yml
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/LICENSE
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/google.golang.org/api/internal/version.go
  vendor/google.golang.org/api/storage/v1/storage-api.json
  vendor/google.golang.org/api/storage/v1/storage-gen.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7728 Assert EventTypes are ready
  test/experimental/features/eventtype_autocreate/features.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/pingsource/features.go
  test/rekt/resources/eventtype/eventtype.go
Labels: size/M, approved, lgtm, area/test-and-release

#7734 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
