Repository knative/eventing, pull requests merged in 2025-10, with the labels that each got.

#8741 Docs: fix cert-manager manual deploy guide in `DEVELOPMENT.md`.
  DEVELOPMENT.md
Labels: approved, lgtm, size/S, ok-to-test, kind/documentation

#8751 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/modules.txt
Labels: size/M, skip-review

#8731 feat: Supporting using pod default credentials for Integration Source and Sink
  config/core/resources/integrationsink.yaml
  config/core/resources/integrationsource.yaml
  pkg/apis/common/integration/v1alpha1/auth.go
  pkg/apis/sinks/v1alpha1/integration_sink_validation_test.go
  pkg/apis/sources/v1alpha1/integration_validation_test.go
  pkg/reconciler/integration/sink/resources/container_image.go
  pkg/reconciler/integration/sink/resources/container_image_test.go
  pkg/reconciler/integration/source/resources/containersource.go
  pkg/reconciler/integration/source/resources/containersource_test.go
  test/rekt/integrationsource_test.go
Labels: approved, size/L, lgtm, area/test-and-release, ok-to-test
