Repository knative/eventing, pull requests merged in 2025-02, with the labels that each got.

#8444 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#8447 Add EventTransform API types
  docs/eventing-api.md
  pkg/apis/eventing/v1alpha1/eventtransform_lifecycle.go
  pkg/apis/eventing/v1alpha1/eventtransform_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/eventtransform_types.go
  pkg/apis/eventing/v1alpha1/eventtransform_validation.go
  pkg/apis/eventing/v1alpha1/register.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventtransform.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventtransform.go
  pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/eventing/v1alpha1/eventtransform.go
  pkg/client/informers/externalversions/eventing/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/injection/informers/eventing/v1alpha1/eventtransform/eventtransform.go
  pkg/client/injection/informers/eventing/v1alpha1/eventtransform/fake/fake.go
  pkg/client/injection/informers/eventing/v1alpha1/eventtransform/filtered/eventtransform.go
  pkg/client/injection/informers/eventing/v1alpha1/eventtransform/filtered/fake/fake.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtransform/controller.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtransform/reconciler.go
  pkg/client/injection/reconciler/eventing/v1alpha1/eventtransform/state.go
  pkg/client/listers/eventing/v1alpha1/eventtransform.go
  pkg/client/listers/eventing/v1alpha1/expansion_generated.go
Labels: approved, lgtm, size/XL

#8451 Scheduler: Resync reserved periodically to keep state consistent
  pkg/scheduler/scheduler.go
  pkg/scheduler/statefulset/scheduler.go
  pkg/scheduler/testing/vpod.go
Labels: size/M, approved, lgtm

#8456 Add EventTransform Jsonata reconciler and CRD
  cmd/controller/main.go
  cmd/schema/main.go
  config/300-eventtransform.yaml
  config/core/resources/eventtransform.yaml
  config/core/roles/addressable-resolvers-clusterrole.yaml
  config/core/roles/controller-clusterroles.yaml
  pkg/reconciler/eventtransform/controller.go
  pkg/reconciler/eventtransform/eventtransform.go
  pkg/reconciler/eventtransform/resources_jsonata.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/deployment/filtered/deployment.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#8460 chore: Adding missing sinks and sources to schema file
  cmd/schema/main.go
Labels: approved, size/XS, lgtm

#8449 Scheduler: log expected vreplicas by vpod
  pkg/scheduler/state/state.go
  pkg/scheduler/statefulset/autoscaler.go
Labels: size/M, approved, lgtm

#8458 EventTransform: Reconcile address and service
  cmd/webhook/main.go
  config/core/deployments/controller.yaml
  docs/eventing-api.md
  pkg/apis/eventing/v1alpha1/eventtransform_defaults.go
  pkg/apis/eventing/v1alpha1/eventtransform_lifecycle.go
  pkg/apis/eventing/v1alpha1/eventtransform_lifecycle_test.go
  pkg/apis/eventing/v1alpha1/eventtransform_types.go
  pkg/apis/eventing/v1alpha1/eventtransform_validation.go
  pkg/apis/eventing/v1alpha1/eventtransform_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/eventtransform/controller.go
  pkg/reconciler/eventtransform/eventtransform.go
  pkg/reconciler/eventtransform/resources_jsonata.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/service/filtered/service.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#8469 EventTransform: Support transforming response from Sink
  docs/eventing-api.md
  pkg/apis/eventing/v1alpha1/eventtransform_types.go
  pkg/apis/eventing/v1alpha1/eventtransform_validation.go
  pkg/apis/eventing/v1alpha1/eventtransform_validation_test.go
  pkg/apis/eventing/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/eventtransform/resources_jsonata.go
Labels: approved, lgtm, size/XL

#8480 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8485 Remove unused code
  pkg/reconciler/resources/service_account.go
  pkg/reconciler/resources/service_account_test.go
Labels: size/M, approved, lgtm

#8486 IntegrationSink prefactors
  pkg/apis/sinks/v1alpha1/integration_sink_types.go
  pkg/reconciler/integration/sink/integrationsink.go
  pkg/reconciler/integration/sink/resources/certificate.go
  pkg/reconciler/integration/sink/resources/container_image.go
  pkg/reconciler/integration/sink/resources/names.go
Labels: size/M, approved, lgtm

#8488 [release-1.16] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#8493 Add initial iteration of eventing-integration resources
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: approved, lgtm, size/S

#8494 fix: verify trigger is not ready before pingsource dependency exists
  test/rekt/features/trigger/feature.go
  test/rekt/resources/trigger/trigger.go
Labels: size/M, approved, lgtm, area/test-and-release, ok-to-test

#8499 Jsonata Event transform e2e tests
  config/400-config-eventing-integrations-images.yaml
  config/400-config-eventing-transformations-images.yaml
  config/core/configmaps/eventing-integrations-images.yaml
  config/core/configmaps/eventing-transformations-images.yaml
  config/core/deployments/controller.yaml
  config/core/resources/eventtransform.yaml
  test/rekt/eventtransform_test.go
  test/rekt/features/eventtransform/eventtransform.go
  test/rekt/resources/eventtransform/eventtransform.go
  test/rekt/resources/eventtransform/eventtransform.yaml
  test/rekt/resources/eventtransform/eventtransform_test.go
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: approved, lgtm, size/XL, area/test-and-release

#8500 Inject integration images from ConfigMap
  config/core/deployments/controller.yaml
  pkg/reconciler/integration/sink/integrationsink_test.go
  pkg/reconciler/integration/sink/resources/container_image.go
  pkg/reconciler/integration/source/integrationsource_test.go
  pkg/reconciler/integration/source/resources/containersource.go
  pkg/reconciler/integration/source/resources/containersource_test.go
Labels: approved, size/L, lgtm

#8457 Guard reserved access with lock and create vpods in tests
  pkg/scheduler/statefulset/scheduler_test.go
Labels: approved, lgtm, size/S

#8502 Fix golangci exclude config
  .golangci.yaml
Labels: approved, size/XS, lgtm

#8506 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: approved, lgtm, size/S, skip-review

#8507 Update to the correct file
  config/400-config-eventing-integrations-images.yaml
Labels: approved, size/XS, lgtm

#8479 EventTransform: Inject tracing configurations
  pkg/reconciler/eventtransform/controller.go
  pkg/reconciler/eventtransform/eventtransform.go
  pkg/reconciler/eventtransform/resources_jsonata.go
Labels: approved, lgtm, size/S

#8512 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#8508 SinkBinding: Set specific conditions for reconciler steps
  pkg/apis/sources/v1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1/sinkbinding_lifecycle_test.go
  pkg/apis/sources/v1/sinkbinding_types.go
  pkg/reconciler/sinkbinding/sinkbinding.go
Labels: size/M, approved, lgtm

#8513 EventTransform: add reconciler unit tests
  pkg/apis/eventing/v1alpha1/eventtransform_lifecycle.go
  pkg/reconciler/eventtransform/eventtransform.go
  pkg/reconciler/eventtransform/eventtransform_test.go
  pkg/reconciler/testing/v1/listers.go
  pkg/reconciler/testing/v1alpha1/eventtransform.go
Labels: approved, lgtm, size/XXL
