Repository knative/eventing, pull requests merged in 2025-04, with the labels that each got.

#8551 If no subscriber uri is present we return 404, instead of 400
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
Labels: approved, size/XS, lgtm

#8557 Migrate golanglint-ci config to v2
  .golangci.yaml
Labels: size/M, approved, lgtm

#8556 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#8558 Compare the entire PodTemplateSpec, instead of just its PodSpec
  pkg/reconciler/containersource/containersource.go
Labels: approved, size/XS, lgtm

#8563 [release-1.17] Migrate golanglint-ci config to v2
  .golangci.yaml
Labels: size/M, approved, lgtm

#8562 [release-1.16] Migrate golanglint-ci config to v2
  .golangci.yaml
Labels: size/M, approved, lgtm

#8565 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8566 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: size/S, skip-review

#8567 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#8570 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8571 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: size/S, skip-review

#8573 fix a typo in broker readme: kantive
  docs/mt-channel-based-broker/README.md
Labels: approved, size/XS, lgtm, ok-to-test

#8576 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/transport/client_stream.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/server_stream.go
  vendor/google.golang.org/grpc/resolver/map.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#8575 Fix hardcoded knative-eventing namespace
  pkg/apis/messaging/v1/in_memory_channel_validation.go
  pkg/apis/messaging/v1/in_memory_channel_validation_test.go
  pkg/reconciler/broker/resources/eventpolicy.go
Labels: approved, lgtm, size/S

#8579 Check for Auth.ServiceAccountName when the OIDC feature flag is switched on to avoid potential nil
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
Labels: approved, size/XS, lgtm
