Repository knative/eventing, pull requests merged in 2025-08, with the labels that each got.

#8652 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/internal/difflib.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_mem_nocgo_darwin.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_procfsenabled.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool_func.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/errors.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/func.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/text.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/internal/modindex/lookup.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#8653 drop use of tracing config map in webhook
  cmd/webhook/main.go
Labels: approved, size/XS, lgtm

#8654 cleanup: drop pkg/tracing from test code
  test/lib/client.go
  test/lib/creation.go
  test/test_images/recordevents/main.go
  test/test_images/utils.go
  test/upgrade/prober/config.toml
  test/upgrade/prober/configuration.go
  test/upgrade/prober/wathola/config/defaults.go
  test/upgrade/prober/wathola/config/structure.go
  test/upgrade/prober/wathola/config/tracing.go
Labels: approved, size/L, lgtm, area/test-and-release

#8626 Injected tracing headers into jobsink event file
  cmd/jobsink/main.go
  pkg/tracing/populate_ce_distributed_tracing.go
  pkg/tracing/populate_ce_distributed_tracing_test.go
Labels: approved, size/L, lgtm, ok-to-test

#8665 remove prometheus from tracing protocol
  config/core/configmaps/observability.yaml
Labels: approved, size/XS, lgtm

#8672 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: size/S, skip-review

#8673 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, skip-review

#8676 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: size/S, skip-review

#8679 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: approved, size/S, skip-review

#8689 [main] Upgrade to latest dependencies
  docs/eventing-api.md
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S, skip-review
