Repository knative/eventing, pull requests merged in 2025-07, with the labels that each got.

#8621 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8624 feat: add new otel config
  config/core/configmaps/observability.yaml
  config/core/configmaps/tracing.yaml
  go.mod
  pkg/observability/config.go
  pkg/observability/config_test.go
  pkg/observability/configmap/configmap.go
  pkg/observability/otel/otel.go
Labels: approved, size/L, lgtm

#8636 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: size/S, skip-review

#8635 feat: migrate kncloudevents, broker filter, broker ingress, inmemorychannel dispatcher to otel
  cmd/broker/filter/main.go
  cmd/broker/ingress/main.go
  go.mod
  pkg/broker/filter/filter_handler.go
  pkg/broker/filter/filter_handler_test.go
  pkg/broker/filter/server_manager.go
  pkg/broker/filter/stats_reporter.go
  pkg/broker/filter/stats_reporter_test.go
  pkg/broker/ingress/ingress_handler.go
  pkg/broker/ingress/ingress_handler_test.go
  pkg/broker/ingress/server_manager.go
  pkg/broker/ingress/stats_reporter.go
  pkg/broker/ingress/stats_reporter_test.go
  pkg/channel/event_receiver.go
  pkg/channel/event_receiver_test.go
  pkg/channel/fanout/fanout_event_handler.go
  pkg/channel/fanout/fanout_event_handler_test.go
  pkg/channel/metrics.go
  pkg/channel/multichannelfanout/multi_channel_fanout_event_handler.go
  pkg/channel/multichannelfanout/multi_channel_fanout_event_handler_test.go
  pkg/channel/stats_reporter.go
  pkg/channel/stats_reporter_test.go
  pkg/eventingtls/servermanager.go
  pkg/inmemorychannel/event_dispatcher_test.go
  pkg/kncloudevents/event_dispatcher.go
  pkg/kncloudevents/event_dispatcher_test.go
  pkg/kncloudevents/event_receiver.go
  pkg/kncloudevents/http_client.go
  pkg/kncloudevents/http_client_test.go
  pkg/observability/key.go
  pkg/observability/newcontext.go
  pkg/observability/newcontext_test.go
  pkg/observability/otel/handler.go
  pkg/reconciler/inmemorychannel/dispatcher/controller.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go
  pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel_test.go
  pkg/tracing/attributes.go
  test/conformance/broker_tracing_test.go
  test/conformance/channel_tracing_test.go
  test/lib/recordevents/receiver/receiver.go
  vendor/go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest/README.md
  vendor/go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest/assertion.go
  vendor/go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest/comparisons.go
  vendor/knative.dev/pkg/observability/metrics/metricstest/assert.go
  vendor/knative.dev/pkg/observability/metrics/metricstest/doc.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, area/test-and-release

#8639 feat: instrument jobsink with otel
  cmd/jobsink/main.go
  pkg/observability/key.go
  pkg/observability/newcontext.go
Labels: approved, size/L, lgtm

#8641 feat: instrument auth verifier with OTel
  pkg/auth/verifier.go
Labels: approved, lgtm, size/S

#8647 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#8648 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: size/S, skip-review
