Repository knative/eventing, pull requests merged in 2025-05, with the labels that each got.

#8587 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/typeutil/callee.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/stdlib/stdlib.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#8589 Try to ensure ordering of referenced source CMs, by name
  pkg/eventingtls/trust_bundle.go
Labels: approved, size/XS, lgtm

#8590 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#8591 [Automated] Update eventing-eventing-integrations nightly
  third_party/eventing-integrations-latest/eventing-integrations-images.yaml
  third_party/eventing-integrations-latest/eventing-transformations-images.yaml
Labels: approved, lgtm, size/S, skip-review

#7726 Eventing TLS: add tests for dynamically added CA trust bundles
  pkg/apis/sources/v1/sinkbinding_lifecycle.go
  pkg/apis/sources/v1/sinkbinding_lifecycle_test.go
  pkg/eventingtls/trust_bundle.go
  pkg/reconciler/apiserversource/apiserversource.go
  pkg/reconciler/sinkbinding/controller.go
  pkg/reconciler/sinkbinding/sinkbinding.go
  test/rekt/apiserversource_test.go
  test/rekt/channel_test.go
  test/rekt/features/apiserversource/data_plane.go
  test/rekt/features/channel/eventing_tls_feature.go
  test/rekt/features/pingsource/features.go
  test/rekt/features/trigger/feature.go
  test/rekt/pingsource_test.go
  test/rekt/trigger_test.go
Labels: approved, size/L, lgtm, area/test-and-release
